<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => true
        ],
        'pageId' => 213,
        'args'   => [
            'PERSON_ID'   => $this->person['id'],
            'PERSON_NAME' => $this->person['name']
        ]
    ]);
?>
<?php $this->pageTitle()->setAutoEscape(false)->captureStart('SET') ?>
    <?=$this->car()->htmlTitle($this->personName) ?>
<?php $this->pageTitle()->captureEnd() ?>
<?php if ($this->canEdit) { ?>
    <ul class="nav nav-pills" style="margin-bottom:10px">
        <li class="active">
            <?=$this->htmlA($this->url('persons/person', [
                'id'   => $this->person['id'],
                'page' => null
            ]), $this->person['name']) ?>
        </li>
        <?php if ($this->canEdit) { ?>
            <li>
                <?=$this->htmlA('/ng/moder/items/item/' . $this->person['id'], '<i class="fa fa-cog"></i> ' . $this->escapeHtml($this->translate('moder/edit-object')), false) ?>
            </li>
        <?php } ?>
    </ul>
<?php } ?>

<?php if ($this->description || count($this->links)) { ?>
    <div class="well">
        <?php if ($this->description) { ?>
            <?=$this->markdown($this->description) ?>
        <?php } ?>

        <?php if (count($this->links)) { ?>
            <p>
                <?=$this->escapeHtml($this->translate('museums/museum/website:'))?>
                <?php foreach ($this->links as $link) { ?>
                    <?=$this->htmlA($link['url'], $link['name'] ? $link['name'] : $link['url'])?><br />
                <?php } ?>
            </p>
        <?php } ?>
    </div>
<?php } ?>

<?php if ($this->authorPictures && count($this->authorPictures['items']) > 0) { ?>
    <h3><?=$this->escapeHtml($this->translate('factories/factory/pictures'))?></h3>
    <?=$this->partial('application/pictures', $this->authorPictures)?>

    <?=$this->paginationControl($this->authorPaginator, null, null, [
        'route' => 'persons/person/page'
    ]) ?>
<?php } ?>

<?php if ($this->contentPictures && count($this->contentPictures['items']) > 0) { ?>
    <h3><?=$this->escapeHtml($this->translate('factories/factory/pictures'))?></h3>
    <?=$this->partial('application/pictures', $this->contentPictures)?>

    <?=$this->paginationControl($this->contentPaginator, null, null, [
        'route' => 'persons/person/page'
    ]) ?>
<?php } ?>