<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 194,
        'args'   => array(
            'BRAND_CATNAME'  => $this->brand->folder,
            'BRAND_NAME'     => $this->brandName,
            'CAR_CATNAME'    => $this->carCatname,
            'CAR_NAME'       => $this->carFullName,
            'SHORT_CAR_NAME' => $this->carShortName,
            'PICTURE_NAME'   => $this->pic()->textTitle($this->picture['name']),
        ),
        'breadcrumbsReplace' => array(
            'pageId'      => 33,
            'breadcrumbs' => $this->breadcrumbs
        )
    ));
?>
<?=$this->partial('picture/picture.phtml', $this->picture)?>