<?php
    $this->pageEnv(array(
        'layout'    => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId'    => 10,
        'pageTitle' => '',
        'args'      => array(
            'BRAND_CATNAME' => $this->brand->folder,
            'BRAND_NAME'    => $this->brandName,
        )
    ));
?>

<header>
    <div class="jumbotron brand-hero-unit">
        <?=$this->img($this->brand->img, array(
            'format' => 'logo',
            'alt'    => 'логотип ' . $this->brand->caption,
            'class'  => 'logo'
        ))?>
        <div class="content">
            <?php if ($this->brandLanguage) { ?>
                <h1><?=$this->escape($this->brandLanguage->name) ?></h1>
                <p>
                    <?=$this->escape($this->brand->caption) ?>
                    <?php if ( $this->brand->full_caption && ($this->brand->full_caption != $this->brand->caption) ) { ?>
                        <small>(<?=$this->escape($this->brand->full_caption)?>)</small>
                    <?php } ?>
                </p>
            <?php } else { ?>
                <h1>
                    <?=$this->escape($this->brand->caption) ?>
                    <?php if ( $this->brand->full_caption && ($this->brand->full_caption != $this->brand->caption) ) { ?>
                        <small>(<?=$this->escape($this->brand->full_caption)?>)</small>
                    <?php } ?>
                </h1>
            <?php } ?>
            <?php if ($this->brand->description) { ?>
                <?=$this->brand->description?>
            <?php } ?>
        </div>
    </div>
    <ul class="nav nav-pills">
        <li>
            <?=$this->htmlA($this->url(array(
                'action' => 'cars'
            ), 'catalogue'), '<span class="glyphicon glyphicon-road"></span> Хронология', false)?>
        </li>
        <li>
            <?=$this->htmlA($this->url(array(
                'action' => 'recent'
            ), 'catalogue'), '<span class="glyphicon glyphicon-th"></span> Новые фото', false)?>
        </li>
        <?php if ($this->haveTwins) { ?>
            <li>
                <?=$this->htmlA($this->url(array(
                    'action'        => 'brand',
                    'brand_catname' => $this->brand->folder
                ), 'twins', true), '<span class="glyphicon glyphicon-adjust"></span> Twins', false)?>
            </li>
        <?php } ?>
        <?php if ($this->mostsActive) { ?>
            <li>
                <?=$this->htmlA($this->url(array(
                    'action'        => 'brand-mosts',
                    'brand_catname' => $this->brand->folder
                ), 'catalogue', true), '<span class="glyphicon glyphicon-sort-by-attributes-alt"></span> Mosts', false)?>
            </li>
        <?php } ?>
    </ul>
</header>

<?php if ($this->topPictures && count($this->topPictures)) { ?>
    <section>
        <h2><?=$this->escape('Популярные картинки') ?></h2>
        <?=$this->partial('pictures.phtml', $this->topPictures)?>
    </section>
<?php } ?>

<?php if (count($this->link_types)) { ?>
    <section>
        <h2><?=$this->escape('Ссылки') ?></h2>
        <?php foreach ($this->link_types as $type) { ?>
            <?php if (count($type['links'])) { ?>
                <p>
                    <strong><?=$this->escape($type['name']) ?></strong><br />
                    <?php foreach ($type['links'] as $link) { ?>
                        <a href="<?=$this->escape($link->url) ?>"><?=$this->escape($link->caption ? $link->caption : $link->url) ?></a><br />
                    <?php } ?>
                </p>
            <?php } ?>
        <?php } ?>
    </section>
<?php } ?>