<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 33,
        'args'   => array(
            'BRAND_CATNAME'  => $this->brand->folder,
            'BRAND_NAME'     => $this->brandName,
            'CAR_CATNAME'    => $this->carCatname,
            'CAR_NAME'       => $this->carFullName,
            'SHORT_CAR_NAME' => $this->carShortName
        ),
        'breadcrumbsReplace' => array(
            'pageId'      => 33,
            'breadcrumbs' => $this->breadcrumbs
        )
    ));
?>

<?php $this->pageTitle()->setAutoEscape(false)->captureStart('SET') ?>
    <?=$this->car()->htmlTitle($this->car)?>
    <?php if ($this->design) { ?>
        <sup class="designBrand"><?=sprintf($this->translate('carlist/designed by %s'), $this->htmlA($this->design['url'], $this->design['name']))?></sup>
    <?php } ?>
    <?php if ($this->car['produced'] > 0) { ?>
        <small class="produced">
            <?php if ($this->car['produced'] > 1) { ?>
                <?=$this->escape(
                    $this->translate(array(
                        $this->car['produced_exactly'] ? 'carlist/produced/%1$s' : 'carlist/produced-about/%1$s',
                        null,
                        $this->car['produced']
                    ), $this->car['produced'])
                )?>
            <?php } else {?>
                <?=$this->escape($this->translate('carlist/produced/one'))?>
            <?php } ?>
        </small>
    <?php } ?>
<?php $this->pageTitle()->captureEnd() ?>

<?php if ($this->user()->inheritsRole('moder')) { ?>
    <p>
        <i class="fa fa-cog"></i>
        <?=$this->htmlA($this->url(array(
            'module'     => 'moder',
            'controller' => 'cars',
            'action'     => 'car',
            'car_id'     => $this->car['id']
        ), 'default', true), 'управление')?>

        <?php if ($this->user()->isAllowed('car', 'add')) { ?>
            <i class="fa fa-plus"></i>
            <?=$this->htmlA($this->url(array(
                'module'     => 'moder',
                'controller' => 'cars',
                'action'     => 'new',
                'parent_id'     => $this->car['id']
            ), 'default', true), 'добавить автомобиль')?>
        <?php } ?>

        <?php if ($this->canAcceptPicture && $this->inboxCount) { ?>
            <i class="fa fa-th"></i>
            <?=$this->htmlA($this->url(array(
                'module'     => 'moder',
                'controller' => 'pictures',
                'action'     => 'index',
                'car_id'     => $this->car['id'],
                'status'     => 'inbox'
            ), 'default', true), 'inbox ('.$this->inboxCount.')')?>
        <?php } ?>

        <?php if ($this->requireAttention) { ?>
            <i class="fa fa-comment"></i>
            <?=$this->htmlA($this->url(array(
                'module'     => 'moder',
                'controller' => 'comments',
                'action'     => 'index',
                'car_id'     => $this->car['id'],
                'moderator_attention' => '1'
            ), 'default', true), 'comments ('.$this->requireAttention.')')?>
        <?php } ?>
    </p>
<?php } ?>

<?=$this->partial('catalogue/partial/brand-car-menu.phtml', array(
    'title' => $this->carFullName,
    'stock' => array(
        'count'  => $this->stockCount,
        'active' => $this->type == Car_Parent::TYPE_DEFAULT
    ),
    'tuning' => array(
        'count'  => $this->tuningCount,
        'active' => $this->type == Car_Parent::TYPE_TUNING
    ),
    'sport' => array(
        'count'  => $this->sportCount,
        'active' => $this->type == Car_Parent::TYPE_SPORT
    ),
    'pictures' => array(
        'count'  => $this->picturesCount,
        'active' => false
    ),
)) ?>

<?php if ($this->hasHtml) { ?>
    <div class="text">
        <?=$this->car['html'] ?>
    </div>
<?php } elseif ($this->car['description']) { ?>
    <div class="text">
        <?=$this->car['description'] ?>
    </div>
<?php } ?>

<?=$this->render('catalogue/partial/modification-filter.phtml')?>

<?=$this->partial('cars.phtml', $this->childListData)?>

<?php if ($this->currentPicturesCount) { ?>
    <h3><?=$this->escape($this->translate('catalogue/other-pictures-of-%1$s', $this->carFullName)) ?></h3>

    <div class="row thumbnails">
        <?php foreach ($this->currentPictures as $picture) { ?>
            <div class="col-md-3">
                <?=$this->htmlA(array(
                    'href'  => $picture['url'],
                    'class' => 'thumbnail'
                ), $this->htmlImg($picture['src'], array(
                    'format'  => 'picture-thumb',
                    'alt'     => $picture['name'],
                    'title'   => $picture['name'],
                    'shuffle' => true
                )), false)?>
            </div>
        <?php } ?>
    </div>

    <?php if ($this->currentPicturesCount > 4) { ?>
        <i class="fa fa-th"></i>
        <?=$this->htmlA($this->currentPicturesUrl, $this->translate('carlist/all pictures').' ('.$this->currentPicturesCount.')')?>
    <?php } ?>
<?php } ?>

<?php if (isset($this->paginator)) { ?>
    <?=$this->paginationControl($this->paginator) ?>
<?php } ?>