<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 36,
        'args'   => array(
            'BRAND_CATNAME'  => $this->brand->folder,
            'BRAND_NAME'     => $this->brandName,
            'CAR_CATNAME'    => $this->carCatname,
            'CAR_NAME'       => $this->car->getFullName(),
            'SHORT_CAR_NAME' => $this->carShortName
        ),
        'breadcrumbsReplace' => array(
            'pageId'      => 33,
            'breadcrumbs' => $this->breadcrumbs
        )
    ));
?>
<?=$this->specs->render($this)?>