<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 36,
        'args'   => array(
            'BRAND_CATNAME'  => $this->brand->folder,
            'BRAND_NAME'     => $this->brandName,
            'CAR_CATNAME'    => $this->carCatname,
            'CAR_NAME'       => $this->carFullName,
            'SHORT_CAR_NAME' => $this->carShortName
        ),
        'breadcrumbsReplace' => array(
            'pageId'      => 33,
            'breadcrumbs' => $this->breadcrumbs
        )
    ));
    $this->layout()->moduleName = 'default/catalogue/brand-car-specifications';
    $this->layout()->moduleOptions = array(
        'disabled' => true
    );
?>
<?=$this->specs->render($this)?>
<?php if (count($this->contributors)) { ?>
    <p>
        Составители:
        <?php foreach ($this->contributors as $contributor) { ?>
            <?=$this->user($contributor)?>
        <?php } ?>
    </p>
<?php } ?>