<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 34,
        'args'   => array(
            'BRAND_CATNAME'  => $this->brand->folder,
            'BRAND_NAME'     => $this->brandName,
            'CAR_CATNAME'    => $this->carCatname,
            'CAR_NAME'       => $this->car->getFullName(),
            'SHORT_CAR_NAME' => $this->carShortName
        ),
        'breadcrumbsReplace' => array(
            'pageId'      => 33,
            'breadcrumbs' => $this->breadcrumbs
        )
    ));
?>

<?=$this->partial('catalogue/partial/brand-car-menu.phtml', array(
    'title' => $this->car->getFullName(),
    'stock' => array(
        'count'  => $this->stockCount,
        'active' => false
    ),
    'tuning' => array(
        'count'  => $this->tuningCount,
        'active' => false
    ),
    'sport' => array(
        'count'  => $this->sportCount,
        'active' => false
    ),
    'pictures' => array(
        'count'  => $this->picturesCount,
        'active' => true
    ),
)) ?>

<?=$this->partial('pictures.phtml', $this->picturesData)?>
<?=$this->paginationControl($this->paginator) ?>