<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 36,
        'args'   => array(
            'BRAND_CATNAME'  => $this->brand->folder,
            'BRAND_NAME'     => $this->brandName,
            'CAR_CATNAME'    => 'car' . $this->car->id,
            'CAR_NAME'       => $this->car->getFullName(),
            'SHORT_CAR_NAME' => $this->carShortName
        )
    ));
?>
<?=$this->specifications($this->carList) ?>