<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 34,
        'args'   => array(
            'BRAND_CATNAME'  => $this->brand->folder,
            'BRAND_NAME'     => $this->brandName,
            'CAR_ID'         => $this->car->id,
            'CAR_NAME'       => $this->car->getFullName(),
            'SHORT_CAR_NAME' => $this->carShortName
        )
    ));
?>

<?=$this->pictures($this->paginator->getCurrentItems(), 4) ?>
<?=$this->paginationControl($this->paginator) ?>