<?php
    $this->pageTitle($this->page->name);
?>

<ul class="nav nav-pills">
    <?php foreach ($this->cartypes as $cartype) { ?>
        <li<?=$this->cartype && $this->cartype->id == $cartype->id ? ' class="active"' : '' ?>>
            <?=$this->htmlA(array(
                'href' => $this->url(array(
                    'cartype_catname' => $cartype->catname,
                    'page'  => 1
                ), 'catalogue')
            ), $this->escape($cartype->name) . ' <small>('.$cartype->cars_count.')</small>', false) ?>
        </li>
    <?php } ?>
</ul>

<?=$this->cars($this->paginator->getCurrentItems()) ?>
<?=$this->paginationControl($this->paginator) ?>