<?php
    if ($this->cartype) {
        $this->pageEnv(array(
            'layout' => array(
                'blankPage' => false,
                'needLeft'  => true,
                'needRight' => false
            ),
            'pageId' => 138,
            'args'   => array(
                'BRAND_CATNAME'    => $this->brand->folder,
                'BRAND_NAME'       => $this->brandName,
                'CAR_TYPE_NAME'    => $this->cartype->name,
                'CAR_TYPE_CATNAME' => $this->cartype->catname
            )
        ));
    } else {
        $this->pageEnv(array(
            'layout'    => array(
                'blankPage' => false,
                'needLeft'  => true,
                'needRight' => false
            ),
            'pageId'    => 14,
            'args'      => array(
                'BRAND_CATNAME'  => $this->brand->folder,
                'BRAND_NAME'     => $this->brandName,
            )
        ));
    }
?>

<ul class="nav nav-pills">
    <?php foreach ($this->cartypes as $cartype) { ?>
        <li<?=$this->cartype && $this->cartype->id == $cartype->id ? ' class="active"' : '' ?>>
            <?=$this->htmlA(array(
                'href' => $this->url(array(
                    'cartype_catname' => $cartype->catname,
                    'page'            => 1
                ), 'catalogue')
            ), $this->escape($cartype->name) . ' <small>('.$cartype->cars_count.')</small>', false) ?>
        </li>
    <?php } ?>
</ul>

<?=$this->cars($this->paginator->getCurrentItems()) ?>
<?=$this->paginationControl($this->paginator) ?>