<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 37,
        'args'   => array(
            'BRAND_CATNAME' => $this->brand->folder,
            'BRAND_NAME'    => $this->brandName,
        )
    ));
?>
<?=$this->cars($this->paginator->getCurrentItems()) ?>
<?=$this->paginationControl($this->paginator) ?>