<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 37,
        'args'   => array(
            'BRAND_CATNAME' => $this->brand['catname'],
            'BRAND_NAME'    => $this->brand['name'],
        )
    ));
?>
<?=$this->partial('cars.phtml', $this->listData)?>
<?=$this->paginationControl($this->paginator) ?>