<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $this->page(37)->initPage();
    $title = $this->page->name . ' ' . $this->brandName;
    $this->pageTitle($title);
    $this->headTitle($title, 'SET');
    $this->breadcrumbs()->params(array(
        'BRAND_NAME'    => $this->brandName,
        'BRAND_CATNAME' => $this->brand->folder
    ));
?>

<?=$this->cars($this->paginator->getCurrentItems()) ?>
<?=$this->paginationControl($this->paginator) ?>