<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 58,
        'args'   => array(
            'BRAND_NAME'      => $this->brandName,
            'BRAND_CATNAME'   => $this->brand->folder,
            'DPBRAND_NAME'    => $this->dpBrand->caption,
            'DPBRAND_CATNAME' => $this->dpBrand->folder
        )
    ));
?>

<?php foreach ($this->items as $dp) { ?>
    <div class="car">
        <h3>
            <?=$this->escape($dp['name'])?>
            <?php if ($dp['year']) { ?> '<?=$dp['year']?><?php } ?>
        </h3>
        <div class="row thumbnails">
            <?php foreach ($dp['pictures'] as $picture) { ?>
                <div class="col-md-3">
                    <?php if ($picture) { ?>
                        <?=$this->htmlA(array(
                            'href'  => $picture['url'],
                            'class' => 'thumbnail'
                        ), $this->img($picture['img'], array(
                            'format'  => 'picture-thumb',
                            'alt'     => $picture['name'],
                            'title'   => $picture['name'],
                            'shuffle' => true
                        )), false)?>
                    <?php } else { ?>
                        &#xa0;
                    <?php } ?>
                </div>
            <?php } ?>
        </div>

        <?php if ($dp['totalPictures'] > 4) { ?>
            <ul class="carLinks"><li>
                <?=$this->htmlA($dp['allPicturesUrl'], 'все картинки ('.$dp['totalPictures'].')') ?>
            </li></ul>
        <?php } ?>
    </div>
<?php } ?>

<?=$this->paginationControl($this->paginator) ?>