<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $title = $this->brandName . ' ' . $this->dpBrand->caption;
    $this->headTitle($title, 'SET');
    $this->pageTitle($title);
    $this->breadcrumbs()->params(array(
        'BRAND_NAME'      => $this->brandName,
        'BRAND_CATNAME'   => $this->brand->folder,
        'DPBRAND_NAME'    => $this->dpBrand->caption,
        'DPBRAND_CATNAME' => $this->dpBrand->folder
    ));
?>

<?php foreach ($this->paginator->getCurrentItems() as $dp) { ?>
    <div class="car">
        <h3>
            <?=$this->escape($dp->name)?>
            <?php if ($dp->year) { ?> '<?=$dp->year?><?php } ?>
        </h3>
        <?=$this->pictureListHorizontal2(
            $dp->findCarsByBrand($this->dpBrand)
                 ->getOrientedPictureList(
                    $this->perspectivesGroups
                 )
        )?>

        <?php
            $items = array();

            $totalPictures = $dp->getPicturesCount();

            if ($totalPictures > 4) {
                $items[] = $this->htmlA($this->url(array(
                    'action' => 'design-project-pictures',
                    'design_project_catname' => $dp->catname
                )), 'все картинки ('.$totalPictures.')');
            }
        ?>

        <?php if (count($items)) { ?>
            <ul class="carLinks"><li><?=implode('</li><li>', $items)?></li></ul>
        <?php } ?>
    </div>
<?php } ?>

<?=$this->paginationControl($this->paginator) ?>