<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $title = $this->brandName . ' ' . $this->designProject->name;
    $this->pageTitle($title);
    $this->headTitle($title, 'SET');
    $this->breadcrumbs()->params(array(
        'BRAND_NAME'             => $this->brandName,
        'BRAND_CATNAME'          => $this->brand->folder,
        'DESIGN_PROJECT_NAME'    => $this->designProject->name,
        'DESIGN_PROJECT_CATNAME' => $this->designProject->catname
    ));
?>

<ul class="nav nav-pills">
    <li class="active">
        <?=$this->htmlA($this->url(array(
            'action'    => 'design-project-cars',
            'page'      => 1
        )), $this->brand->caption.' '.$this->designProject->name) ?>
    </li>
    <li>
        <?=$this->htmlA($this->url(array(
            'action'    => 'design-project-pictures',
            'page'      => 1
        )), 'Все изображения '.$this->brand->caption.' '.$this->designProject->name) ?>
    </li>
</ul>

<?=$this->cars($this->paginator->getCurrentItems()) ?>
<?=$this->paginationControl($this->paginator) ?>