<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => $this->engine ? 168 : 38,
        'args'   => array(
            'BRAND_NAME'    => $this->brand['name'],
            'BRAND_CATNAME' => $this->brand['catname'],
            'ENGINE_NAME'   => $this->engine ? $this->engine->caption : null
        )
    ));
?>
<?php if ($this->user()->inheritsRole('moder')) { ?>
    <p>
        <?php if ($this->engine) { ?>
            <i class="fa fa-cog"></i>
            <?=$this->htmlA($this->url(array(
                'module'     => 'moder',
                'controller' => 'engines',
                'action'     => 'engine',
                'engine_id'  => $this->engine->id
            ), 'default', true), 'управление')?>
        <?php } ?>
        <?php if ($this->user()->isAllowed('engine', 'add')) { ?>
            <i class="fa fa-plus"></i>
            <?php if ($this->engine) { ?>
                <?=$this->htmlA($this->url(array(
                    'module'     => 'moder',
                    'controller' => 'engines',
                    'action'     => 'add',
                    'parent_id'  => $this->engine->id
                ), 'default', true), 'добавить двигатель')?>
            <?php } else { ?>
                <?=$this->htmlA($this->url(array(
                    'module'     => 'moder',
                    'controller' => 'engines',
                    'action'     => 'add',
                    'brand_id'   => $this->brand['id']
                ), 'default', true), 'добавить двигатель')?>
            <?php } ?>
        <?php } ?>
    </p>
<?php } ?>

<?php if ($this->engine) { ?>
    <?=$this->partial('catalogue/partial/brand-engine-menu.phtml', array(
        'title' => $this->engine->caption,
        'tree'  => array(
            'count'  => $this->childsCount,
            'active' => true
        ),
        'cars'  => array(
            'count'  => $this->carsCount,
            'active' => false
        ),
        'specs' => array(
            'count'  => $this->specsCount,
            'active' => false
        ),
        'pictures' => array(
            'count'  => $this->picturesCount,
            'active' => false
        ),
    )) ?>
<?php } ?>
<?php foreach ($this->engines as $engine) { ?>
    <div>
        <h3><?=$this->escape($engine['name'])?></h3>
        <div class="row thumbnails">
            <?php foreach ($engine['pictures'] as $picture) { ?>
                <div class="col-lg-3 col-md-3 col-sm-6">
                    <?=$this->htmlA(array(
                        'href'  => $picture['url'],
                        'class' => 'thumbnail'
                    ), $this->img($picture['img'], array(
                        'format'  => 'picture-thumb',
                        'alt'     => $picture['name'],
                        'title'   => $picture['name'],
                        'shuffle' => true
                    )), false)?>
                </div>
            <?php } ?>
        </div>
        <?php if (count($engine['cars'])) { ?>
            <p>Устанавливался на:</p>
            <ul>
                <?php foreach ($engine['cars'] as $car) { ?>
                    <li><?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?></li>
                <?php } ?>
            </ul>
        <?php } ?>
        <ul class="list-inline">
            <?php if ($engine['detailsUrl']) { ?>
                <li>
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($engine['detailsUrl'], $this->translate('carlist/details') . ' (' . $engine['childsCount'] . ')')?>
                </li>
            <?php } ?>
            <?php if ($engine['moderUrl']) { ?>
                <li>
                    <i class="fa fa-cog"></i>
                    <?=$this->htmlA($engine['moderUrl'], 'управление')?>
                </li>
            <?php } ?>
            <?php if ($engine['specsUrl']) { ?>
                <li>
                    <i class="fa fa-list-alt"></i>
                    <?=$this->htmlA($engine['specsUrl'], $this->translate('carlist/specifications'))?>
                </li>
            <?php } ?>
            <?php if ($engine['specsEditUrl']) { ?>
                <li>
                    <i class="fa fa-pencil"></i>
                    <?=$this->htmlA($engine['specsEditUrl'], 'ввод ттх')?>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>
<?=$this->paginationControl($this->paginator) ?>