<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 168,
        'args'   => array(
            'BRAND_CATNAME' => $this->brand['catname'],
            'BRAND_NAME'    => $this->brand['name'],
            'ENGINE_ID'     => $this->engine['id'],
            'ENGINE_NAME'   => $this->engine['name'],
        ),
    ));
?>
<?=$this->partial('catalogue/partial/brand-engine-menu.phtml', array(
    'title' => $this->engine['name'],
    'tree'  => array(
        'count'  => $this->childsCount,
        'active' => false
    ),
    'cars'  => array(
        'count'  => $this->carsCount,
        'active' => false
    ),
    'specs' => array(
        'count'  => $this->specsCount,
        'active' => true
    ),
    'pictures' => array(
        'count'  => $this->picturesCount,
        'active' => false
    ),
)) ?>
<?=$this->specs->render($this)?>