<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 172,
        'args'   => array(
            'BRAND_NAME'    => $this->brandName,
            'BRAND_CATNAME' => $this->brand->folder,
            'ENGINE_ID'     => $this->engine['id'],
            'ENGINE_NAME'   => $this->engine['name']
        )
    ));
?>
<?=$this->partial('catalogue/partial/brand-engine-menu.phtml', array(
    'title' => $this->engine['name'],
    'tree'  => array(
        'count'  => $this->childsCount,
        'active' => false
    ),
    'cars'  => array(
        'count'  => $this->carsCount,
        'active' => true
    ),
    'specs' => array(
        'count'  => $this->specsCount,
        'active' => false
    ),
)) ?>
<?=$this->partial('cars.phtml', $this->cars)?>