<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $this->page(39)->initPage();
    $title = $this->page->name . ' ' . $this->brandName;
    $this->headTitle($title, 'SET');
    $this->pageTitle($title);
    $this->breadcrumbs()->params(array(
        'BRAND_NAME'    => $this->brandName,
        'BRAND_CATNAME' => $this->brand->folder,
    ));
?>
<?=$this->pictures($this->paginator->getCurrentItems(), array(
    'scheme' => '422'
)) ?>
<?=$this->paginationControl($this->paginator) ?>