<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 40,
        'args'   => array(
            'BRAND_NAME'    => $this->brandName,
            'BRAND_CATNAME' => $this->brand->folder,
        )
    ));
?>
<?=$this->partial('pictures.phtml', $this->picturesData)?>
<?=$this->paginationControl($this->paginator) ?>