<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 190,
        'args'   => array(
            'PICTURE_ID'    => $this->picture['identity'] ? $this->picture['identity'] : $this->picture['id'],
            'PICTURE_NAME'  => $this->pic()->textTitle($this->picture['name']),
            'BRAND_NAME'    => $this->brand['name'],
            'BRAND_CATNAME' => $this->brand['catname'],
        )
    ));
?>
<?=$this->partial('picture/picture.phtml', $this->picture)?>