<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 16,
        'args'   => array(
            'BRAND_CATNAME' => $this->brand->folder,
            'BRAND_NAME'    => $this->brandName,
            'MODEL_CATNAME' => $this->model->folder,
            'MODEL_NAME'    => $this->model->name,
        )
    ));
?>

<?=$this->partial('catalogue/partial/model-menu.phtml', array(
    'title' => $this->brandName . ' ' . $this->model->name,
    'stock' => array(
        'count'  => $this->stockCount,
        'active' => false
    ),
    'tuning' => array(
        'count'  => $this->tuningCount,
        'active' => false
    ),
    'pictures' => array(
        'count'  => $this->picturesCount,
        'active' => true
    ),
)) ?>

<?=$this->pictures($this->paginator->getCurrentItems(), 4) ?>
<?=$this->paginationControl($this->paginator) ?>