<?php
    $brandName = $this->brandLanguage ? $this->brandLanguage->name : $this->brand->caption;
    $title = $this->page->name.' '.$brandName . ' ' . $this->model->name . ' ' . $this->generation->shortname;
    $this->pageTitle($title);
    $this->headTitle($title, 'SET');
?>

<?=$this->partial('catalogue/partial/model-generation-menu.phtml', array(
    'title' => $brandName . ' ' . $this->model->name . ' ' . $this->generation->name,
    'stock' => array(
        'count'  => $this->stockCount,
        'active' => false
    ),
    'tuning' => array(
        'count'  => $this->tuningCount,
        'active' => false
    ),
    'pictures' => array(
        'count'  => $this->picturesCount,
        'active' => true
    ),
)) ?>

<?=$this->pictures($this->paginator->getCurrentItems(), 4) ?>
<?=$this->paginationControl($this->paginator) ?>