<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $title = $this->page->name.' '.$this->car->getFullName();
    $this->pageTitle($title);
    $this->headTitle($title, 'SET');
?>

<?=$this->cars($this->cars, array(
    'disableDesctiption' => $this->hasHtml,
    'disableDetailsLink' => true
)) ?>

<?php if ($this->hasHtml) { ?>
    <div class="text">
        <?=$this->car->html ?>
    </div>
<?php } ?>