<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $title = $this->page->name . ' ' . $this->brand->caption . ' ' . $this->model->name;
    $this->pageTitle($title);
    $this->headTitle($title, 'SET');
?>
<?=$this->pictures($this->paginator->getCurrentItems(), 4) ?>
<?=$this->paginationControl($this->paginator) ?>