<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $this->page(65)->initPage();
    $title = $this->brandName . ' ' . $this->model->name . ' ' . $this->layout['name'];
    $this->pageTitle($title);
    $this->headTitle($title, 'SET');
    $this->breadcrumbs()->params(array(
        'BRAND_NAME'     => $this->brandName,
        'BRAND_CATNAME'  => $this->brand->folder,
        'MODEL_CATNAME'  => $this->model->folder,
        'MODEL_NAME'     => $this->model->name,
        'LAYOUT_CATNAME' => $this->layout['catname'],
        'LAYOUT_NAME'    => $this->layout['name'],
    ));
?>
<?=$this->specifications($this->cars) ?>