<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 84,
        'args'   => array(
            'BRAND_CATNAME'      => $this->brand->folder,
            'BRAND_NAME'         => $this->brandName,
            'MODEL_CATNAME'      => $this->model->folder,
            'MODEL_NAME'         => $this->model->name,
            'GENERATION_CATNAME' => mb_strtolower($this->generation->shortname),
            'GENERATION_NAME'    => $this->generation->name
        )
    ));
?>
<?=$this->specifications($this->cars) ?>