<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $title = 'Другие ' . $this->brandName . ' ' . $this->model->name;
    $this->pageTitle($title);
    $this->headTitle($title, 'SET');
    $this->breadcrumbs()->params(array(
        'BRAND_CATNAME'      => $this->brand->folder,
        'BRAND_NAME'         => $this->brandName,
        'MODEL_CATNAME'      => $this->model->folder,
        'MODEL_NAME'         => $this->model->name,
        'GENERATION_CATNAME' => 'other',
        'GENERATION_NAME'    => 'Другие'
    ));
?>

<?=$this->cars($this->paginator->getCurrentItems()) ?>
<?=$this->paginationControl($this->paginator) ?>