<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 13,
        'args'   => array(
            'BRAND_CATNAME' => $this->brand->folder,
            'BRAND_NAME'    => $this->brandName,
            'MODEL_CATNAME' => $this->model->folder,
            'MODEL_NAME'    => $this->model->name,
        )
    ));
?>
<?=$this->specifications($this->cars) ?>