<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 47,
        'args'   => array(
            'BRAND_CATNAME'      => $this->brand->folder,
            'BRAND_NAME'         => $this->brandName,
            'MODEL_CATNAME'      => $this->model->folder,
            'MODEL_NAME'         => $this->model->name,
        )
    ));
?>
<?=$this->pictures($this->paginator->getCurrentItems(), 4) ?>
<?=$this->paginationControl($this->paginator) ?>