<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 65,
        'args'   => array(
            'BRAND_NAME'     => $this->brandName,
            'BRAND_CATNAME'  => $this->brand->folder,
            'MODEL_CATNAME'  => $this->model->folder,
            'MODEL_NAME'     => $this->model->name,
            'LAYOUT_CATNAME' => $this->layout['catname'],
            'LAYOUT_NAME'    => $this->layout['name'],
        )
    ));
?>
<?=$this->partial('cars.phtml', $this->listData)?>
<?=$this->paginationControl($this->paginator) ?>