<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $this->pageTitle($this->page->name.' '.$this->car->getFullName());
    $this->headTitle($this->page->name.' '.$this->car->getFullName(), 'SET');
?>

<?=$this->pictures($this->paginator->getCurrentItems(), 4) ?>
<?=$this->paginationControl($this->paginator) ?>