<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $this->page(17)->initPage();
    $title = $this->page->name.' '.$this->car->getFullName();
    $this->pageTitle($title);
    $this->headTitle($title, 'SET');
    $this->breadcrumbs()->params(array(
        'BRAND_CATNAME'  => $this->brand->folder,
        'BRAND_NAME'     => $this->brandName,
        'MODEL_CATNAME'  => $this->model->folder,
        'MODEL_NAME'     => $this->model->name,
        'CAR_ID'         => $this->car->id,
        'SHORT_CAR_NAME' => $this->carShortName
    ));
?>

<?=$this->pictures($this->paginator->getCurrentItems(), 4) ?>
<?=$this->paginationControl($this->paginator) ?>