<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => false,
        'needRight' => false
    ));
    $title = $this->page->name . ' ' . $this->brandName . ' ' . $this->model->name;
    $this->pageTitle($title);
    $this->headTitle($title, 'SET');
    $this->breadcrumbs()->params(array(
        'BRAND_CATNAME'  => $this->brand->folder,
        'BRAND_NAME'     => $this->brandName,
        'MODEL_CATNAME'  => $this->model->folder,
        'MODEL_NAME'     => $this->model->name,
    ));
?>
<?=$this->specifications($this->cars) ?>