<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 12,
        'args'   => array(
            'BRAND_CATNAME'  => $this->brand->folder,
            'BRAND_NAME'     => $this->brandName,
            'MODEL_CATNAME'  => $this->model->folder,
            'MODEL_NAME'     => $this->model->name,
            'CAR_ID'         => $this->car->id,
            'CAR_NAME'       => $this->car->getFullName(),
            'SHORT_CAR_NAME' => $this->carShortName
        )
    ));
?>

<?=$this->partial('cars.phtml', $this->listData)?>
<?php if (count($this->childListData['items']) > 0) { ?>
    <?=$this->partial('cars.phtml', $this->childListData)?>
<?php } ?>

<?php if ($this->hasHtml) { ?>
    <div class="text">
        <?=$this->car->html ?>
    </div>
<?php } ?>