<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 15,
        'args'   => array(
            'BRAND_NAME'    => $this->brandName,
            'BRAND_CATNAME' => $this->brand->folder,
        )
    ));
?>
<?=$this->pictures($this->paginator->getCurrentItems(), array(
    'scheme' => '422'
)) ?>
<?=$this->paginationControl($this->paginator) ?>