<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $this->page(15)->initPage();
    $this->headTitle($this->page->name . ' ' . $this->brandName, 'SET');
    $this->breadcrumbs()->params(array(
        'BRAND_NAME'    => $this->brandName,
        'BRAND_CATNAME' => $this->brand->folder
    ));
?>
<?=$this->pictures($this->paginator->getCurrentItems(), array(
    'scheme' => '422'
)) ?>
<?=$this->paginationControl($this->paginator) ?>