<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 111,
        'args'   => [
            'ENGINE_NAME' => $this->engine->caption
        ]
    ]);

    $this->layout()->moduleName = 'default/cars/engine-spec-editor';
?>
<div class="well">
    <?=$this->form->render($this) ?>
</div>