<div class="well">
    <ul class="nav nav-pills nav-stacked">
        <li class="nav-header">Самые …</li>
        <?php foreach ($this->sidebar['mosts'] as $most) { ?>
            <li<?=$most['active'] ? ' class="active"' : '' ?>>
                <?=$this->htmlA($most['url'], $this->translate($most['name'])) ?>
            </li>
        <?php } ?>
        <li class="nav-header">среди …</li>
        <?php foreach ($this->sidebar['carTypes'] as $carType) { ?>
            <li<?=$carType['active'] ? ' class="active"' : '' ?>>
                <?=$this->htmlA($carType['url'], $carType['name']) ?>
                <?php if ($carType['childs']) { ?>
                    <ul class="nav nav-pills nav-stacked">
                        <?php foreach ($carType['childs'] as $child) { ?>
                            <li<?=$child['active'] ? ' class="active"' : '' ?>>
                                <?=$this->htmlA($child['url'], $child['name']) ?>
                            </li>
                        <?php } ?>
                    </ul>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>
</div>