<div class="well">
    <ul class="nav nav-list">
        <li class="nav-header">Самые …</li>
        <?php foreach ($this->mosts as $id => $most) { ?>
            <li<?=($id == $this->mostId) ? ' class="active"' : '' ?>>
                <?=$this->htmlA($this->url(array(
                    'most_catname' => $most['catName'],
                    'shape_catname' => $this->carType ? $this->carType['catname'] : null,
                    'years_catname' => $this->cYear['folder']
                ), 'most'), $this->translate('most/'.$most['catName'])) ?>
            </li>
        <?php } ?>
        <li class="nav-header">среди …</li>
        <?php foreach ($this->carTypes as $carType) { ?>
            <?php
                $url = $this->url(array(
                    'most_catname' => $this->cMost['catName'],
                    'shape_catname' => $carType['catname'],
                    'years_catname' => $this->cYear['folder']
                ), 'most');
                $active = ($this->carType && $carType['id'] == $this->carType['id']);
            ?>
            <li<?= $active ? ' class="active"' : '' ?>>
                <?=$this->htmlA($url, $carType['name']) ?>
                <?php if ($carType['childs']) { ?>
                    <ul class="nav nav-list">
                        <?php foreach ($carType['childs'] as $child) { ?>
                            <li<?= ($this->carType && $child['id'] == $this->carType['id']) ? ' class="active"' : '' ?>>
                                <?=$this->htmlA($this->url(array(
                                    'most_catname' => $this->cMost['catName'],
                                    'shape_catname' => $child['catname'],
                                    'years_catname' => $this->cYear['folder']
                                ), 'most'), $child['name']) ?>
                            </li>
                        <?php } ?>
                    </ul>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>
</div>