<?php
    $this->element->setAttrib(
        'class',
        $this->element->getAttrib('class') . ' form-horizontal'
    );
?>
<fieldset>
    <?php if ($legend = $this->element->getLegend()) { ?>
        <legend><?=$this->escape($legend)?></legend>
    <?php } ?>
    <?php foreach ($this->element->getElements() as $element) { ?>
        <?php if ($element instanceof Zend_Form_Element) { ?>
            <?php if ($element instanceof Zend_Form_Element_File) { ?>
                <div class="form-group<?=$element->hasErrors() ? ' has-error' : ''?>">
                    <label class="col-lg-2 control-label" for="<?=$element->getId()?>"><?=$this->escape($element->getLabel())?></label>
                    <div class="col-lg-10">
                        <?=$element?>
                        <?php foreach ($element->getMessages() as $error) { ?>
                            <p class="help-block"><?=$this->escape($error)?></p>
                        <?php } ?>
                    </div>
                </div>
            <?php } elseif ($element instanceof Zend_Form_Element_Multicheckbox) { ?>
                <div class="form-group<?=$element->hasErrors() ? ' has-error' : ''?>">
                    <label class="col-lg-2 control-label" for="<?=$element->getId()?>"><?=$this->escape($element->getLabel())?></label>
                    <div class="col-lg-10">
                        <?=$element ?>
                        <?php foreach ($element->getMessages() as $error) { ?>
                            <p class="help-block"><?=$this->escape($error)?></p>
                        <?php } ?>
                    </div>
                </div>
            <?php } elseif ($element instanceof Zend_Form_Element_Checkbox) { ?>
                <div class="form-group">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-10">
                        <div class="checkbox<?=$element->hasErrors() ? ' has-error' : ''?>">
                            <label>
                                <?=$element?>
                                <?=$this->escape($element->getLabel())?>
                            </label>
                            <?php foreach ($element->getMessages() as $error) { ?>
                                <p class="help-block"><?=$this->escape($error)?></p>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            <?php } elseif (!$element instanceof Zend_Form_Element_Submit) { ?>
                <div class="form-group<?=$element->hasErrors() ? ' has-error' : ''?>">
                    <label class="col-lg-2 control-label" for="<?=$element->getId()?>"><?=$this->escape($element->getLabel())?></label>
                    <div class="col-lg-10">
                        <?=$element->setAttrib('class', $element->getAttrib('class') . ' form-control')?>
                        <?php foreach ($element->getMessages() as $error) { ?>
                            <p class="help-block"><?=$this->escape($error)?></p>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
        <?php } elseif ($element instanceof Zend_Form) { ?>
            <?=$element->render($this)?>
        <?php } elseif ($element instanceof Zend_Form_DisplayGroup) { ?>
            <div class="form-group">
                <label class="col-lg-2 control-label"><?=$this->escape($element->getLegend())?></label>
                <div class="col-lg-10">
                    <?=$element->render($this)?>
                </div>
            </div>
        <?php } ?>
    <?php } ?>
    <?php
        $submitFound = false;
    ?>
    <?php foreach ($this->element as $element) { ?>
        <?php if ($element instanceof Zend_Form_Element_Submit) { ?>
            <?php
                $element->setAttrib(
                    'class',
                    $element->getAttrib('class') . ($element->getAttrib('class') ? ' ' : '') . 'btn'
                );
                if (!$submitFound) {
                    $element->setAttrib(
                        'class',
                        $element->getAttrib('class') . ' btn-primary'
                    );
                    $submitFound = true;
                }
            ?>
            <div class="form-group">
                <div class="col-lg-2"></div>
                <div class="col-lg-10">
                    <?=$element ?>
                </div>
            </div>
        <?php } ?>
    <?php } ?>
    <?php if ($desc = $this->element->getDescription()) { ?>
        <p><?=$this->escape($desc)?></p>
    <?php } ?>
    <?php if (!$submitFound && !$this->element instanceof Zend_Form_SubForm) { ?>
        <div class="row">
            <div class="col-lg-10 col-offset-2">
                <?=$this->formSubmit('submit', 'Отправить', array(
                    'class' => 'btn btn-primary'
                ))?>
            </div>
        </div>
    <?php } ?>

</fieldset>