<?php
    $this->element->setAttrib('class', 'form-horizontal');
?>
<fieldset>
    <?php if ($legend = $this->element->getLegend()) { ?>
        <legend><?=$this->escape($legend)?></legend>
    <?php } ?>
    <?php foreach ($this->element->getElements() as $element) { ?>
        <?php
            $errors = $element->getMessages();
        ?>
        <div class="form-group<?=$errors ? ' has-error' : ''?>">
            <?php if ($element instanceof Zend_Form_Element_Checkbox) { ?>
                <div class="col-lg-offset-3 col-lg-9">
                    <label class="checkbox" for="<?=$element->getId()?>">
                        <?=$this->escape($element->getLabel())?>
                        <?=$element?>
                    </label>
                    <?php foreach ($errors as $error) { ?>
                        <p class="help-block"><?=$this->escape($error)?></p>
                    <?php } ?>
                </div>
            <?php } else { ?>
                <label class="col-lg-3 control-label" for="<?=$element->getId()?>"><?=$this->escape($element->getLabel())?></label>
                <div class="col-lg-9">
                    <?=$element->setAttrib('class', $element->getAttrib('class') . ' form-control')?>
                    <?php foreach ($errors as $error) { ?>
                        <p class="help-block"><?=$this->escape($error)?></p>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
    <div class="form-group">
        <div class="col-lg-9 col-lg-offset-3">
            <?=$this->formSubmit('submit', 'Войти', array(
                'class' => 'btn btn-primary'
            ))?>
        </div>
    </div>
</fieldset>