<?php 
	$this->element->setAttrib('class', 'form-inline');
?>
<fieldset>
	<?php if ($element = $this->element->getElement('email')) { ?>
		<label class="control-label" for="<?=$element->getId()?>"><?=$this->escape($element->getLabel())?></label>
		<?=$element?>
		<?=$this->formSubmit('submit', 'Выслать пароль', array(
			'class'	=>	'btn btn-primary'
		))?>
		<?php foreach ($element->getMessages() as $error) { ?>
			<p class="alert alert-block alert-error"><?=$this->escape($error)?></p>
		<?php } ?>
	<?php } ?>
</fieldset>