<?php
    $classes = $this->classes;
    $classes[] = 'element-row';
    if ($this->element->hasErrors()) {
        $classes[] = 'has-error';
    }
?>
<tr class="<?=$this->escape(implode(' ', $classes))?>">
    <td>
        <label for="<?=$this->escape($this->element->getId())?>" style="padding-left:<?=$this->deep * 20?>px">
            <?=$this->escape($this->element->getLabel())?>
        </label>
    </td>
    <td>
        <?php if ($this->unit) { ?>
            <div class="input-group">
                <?=$this->content?>
                <span class="input-group-addon" title="<?=$this->escape($this->unit['name'])?>" class="unit">
                    <?=$this->escape($this->unit['abbr'])?>
                </span>
            </div>
        <?php } else { ?>
            <?=$this->content?>
        <?php } ?>
        <?php if ($desc = $this->element->getDescription()) { ?>
            <small><?=$this->escape($desc)?></small>
        <?php } ?>

        <?php if ($this->element->hasErrors()) { ?>
            <ul>
                <?php foreach ($this->element->getMessages() as $message) { ?>
                    <li><?=$this->escape($message)?></li>
                <?php } ?>
            </ul>
        <?php } ?>
    </td>
    <td class="actual">
        <?=$this->escape($this->actual)?>
        <?php if ($this->unit) { ?>
            <span class="unit" title="<?=$this->escape($this->unit['name'])?>"><?=$this->escape($this->unit['abbr'])?></span>
        <?php } ?>
    </td>
    <td>
        <?php foreach ($this->allValues as $value) { ?>
            <?=$this->escape($value['value'])?>
            <?=$this->user($value['user'])?>
            <span class="date">[<?=$this->escape($this->humanTime($value['date']))?>]</span>
            <br />
        <?php } ?>
    </td>
</tr>