<?php
    $this->element->setAttrib(
        'class',
        $this->element->getAttrib('class') . ' spec-editor-form'
    );
?>
<?php if ($this->element->hasErrors()) { ?>
    <p class="alert alert-danger"><i class="fa fa-exclamation-triangle"></i> Данные не сохранены из-за ошибки. Подробности ниже</p>
<?php } ?>
<table class="table table-condensed">
    <thead>
        <tr>
            <th class="col-lg-3 col-sm-3 col-3">Характеристика</th>
            <th class="col-lg-4 col-sm-4 col-4">Ваше значение</th>
            <th class="col-lg-2 col-sm-2 col-2">Актуальное значение</th>
            <th class="col-lg-3 col-sm-3 col-3">Введеные значения</th>
        </tr>
    </thead>
    <tbody>
        <?=$this->content?>
        <tr><td>
            <input type="submit" value="Сохранить" class="btn btn-success" />
        </td></tr>
    </tbody>
</table>