<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 71,
    ]);
?>

<ul>
    <?=$this->partial('application/moder/rights/tree', [
        'roles' => $this->rolesTree
    ])?>
</ul>

<table class="table table-border table-striped">
    <tr>
        <td></td>
        <?php foreach ($this->roles as $role) { ?>
            <td><?=$this->escapeHtml($role['name']) ?></td>
        <?php } ?>
    </tr>
    <?php foreach ($this->resources as $resource) { ?>
        <tr>
            <td><?=$this->escapeHtml($resource['name']) ?></td>
        </tr>
        <?php foreach ($resource['privileges'] as $privilege) { ?>
            <tr>
                <td><?=$this->escapeHtml($resource['name'] . ' / ' . $privilege['name']) ?></td>
                <?php foreach ($this->roles as $role) { ?>
                    <td class="text-center">
                        <?php if ($this->acl->isAllowed($role['name'], $resource['name'], $privilege['name'])) { ?>
                            <i class="fa fa-check"></i>
                        <?php } ?>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>
    <?php } ?>
</table>

<table>
    <thead>
        <tr>
            <th>role</th>
            <th>resource</th>
            <th>privilege</th>
            <th>allowed</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->rules as $rule) { ?>
            <tr>
                <td><?=$this->escapeHtml($rule['role'])?></td>
                <td><?=$this->escapeHtml($rule['resource'])?></td>
                <td><?=$this->escapeHtml($rule['privilege'])?></td>
                <td>
                    <?php if ($rule['allowed']) { ?>
                        <i class="fa fa-check-circle"></i>
                    <?php } else { ?>
                        <i class="fa fa-times-circle"></i>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<div class="well">
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->addRoleForm
    ])?>
</div>
<div class="well">
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->addRuleForm
    ])?>
</div>
<div class="well">
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->addRoleParentForm
    ])?>
</div>