<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 71,
    ]);

    $roles = new Application\Model\DbTable\Acl\Role();

    function printRolesRecuirsive($roles, $role) {
        $select = $roles->select()
            ->from($roles)
            ->joinLeft('acl_roles_parents', 'acl_roles.id=acl_roles_parents.role_id', null)
            ->where('acl_roles_parents.parent_role_id=?', $role->id);

        ?>
        <?=sprintf('%02d', $role->id) ?>. <?=$role->name ?>
        <div style="margin-left:16px">
            <?php foreach ($roles->fetchAll($select) as $role) { ?>
                <?php printRolesRecuirsive($roles, $role) ?>
            <?php } ?>
        </div>
        <?php
    }


    $select = $roles->select()
        ->from($roles)
        ->joinLeft('acl_roles_parents', 'acl_roles.id=acl_roles_parents.role_id', null)
        ->where('acl_roles_parents.role_id IS NULL');
?>

<?php foreach ($roles->fetchAll($select) as $role) { ?>
    <div>
        <?php printRolesRecuirsive($roles, $role) ?>
    </div>
<?php } ?>

<table class="table table-border table-striped">
    <tr>
        <td></td>
        <?php foreach ($this->roles as $role) { ?>
            <td><?=$role->name ?></td>
        <?php } ?>
    </tr>
    <?php foreach ($this->resources as $resource) { ?>
        <tr>
            <td><?=$resource->name ?></td>
        </tr>
        <?php foreach ($resource->findfindDependentRowset(Application\Model\DbTable\Acl\ResourcePrivilege::class) as $privilege) { ?>
            <tr>
                <td><?=$resource->name ?> / <?=$privilege->name ?></td>
                <?php foreach ($this->roles as $role) { ?>
                    <td class="text-center">
                        <?php if ($this->acl->isAllowed($role->name, $resource->name, $privilege->name)) { ?>
                            <i class="fa fa-check"></i>
                        <?php } else { ?>
                        <?php } ?>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>
    <?php } ?>
</table>

<table>
    <thead>
        <tr>
            <th>role</th>
            <th>resource</th>
            <th>privilege</th>
            <th>allowed</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->rules as $rule) { ?>
            <tr>
                <td><?=$this->escapeHtml($rule['role'])?></td>
                <td><?=$this->escapeHtml($rule['resource'])?></td>
                <td><?=$this->escapeHtml($rule['privilege'])?></td>
                <td>
                    <?php if ($rule['allowed']) { ?>
                        <i class="fa fa-check-circle"></i>
                    <?php } else { ?>
                        <i class="fa fa-times-circle"></i>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<div class="well">
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->addRoleForm
    ])?>
</div>
<div class="well">
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->addRuleForm
    ])?>
</div>
<div class="well">
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->addRoleParentForm
    ])?>
</div>