<div class="card card-body">
    <div class="nav flex-column nav-pills">
        <?php foreach ($this->sections as $sectoin) { ?>
            <?php if (count($sectoin['groups'])) { ?>
                <?php if ($sectoin['name']) { ?>
                    <?php if ($sectoin['url']) { ?>
                        <?=$this->htmlA([
                            'class' => 'nav-link',
                            'href'  => $sectoin['url'],
                            'style' => 'font-weight:bold'
                        ], $this->translate($sectoin['name']))?>
                    <?php } else { ?>
                        <h5 style="padding:10px 15px;margin:0;font-weight:bold"><?=$this->escapeHtml($this->translate($sectoin['name']))?></h5>
                    <?php } ?>
                <?php } ?>
                    <?php foreach ($sectoin['groups'] as $group) { ?>
                        <?=$this->htmlA([
                            'class' => 'nav-link' . (isset($group['active']) && $group['active'] ? ' active' : ''),
                            'href' => $group['url']
                        ], $this->escapeHtml($group['name']) . (isset($group['count']) ? ' ' .$this->count($group['count']) : ''), false) ?>
                    <?php } ?>
            <?php } ?>
        <?php } ?>
    </div>
</div>
