<?php if (count($this->brands) > 1) { ?>
    <ul class="brands-switch nav nav-tabs" style="margin-bottom:0">
        <?php foreach ($this->brands as $i => $brand) { ?>
            <li<?=$brand['active'] ? ' class="active"' : ''?>><?=$this->htmlA('#', $brand['brand']['name'])?></li>
        <?php } ?>
    </ul>
<?php } ?>
<div class="card card-body">
    <?php foreach ($this->brands as $brand) { ?>
        <ul class="nav flex-column nav-pills"<?=$brand['active'] ? '' : ' style="display:none"'?>>
            <?php foreach ($brand['groups'] as $group) { ?>
                <li class="nav-item">
                    <?=$this->htmlA([
                        'class' => 'nav-link' . (isset($group['active']) && $group['active'] ? ' active' : ''),
                        'href'  => $group['url']
                    ], $this->escapeHtml($group['name']) . (isset($group['count']) ? ' ' .$this->count($group['count']) : ''), false) ?>
                </li>
            <?php } ?>
        </ul>
    <?php } ?>
</div>
