<?php

    if (!$this->theme) {
        $this->pageEnv(array(
            'layout' => array(
                'blankPage' => false,
                'needLeft'  => false,
                'needRight' => true
            ),
            'pageId' => 42,
        ));
    } else {
        $this->pageEnv(array(
            'layout' => array(
                'blankPage' => false,
                'needLeft'  => false,
                'needRight' => true
            ),
            'pageId' => 43,
            'args'   => array(
                'THEME_NAME' => $this->translate($this->theme['name']),
                'THEME_ID'   => $this->theme['id']
            )
        ));
        
        if ($this->forumAdmin) {
            $this->layout()->moduleName = 'default/forums/theme';
            $this->layout()->moduleOptions = array(
                'openUrl'   => $this->openUrl,
                'closeUrl'  => $this->closeUrl,
                'deleteUrl' => $this->deleteUrl
            );
        }
    }
?>

<?php foreach ($this->themes as $theme) { ?>
    <div class="row">
        <div class="col-md-6">
            <div class="well">
                <p><i class="fa fa-th-list"></i> <strong><?=$this->htmlA(array(
                    'href'  => $theme['url'],
                    'title' => $this->translate('forums/go-to-theme-%1$s', $this->translate($theme['name']))
                ), $this->translate($theme['name'])) ?></strong></p>
                <?php if ($theme['description']) { ?>
                    <p><?=$this->escape($theme['description']) ?></p>
                <?php } ?>
                <p>
                    <?=$this->escape($this->translate(['%1$s topics', null, $theme['topics']], $theme['topics']))?>,
                    <?=$this->escape($this->translate(['%1$s messages', null, $theme['messages']], $theme['messages']))?>
                </p>
                <?php if (count($theme['subthemes'])) { ?>
                    <?=$this->escape($this->translate('forums/subforums'))?>:
                    <?php foreach ($theme['subthemes'] as $idx => $subtheme) {
                        if ($idx) {
                            print ', ';
                        }
                        print $this->htmlA($subtheme['url'], $this->translate($subtheme['name']));
                    } ?>
                <?php } else { ?>
                    <p><?=$this->htmlA($theme['url'], $this->translate('forums/go-to-theme')) ?></p>
                <?php } ?>
            </div>
        </div>
        <?php if ($theme['lastTopic']) { ?>
            <div class="col-md-6">
                <div class="well transparent">
                    <?php if ($lastMessage = $theme['lastMessage']) { ?>
                        <p>
                            <i class="fa fa-comment"></i>
                            <?=$this->translate('forums/last-message-in-topic-%1$s', $this->htmlA($lastMessage['url'], $theme['lastTopic']['name']))?>
                        </p>
                        <p>
                            <?php if ($lastMessage['date']) { ?>
                                <?=$this->pastTimeIndicator($lastMessage['date'])?>
                            <?php } ?>
                            <?php if ($lastMessage['author']) { ?>
                                <?=$this->user($lastMessage['author']) ?>
                            <?php } ?>
                            <?=$this->htmlA(array(
                                'href'  => $lastMessage['message-url'],
                                'title' => $this->translate('forums/go-to-last-message')
                            ), '<i class="fa fa-share"></i>', false) ?>
                        </p>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>

<?php if ($this->theme && !$this->theme['disable_topics']) { ?>
    <?=$this->htmlA(array(
        'class' => 'btn btn-info',
        'href'  => $this->newTopicUrl,
    ), '<i class="fa fa-comment"></i> ' . $this->escape($this->translate('forums/create-new-topic')), false) ?>

    <table class="table table-striped">
        <thead>
            <tr>
                <th><?=$this->escape($this->translate('forums/theme/topics'))?></th>
                <th><?=$this->escape($this->translate('forums/theme/author'))?></th>
                <th><?=$this->escape($this->translate('forums/theme/last-message'))?></th>
                <?php if ($this->forumAdmin) { ?>
                    <th></th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->topics as $topic) { ?>
                <tr>
                    <td>
                        <?=$this->htmlA($topic['url'], $topic['name']) ?>
                        <span class="badge"><?=$topic['oldMessages'] ?><?php if ($topic['newMessages'] > 0) { ?>+<?=$topic['newMessages']?><?php } ?></span>
                        <?=$this->paginationControl($topic['paginator'], 'Sliding', 'forums/paginator.phtml', array(
                            'topic_id' => $topic['id']
                        )) ?>
                    </td>
                    <td>
                        <?php if ($topic['addDatetime']) { ?>
                            <small><?=$this->pastTimeIndicator($topic['addDatetime'])?></small><br />
                        <?php } ?>
                        <?php if ($topic['author']) { ?>
                            <?=$this->user($topic['author']) ?>
                        <?php } ?>
                    </td>
                    <td>
                        <?php if ($topic['lastMessage']) { ?>
                            <?php if ($topic['lastMessage']['date']) { ?>
                                <small><?=$this->pastTimeIndicator($topic['lastMessage']['date'])?></small><br />
                            <?php } ?>
                            <?php if ($topic['lastMessage']['author']) { ?>
                                <?=$this->user($topic['lastMessage']['author']) ?>
                                <?=$this->htmlA(array(
                                    'href'  => $topic['lastMessage']['url'],
                                    'title' => $this->translate('forums/go-to-last-message')
                                ), '<i class="fa fa-share"></i>', false) ?>
                            <?php } ?>
                        <?php } else { ?>
                            &#x2014;
                        <?php } ?>
                    </td>
                    <?php if ($this->forumAdmin) { ?>
                        <td>
                            <div class="btn-group">
                                <?php if ($topic['status'] == Forums_Topics::STATUS_CLOSED) { ?>
                                    <button title="открыть" class="btn btn-xs btn-warning open" id="open-topic-<?=$topic['id'] ?>">
                                        <i class="fa fa-check-circle"></i>
                                    </button>
                                <?php } else { ?>
                                    <button title="закрыть" class="btn btn-xs btn-warning close-topic" id="close-topic-<?=$topic['id'] ?>">
                                        <i class="fa fa-times-circle"></i>
                                    </button>
                                <?php } ?>
                                <?=$this->htmlA(array(
                                    'href'  => $this->url(array(
                                        'module'     => 'forums',
                                        'controller' => 'topic',
                                        'action'     => 'move',
                                        'topic_id'   => $topic['id'],
                                        'theme_id'   => null
                                    )),
                                    'class' => 'btn btn-default btn-xs',
                                    'title' => 'переместить'
                                ), '<i class="fa fa-share"></i>', false) ?>
                                <button title="удалить" class="btn btn-xs btn-danger delete" id="delete-topic-<?=$topic['id'] ?>">
                                    <i class="fa fa-ban"></i>
                                </button>
                            </div>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <?php if ($this->paginator) { ?>
    	<?=$this->paginationControl($this->paginator) ?>
	<?php } ?>
<?php } ?>

<?php if ($this->theme) { ?>
    <p class="text-right small">
        <?=$this->escape($this->translate('forums/theme/total:'))?>
        <?=$this->escape($this->translate(['%1$s topics', null, $this->theme['topics']], $this->theme['topics']))?>,
        <?=$this->escape($this->translate(['%1$s messages', null, $this->theme['messages']], $this->theme['messages']))?>
    </p>
<?php } ?>