<?php if ($this->pageCount > 1) { ?>
    <br />
    <?php foreach ($this->pagesInRange as $page) { ?>
        <?=$this->htmlA($this->url(array(
            'controller' => 'forums',
            'action'     => 'topic',
            'topic_id'   => $this->topic_id,
            'page'       => $page
        ), null, true), $page > 1 && $page == $this->firstPageInRange ? '...' : '['. $page . ']') ?>
    <?php } ?>
<?php } ?>