<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 77,
    ));

    $this->layout()->moduleName = 'moder/traffic/whitelist';
    $this->layout()->moduleOptions = array(
        'hostByAddrUrl' => $this->url(array(
            'action' => 'host-by-addr'
        ))
    );
?>

<ul class="nav nav-pills">
    <li><a href="/moder/trafic/">Traffic</a></li>
    <li class="active"><a href="/moder/trafic/whitelist">Whitelist</a></li>
</ul>
<table class="table table-striped table-condensed">
    <tbody>
        <?php foreach ($this->rows as $row) { ?>
            <tr>
                <td><?=$this->escape($row['ip']) ?></td>
                <td>
                    <?php foreach ($row['users'] as $user) { ?>
                        <?=$this->user($user) ?>
                    <?php } ?>
                </td>
                <td class="host-name"><?=$this->escape($row['ip']) ?></td>
                <td><?=$this->escape($row['description'])?></td>
                <td><?=$this->htmlA('http://nic.ru/whois/?query='.$row['ip'], 'whois') ?></td>
                <td>
                    <form class="form-inline" style="margin:0" method="post" action="<?=$this->escape($row['delete_url'])?>">
                        <button type="submit" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span></button>
                    </form>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>