<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 61,
    ]);

    $this->layout()->moduleName = 'default/brands';
?>
<div><div class="btn-group">
    <?php foreach ($this->brandList as $char => $info) { ?>
        <?php if (preg_match('/[A-Za-z0-9]/isu', $char)) { ?>
            <?=$this->htmlA([
                'class' => 'btn btn-default',
                'href'  => '#char' . $info['id']
            ], $char)?>
        <?php } ?>
    <?php } ?>
</div></div>
<div><div class="btn-group">
    <?php foreach ($this->brandList as $char => $info) { ?>
        <?php if (!preg_match('/[A-Za-z0-9]/isu', $char)) { ?>
            <?=$this->htmlA([
                'class' => 'btn btn-default',
                'href'  => '#char' . $info['id']
            ], $char)?>
        <?php } ?>
    <?php } ?>
</div></div>


<?php foreach ($this->brandList as $char => $info) { ?>
    <h2 id="char<?=urlencode($info['id'])?>">→ <?=$this->escape($char)?></h2>
    <div class="brand-icons">
        <?php foreach ($info['brands'] as $idx => $brand) {
            $newCars = $brand['newCars'];
            $oldCars = $brand['totalCars'] - $newCars;

            /*if ($idx && ($idx % 4 == 0)) {
                ?></div><div class="row brand-icons"><?php
            }*/

            ?><div class="row">
                <div class="col-sm-4">
                    <?php if ($brand['logo']) { ?>
                        <?=$this->htmlA($brand['url'], $this->htmlImg([
                            'src'   => $brand['logo'],
                            'alt'   => 'логотип '. $brand['name'],
                            'title' => 'логотип '. $brand['name'],
                            'class' => 'max-width'
                        ]), false) ?>
                    <?php } else { ?>
                        &#xa0;
                    <?php } ?>
                </div>
                <div class="col-sm-8">
                    <h4>
                        <?=$this->htmlA($brand['url'], $brand['name'])?>
                        <small>(<?=$oldCars ?><?php if ($newCars > 0) {
                            echo '<span data-href="'.$this->escape($brand['newCarsUrl']).'" data-toggle="popover" data-container="body" class="popover-handler" title="'.$this->escape(sprintf($this->translate('brands/new-cars-of-brand'), $brand['name'])).'">+'.$newCars.'</span>';
                        } ?>)</small>
                    </h4>
                    <p><small>картинок: (<?=$brand['totalPictures'] ?>)</small></p>
                </div><?php
            ?></div><?php
        } ?>
    </div>
<?php } ?>