<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => true
        ],
        'pageId' => 181,
        'args'   => [
            'FACTORY_ID'   => $this->factory->id,
            'FACTORY_NAME' => $this->factory->name
        ]
    ]);

    $this->layout()->moduleName = 'default/factory/factory';
    if ($this->point) {
        $this->layout()->moduleOptions = [
            'lat' => $this->point->y(),
            'lng' => $this->point->x(),
        ];
    }
?>
<ul class="nav nav-pills" style="margin-bottom:10px">
    <li class="active">
        <?=$this->htmlA($this->url('factories/factory', [
            'id'   => $this->factory->id,
            'page' => null
        ]), $this->factory->name) ?>
    </li>
    <li>
        <?=$this->htmlA($this->url('factories/factory-cars', [
            'id' => $this->factory->id,
        ]), 'Автомобили') ?>
    </li>
    <?php if ($this->canEdit) { ?>
        <li>
            <?=$this->htmlA($this->url('moder/factories/params', [
                'action'     => 'factory',
                'factory_id' => $this->factory->id
            ]), '<i class="fa fa-cog"></i> Управление', false) ?>
        </li>
    <?php } ?>
</ul>

<div id="google-map" style="height:300px;margin:0 0 40px;width:100%"></div>

<?php if ($this->description) { ?>
    <div class="well">
        <?=$this->markdown($this->description) ?>
    </div>
<?php } ?>

<?php if ($this->pictures && count($this->pictures['items']) > 0) { ?>
    <h3>Фотографии</h3>
    <?=$this->partial('application/pictures', $this->pictures)?>
<?php } ?>

<?php if (count($this->carPictures) > 0) { ?>
    <h3>Автомобили</h3>
    <?php
        $items = $this->carPictures;
    ?>
    <?php while ($currentItems = array_splice($items, 0, 4)) { ?>
        <div class="row">
            <?php foreach ($currentItems as $item) { ?>
                <div class="picture-preview col-md-3">
                    <div class="thumbnail">
                        <?=$this->htmlA($item['url'], $this->htmlImg([
                            'src'     => $item['src'],
                            'alt'     => $item['name'],
                            'title'   => $item['name'],
                            'shuffle' => true
                        ]), false) ?>
                        <div class="caption">
                            <p><?=$this->htmlA($item['url'], $item['name'])?></p>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
    <p><?=$this->htmlA($this->url('factories/factory-cars', [
        'id' => $this->factory->id
    ]), $this->translate('carlist/details'))?></p>
<?php } ?>