<?php 
$numberFormatter = NumberFormatter::create($this->language(), NumberFormatter::DECIMAL);
if (isset($this->thumbColumns) && $this->thumbColumns) {
    $thumbColumns = $this->thumbColumns;
} else {
    $thumbColumns = 4;
}
$singleThumbPart = round(12 / $thumbColumns);
?>
<?php foreach ($this->items as $item) { ?>
    <div class="car item-list-item" data-module="car-list">

        <?php if (!$this->disableTitle) { ?>
            <h3>
                <?=$this->car()->htmlTitle($item['nameData'])?>
                <?php if ($item['designProject']) { ?>
                    <sup class="designBrand"><?=sprintf($this->translate('carlist/designed by %s'), $this->htmlA($item['designProject']['url'], $item['designProject']['brandName']))?></sup>
                <?php } ?>
                <?php if ($item['produced'] > 0) { ?>
                    <small>
                        <?php if ($item['produced'] > 1) { ?>
                            <?=$this->escapeHtml(
                                sprintf(
                                    $this->translatePlural(
                                        $item['produced_exactly'] ? 'carlist/produced/%1$s' : 'carlist/produced-about/%1$s',
                                        null,
                                        $item['produced']
                                    ),
                                    $numberFormatter->format($item['produced'])
                                )
                            ) ?>
                        <?php } else {?>
                            <?=$this->escapeHtml($this->translate('carlist/produced/one'))?>
                        <?php } ?>
                    </small>
                <?php } ?>
            </h3>
        <?php } ?>

        <?php if ($item['nameData']['name'] != $item['name']) { ?>
            <h4><?=$this->escapeHtml($item['name'])?></h4>
        <?php } ?>

        <div class="row thumbnails">
            <?php
                $canHavePhoto = in_array($item['itemTypeId'], [
                    Application\Model\DbTable\Item\Type::VEHICLE,
                    Application\Model\DbTable\Item\Type::ENGINE,
                    Application\Model\DbTable\Item\Type::BRAND,
                    Application\Model\DbTable\Item\Type::FACTORY,
                    Application\Model\DbTable\Item\Type::MUSEUM
                ]);
                $havePhoto = false;
                foreach ($item['pictures'] as $picture) {
                    if ($picture) {
                        $havePhoto = true;
                        break;
                    }
                }
            ?>
        
            <?php if ($havePhoto) { ?>
                <?php foreach ($item['pictures'] as $idx => $picture) { ?>
                    <?php
                        $col = $item['largeFormat'] && $idx == 0  ? 2*$singleThumbPart : $singleThumbPart;
                        $colSm = $item['largeFormat'] && $idx == 0  ? 12 : 6;
                    ?>
                    <div class="col-md-<?=$col?> col-sm-<?=$colSm?>">
                        <?php if ($picture) { ?>
                            <?=$this->htmlA(
                                [
                                    'href'  => $picture['url'],
                                    'class' => 'thumbnail'
                                ],
                                $this->htmlImg([
                                    'src'   => $picture['src'],
                                    'alt'   => $this->pic()->textTitle($picture['name']),
                                    'title' => $this->pic()->textTitle($picture['name']),
                                ]),
                                false
                            )?>
                        <?php } else { ?>
                            &#xa0;
                        <?php } ?>
                    </div>
                <?php } ?>
            <?php } elseif ($canHavePhoto) { ?>
                <div class="col-md-<?=$singleThumbPart?> col-sm-6">
                    <div class="thumbnail no-photo" title="<?=$this->escapeHtmlAttr($this->translate('carlist/no-photo'))?>">
                        <?=$this->htmlA([
                            'title' => $this->translate('carlist/no-photo/add'),
                            'href'  => $item['uploadUrl'],
                            'class' => 'fa fa-plus-circle text-success'
                        ], '') ?>
                        <span class="fa fa-camera fa-lg fa-4x" aria-hidden="true"></span>
                    </div>
                </div>
            <?php } ?>
        </div>


        <?php if (!$this->disableDescription && strlen($item['description'])) { ?>
            <div class="text"><?=$this->markdown($item['description'])?></div>
        <?php } ?>
        
        <?php if (count($item['vehiclesOnEngine'])) { ?>
            <p><?=$this->escapeHtml($this->translate('catalogue/engine/mounted-on:'))?></p>
            <ul>
                <?php foreach ($item['vehiclesOnEngine'] as $car) { ?>
                    <li><?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?></li>
                <?php } ?>
            </ul>
        <?php } ?>

        <ul class="list-inline">

            <?php if (!$this->disableDetailsLink && ($item['hasHtml'] || $item['childsCount']) && isset($item['details']['url'])) { ?>
                <li>
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($item['details']['url'], $this->translate('carlist/details') . ( $item['childsCount'] > 1 ? ' (' . $item['childsCount'] . ')' : '')) ?>
                </li>
            <?php } ?>

            <?php if (isset($item['tuning']) && $item['tuning']) { ?>
                <li>
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($item['tuning']['url'], mb_strtolower($this->translate('catalogue/related')) . ' ('.$item['tuning']['count'].')')?>
                </li>
            <?php } ?>

            <?php if (isset($item['sport']) && $item['sport']) { ?>
                <li>
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($item['sport']['url'], mb_strtolower($this->translate('catalogue/sport')) . ' ('.$item['sport']['count'].')')?>
                </li>
            <?php } ?>

            <?php if (isset($item['allPicturesUrl']) && $item['allPicturesUrl']) { ?>
                <li>
                    <span class="fa fa-th"></span>
                    <?=$this->htmlA($item['allPicturesUrl'], $this->translate('carlist/all pictures').' ('.$item['totalPictures'].')')?>
                </li>
            <?php } ?>

            <?php if (count($item['specsLinks']) > 1) { ?>
                <li>
                    <i class="fa fa-list-alt"></i>
                    <?=$this->escapeHtml($this->translate('carlist/specifications'))?>
                    <?php foreach ($item['specsLinks'] as $specLink) { ?>
                        <?=$this->htmlA($specLink['url'], $specLink['name'])?>
                    <?php } ?>
                </li>
            <?php } else { ?>
                <?php foreach ($item['specsLinks'] as $specLink) { ?>
                    <li>
                        <i class="fa fa-list-alt"></i>
                        <?=$this->htmlA($specLink['url'], $this->translate('carlist/specifications'))?>
                    </li>
                <?php } ?>
            <?php } ?>

            <?php if (isset($item['twinsGroups'])) { ?>
                <?php foreach ($item['twinsGroups'] as $twinsGroup) { ?>
                    <li>
                        <i class="fa fa-adjust"></i>
                        <?=$this->htmlA($twinsGroup['url'], $this->translate('carlist/twins')) ?>
                    </li>
                <?php } ?>
            <?php } ?>

            <?php foreach ($item['categories'] as $category) { ?>
                <li>
                    <i class="fa fa-tag"></i>
                    <?=$this->htmlA($category['url'], $category['name'])?>
                </li>
            <?php } ?>

            <?php if ($this->isCarModer) { ?>
                <li>
                    <i class="fa fa-cog"></i>
                    <?=$this->htmlA($item['moderUrl'], $this->translate('moder/edit-object')) ?>
                </li>
            <?php } ?>

            <?php if ($this->specEditor) { ?>
                <li>
                    <i class="fa fa-pencil"></i>
                    <?=$this->htmlA($item['specEditorUrl'], $this->translate('carlist/edit-specs')) ?>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>