<?php
$numberFormatter = NumberFormatter::create($this->language(), NumberFormatter::DECIMAL);
if (isset($this->thumbColumns) && $this->thumbColumns) {
    $thumbColumns = $this->thumbColumns;
} else {
    $thumbColumns = 4;
}
$singleThumbPart = round(12 / $thumbColumns);
?>
<?php foreach ($this->items as $item) { ?>
    <div class="car item-list-item" data-module="car-list">

        <?php if (! $this->disableTitle) { ?>
            <h3>
                <?=$this->car()->htmlTitle($item['nameData'])?>
                <?php if ($item['designProject']) { ?>
                    <sup class="design-brand"><?=sprintf($this->translate('carlist/designed by %s'), $this->htmlA($item['designProject']['url'], $item['designProject']['name']))?></sup>
                <?php } ?>
                <?php if ($item['produced'] > 0) { ?>
                    <small>
                        <?php if ($item['produced'] > 1) { ?>
                            <?=$this->escapeHtml(
                                sprintf(
                                    $this->translatePlural(
                                        $item['produced_exactly'] ? 'carlist/produced/%1$s' : 'carlist/produced-about/%1$s',
                                        null,
                                        $item['produced']
                                    ),
                                    $numberFormatter->format($item['produced'])
                                )
                            ) ?>
                        <?php } else {?>
                            <?=$this->escapeHtml($this->translate('carlist/produced/one'))?>
                        <?php } ?>
                    </small>
                <?php } ?>
            </h3>
        <?php } ?>

        <?php if ($item['nameData']['name'] != $item['name']) { ?>
            <h4><?=$this->escapeHtml($item['name'])?></h4>
        <?php } ?>

        <div class="row">
            <?php
                $canHavePhoto = in_array($item['itemTypeId'], [
                    Application\Model\Item::VEHICLE,
                    Application\Model\Item::ENGINE,
                    Application\Model\Item::BRAND,
                    Application\Model\Item::FACTORY,
                    Application\Model\Item::MUSEUM
                ]);
                $havePhoto = false;
                foreach ($item['pictures'] as $picture) {
                    if ($picture) {
                        $havePhoto = true;
                        break;
                    }
                }
            ?>

            <?php if ($havePhoto) { ?>
                <?php if ($item['largeFormat']) { ?>
                    <div class="col-md-6">
                        <?php foreach ($item['pictures'] as $idx => $picture) { ?>
                            <?php if ($idx == 0) { ?>
                                <?php if ($picture) { ?>
                                    <?=$this->htmlA(
                                        [
                                            'href'  => $picture['url'],
                                            'class' => 'd-block rounded mb-4'
                                        ],
                                        $this->htmlImg([
                                            'src'   => $picture['large']['src'],
                                            'class' => 'rounded w-100 border border-light',
                                            'alt'   => $this->pic()->textTitle($picture['name']),
                                            'title' => $this->pic()->textTitle($picture['name']),
                                        ]),
                                        false
                                    )?>
                                <?php } else { ?>
                                    &#xa0;
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                    </div>
                    <div class="col-md-6">
                        <?php for ($row = 0; $row < 2; $row++) { ?>
                            <div class="row">
                                <?php for ($col = 0; $col < 2; $col++) { ?>
                                    <div class="col">
                                        <?php
                                            $idx = 1 + $row * 2 + $col;
                                            $picture = isset($item['pictures'][$idx]) ? $item['pictures'][$idx] : null;
                                        ?>
                                        <?php if ($picture) { ?>
                                            <?=$this->htmlA(
                                                [
                                                    'href'  => $picture['url'],
                                                    'class' => 'd-block rounded mb-3'
                                                ],
                                                $this->htmlImg([
                                                    'src'   => $picture['medium']['src'],
                                                    'class' => 'rounded w-100 border border-light',
                                                    'alt'   => $this->pic()->textTitle($picture['name']),
                                                    'title' => $this->pic()->textTitle($picture['name']),
                                                ]),
                                                false
                                            )?>
                                        <?php } else { ?>
                                            &#xa0;
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>
                <?php } else { ?>
                    <?php foreach ($item['pictures'] as $idx => $picture) { ?>
                        <?php
                            $col = $singleThumbPart;
                            $colSm = 12;
                        ?>
                        <div class="col-md-<?=$col?> col-sm-12">
                            <?php if ($picture) { ?>
                                <?=$this->htmlA(
                                    [
                                        'href'  => $picture['url'],
                                        'class' => 'd-block rounded mb-4'
                                    ],
                                    $this->htmlImg([
                                        'src'   => $picture['medium']['src'],
                                        'class' => 'rounded w-100 border border-light',
                                        'alt'   => $this->pic()->textTitle($picture['name']),
                                        'title' => $this->pic()->textTitle($picture['name']),
                                    ]),
                                    false
                                )?>
                            <?php } else { ?>
                                &#xa0;
                            <?php } ?>
                        </div>
                    <?php } ?>
                <?php } ?>
            <?php } elseif ($canHavePhoto) { ?>
                <div class="col-md-<?=$singleThumbPart?> col-sm-6">
                    <div class="no-photo d-block rounded mb-4" title="<?=$this->escapeHtmlAttr($this->translate('carlist/no-photo'))?>">
                        <?=$this->htmlA([
                            'title' => $this->translate('carlist/no-photo/add'),
                            'href'  => $item['uploadUrl'],
                            'class' => 'fa fa-plus-circle text-success'
                        ], '') ?>
                        <span class="fa fa-camera fa-lg fa-4x" aria-hidden="true"></span>
                    </div>
                </div>
            <?php } ?>
        </div>


        <?php if (! $this->disableDescription && strlen($item['description'])) { ?>
            <div class="text"><?=$this->markdown($item['description'])?></div>
        <?php } ?>

        <?php if (count($item['vehiclesOnEngine'])) { ?>
            <p><?=$this->escapeHtml($this->translate('catalogue/engine/mounted-on:'))?></p>
            <ul>
                <?php foreach ($item['vehiclesOnEngine'] as $car) { ?>
                    <li><?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?></li>
                <?php } ?>
            </ul>
        <?php } ?>

        <ul class="list-inline">

            <?php if (! $this->disableDetailsLink && ($item['hasHtml'] || $item['childsCount']) && isset($item['details']['url'])) { ?>
                <li class="list-inline-item">
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($item['details']['url'], $this->translate('carlist/details') . ( $item['childsCount'] > 1 ? ' (' . $item['childsCount'] . ')' : '')) ?>
                </li>
            <?php } ?>

            <?php if (isset($item['tuning']) && $item['tuning']) { ?>
                <li class="list-inline-item">
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($item['tuning']['url'], mb_strtolower($this->translate('catalogue/related')) . ' ('.$item['tuning']['count'].')')?>
                </li>
            <?php } ?>

            <?php if (isset($item['sport']) && $item['sport']) { ?>
                <li class="list-inline-item">
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($item['sport']['url'], mb_strtolower($this->translate('catalogue/sport')) . ' ('.$item['sport']['count'].')')?>
                </li>
            <?php } ?>

            <?php if (isset($item['allPicturesUrl']) && $item['allPicturesUrl']) { ?>
                <li class="list-inline-item">
                    <span class="fa fa-th"></span>
                    <?=$this->htmlA($item['allPicturesUrl'], $this->translate('carlist/all pictures').' ('.$item['totalPictures'].')')?>
                </li>
            <?php } ?>

            <?php if (count($item['specsLinks']) > 1) { ?>
                <li class="list-inline-item">
                    <i class="fa fa-list-alt"></i>
                    <?=$this->escapeHtml($this->translate('carlist/specifications'))?>
                    <?php foreach ($item['specsLinks'] as $specLink) { ?>
                        <?=$this->htmlA($specLink['url'], $specLink['name'])?>
                    <?php } ?>
                </li>
            <?php } else { ?>
                <?php foreach ($item['specsLinks'] as $specLink) { ?>
                    <li class="list-inline-item">
                        <i class="fa fa-list-alt"></i>
                        <?=$this->htmlA($specLink['url'], $this->translate('carlist/specifications'))?>
                    </li>
                <?php } ?>
            <?php } ?>

            <?php if (isset($item['twinsGroups'])) { ?>
                <?php foreach ($item['twinsGroups'] as $twinsGroup) { ?>
                    <li class="list-inline-item">
                        <i class="fa fa-adjust"></i>
                        <?=$this->htmlA([
                            'href'  => $twinsGroup['url'],
                            'title' => $twinsGroup['name']
                        ], $this->translate('carlist/twins')) ?>
                    </li>
                <?php } ?>
            <?php } ?>

            <?php foreach ($item['categories'] as $category) { ?>
                <li class="list-inline-item">
                    <i class="fa fa-tag"></i>
                    <?=$this->htmlA($category['url'], $category['name'])?>
                </li>
            <?php } ?>

            <?php if ($this->isCarModer) { ?>
                <li class="list-inline-item">
                    <i class="fa fa-cog"></i>
                    <?=$this->htmlA($item['moderUrl'], $this->translate('moder/edit-object')) ?>
                </li>
            <?php } ?>

            <?php if ($this->specEditor) { ?>
                <li class="list-inline-item">
                    <i class="fa fa-pencil"></i>
                    <?=$this->htmlA($item['specEditorUrl'], $this->translate('carlist/edit-specs')) ?>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>
