<?php if ($this->items) { ?>
    <div id="moderatorMenuContainer" style="z-index:100">
        <div class="btn-group dropup" >
            <button data-toggle="dropdown" class="btn btn-secondary dropdown-toggle">
                <?=$this->escapeHtml($this->translate('moder-menu/title'))?>
                <span class="caret"></span>
            </button>
            <div class="dropdown-menu float-right">
                <?php foreach ($this->items as $item) { ?>
                    <?=$this->htmlA(
                        [
                            'href' => $item['href'],
                            'class' => 'dropdown-item'
                        ],
                        (isset($item['icon']) ? '<i class="fa-fw '.$item['icon'].'" aria-hidden="true"></i> ' : '') . $this->escapeHtml($item['label']) . (isset($item['count']) ? ' <span class="badge badge-pill badge-secondary">'.$item['count'].'</span>' : ''),
                        false
                    ) ?>
                <?php } ?>
                <div class="dropdown-divider"></div>
                <a href="/ng/moder" class="dropdown-item">
                    <i class="fa fa-cog" aria-hidden="true"></i>
                    <?=$this->escapeHtml($this->page(67)->name)?>
                </a>
            </div>
        </div>
    </div>
<?php } ?>
