<?php
    $classes = ['picture-preview'];
    if (isset($this->colClass)) {
        $classes[] = $this->colClass;
    }
    if ($this->moderVote !== null) {
        if ($this->moderVote > 0) {
            $classes[] = 'vote-accept';
        } elseif ($this->moderVote < 0) {
            $classes[] = 'vote-remove';
        } else {
            $classes[] = 'vote-neutral';
        }
    }
?>
<div class="<?=$this->escapeHtmlAttr(implode(' ', $classes))?>">
    <div class="thumbnail">
        <?=$this->htmlA($this->url, $this->htmlImg([
            'src'     => $this->src,
            'alt'     => $this->pic()->textTitle($this->name),
            'title'   => $this->pic()->textTitle($this->name),
            'shuffle' => true
        ]), false) ?>
        <div class="name">
            <p><?=$this->htmlA($this->url, $this->pic()->htmlTitle($this->name), false)?></p>
            <?php if (!$this->disableBehaviour) { ?>
                <?=$this->render('application/picture-behaviour')?>
            <?php } ?>
        </div>
    </div>
</div>