<p class="picture-behaviour clearfix">
    <?php if ($this->isModer) { ?>
        <span title="Status">
            <?php
                switch ($this->status) {
                    case Application\Model\Picture::STATUS_ACCEPTED: ?><i class="fa fa-check text-success"></i><?php break;
                    case Application\Model\Picture::STATUS_INBOX:    ?><i class="fa fa-hourglass text-warning"></i><?php break;
                    case Application\Model\Picture::STATUS_REMOVED:  ?><i class="fa fa-trash text-danger"></i><?php break;
                    case Application\Model\Picture::STATUS_REMOVING: ?><i class="fa fa-trash text-danger"></i><?php break;
                }
            ?>
        </span>
    <?php } ?>

    <span title="<?=$this->escapeHtmlAttr($this->translate('Resolution'))?>">
        <?=$this->escapeHtml($this->resolution)?>
        <?php if ($this->isModer && $this->cropped) { ?>
            <i class="fa fa-scissors" style="cursor:help" title="<?=$this->escapeHtmlAttr($this->translate('picture-preview/crop-desc'))?> (<?=$this->escapeHtml($this->crop_resolution)?>)"></i>
        <?php } ?>
        <?php /*<i class="fa fa-file-image-o"></i>*/?>
    </span>

    <br />

    <?php if ($this->views > 0) { ?>
        <span title="<?=$this->escapeHtmlAttr($this->translate('Views'))?>" class="mr-2">
            <?=$this->escapeHtml($this->views > 1000 ? round($this->views / 1000) . 'K' : $this->views)?>
            <i class="fa fa-eye"></i>
        </span>
    <?php } ?>

    <?php if ($this->votes['positive'] > 0) { ?>
        <span class="mr-2">
            <?=$this->votes['positive']?>
            <i class="fa fa-thumbs-up"></i>
        </span>
    <?php } ?>

    <span title="<?=$this->escapeHtmlAttr($this->translate('Comments count'))?>" class="mr-2">
        <?php if ($this->newMsgCount > 0) { ?>
            <?=$this->htmlA(
                $this->url. '#comments',
                ($this->msgCount > $this->newMsgCount ? $this->msgCount - $this->newMsgCount : '') .
                '<span class="text-danger">' . $this->escapeHtml('+'.$this->newMsgCount) .'</span> ' .
                '<i class="fa fa-comment text-danger"></i>',
                false
            )?>
        <?php } elseif ($this->msgCount > 0) { ?>
            <?=$this->htmlA($this->url. '#comments', $this->msgCount . ' <i class="fa fa-comment"></i>', false)?>
        <?php } ?>
    </span>

    <?php if ($this->ownerId) { ?>
        <br />
        <?=$this->user($this->ownerId)?>
    <?php } ?>
</p>
