<div class="share">
    <?=$this->htmlA([
        'href'   => 'https://facebook.com/sharer/sharer.php?'. http_build_query([
            'u' => $this->url
        ]),
        'target' => "_blank",
        'class'  => "fa fa-facebook",
        'title'  => 'Facebook'
    ], '')?>
    
    <?=$this->htmlA([
        'href'   => 'https://twitter.com/intent/tweet/?' . http_build_query([
            'text' => $this->text,
            'url'  => $this->url
        ]),
        'target' => "_blank",
        'class'  => "fa fa-twitter",
        'title'  => 'Twitter'
    ], '')?>
    
    <?=$this->htmlA([
        'href'   => 'https://plus.google.com/share?' . http_build_query([
            'url' => $this->url
        ]),
        'target' => "_blank",
        'class'  => "fa fa-google-plus",
        'title'  => 'G+'
    ], '')?>
    
    <?=$this->htmlA([
        'href'   => 'https://www.linkedin.com/shareArticle?' . http_build_query([
            'mini'   => 'true',
            'url'    => $this->url,
            'title'  => $this->text,
            'source' => $this->url
        ]),
        'target' => "_blank",
        'class'  => "fa fa-linkedin",
        'title'  => 'LinkedIn'
    ], '')?>
    
    <?=$this->htmlA([
        'href'   => 'https://reddit.com/submit/?' . http_build_query([
            'url' => $this->url,
        ]),
        'target' => "_blank",
        'class'  => "fa fa-reddit",
        'title'  => 'Reddit'
    ], '')?>
    
    <?=$this->htmlA([
        'href'   => 'https://www.tumblr.com/widgets/share/tool?' . http_build_query([
            'posttype'     => 'link',
            'title'        => $this->text,
            'caption'      => $this->text,
            'content'      => $this->url,
            'canonicalUrl' => $this->url,
            'shareSource'  => 'tumblr_share_button'
        ]),
        'target' => "_blank",
        'class'  => "fa fa-tumblr",
        'title'  => 'Tumblr'
    ], '')?>
    
    <?=$this->htmlA([
        'href'   => 'https://pinterest.com/pin/create/button/?' . http_build_query([
            'url'         => $this->url,
            'media'       => $this->url,
            'description' => $this->text
        ]),
        'target' => "_blank",
        'class'  => "fa fa-pinterest",
        'title'  => 'Pinterest'
    ], '')?>
    
    <?=$this->htmlA([
        'href'   => 'http://vk.com/share.php?' . http_build_query([
            'title' => $this->text,
            'url'   => $this->url
        ]),
        'target' => "_blank",
        'class'  => "fa fa-vk",
        'title'  => 'VK'
    ], '')?>
    
    <?=$this->htmlA([
        'href'   => 'whatsapp://send?' . http_build_query([
            'url'  => $this->url,
            'text' => $this->text . ' ' . $this->url
        ]),
        'target' => "_blank",
        'class'  => "fa fa-whatsapp",
        'title'  => 'Whatsapp'
    ], '')?>
    
    <?=$this->htmlA([
        'href'   => 'https://telegram.me/share/url?' . http_build_query([
            'text' => $this->text,
            'url'  => $this->url
        ]),
        'target' => "_blank",
        'class'  => "fa fa-telegram",
        'title'  => 'Telegram'
    ], '')?>
    
    <?=$this->htmlA([
        'href'   => 'mailto:?' . http_build_query([
            'subject' => $this->text,
            'body'    => $this->url
        ]),
        'target' => "_blank",
        'class'  => "fa fa-envelope-o",
        'title'  => 'E-mail'
    ], '')?>
</div>