<table class="table table-condensed table-striped table-bordered" style="width:auto" data-specs="1">
    <thead>
        <tr>
            <th></th>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <th><?=$this->escapeHtml($car['name'])?></th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <td style="padding:0">
                    <?php if ($car['topPicture']) { ?>
                        <?=$this->htmlA(
                            $this->pic($car['topPicture'])->url(),
                            $this->img($car['topPictureRequest'], [
                                'format'  => 'picture-thumb',
                                'shuffle' => true
                            ]),
                            false
                        )?>
                    <?php } ?>
                </td>
            <?php } ?>
        </tr>
        <tr>
            <td></td>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <td>
                    <?php if ($car['beginYear'] || $car['endYear']) { ?>
                        <?php if ($car['beginYear'] != $car['endYear']) { ?>
                            <?=$car['beginYear']?>–<?=$car['endYear']?>
                        <?php } else { ?>
                            <?=$car['beginYear']?>
                        <?php } ?>
                    <?php } ?>
                </td>
            <?php } ?>
        </tr>
        <?php foreach ($this->table->getAttributes() as $attribute) { ?>
            <?php if (count($attribute['childs'])) { ?>
                <tr>
                    <th colspan="<?=count($this->table->getCars()) + 1?>">
                        <?=$this->escapeHtml($this->translate($attribute['name']))?>
                    </th>
                </tr>
                <?php foreach ($attribute['childs'] as $child) { ?>
                    <?=$this->partial('application/specs-row', [
                        'attribute' => $child,
                        'table'     => $this->table,
                        'deep'      => 0
                    ])?>
                <?php } ?>
            <?php } else { ?>
                <?=$this->partial('application/specs-row', [
                    'attribute' => $attribute,
                    'table'     => $this->table,
                    'deep'      => 0
                ])?>
            <?php } ?>
        <?php } ?>
        <tr>
            <td></td>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <td style="padding:0">
                    <?php if ($car['bottomPicture']) { ?>
                        <?=$this->htmlA(
                            $this->pic($car['bottomPicture'])->url(),
                            $this->img($car['bottomPictureRequest'], [
                                'format'  => 'picture-thumb',
                                'shuffle' => true
                            ]),
                            false
                        )?>
                    <?php } ?>
                </td>
            <?php } ?>
        </tr>
        <?php if ($this->user()->isAllowed('specifications', 'edit')) { ?>
            <tr>
                <td></td>
                <?php foreach ($this->table->getCars() as $car) { ?>
                    <td>
                        <?=$this->htmlA($this->url('cars/params', [
                            'action'  => 'car-specifications-editor',
                            'item_id' => $car['id']
                        ]), $this->translate('carlist/edit-specs'))?>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>
    </tbody>
</table>