<table class="table table-condensed table-striped table-bordered" style="width:auto" data-specs="1">
    <thead>
        <tr>
            <td></td>
            <?php foreach ($this->table->getEngines() as $engine) { ?>
                <td>
                    <?=$this->escapeHtml($engine['name'])?>
                </td>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <?php foreach ($this->table->getEngines() as $engine) { ?>
                <td style="padding:0">
                    <?php if ($engine['picture']) { ?>
                        <?=$this->htmlA(
                            $this->pic($engine['picture'])->url(),
                            $this->img($engine['picture']->getFormatRequest(), [
                                'format'  => 'picture-thumb',
                                'shuffle' => true
                            ]),
                            false
                        )?>
                    <?php } ?>
                </td>
            <?php } ?>
        </tr>
        <?php foreach ($this->table->getAttributes() as $attribute) { ?>
            <?php if (count($attribute['childs'])) { ?>
                <tr>
                    <th colspan="<?=count($this->table->getEngines()) + 1?>">
                        <?=$this->escapeHtml($this->translate($attribute['name']))?>
                    </th>
                </tr>
                <?php foreach ($attribute['childs'] as $child) { ?>
                    <?=$this->partial('application/specs-engine-row', [
                        'attribute' => $child,
                        'table'     => $this->table,
                        'deep'      => 0
                    ])?>
                <?php } ?>
            <?php } else { ?>
                <?=$this->partial('application/specs-row', [
                    'attribute' => $attribute,
                    'table'     => $this->table,
                    'deep'      => 0
                ])?>
            <?php } ?>
        <?php } ?>
        <?php if ($this->user()->isAllowed('specifications', 'edit')) { ?>
            <tr>
                <td></td>
                <?php foreach ($this->table->getEngines() as $engine) { ?>
                    <td>
                        <?=$this->htmlA($this->url('cars/params', [
                            'action'     => 'engine-spec-editor',
                            'engine_id'  => $engine['id']
                        ]), $this->translate('carlist/edit-specs'))?>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>
    </tbody>
</table>