<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => true
        ],
        'pageId' => 136,
    ]);
    
    $users = [];
    foreach ($this->contributors as $user) {
        $users[] = $this->user($user)->__toString();
    }
?>
<div class="well">
    <?=$this->markdown(strtr($this->translate('about/text'), [
        '%users%'          => implode(' ', $users),
        '%total-pictures%' => $this->totalPictures,
        '%total-vehicles%' => $this->totalCars,
        '%total-size%'     => $this->fileSize($this->picturesSize),
        '%total-users%'    => $this->totalUsers,
        '%total-comments%' => $this->totalComments,
        '%github%'         => '<i class="fa fa-github"></i> <a href="https://github.com/autowp/autowp">https://github.com/autowp/autowp</a>',
        '%developer%'      => $this->user($this->developer)->__toString(),
        '%fr-translator%'  => $this->user($this->frTranslator)->__toString(),
        '%zh-translator%'  => $this->user($this->zhTranslator)->__toString(),
    ]))?>
</div>