<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 177,
        'args'   => array(
            'FACTORY_ID'   => $this->factory->id,
            'FACTORY_NAME' => $this->factory->name
        )
    ));
    $this->layout()->moduleName = 'moder/factory/edit';
?>
<div class="row">
    <div class="col-lg-8 col-md-8">
        <div class="well">
            <p>В базе данных чиcлится под номером <strong><?=$this->factory->id ?></strong></p>
            <p><?=$this->htmlA($this->url(array(
                'module'     => 'default',
                'controller' => 'log',
                'action'     => 'index',
                'factory_id' => $this->factory->id
            )), 'Журнал событий по заводу') ?></p>

            <?php
                $url = $this->url(array(
                    'controller' => 'factory',
                    'action'     => 'factory',
                    'id'         => $this->factory->id
                ), 'default', true);
            ?>
            <p>На сайте: <?=$this->htmlA($url, $url)?></p>
        </div>

        <div class="well">
            <?php if ($this->canEdit) { ?>
                <?=$this->formModerFactoryEdit->render($this) ?>
            <?php } ?>
        </div>
    </div>
    <div class="col-lg-4 col-md-4">
        <h3>Автомобили завода</h3>
        <div class="well">
            <?php  foreach ($this->cars as $car) { ?>
                <?=$this->htmlA($this->url(array(
                    'module'     => 'moder',
                    'controller' => 'cars',
                    'action'     => 'car',
                    'car_id'     => $car->id
                ), 'default', true), $car->getFullName()) ?><br />
            <?php } ?>
        </div>
    </div>
</div>