package items

import (
	"fmt"

	"github.com/autowp/goautowp/schema"
	"github.com/doug-martin/goqu/v9"
	"github.com/doug-martin/goqu/v9/exp"
)

var languagePriority = map[string][]string{
	schema.DefaultLanguageCode: {
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.RussianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.EnglishLanguageCode: {
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.RussianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.FrenchLanguageCode: {
		schema.FrenchLanguageCode,
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.RussianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.PortugueseLanguageCode: {
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.RussianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.PortugueseBrazilianLanguageCode: {
		schema.PortugueseBrazilianLanguageCode,
		schema.PortugueseLanguageCode,
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.RussianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.RussianLanguageCode: {
		schema.RussianLanguageCode,
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.BelarusianLanguageCode: {
		schema.BelarusianLanguageCode,
		schema.RussianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.UkrainianLanguageCode: {
		schema.UkrainianLanguageCode,
		schema.RussianLanguageCode,
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.SimplifiedChineseLanguageCode: {
		schema.SimplifiedChineseLanguageCode,
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.RussianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.SpanishLanguageCode: {
		schema.SpanishLanguageCode,
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.RussianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.ItalianLanguageCode: {
		schema.ItalianLanguageCode,
		schema.EnglishLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.RussianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.HebrewLanguageCode: {
		schema.HebrewLanguageCode,
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.RussianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.JapaneseLanguageCode: {
		schema.JapaneseLanguageCode,
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.GermanLanguageCode,
		schema.SpanishLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.RussianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
	schema.GermanLanguageCode: {
		schema.GermanLanguageCode,
		schema.EnglishLanguageCode,
		schema.ItalianLanguageCode,
		schema.FrenchLanguageCode,
		schema.SpanishLanguageCode,
		schema.PortugueseLanguageCode,
		schema.PortugueseBrazilianLanguageCode,
		schema.RussianLanguageCode,
		schema.BelarusianLanguageCode,
		schema.UkrainianLanguageCode,
		schema.SimplifiedChineseLanguageCode,
		schema.JapaneseLanguageCode,
		schema.HebrewLanguageCode,
		schema.DefaultLanguageCode,
	},
}

func langPriorityOrderExpr( //nolint: ireturn
	col exp.IdentifierExpression, lang string,
) (exp.OrderedExpression, error) {
	langPriority, ok := languagePriority[lang]
	if !ok {
		langPriority, ok = languagePriority[schema.DefaultLanguageCode]
	}

	if !ok {
		return nil, fmt.Errorf("%w: `%s`", errLangNotFound, schema.DefaultLanguageCode)
	}

	args := make([]interface{}, len(langPriority)+1)
	args[0] = col

	for i, v := range langPriority {
		args[i+1] = v
	}

	return goqu.Func("FIELD", args...).Asc(), nil
}
