/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GoautowpMessage } from '../model/models';
import { GoautowpMessageNewCount } from '../model/models';
import { GoautowpMessageSummary } from '../model/models';
import { GoautowpMessagingGetMessagesResponse } from '../model/models';
import { RpcStatus } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface MessagingClearFolderRequestParams {
    folder: string;
}

export interface MessagingCreateMessageRequestParams {
    message: GoautowpMessage;
}

export interface MessagingDeleteMessageRequestParams {
    messageId: string;
}

export interface MessagingGetMessagesRequestParams {
    userId: string;
    folder: string;
    page: number;
}


export interface MessagingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    messagingClearFolder(requestParameters: MessagingClearFolderRequestParams, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
* @param requestParameters
     */
    messagingCreateMessage(requestParameters: MessagingCreateMessageRequestParams, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
* @param requestParameters
     */
    messagingDeleteMessage(requestParameters: MessagingDeleteMessageRequestParams, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
* @param requestParameters
     */
    messagingGetMessages(requestParameters: MessagingGetMessagesRequestParams, extraHttpRequestParams?: any): Observable<GoautowpMessagingGetMessagesResponse>;

    /**
     * 
     * 
*/
    messagingGetMessagesNewCount(extraHttpRequestParams?: any): Observable<GoautowpMessageNewCount>;

    /**
     * 
     * 
*/
    messagingGetMessagesSummary(extraHttpRequestParams?: any): Observable<GoautowpMessageSummary>;

}
