/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GoautowpAboutDataResponse } from '../model/models';
import { GoautowpPulseResponse } from '../model/models';
import { RpcStatus } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface StatisticsGetPulseRequestParams {
    period: 'DEFAULT' | 'YEAR' | 'MONTH';
}


export interface StatisticsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    statisticsGetAboutData(extraHttpRequestParams?: any): Observable<GoautowpAboutDataResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    statisticsGetPulse(requestParameters: StatisticsGetPulseRequestParams, extraHttpRequestParams?: any): Observable<GoautowpPulseResponse>;

}
