<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageTitle' => $this->title,
        'pageId' => 23,
        'args'   => [
            'CATEGORY_SHORT_NAME' => $this->categoryLang ? $this->categoryLang->short_name : $this->category->short_name,
            'CATEGORY_NAME'       => $this->categoryLang ? $this->categoryLang->name : $this->category->name,
            'CATEGORY_CATNAME'    => $this->category->catname
        ],
        'breadcrumbsReplace' => [
            'pageId'      => 23,
            'breadcrumbs' => $this->breadcrumbs
        ]
    ]);
?>
<?=$this->partial('application/cars', $this->listData)?>
<?=$this->paginationControl($this->paginator, null, null, [
    'urlParams' => $this->urlParams
]) ?>

<?php if (count($this->contributors)) { ?>
    <p>
        Составители:
        <?php foreach ($this->contributors as $contributor) { ?>
            <?=$this->user($contributor)?>
        <?php } ?>
    </p>
<?php } ?>