<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageTitle' => $this->car()->textTitle($this->currentItem->getNameData($this->language())),
        'pageId' => 23,
        'args'   => [
            'CATEGORY_SHORT_NAME' => $this->category->name, //$this->categoryLang ? $this->categoryLang->short_name : $this->category->short_name,
            'CATEGORY_NAME'       => $this->categoryLang ? $this->categoryLang->name : $this->category->name,
            'CATEGORY_CATNAME'    => $this->category->catname
        ],
        'breadcrumbsReplace' => [
            'pageId'      => 23,
            'breadcrumbs' => $this->breadcrumbs
        ]
    ]);
?>

<?php if ($this->user()->inheritsRole('moder')) { ?>
    <p>
        <i class="fa fa-cog"></i>
        <?=$this->htmlA($this->url('moder/cars/params', [
            'action'  => 'car',
            'item_id' => $this->category['id']
        ]), $this->translate('moder/edit-object'))?>

        <?php if ($this->user()->isAllowed('car', 'add')) { ?>
            <i class="fa fa-plus"></i>
            <?=$this->htmlA(
                '/ng/moder/items/new?item_type_id='.$this->currentItem['item_type_id'].'&parent_id=' . $this->currentItem['id'],
                mb_strtolower($this->translate('item/type/'.$this->currentItem['item_type_id'].'/add-sub-item')
            ))?>
        <?php } ?>
    </p>
<?php } ?>

<?php if ($this->description) { ?>
    <?=$this->markdown($this->description)?>
<?php } ?>

<?=$this->partial('application/cars', $this->listData)?>

<?php if ($this->otherItemsCount > 0) { ?>
    <h3><?=$this->escapeHtml($this->otherCategoryName)?></h3>
    <div class="row thumbnails">
        <?php foreach ($this->otherPictures as $picture) { ?>
            <div class="col-md-3">
                <?=$this->htmlA([
                    'href'  => $picture['url'],
                    'class' => 'thumbnail'
                ], $this->htmlImg([
                    'src'     => $picture['src'],
                    'alt'     => $picture['name'],
                    'title'   => $picture['name'],
                    'shuffle' => true
                ]), false)?>
            </div>
        <?php } ?>
    </div>
    <?php if ($this->user()->isAllowed('car', 'add')) { ?>
        <i class="fa fa-align-left"></i>
        <?=$this->htmlA($this->url('categories', [
            'action'           => 'category',
            'category_catname' => $this->category['catname'],
            'other'            => true,
        ]), $this->translate('carlist/details') . ' ('.$this->otherItemsCount.')')?>
    <?php } ?>
<?php } ?>

<?=$this->paginationControl($this->paginator, null, null, [
    'urlParams' => $this->urlParams
]) ?>

<?php if (count($this->contributors)) { ?>
    <p>
        <?=$this->escapeHtml($this->translate('catalogue/specifications/contributors:'))?>
        <?php foreach ($this->contributors as $contributor) { ?>
            <?=$this->user($contributor)?>
        <?php } ?>
    </p>
<?php } ?>