<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 162,
        'args'   => [
            'CATEGORY_SHORT_NAME' => $this->categoryLang ? $this->categoryLang->short_name : $this->category->short_name,
            'CATEGORY_NAME'       => $this->categoryLang ? $this->categoryLang->name : $this->category->name,
            'CATEGORY_CATNAME'    => $this->category->catname
        ],
        'breadcrumbsReplace' => [
            'pageId'      => 23,
            'breadcrumbs' => $this->breadcrumbs
        ]
    ]);
?>
<div class="row">
    <div class="col-md-4">
        <div class="well nav-tree">
            <?=$this->partial('application/category/menu', [
                'categories' => $this->categories,
                'category'   => $this->category,
                'isOther'    => $this->isOther,
                'deep'       => 1
            ])?>
        </div>
    </div>
    <div class="col-md-8">
        <?=$this->partial('application/pictures', $this->picturesData)?>
        <?=$this->paginationControl($this->paginator) ?>
    </div>
</div>