<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 22,
    ]);
?>
<div class="row destinations thumbnails">
    <?php foreach ($this->categories as $idx => $category) { ?>
        <?php if ($idx && ($idx % 6 == 0)) { ?></div><div class="row destinations thumbnails"><?php }?>
        <div class="col-md-2">
            <div class="thumbnail">
                <?php if ($picture = $category['top_picture']) { ?>
                    <?php if ($picture['image']) { ?>
                        <?=$this->htmlA(
                            $category['url'],
                            $this->htmlImg($picture['image']->getSrc(), [
                                'format' => 'picture-thumb'
                            ]),
                            false
                        ) ?>
                    <?php } ?>
                <?php } ?>
                <div class="name">
                    <h4><?=$this->htmlA([
                        'href'  => $category['url'],
                        'title' => $category['name']
                    ], $category['short_name']) ?></h4>
                    <p>
                        <?=$this->escapeHtml(sprintf($this->translatePlural('category/%s cars', null, $category['cars_count']), $category['cars_count']))?>
                        <?php if ($category['new_cars_count'] > 0) { ?>
                            <small>(<?=$this->escapeHtml(sprintf($this->translatePlural('category/%s new cars', null, $category['new_cars_count']), $category['new_cars_count']))?>)</small>
                        <?php } ?>
                    </p>
                </div>
            </div>
        </div>
    <?php } ?>
</div>