image: $CI_REGISTRY/autowp/runner-base-image

stages:
  - test
  - release
  - publish
  - deploy

test:
  stage: test
  script:
    - cd chart
    - helm dependency update
    - helm lint
    - kube-linter lint .
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d.*/

trigger-release:
  stage: release
  script:
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d.*/
  when: manual

publish:
  stage: publish
  script:
    - cd chart
    - helm repo add --username helm --password "$DEPLOY_TOKEN" gitlab https://gitlab.pereslegin.ru/api/v4/projects/$CI_PROJECT_ID/packages/helm/stable
    - helm cm-push ./ --version="$CI_COMMIT_TAG" gitlab
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d.*/

deploy:
  stage: deploy
  script:
    - cd chart
    - helm dependency build
    - helm -n autowp upgrade autowp . -f "$VALUES"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d.*/
  environment:
    name: production
    url: https://www.wheelsage.org/
