image: docker

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375

stages:
  - build
  - publish

build-php-fpm:
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add --update docker-compose

  script:
    - docker pull autowp/autowp || true
    - docker build --build-arg COMMIT=$CI_COMMIT_SHA --cache-from autowp/autowp -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --pull .
    - docker-compose -f docker-compose-test.yml up -d
    - docker-compose -f docker-compose-test.yml exec -T backend bash -c "waitforit -host=mysql -port=3306 -timeout=60" || docker logs autowp_test_backend
    - docker-compose -f docker-compose-test.yml exec -T backend bash -c "waitforit -host=goautowp -port=8080 -timeout=60" || docker logs autowp_test_backend
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./install-dev-db.sh" || docker logs autowp_test_backend
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./install-dev.sh" || docker logs autowp_test_backend
    # - docker-compose -f docker-compose-test.yml exec -T -e CC_TEST_REPORTER_ID="$CC_TEST_REPORTER_ID" backend sh -c "./cc-test-reporter before-build"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./vendor/bin/security-checker security:check composer.lock"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./vendor/bin/phpcs --encoding=utf-8"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "composer phpmd"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./vendor/bin/psalm --no-progress"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./vendor/bin/phpstan analyze --no-progress"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "php -dzend_extension=xdebug.so -dmemory_limit=768M vendor/bin/phpunit --log-junit ./logs/junit.xml --coverage-clover ./clover.xml"
    #- docker-compose -f docker-compose-test.yml exec -T backend bash -c "./vendor/bin/php-coveralls -v"
    #- docker-compose -f docker-compose-test.yml exec -T backend bash -c "./sonar-scanner/bin/sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN || true"
    #- docker-compose -f docker-compose-test.yml exec -T -e CC_TEST_REPORTER_ID="$CC_TEST_REPORTER_ID" backend bash -c "./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT ./clover.xml"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build-nginx:
  stage: build
  services:
    - docker:dind
  script:
    - docker pull autowp/autowp:nginx || true
    - docker build --build-arg COMMIT=$CI_COMMIT_SHA --cache-from autowp/autowp:nginx -t $CI_REGISTRY_IMAGE:nginx-$CI_COMMIT_REF_SLUG --pull nginx
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:nginx-$CI_COMMIT_REF_SLUG

publish-php-fpm:
  stage: publish
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG autowp/autowp
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push autowp/autowp
  only:
    - master

publish-nginx:
  stage: publish
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:nginx-$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE:nginx-$CI_COMMIT_REF_SLUG autowp/autowp:nginx
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push autowp/autowp:nginx
  only:
    - master
