image: $CI_REGISTRY/autowp/runner-base-image

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

stages:
  - build
  - publish

build:
  stage: build
  services:
    - name: docker:dind
      alias: docker

  before_script:
    - waitforit -address=tcp://docker:2375 -timeout=30
    - cp /opt/sonar-scanner.zip sonar-scanner.zip
    - cp /usr/local/bin/waitforit waitforit
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - local-php-security-checker --path=composer.lock
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --build-arg COMMIT="$CI_COMMIT_SHA" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -t autowp/autowp --pull .
    - docker-compose -f docker-compose-test.yml up -d
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./tools/wait.sh"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./install-dev-db.sh"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./install-dev.sh"
    # - docker-compose -f docker-compose-test.yml exec -T -e CC_TEST_REPORTER_ID="$CC_TEST_REPORTER_ID" backend sh -c "./cc-test-reporter before-build"
    #- docker-compose -f docker-compose-test.yml exec -T backend sh -c "php -d memory_limit=100M ./vendor/bin/phpcs --encoding=utf-8"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./vendor/bin/phpdd module/ --target=7.4"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "composer phpmd"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./vendor/bin/psalm --no-progress"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "./vendor/bin/phpstan analyze --no-progress"
    - docker-compose -f docker-compose-test.yml exec -T backend sh -c "php -dzend_extension=xdebug.so -dmemory_limit=768M vendor/bin/phpunit --log-junit ./logs/junit.xml --coverage-clover ./clover.xml"
    #- docker-compose -f docker-compose-test.yml exec -T backend bash -c "./vendor/bin/php-coveralls -v"
    - docker-compose -f docker-compose-test.yml exec -T backend bash -c "sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN"
    #- docker-compose -f docker-compose-test.yml exec -T -e CC_TEST_REPORTER_ID="$CC_TEST_REPORTER_ID" backend bash -c "./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT ./clover.xml"
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

    - docker pull $CI_REGISTRY_IMAGE:nginx-latest || true
    - docker build -t "$CI_REGISTRY_IMAGE:nginx-$CI_COMMIT_REF_SLUG" --pull nginx

    - npx semantic-release
  interruptible: true
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d.*/

publish:
  stage: publish
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - waitforit -address=tcp://docker:2375 -timeout=30
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker pull "$CI_REGISTRY_IMAGE:latest" || true
    - docker build --build-arg COMMIT=$CI_COMMIT_SHA -t "autowp/autowp:$CI_COMMIT_TAG" -t "$CI_REGISTRY_IMAGE:latest" --pull .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker push autowp/autowp:$CI_COMMIT_TAG

    - docker pull "$CI_REGISTRY_IMAGE:nginx:latest" || true
    - docker build -t "autowp/autowp:nginx-$CI_COMMIT_TAG" -t "$CI_REGISTRY_IMAGE:nginx-latest" --pull nginx
    - docker push "$CI_REGISTRY_IMAGE:nginx-$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE:nginx-latest"
    - docker push autowp/autowp:nginx-$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d.*/
  environment:
    name: production
    url: https://www.wheelsage.org/
