variables:
  SONAR_HOST_URL: https://sonarcloud.io
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  GIT_DEPTH: 0

image: $CI_REGISTRY/autowp/runner-base-image

stages:
  - test
  - release
  - publish
  - deploy

test-chart:
  stage: test
  script:
    - cd chart
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
    - echo "$DOCKER_PASSWORD" | helm registry login -u="$DOCKER_USERNAME" --password-stdin docker.io
    - helm dependency update
    - helm lint .
    - kube-linter lint .
    - trivy config --severity MEDIUM,HIGH,CRITICAL --exit-code 1 --config-data ./trusted-registries.yaml . --report=summary
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d.*/

test-root:
  stage: test
  script:
    - editorconfig-checker -v .editorconfig
    - dclint .
    - trivy fs .
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d.*/

test-frontend:
  stage: test
  cache:
    key:
      files:
        - frontend/package-lock.json
    paths:
      - /root/.npm/
  script:
    - ./protoc.sh
    - cd frontend/
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
    - hadolint Dockerfile
    - npm ci || npm cache clear --force && npm ci
    - npx ng lint
    - npx stylelint "src/**/*.scss"
    - ./node_modules/.bin/ng build --configuration production --no-progress --base-href=/
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d.*/

test-goautowp-lint:
  stage: test
  cache:
    paths:
      - /root/go/pkg/mod/
      - /root/.cache/go-build
  script:
    - ./protoc.sh
    - cd goautowp/
    - hadolint ./build/package/Dockerfile
    - dclint .
    - go mod download
    - go mod verify
    - golangci-lint run ./... -v --timeout 10m
    - govulncheck ./...
  interruptible: true
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d.*/

test-goautowp:
  stage: test
  services:
    - name: docker:dind
      alias: docker
  cache:
    paths:
      - /root/go/pkg/mod/
      - /root/.cache/go-build
  script:
    - ./protoc.sh
    - cd goautowp/
    - go mod download
    - go mod verify

    - waitforit -address=tcp://docker:2375 -timeout=30
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u="$CI_REGISTRY_USER" --password-stdin
    - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin docker.io
    - docker compose up -d --quiet-pull

    - ./tools/wait.sh

    - go test -run TestPostgresMigrations
    - docker exec -t goautowp_postgres_test sh -c "psql --username=traffic traffic < /dump.sql"
    - gotestsum --junitfile report.xml --format testname -- -race -coverpkg=./... -coverprofile=cov.out -covermode atomic ./... -timeout=40m
    - gocover-cobertura < cov.out > coverage.xml
    - sonar-scanner -Dsonar.token="$SONAR_TOKEN"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: goautowp/coverage.xml
      junit: goautowp/report.xml
  interruptible: true
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d.*/

trigger-release:
  stage: release
  script:
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d.*/
  when: manual

publish-chart:
  stage: publish
  script:
    - cd chart
    - helm repo add --username helm --password "$DEPLOY_TOKEN" gitlab https://gitlab.pereslegin.ru/api/v4/projects/$CI_PROJECT_ID/packages/helm/stable
    - helm cm-push ./ --version="$CI_COMMIT_TAG" gitlab
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d.*/

publish-frontend:
  stage: publish
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/frontend
  cache:
    key:
      files:
        - frontend/package-lock.json
    paths:
      - /root/.npm/
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login "$CI_REGISTRY" -u="$CI_REGISTRY_USER" --password-stdin
    - echo "$DOCKER_PASSWORD" | buildah login -u="$DOCKER_USERNAME" --password-stdin docker.io
  script:
    - ./protoc.sh
    - cd frontend
    - npm ci || npm cache clear --force && npm ci
    - "jq -n --arg release \"$CI_COMMIT_TAG\" '{release: $release}' > src/version.json"
    - NG_BUILD_OPTIMIZE_CHUNKS=1 ./node_modules/.bin/ng build --configuration production --no-progress --base-href=/

    - buildah pull "$IMAGE" || true
    - buildah build -t "$IMAGE:$CI_COMMIT_TAG" -t autowp/autowp-frontend:$CI_COMMIT_TAG .
    - buildah push "$IMAGE:$CI_COMMIT_TAG"
    - buildah push autowp/autowp-frontend:$CI_COMMIT_TAG

    - trivy image autowp/autowp-frontend:$CI_COMMIT_TAG
    - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
    - grype autowp/autowp-frontend:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d.*/

publish-goautowp:
  stage: publish
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/goautowp
  cache:
    paths:
      - /root/go/pkg/mod/
      - /root/.cache/go-build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login "$CI_REGISTRY" -u="$CI_REGISTRY_USER" --password-stdin
    - echo "$DOCKER_PASSWORD" | buildah login -u="$DOCKER_USERNAME" --password-stdin docker.io
  script:
    - ./protoc.sh
    - cd goautowp
    - go mod download
    - go mod verify
    - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o goautowp cmd/goautowp/goautowp.go

    - buildah pull "$IMAGE" || true
    - buildah build -f build/package/Dockerfile -t "$IMAGE:$CI_COMMIT_TAG" -t autowp/goautowp:$CI_COMMIT_TAG .
    - buildah push "$IMAGE:$CI_COMMIT_TAG"
    - buildah push autowp/goautowp:$CI_COMMIT_TAG

    - trivy image autowp/goautowp:$CI_COMMIT_TAG
    - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
    - grype autowp/goautowp:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d.*/

deploy:
  stage: deploy
  script:
    - cd chart
    - echo "$DOCKER_PASSWORD" | helm registry login -u="$DOCKER_USERNAME" --password-stdin docker.io
    - helm dependency build
    - helm -n autowp upgrade autowp . -f "$VALUES" --set frontend.image.tag=$CI_COMMIT_TAG --set goautowp.image.tag=$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d.*/
  environment:
    name: production
    url: https://www.wheelsage.org/
  when: manual
