version: "3.8"
services:
  router:
    image: nginx:1-alpine
    container_name: autowp_test_router
    restart: always
    volumes:
    - ./router.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - backend
    - frontend
    - goautowp
    - auth
    ports:
    - "80:80"

  backend:
    image: autowp/autowp
    container_name: autowp_test_backend
    restart: always
    environment:
      AUTOWP_DB_HOST: "autowp_test_mysql"
      AUTOWP_DB_PORT: "3306"
      AUTOWP_DB_USERNAME: "autowp_test"
      AUTOWP_DB_PASSWORD: "test"
      AUTOWP_DB_DBNAME: "autowp_test"
      AUTOWP_USERS_SALT: "users-salt"
      AUTOWP_EMAIL_SALT: "email-salt"
      AUTOWP_MEMCACHED_HOST: "autowp_test_memcached"
      AUTOWP_HOST: "localhost"
      AUTOWP_HOST_RU: "ru.localhost"
      AUTOWP_MAIL_TYPE: "in-memory"
      AUTOWP_MAIL_SMTP_HOST: ""
      AUTOWP_MAIL_SMTP_USERNAME: ""
      AUTOWP_MAIL_SMTP_PASSWORD: ""
      AUTOWP_TELEGRAM_ACCESS_TOKEN: ""
      AUTOWP_TELEGRAM_TOKEN: ""
      AUTOWP_TWITTER_USERNAME: ""
      AUTOWP_TWITTER_OAUTH_KEY: ""
      AUTOWP_TWITTER_OAUTH_SECRET: ""
      AUTOWP_TWITTER_TOKEN_OAUTH: ""
      AUTOWP_TWITTER_TOKEN_OAUTH_SECRET: ""
      AUTOWP_FACEBOOK_APP_ID: ""
      AUTOWP_FACEBOOK_APP_SECRET: ""
      AUTOWP_FACEBOOK_PAGE_ACCESS_TOKEN: ""
      AUTOWP_YANDEX_SECRET: ""
      AUTOWP_YANDEX_PRICE: "1"
      AUTOWP_VK_TOKEN: ""
      AUTOWP_VK_OWNER_ID: ""
      AUTOWP_CAPTCHA: 0
      AUTOWP_RECAPTCHA_PUBLICKEY: "public"
      AUTOWP_RECAPTCHA_PRIVATEKEY: "private"
      SENTRY_DSN: ""
      SENTRY_ENVIRONMENT: "development"
      SENTRY_RELEASE: "dev"
      AUTOWP_AUTH_SECRET: example_secret
    volumes:
    - ./config:/app/config
    - ./data:/app/data
    - ./cache:/app/cache
    - ./module:/app/module
    - ./public_html:/app/public_html
    - ./vendor:/app/vendor
    - ./etc/nginx/conf.d:/etc/nginx/conf.d
    #- ./etc/php/7.3/fpm/php-fpm.conf:/etc/php/7.3/fpm/php-fpm.conf
    #- ./etc/php/7.3/fpm/pool.d/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
    - ./etc/nginx/sites-available:/etc/nginx/sites-available
    - ./etc/supervisor/conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    - ./composer.json:/app/composer.json
    - ./composer.lock:/app/composer.lock
    - ./install-dev-db.sh:/app/install-dev-db.sh
    #- ./goautowp:/app/goautowp
    - ./start.sh:/app/start.sh
    depends_on:
    - memcached
    - mysql
    - rabbitmq
    - traffic
    - minio
    - createbuckets

  memcached:
    image: memcached
    container_name: autowp_test_memcached
    restart: always
    expose:
    - "11211"

  mysql:
    image: mysql:8
    container_name: autowp_test_mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=autowp_test
    - MYSQL_USER=autowp_test
    - MYSQL_PASSWORD=test
    volumes:
    - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    - "./mysql:/var/lib/mysql"
    - "./mysql.conf.d:/etc/mysql/conf.d"
    expose:
    - "3306"
    ports:
    - "3306:3306"

  frontend:
    image: autowp/autowp-frontend
    container_name: autowp_test_frontend
    restart: always
    volumes:
    - "./frontend/be-BY:/usr/share/nginx/html/be-BY"
    - "./frontend/en-GB:/usr/share/nginx/html/en-GB"
    - "./frontend/fr:/usr/share/nginx/html/fr"
    - "./frontend/pt-BR:/usr/share/nginx/html/pt-BR"
    - "./frontend/ru:/usr/share/nginx/html/ru"
    - "./frontend/uk:/usr/share/nginx/html/uk"
    - "./frontend/zh-CN:/usr/share/nginx/html/zh-CN"
    - "/home/dvp/WebstormProjects/autowp-frontend/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "./hostmap:/etc/nginx/hostmap:ro"
    user: "101:101"

  rabbitmq:
    image: rabbitmq:management
    container_name: autowp_test_rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"

  traffic:
    image: autowp/traffic
    container_name: autowp_test_traffic
    restart: always
    depends_on:
    - rabbitmq
    - traffic-mysql
    volumes:
    - "./traffic/logs:/var/log"
    environment:
    - TRAFFIC_RABBITMQ_HOST=autowp_test_rabbitmq
    - TRAFFIC_RABBITMQ_PORT=5672
    - TRAFFIC_MONITORING_QUEUE=input
    - TRAFFIC_HOTLINK_QUEUE=hotlink
    - TRAFFIC_MYSQL_DSN=root:password@tcp(autowp_test_traffic_mysql:3306)/traffic?charset=utf8mb4&parseTime=true&loc=UTC
    - TRAFFIC_MIGRATIONS_DSN=mysql://root:password@tcp(autowp_test_traffic_mysql)/traffic?charset=utf8mb4&parseTime=true&loc=UTC
    - TRAFFIC_SENTRY_DSN=
    - TRAFFIC_SENTRY_ENVIRONMENT=development

  traffic-mysql:
    image: mysql:8
    container_name: autowp_test_traffic_mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=traffic

  goautowp:
    image: autowp/goautowp
    container_name: autowp_test_goautowp
    restart: always
    depends_on:
    - rabbitmq
    - mysql
    volumes:
    - ./goautowp/logs:/var/log
    - ./public_html/pictures:/app/pictures:ro
    environment:
    - AUTOWP_RABBITMQ_HOST=autowp_test_rabbitmq
    - AUTOWP_RABBITMQ_PORT=5672
    - AUTOWP_DUPLICATE_FINDER_QUEUE=duplicate_finder
    - AUTOWP_MYSQL_DSN=autowp_test:test@tcp(autowp_test_mysql:3306)/autowp_test?charset=utf8mb4&parseTime=true&loc=UTC
    - AUTOWP_MIGRATIONS_DSN=mysql://autowp_test:test@tcp(autowp_test_mysql)/autowp_test?charset=utf8mb4&parseTime=true&loc=UTC
    - AUTOWP_SENTRY_DSN=
    - AUTOWP_SENTRY_ENVIRONMENT=development
    - AUTOWP_IMAGES_DIR=/app/pictures
    - AUTOWP_MIGRATIONS_DIR=/app/migrations

  auth:
    image: autowp/auth
    container_name: autowp_test_auth
    restart: always
    volumes:
    - "./auth-config.yaml:/config.yaml:ro"
    depends_on:
    - auth-postgres
    - mysql
    expose:
    - "8080"
    ports:
    - "8080:8080"

  auth-postgres:
    image: postgres:12
    container_name: autowp_test_auth_postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=auth
      - POSTGRES_DB=auth
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: autowp_test_minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - "9000:9000"
    volumes:
      - "./minio/data:/data"
    command: server /data

  createbuckets:
    image: minio/mc
    container_name: autowp_test_createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add autowp http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb autowp/format;
      /usr/bin/mc policy set download autowp/format;
      /usr/bin/mc mb autowp/user;
      /usr/bin/mc policy set download autowp/user;
      /usr/bin/mc mb autowp/brand;
      /usr/bin/mc policy set download autowp/brand;
      /usr/bin/mc mb autowp/picture;
      /usr/bin/mc policy set download autowp/picture;
      /usr/bin/mc mb autowp/files;
      /usr/bin/mc policy set download autowp/files;
      exit 0;
      "
