name: autowp
services:
  createbuckets:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: autowp_test_createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      while ! /usr/bin/mc alias set autowp http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
        do echo 'Wait minio to startup...' && sleep 1;
      done;
      /usr/bin/mc mb autowp/format;
      /usr/bin/mc anonymous set download autowp/format;
      /usr/bin/mc mb autowp/user;
      /usr/bin/mc anonymous set download autowp/user;
      /usr/bin/mc mb autowp/brand;
      /usr/bin/mc anonymous set download autowp/brand;
      /usr/bin/mc mb autowp/picture;
      /usr/bin/mc anonymous set download autowp/picture;
      /usr/bin/mc mb autowp/files;
      /usr/bin/mc anonymous set download autowp/files;
      exit 0;
      "

  frontend:
    image: registry.pereslegin.ru/autowp/autowp/frontend:v8.21.0
    container_name: autowp_test_frontend
    depends_on:
      - goautowp-serve
    network_mode: "service:goautowp-serve"
    volumes:
      - ./frontend/dist:/app
    restart: always
    user: "101:101"
    read_only: true

  goautowp-scheduler-generate-index-cache:
    image: registry.pereslegin.ru/autowp/autowp/goautowp:v8.21.0
    container_name: autowp_test_goautowp_scheduler_generate_index_cache
    depends_on:
      - keycloak
      - rabbitmq
      - redis
      - postgres
    volumes:
      - ./goautowp-config.yaml:/config.yaml:ro
    command: scheduler-generate-index-cache --loglevel=debug

  goautowp-serve:
    image: registry.pereslegin.ru/autowp/autowp/goautowp:v8.21.0
    container_name: autowp_test_goautowp_serve
    depends_on:
      - keycloak
      - rabbitmq
      - redis
      - postgres
    volumes:
      - ./goautowp-config.yaml:/config.yaml:ro
    ports:
      - '0.0.0.0:2112:2112'
      - '0.0.0.0:2113:8080'
    command: serve --df-amqp --monitoring-amqp --grpc --public --autoban --attrs-update-values-amqp --loglevel=debug
    restart: always
    user: "0"

  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    container_name: autowp_test_keycloak
    depends_on:
      - postgres
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    ports:
      - '0.0.0.0:8081:8080'
    command:
      - "start"
      - "--import-realm"
      - "--hostname=localhost"
      - "--http-enabled=true"
      - "--db=postgres"
      - "--db-url=jdbc:postgresql://postgres:5432/keycloak"
      - "--db-username=keycloak"
      - "--db-password=password"
    restart: always

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: autowp_test_minio
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: "AKIAIOSFODNN7EXAMPLE"
      MINIO_ROOT_PASSWORD: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    ports:
      - '0.0.0.0:9000:9000'
      - '0.0.0.0:9001:9001'
    command: server --console-address ":9001" /data
    restart: always

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: autowp_test_rabbitmq
    ports:
      - '0.0.0.0:4369:4369'
      - '0.0.0.0:5671:5671'
      - '0.0.0.0:5672:5672'
      - '0.0.0.0:15671:15671'
      - '0.0.0.0:15672:15672'
      - '0.0.0.0:15691:15691'
      - '0.0.0.0:15692:15692'
      - '0.0.0.0:25672:25672'

  redis:
    image: redis:alpine
    container_name: autowp_test_redis
    restart: always
    expose:
      - '6379'
  router:
    image: nginx:1-alpine
    container_name: autowp_test_router
    depends_on:
      - frontend
      - goautowp-serve
      - keycloak
    volumes:
      - ./router.conf:/etc/nginx/nginx.conf:ro
      - ./localhost.crt:/localhost.crt
      - ./localhost.key:/localhost.key
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    restart: always

  postgres:
    image: postgis/postgis:18-3.6-alpine
    container_name: autowp_test_traffic_postgres
    volumes:
      - ./goautowp/test/postgres-initdb.d/init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql:ro
      - ./goautowp/test/postgres-initdb.d/create-keycloak-database.sh:/docker-entrypoint-initdb.d/create-keycloak-database.sh:ro
    environment:
      - POSTGRES_DB=traffic
      - POSTGRES_USER=traffic
      - POSTGRES_PASSWORD=password
      - KECYLOAK_DB_NAME=keycloak
      - KECYLOAK_DB_USER=keycloak
      - KECYLOAK_DB_PASSWORD=password
    ports:
      - '0.0.0.0:5432:5432'
    restart: always
    expose:
      - '5432'
