sonar.organization=autowp-github
sonar.projectKey=autowp_autowp
sonar.projectName=WheelsAge
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src
sonar.exclusions=frontend/src/grpc/**, frontend/src/rest/**, frontend/node_modules/**, frontend/src/app/jcrop/jquery.Jcrop.js
sonar.host.url=https://sonarcloud.io/
