<?php if ($this->formPictureVote) { ?>
    <?=$this->formPictureVote->render($this) ?>
<?php } ?>

<?php if ($this->formPictureUnvote) { ?>
    <?=$this->formPictureUnvote->render($this) ?>
<?php } ?>

<?php if (isset($this->moderVotes) && count($this->moderVotes) > 0) { ?>
    Уже подали:
    <?php $idx = 0 ?>
    <?php foreach ($this->moderVotes as $vote) { ?>
        <?php if ($idx++ > 0) { ?>, <?php } ?>
        <?php if ($user = $vote->findParentUsers()) { ?>
            <?=$this->user($user) ?>
        <?php } ?>
        <span style="color:<?=$vote->vote ? 'green' : 'red' ?>">&#xa0;(<?=$this->escape($vote->reason) ?>)</span>
    <?php } ?>
<?php } ?>

<?php if ($this->canDelete) { ?>
    <?=$this->deletePictureForm->render($this) ?>
<?php } ?>

<?php if ($this->isLastPicture) { ?>
    <p><span class="label label-warning">Это единственная принятая картинка этого автомобиля</span></p>
<?php } elseif ($this->acceptedCount !== null && $this->acceptedCount <= 4) { ?>
    <p><span class="label label-warning">Принятых картинок этого автомобиля всего <?=$this->acceptedCount ?></span></p>
<?php } ?>