<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 180,
    ));

    $this->layout()->moduleName = 'default/factory/index';
    $this->layout()->moduleOptions = array(
        'factories' => $this->factories
    );
?>

<div id="google-map" style="width:100%;height:400px;margin: 0 0 40px">карта</div>