<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 141,
        'args'   => [
            'BRAND_NAME'    => $this->brand['name'],
            'USER_NAME'     => $this->user['name'],
            'USER_IDENTITY' => $this->user['identity'] ? $this->user['identity'] : 'user' . $this->user['id'],
            'BRAND_NAME'    => $this->brand['name'],
            'BRAND_CATNAME' => $this->brand['catname']
        ]
    ]);
?>
<?=$this->partial('application/pictures', $this->picturesData)?>
<?=$this->paginationControl($this->paginator, null, null, [
    'route'     => 'users/user/pictures/brand',
    'urlParams' => $this->urlParams
]) ?>