<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 63,
        'args'   => [
            'USER_NAME'     => $this->user->name,
            'USER_IDENTITY' => $this->user->identity ? $this->user->identity : 'user' . $this->user->id,
        ]
    ]);

    $cols = 4;
    $count = count($this->brands);
    $rows = ceil($count / $cols);
?>

<?php for ($i=0; $i<$rows; $i++) { ?>
    <div class="brand-icons">
        <?php for ($j=0; $j<$cols; $j++) {
            ?><div>
                <?php
                    $idx = $j*$rows+$i;
                    $brand = $idx < $count ? $this->brands[$idx] : 0;
                ?>
                <?php if ($brand) { ?>
                    <?=$this->htmlA([
                        'href'  => $brand['url'],
                        'class' => 'brandicon brandicon-' . $brand['catname']
                    ], '') ?>
                
                    <?php
                        $image = $this->img($brand['img'], [
                            'alt'    => 'логотип '. $brand['name'],
                            'title'  => 'логотип '. $brand['name'],
                            'format' => 'brandicon'
                        ]);
                    ?>
                    <h4><?=$this->htmlA($brand['url'], $brand['name'])?> <span class="count">(<?=$brand['picturesCount'] ?>)</span></h4>
                <?php } else { ?>
                    &#xa0;
                <?php } ?>
            </div><?php 
        } ?>
    </div>
<?php } ?>
