<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => true
        ],
        'pageId' => 173,
    ]);
?>
<ul class="nav nav-pills" style="margin-bottom:10px">
    <li<?=$this->rating == 'specs' ? ' class="active"' : ''?>>
        <?=$this->htmlA($this->url('users/rating'), $this->translate('users/rating/specifications'))?>
    </li>
    <li<?=$this->rating == 'pictures' ? ' class="active"' : ''?>>
        <?=$this->htmlA($this->url('users/rating/pictures'), $this->translate('users/rating/pictures'))?>
    </li>
</ul>
<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th></th>
            <th></th>
            <th class="text-right"><?=$this->escapeHtml($this->translate($this->valueTitle))?></th>
            <?php if ($this->rating == 'specs') { ?>
                <th class="text-right"><?=$this->escapeHtml($this->translate('users/rating/specs-volume'))?></th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->users as $idx => $user) { ?>
            <tr>
                <td><?=$idx + 1?></td>
                <td><?=$this->user($user['row'])?></td>
                <td>
                    <?php if (count($user['brands'])) { ?>
                        <?php foreach ($user['brands'] as $j => $brand) {
                            if ($j != 0) { ?>, <?php }
                            echo $this->htmlA($brand['url'], $brand['name']);
                            //echo ' <span class="label label-default">'.$brand['value'] .'</span>';
                        } ?>, …
                    <?php } ?>
                </td>
                <td class="text-right"><?=number_format($user['volume'], 0 , '.', ' ')?></td>
                <?php if ($this->rating == 'specs') { ?>
                    <?php
                        if ($user['weight'] < 0.50) {
                            $class = 'danger';
                        } elseif ($user['weight'] < 1.50) {
                            $class = 'warning';
                        } else {
                            $class = '';
                        }
                    ?>
                    <td class="text-right <?=$class?>"><?=number_format($user['weight'], 2 , '.', ' ')?></td>
                <?php } ?>
            </tr>
        <?php } ?>
    </tbody>
</table>