<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 62,
        'args'   => [
            'USER_NAME'     => $this->currentUser->getCompoundName(),
            'USER_IDENTITY' => $this->currentUser->identity ? $this->currentUser->identity : 'user' . $this->currentUser->id,
        ]
    ]);

    $this->layout()->moduleName = 'default/users/user';
    $this->layout()->moduleOptions = [
        'contactApiUrl' => $this->contactApiUrl
    ];
?>
<div class="row">
    <div class="col-md-6">

        <div class="user-photo">
            <?php if ($this->currentUser->img) { ?>
                <?=$this->img($this->currentUser->img, [
                    'format' => 'photo',
                    'alt'    => 'фотография ' . $this->currentUser->getCompoundName(),
                ])?>
            <?php } elseif ($this->currentUser->e_mail) { ?>
                <?=$this->gravatar($this->currentUser->e_mail, [
                    'img_size'    => 270,
                    'default_img' => 'http://www.autowp.ru/_.gif'
                ]) ?>
            <?php } ?>
        </div>

        <p>
            Представился как: <strong>«<?=$this->escapeHtml($this->currentUser->getCompoundName()) ?>»</strong>
            <?php foreach ($this->renames as $rename) { ?>
                <div style="color:#666666;margin-left:40px;cursor:help" title="<?=$this->escapeHtmlAttr($this->user()->humanTime($rename->getDateTime('date')))?>">ранее известен как <strong style="color:#666666">«<?=$this->escapeHtml($rename->old_name) ?>»</strong></div>
            <?php } ?>
        </p>

        <p>Тип учетной записи: <strong>
        <?php if ($this->user($this->currentUser)->inheritsRole('moder')) { ?>
            Модератор
        <?php } else { ?>
            Посетитель
        <?php } ?>
        </strong></p>

        <p>
            <?=$this->escapeHtml($this->translate('users/user/registration-date'))?>:
            <strong><?=$this->escapeHtml($this->user()->humanDate($this->currentUser->getDate('reg_date')))?></strong>
        </p>
        <p>
            <?=$this->escapeHtml($this->translate('users/user/last-visited'))?>:
            <strong><?=$this->escapeHtml($this->user()->humanTime($this->currentUser->getDate('last_online')))?></strong>
        </p>
        <?php if ($this->user()->logedIn()) { ?>
            <p>
                <i class="fa fa-reply"></i>
                <?=$this->htmlA([
                    'href'         => '#',
                    'data-trigger' => 'show-pm-dialog',
                    'data-user-id' => $this->currentUser->id
                ], $this->translate('users/user/send-personal-message'))?>
            </p>
        <?php } ?>

        <?php if (count($this->accounts)) { ?>
            <?php foreach ($this->accounts as $account) { ?>
                <p>
                    <i class="fa fa-fw fa-<?=$this->escapeHtmlAttr(str_replace('googleplus', 'google-plus', $account->service_id))?>"></i>
                    <?php if ($account->link) { ?>
                        <?=$this->htmlA($account->link, $account->name)?>
                    <?php } else { ?>
                        <?=$this->escapeHtml($account->name)?>
                    <?php } ?>
                </p>
            <?php } ?>
        <?php } ?>

        <h2><?=$this->escapeHtml($this->translate('users/user/recent-activity'))?></h2>
        <div class="well">
            <?php if ($this->currentUser->pictures_added > 0) { ?>
                <p>Добавил изображений: <strong><?=$this->currentUser->pictures_added ?></strong></p>
                <?php if ($this->picturesExists < $this->currentUser->pictures_added) { ?>
                    <p>из них на сайте осталось: <strong><?=$this->picturesExists?></strong></p>
                <?php } ?>

                <p><a href="<?=$this->escapeHtmlAttr($this->url('users/user/pictures', [
                    'user_id'  => $this->currentUser->identity ? $this->currentUser->identity : 'user' . $this->currentUser->id,
                ])) ?>"><?=$this->escapeHtml($this->translate('users/user/uploaded-pictures'))?></a></p>
            <?php } else { ?>
                <p><?=$this->escapeHtml($this->translate('users/user/not-upload-pictures'))?></p>
            <?php } ?>


            <?php if ($this->user()->inheritsRole('moder')) { ?>
                <p><?=$this->htmlA($this->url('log/params', [
                    'user_id' => $this->currentUser->id
                ]), $this->translate('users/user/log')) ?></p>
            <?php } ?>
        </div>


        <?php if (count($this->last_pictures)) { ?>
            <h2><?=$this->escapeHtml($this->translate('users/user/recent-uploads'))?></h2>
            <div class="well">
                <ul>
                    <?php foreach ($this->last_pictures as $picture) { ?>
                        <li><?=$this->htmlA([
                            'href'  => $picture['url'],
                            'class' => 'picture-hover-preview'
                        ], $picture['name'])?></li>
                    <?php } ?>
                </ul>
            </div>
        <?php } ?>

        <?php if (count($this->last_comments)) { ?>
            <h2><?=$this->escapeHtml($this->translate('users/user/recent-comments'))?></h2>
            <div class="well">
                <ul class="comments">
                    <?php foreach ($this->last_comments as $comment) { ?>
                        <li>
                            <?=$this->htmlA($comment->getUrl(), $comment->getMessagePreview())?>
                        </li>
                    <?php } ?>
                    <li>&#xa0;...</li>
                </ul>
            </div>
        <?php } ?>


    </div>
    <div class="col-md-6">

        <?php if ($this->canBeInContacts) { ?>
            <div class="well">
                <button type="submit" class="btn btn-lg btn-contact<?=$this->inContacts ? ' in-contacts' : ''?>">
                    <span class="not-in-contacts">
                        <span class="fa fa-plus-circle"></span>
                        <?=$this->escapeHtml($this->translate('user/add-to-contacts'))?>
                    </span>
                    <span class="in-contacts">
                        <span class="fa fa-minus-circle"></span>
                        <?=$this->escapeHtml($this->translate('user/remove-from-contacts'))?>
                    </span>
                </button>
            </div>
        <?php } ?>

        <?php /* if ($this->currentUser->own_car || $this->currentUser->dream_car) { ?>
            <h2>Автомобиль</h2>
            <div class="well">
                <?php if ($this->currentUser->own_car) { ?>
                    <p>Личный: <strong><?=$this->escape($this->currentUser->own_car) ?></strong></p>
                <?php } ?>
                <?php if ($this->currentUser->dream_car) { ?>
                    <p>Желаемый: <strong><?=$this->escape($this->currentUser->dream_car) ?></strong></p>
                <?php } ?>
            </div>
        <?php } */ ?>

        <?php if ($this->canViewIp) { ?>
            <h2>Для модераторов</h2>
            <div class="well">
                <?php if ($this->canRemovePhoto && $this->currentUser->photo) { ?>
                    <form action="<?=$this->escapeHtmlAttr($this->url('moder/users/params', [
                        'action' => 'remove-user-photo',
                        'id'     => $this->currentUser->id
                    ]))?>" method="post">
                        <button type="submit" class="btn btn-warning btn-block">Удалить фотографию пользователя</button>
                    </form>
                <?php } ?>

                <?php if ($this->canDeleteUser) { ?>
                    <form action="<?=$this->escapeHtmlAttr($this->url('moder/users/params', [
                        'action' => 'delete-user',
                        'id'     => $this->currentUser->id
                    ]))?>" method="post">
                        <button type="submit" class="btn btn-danger btn-block">Удалить пользователя</button>
                    </form>
                <?php } ?>

                <p>
                    Последний раз заходил с IP-адреса:
                    <?=inet_ntop($this->currentUser->last_ip) ?>
                </p>

                <?php if ($this->ban) { ?>
                    <p>
                        Этот адрес забанил
                        <?php if ($this->ban['user']) { ?>
                            <?=$this->user($this->ban['user']) ?>
                        <?php } ?>
                        <?php if ($this->ban['up_to']) { ?>
                            до
                            <?=$this->escapeHtml($this->humanTime($this->ban['up_to'])) ?>
                            <?php if ($this->ban['reason']) { ?>
                                (<?=$this->escapeHtml($this->ban['reason'])?>)
                            <?php } ?>
                        <?php } ?>
                    </p>

                    <?php if ($this->canBan) { ?>
                        <form action="<?=$this->escapeHtmlAttr($this->url('ban/unban-user', [
                            'user_id' => $this->currentUser->id
                        ])) ?>" method="post" style="margin:10px 0">
                            <input type="submit" value="снять бан" />
                        </form>
                    <?php } ?>
                <?php } ?>

                <?php if ($this->canBan) { ?>
                    <form action="<?=$this->escapeHtmlAttr($this->url('ban/ban-user', [
                        'user_id' => $this->currentUser->id
                    ])) ?>" method="post" class="form-horizontal">
                        <fieldset>
                            <legend>Забанить</legend>
                            <div class="control-group">
                                <label class="control-label" for="period">На время</label>
                                <div class="controls">
                                    <?=$this->formElement((new Zend\Form\Element\Select('period'))
                                        ->setValueOptions([
                                            1  => 'час',
                                            2  => '2 часа',
                                            4  => '4 часа',
                                            8  => '8 часов',
                                            16 => '16 часов',
                                            24 => 'сутки',
                                            48 => 'двое суток',
                                        ])
                                        ->setValue('1')
                                    )?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="period">Причина</label>
                                <div class="controls">
                                    <?=$this->formElement(new Zend\Form\Element\Text('reason'))?>
                                </div>
                            </div>
                            <div class="form-actions">
                                <button class="btn btn-danger" type="submit">забанить</button>
                            </div>
                        </fieldset>
                    </form>
                <?php } ?>

            </div>
        <?php } ?>

    </div>
</div>