<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 141,
        'args'   => array(
            'BRAND_NAME'    => $this->brand->caption,
            'USER_NAME'     => $this->user->getCompoundName(),
            'USER_IDENTITY' => $this->user->identity ? $this->user->identity : 'user' . $this->user->id,
            'BRAND_NAME'    => $this->brand->caption,
            'BRAND_CATNAME' => $this->brand->folder,
        )
    ));
?>
<?=$this->pictures($this->paginator->getCurrentItems(), 6) ?>
<?=$this->paginationControl($this->paginator) ?>