<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 141,
        'args'   => array(
            'BRAND_NAME'    => $this->brand['name'],
            'USER_NAME'     => $this->user->getCompoundName(),
            'USER_IDENTITY' => $this->user->identity ? $this->user->identity : 'user' . $this->user->id,
            'BRAND_NAME'    => $this->brand['name'],
            'BRAND_CATNAME' => $this->brand['catname']
        )
    ));
?>
<?=$this->partial('pictures.phtml', $this->picturesData)?>
<?=$this->paginationControl($this->paginator) ?>