<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 116,
        'args'   => array(
            'MUSEUM_ID'   => $this->museum->id,
            'MUSEUM_NAME' => $this->museum->name,
        )
    ));

    $this->jQuery()->addJavascriptFile('http://maps.googleapis.com/maps/api/js?sensor=false');
?>
<?php $this->jQuery()->onLoadCaptureStart() ?>
$(function() {
    var startPosition = new google.maps.LatLng(55.7423627, 37.6786422);
    var lat = parseFloat($('#lat').val());
    var lng = parseFloat($('#lng').val());
    if (lng && lat) {
        startPosition = new google.maps.LatLng(lat, lng);
    }

    var node = $('<div style="width:100%; height: 300px" />').insertAfter($('#lng'))[0];
    var marker = null;

    var map = new google.maps.Map(node, {
        zoom: 2,
        center: startPosition,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    if (lng && lat) {
        setMarkerPoint(startPosition);
    }

    function setMarkerPoint(latLng) {
        if (marker) {
            marker.setPosition(latLng);
        } else {
            marker = new google.maps.Marker({
                position: latLng,
                map: map
            });
        }
    }

    function clearMarker() {
        if (marker) {
            marker.setMap(null);
            marker = null;
        }
    }

    $('#lng, #lat').change(function() {
        var lat = parseFloat($('#lat').val());
        var lng = parseFloat($('#lng').val());
        if (lng && lat) {
            var point = new google.maps.LatLng(lat, lng);
            setMarkerPoint(point);
        } else {
            clearMarker();
        }
    });

    google.maps.event.addListener(map, 'click', function(event) {
        setMarkerPoint(event.latLng);
        $('#lng').val(event.latLng.lng());
        $('#lat').val(event.latLng.lat());
    });

    $('#address').change(function() {
        $.getJSON(<?=Zend_Json::encode($this->url(array(
            'action' => 'address-to-lat-lng'
        )))?>, {address: $(this).val()}, function(point) {
            if (point) {
                var latLng = new google.maps.LatLng(point.lat, point.lng);
                setMarkerPoint(latLng);
                $('#lat').val(point.lat);
                $('#lng').val(point.lng);
            }
        });
    });
});
<?php $this->jQuery()->onLoadCaptureEnd() ?>

<div class="well">
    <?=$this->form->render($this)?>
</div>