<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 116,
        'args'   => array(
            'MUSEUM_ID'   => $this->museum->id,
            'MUSEUM_NAME' => $this->museum->name,
        )
    ));

    $this->layout()->moduleName = 'moder/museum/edit';
    $this->layout()->moduleOptions = array(
        'addressToLatLngUrl' => $this->url(array(
            'action' => 'address-to-lat-lng'
        ))
    );
?>

<div class="well">
    <?=$this->form->render($this)?>
</div>