<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 118,
    ));

    $this->layout()->moduleName = 'moder/museum/new';
    $this->layout()->moduleOptions = array(
        'addressToLatLngUrl' => $this->url(array(
            'action' => 'address-to-lat-lng'
        ))
    );
?>

<div class="well">
    <?=$this->form->render($this)?>
</div>