<ul class="nav nav-pills" style="margin-bottom:10px">
    <?php if ($this->tree['count'] > 0) { ?>
        <li class="nav-item">
            <?=$this->htmlA([
                'class' => 'nav-link' . ($this->tree['active'] ? ' active' : ''),
                'href'  => $this->url('catalogue', [
                    'action' => 'engines',
                ], [], true)
            ], '<i class="fa fa-list" aria-hidden="true"></i> ' . $this->escapeHtml($this->title) . ' <span class="badge badge-pill badge-secondary">'.$this->tree['count'].'</span>', false) ?>
        </li>
    <?php } ?>
    <?php if ($this->specs['count'] > 0) { ?>
        <li class="nav-item">
            <?=$this->htmlA([
                'class' => 'nav-link' . ($this->specs['active'] ? ' active' : ''),
                'href'  => $this->url('catalogue', [
                    'action' => 'engine-specs',
                ], [], true)
            ], '<i class="fa fa-list-alt" aria-hidden="true"></i> ' . $this->escapeHtml($this->translate('carlist/specifications')) . ' <span class="badge badge-pill badge-secondary">'.$this->specs['count'].'</span>', false) ?>
        </li>
    <?php } ?>
    <?php if ($this->cars['count'] > 0) { ?>
        <li class="nav-item">
            <?=$this->htmlA([
                'class' => 'nav-link' . ($this->cars['active'] ? ' active' : ''),
                'href'  => $this->url('catalogue', [
                    'action' => 'engine-cars',
                ], [], true)
            ], '<span class="fa fa-car" aria-hidden="true"></span> '.$this->escapeHtml($this->translate('catalogue/engine-menu/vehicles')).' <span class="badge badge-pill badge-secondary">'.$this->cars['count'].'</span>', false) ?>
        </li>
    <?php } ?>
    <?php if ($this->pictures['count'] > 0) { ?>
        <li class="nav-item">
            <?=$this->htmlA([
                'class' => 'nav-link' . ($this->pictures['active'] ? ' active' : ''),
                'href'  => $this->url('catalogue', [
                    'action' => 'engine-pictures',
                ], [], true)
            ], '<i class="fa fa-th" aria-hidden="true"></i> '.$this->escapeHtml($this->translate('catalogue/engine-menu/pictures')).' <span class="badge badge-pill badge-secondary">'.$this->pictures['count'].'</span>', false) ?>
        </li>
    <?php } ?>
</ul>
