<?php if (count($this->brands) > 1) { ?>
    <ul class="brands-switch nav nav-tabs" style="margin-bottom:0">
        <?php foreach ($this->brands as $i => $brand) { ?>
            <li<?=$brand['active'] ? ' class="active"' : ''?>><?=$this->htmlA('#', $brand['brand']->caption)?></li>
        <?php } ?>
    </ul>
<?php } ?>
<div id="BrandGroupsContainer" class="well">
    <?php foreach ($this->brands as $brand) { ?>
        <ul class="nav nav-list"<?=$brand['active'] ? '' : ' style="display:none"'?>>
            <?php foreach ($brand['groups'] as $group) { ?>
                <li<?=isset($group['childs']) && (count($group['childs']) > 0) ? ' class="dropdown-submenu"' : ''?>>
                    <?=$this->htmlA($group['url'], $this->escape($group['caption']) . (isset($group['count']) ? ' ' .$this->count($group['count']) : ''), false) ?>
                </li>
            <?php } ?>
        </ul>
    <?php } ?>
</div>