<div id="BrandGroupsContainer" class="well">
    <ul class="nav nav-pills nav-stacked">
        <?php foreach ($this->groups as $group) { ?>
            <li<?=isset($group['active']) && $group['active'] ? ' class="active"' : ''?>>
                <?=$this->htmlA($group['url'], $this->escape($group['caption']) . (isset($group['count']) ? ' ' .$this->count($group['count']) : ''), false) ?>
            </li>
        <?php } ?>
    </ul>
</div>