<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 60,
    ]);
?>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
        <?=$this->markdown($this->translate('restore-password/text'))?>
        <?=$this->partial('application/forms/bootstrap-horizontal', [
            'form' => $this->form
        ])?>
        <?php if ($this->message) { ?>
            <?php if ($this->success) { ?>
                <p class="alert alert-block alert-success"><?=$this->message ?></p>
            <?php } else { ?>
                <p class="alert alert-block alert-error"><?=$this->message ?></p>
            <?php } ?>
        <?php } ?>
    </div>
</div>