<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 134,
    ]);
?>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="well">
            <?=$this->markdown($this->translate('restore-password/new-password/text'))?>
            <?=$this->partial('application/forms/bootstrap-horizontal', [
                'form' => $this->form
            ])?>
        </div>
    </div>
</div>