<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 171,
        'args'   => [
            'ENGINE_NAME' => $this->engine->caption,
            'ENGINE_ID'   => $this->engine->id
        ]
    ]);
?>
<form action="<?=$this->escapeHtmlAttr($this->url('moder/engines/params', [
    'action'    => 'add-brand',
    'engine_id' => $this->engine->id
]))?>" method="post">
    <?php
        $columns = 6;
        $rows = ceil(count($this->brands) / $columns);
    ?>
    <div class="row">
        <div class="col-lg-2 col-md-2">
            <?php foreach ($this->brands as $idx => $brand) { ?>
                <button type="submit" name="brand_id" class="btn btn-link" value="<?=$this->escapeHtmlAttr($brand->id)?>">
                    <?=$this->escapeHtml($brand->caption)?>
                </button><br />
                <?php if ($idx && ($idx % $rows == 0)) { ?></div><div class="col-lg-2 col-md-2"><?php } ?>
            <?php } ?>
        </div>
    </div>
</form>