<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 170,
    ]);
?>
<?php if ($this->parentEngine) { ?>
    <p>
        <?=$this->escapeHtml($this->translate('moder/engines/as-subengine'))?>
        <?=$this->escapeHtml($this->parentEngine->caption)?>
    </p>
<?php } ?>
<?=$this->partial('application/forms/bootstrap-horizontal', [
    'form' => $this->form
])?>