<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ],
        'pageId' => 169,
        'args'   => [
            'ENGINE_ID'   => $this->engine->id,
            'ENGINE_NAME' => $this->engine->getMetaCaption()
        ]
    ]);
?>
<div class="row">
    <div class="col-lg-6 col-md-6">
        <div class="well">
            <p>В базе данных чиcлится под номером <strong><?=$this->engine->id ?></strong></p>
            <?php if ($lastEditor = $this->engine->findParentUsersByLast_Editor()) { ?>
                <p>Последний раз редактировал информацию: <?=$this->user($lastEditor) ?></p>
            <?php } ?>
            <p><?=$this->htmlA($this->url('log/params', [
                'engine_id' => $this->engine->id
            ]), 'Журнал событий по двигателю') ?></p>
            <p>
                <?=$this->htmlA($this->url('cars/params', [
                    'action'    => 'engine-spec-editor',
                    'engine_id' => $this->engine->id
                ]), 'Ввод ТТХ двигателя') ?>
                <?php if ($this->specsCount > 0) { ?>
                    <span class="badge"><?=$this->specsCount?></span>
                <?php } ?>
            </p>
        </div>

        <div class="well">
            <?php if ($this->canEdit) { ?>
                <?=$this->partial('application/forms/bootstrap-vertical', [
                    'form' => $this->formModerEngineEdit
                ])?>
            <?php } ?>
        </div>

        <h3>Бренды</h3>
        <div class="well">
            <table class="table table-border">
                <thead>
                    <tr>
                        <th>Бренд</th>
                        <th>На сайте</th>
                        <?php if ($this->canEdit) { ?>
                            <th>Уд.</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->brands as $brand) { ?>
                        <tr<?=$brand['inherited'] ? ' class="warning"' : ''?>>
                            <td>
                                <?=$this->htmlA($brand['moderUrl'], $brand['name'])?>
                                <?php if ($brand['inherited']) { ?>
                                    <h6><em>Inherited from <?=$this->htmlA($brand['inheritedFrom']['url'], $brand['inheritedFrom']['name'])?></em></h6>
                                <?php } ?>
                            </td>
                            <td>
                                <?php foreach ($brand['urls'] as $url) { ?>
                                    <?=$this->htmlA($url, $url)?><br />
                                <?php } ?>
                            </td>
                            <?php if ($this->canEdit) { ?>
                                <td>
                                    <?php if (!$brand['inherited']) { ?>
                                        <form action="<?=$this->escapeHtmlAttr($brand['removeUrl'])?>" method="post">
                                            <button type="submit" class="btn btn-xs btn-danger">
                                                <i class="fa fa-times"></i>
                                            </button>
                                        </form>
                                    <?php } ?>
                                </td>
                            <?php } ?>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
            <?php if ($this->canEdit) { ?>
                <form action="<?=$this->escapeHtmlAttr($this->url('moder/engines/params', [
                    'action'    => 'add-brand',
                    'engine_id' => $this->engine->id
                ]))?>" method="post">
                    <button type="submit" class="btn btn-default">Добавить бренд</button>
                </form>
            <?php } ?>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <h3>Родительский двигатель</h3>
        <div class="well">
            <?php if ($this->parentEngine) { ?>
                <?=$this->htmlA($this->url('moder/engines/params', [
                    'action'     => 'engine',
                    'engine_id'  => $this->parentEngine->id
                ]), $this->parentEngine->caption)?>
            <?php } ?>
            <?php if ($this->user()->isAllowed('engine', 'edit')) { ?>
                <?php if ($this->parentEngine) { ?>
                    <form action="<?=$this->escapeHtmlAttr($this->url('moder/engines/params', [
                        'action'    => 'cancel-parent',
                        'engine_id' => $this->engine->id
                    ]))?>" method="post">
                        <button type="submit" class="btn btn-warning">Отменить</button>
                    </form>
                <?php } ?>
                <form action="<?=$this->escapeHtmlAttr($this->url('moder/engines/params', [
                    'action'     => 'select-parent',
                    'engine_id'  => $this->engine->id
                ]))?>" method="post">
                    <button type="submit" class="btn btn-primary">Выбрать ...</button>
                </form>
            <?php } ?>
        </div>
        <h3>Подварианты двигателя</h3>
        <div class="well">
            <?php foreach ($this->childEngines as $engine) { ?>
                <?=$this->htmlA($this->url('moder/engines/params', [
                    'action'    => 'engine',
                    'engine_id' => $engine->id
                ]), $engine->caption) ?><br />
            <?php } ?>
            <?=$this->htmlA($this->url('moder/engines/params', [
                'action'    => 'add',
                'parent_id' => $this->engine->id
            ]), 'добавить двигатель ...')?>
        </div>
        <h3>Автомобили на этом двигателе</h3>
        <div class="well">
            <?php foreach ($this->cars as $car) { ?>
                <?=$this->htmlA($this->url('moder/cars/params', [
                    'action' => 'car',
                    'car_id' => $car->id
                ]), $car->getFullName()) ?><br />
            <?php } ?>
        </div>
    </div>
</div>