<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 169,
        'args'   => [
            'ENGINE_ID'   => $this->engine->id,
            'ENGINE_NAME' => $this->engine->caption
        ]
    ]);
?>
<div class="row">
    <div class="col-lg-6 col-md-6">
        <div class="well">
            <p><?=$this->escapeHtml(sprintf($this->translate('moder/database-id-%s'), $this->engine->id))?></p>
            <?php if ($lastEditor = $this->engine->findParentRow(Application\Model\DbTable\User::class, 'Last_Editor')) { ?>
                <p>
                    <?=$this->escapeHtml($this->translate('moder/engines/engine/last-edit:'))?>
                    <?=$this->user($lastEditor) ?>
                </p>
            <?php } ?>
            <p><?=$this->htmlA($this->url('log/params', [
                'engine_id' => $this->engine->id
            ]), $this->translate('moder/log-of-events')) ?></p>
            <p>
                <?=$this->htmlA($this->url('cars/params', [
                    'action'    => 'engine-spec-editor',
                    'engine_id' => $this->engine->id
                ]), $this->translate('moder/engines/engine/edit-specs')) ?>
                <?php if ($this->specsCount > 0) { ?>
                    <span class="badge"><?=$this->specsCount?></span>
                <?php } ?>
            </p>
        </div>

        <div class="well">
            <?php if ($this->canEdit) { ?>
                <?=$this->partial('application/forms/bootstrap-vertical', [
                    'form' => $this->formModerEngineEdit
                ])?>
            <?php } ?>
        </div>

        <h3><?=$this->escapeHtml($this->translate('moder/engines/engine/brands'))?></h3>
        <div class="well">
            <table class="table table-border">
                <thead>
                    <tr>
                        <th><?=$this->escapeHtml($this->translate('moder/engines/engine/brands/brand'))?></th>
                        <th><?=$this->escapeHtml($this->translate('moder/engines/engine/brands/public-url'))?></th>
                        <?php if ($this->canEdit) { ?>
                            <th><?=$this->escapeHtml($this->translate('moder/engines/engine/brands/remove'))?></th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->brands as $brand) { ?>
                        <tr<?=$brand['inherited'] ? ' class="warning"' : ''?>>
                            <td>
                                <?=$this->htmlA($brand['moderUrl'], $brand['name'])?>
                                <?php if ($brand['inherited']) { ?>
                                    <h6><em>
                                        <?=$this->escapeHtml($this->translate('moder/engines/engine/brands/inherited-from'))?>
                                        <?=$this->htmlA($brand['inheritedFrom']['url'], $brand['inheritedFrom']['name'])?>
                                    </em></h6>
                                <?php } ?>
                            </td>
                            <td>
                                <?php foreach ($brand['urls'] as $url) { ?>
                                    <?=$this->htmlA($url, $url)?><br />
                                <?php } ?>
                            </td>
                            <?php if ($this->canEdit) { ?>
                                <td>
                                    <?php if (!$brand['inherited']) { ?>
                                        <form action="<?=$this->escapeHtmlAttr($brand['removeUrl'])?>" method="post">
                                            <button type="submit" class="btn btn-xs btn-danger">
                                                <i class="fa fa-times"></i>
                                            </button>
                                        </form>
                                    <?php } ?>
                                </td>
                            <?php } ?>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
            <?php if ($this->canEdit) { ?>
                <form action="<?=$this->escapeHtmlAttr($this->url('moder/engines/params', [
                    'action'    => 'add-brand',
                    'engine_id' => $this->engine->id
                ]))?>" method="post">
                    <button type="submit" class="btn btn-default">
                        <?=$this->escapeHtml($this->translate('moder/engines/engine/brands/add'))?>
                    </button>
                </form>
            <?php } ?>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <h3><?=$this->escapeHtml($this->translate('moder/engines/engine/parent'))?></h3>
        <div class="well">
            <?php if ($this->parentEngine) { ?>
                <?=$this->htmlA($this->url('moder/engines/params', [
                    'action'     => 'engine',
                    'engine_id'  => $this->parentEngine->id
                ]), $this->parentEngine->caption)?>
            <?php } ?>
            <?php if ($this->user()->isAllowed('engine', 'edit')) { ?>
                <?php if ($this->parentEngine) { ?>
                    <form action="<?=$this->escapeHtmlAttr($this->url('moder/engines/params', [
                        'action'    => 'cancel-parent',
                        'engine_id' => $this->engine->id
                    ]))?>" method="post">
                        <button type="submit" class="btn btn-warning">
                            <?=$this->escapeHtml($this->translate('moder/engines/engine/cancel'))?>
                        </button>
                    </form>
                <?php } ?>
                <form action="<?=$this->escapeHtmlAttr($this->url('moder/engines/params', [
                    'action'     => 'select-parent',
                    'engine_id'  => $this->engine->id
                ]))?>" method="post">
                    <button type="submit" class="btn btn-primary">
                        <?=$this->escapeHtml($this->translate('moder/engines/engine/select'))?>
                    </button>
                </form>
            <?php } ?>
        </div>
        <h3><?=$this->escapeHtml($this->translate('moder/engines/engine/subengines'))?></h3>
        <div class="well">
            <?php foreach ($this->childEngines as $engine) { ?>
                <?=$this->htmlA($this->url('moder/engines/params', [
                    'action'    => 'engine',
                    'engine_id' => $engine->id
                ]), $engine->caption) ?><br />
            <?php } ?>
            <?=$this->htmlA($this->url('moder/engines/params', [
                'action'    => 'add',
                'parent_id' => $this->engine->id
            ]), $this->translate('moder/engines/add'))?>
        </div>
        <h3><?=$this->escapeHtml($this->translate('moder/engines/engine/vehicles'))?></h3>
        <div class="well">
            <?php foreach ($this->cars as $car) { ?>
                <?=$this->htmlA($this->url('moder/cars/params', [
                    'action' => 'car',
                    'car_id' => $car->id
                ]), $this->car()->htmlTitle($car->getNameData($this->language())), false) ?><br />
            <?php } ?>
        </div>
    </div>
</div>