<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 171,
        'args'   => [
            'ENGINE_NAME' => $this->engine->name,
            'ENGINE_ID'   => $this->engine->id
        ]
    ]);
?>
<form action="<?=$this->escapeHtmlAttr($this->url('moder/engines/params', [
    'action'    => 'select-parent',
    'engine_id' => $this->engine->id
]))?>" method="post">
    <?php if (!$this->brand) { ?>
        <?php
            $columns = 6;
            $rows = ceil(count($this->brands) / $columns);
        ?>
        <div class="row">
            <div class="col-lg-2 col-md-2">
                <?php foreach ($this->brands as $idx => $brand) { ?>
                    <button type="submit" name="brand_id" class="btn btn-link" value="<?=$this->escapeHtmlAttr($brand->id)?>">
                        <?=$this->escapeHtml($brand->name)?>
                    </button><br />
                    <?php if ($idx && ($idx % $rows == 0)) { ?></div><div class="col-lg-2 col-md-2"><?php } ?>
                <?php } ?>
            </div>
        </div>
    <?php } else { ?>
        <input type="hidden" name="brand_id" value="<?=$this->escapeHtmlAttr($this->brand->id)?>" />
        <?=$this->partial('application/moder/engines/select-parent-walk-tree.phtml', [
            'engines' => $this->engines
        ])?>
    <?php } ?>
</form>