<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 202
    ]);
?>
<ul>
    <?php foreach ($this->pages as $page) { ?>
        <li>
            [<?=$this->escapeHtml($page['id'])?>]
            <?=$this->escapeHtml($page['name'])?>
            <table style="margin-bottom:20px"><tr>
                <?php foreach ($page['groups'] as $group) { ?>
                    <td>
                        [<?=$this->escapeHtml($group['id'])?>]
                        <?=$this->escapeHtml($group['name'])?>
                        <ul>
                            <?php foreach ($group['perspectives'] as $perspective) { ?>
                                <li>
                                    [<?=$this->escapeHtml($perspective['id'])?>]
                                    <?=$this->escapeHtml($perspective['name'])?>
                                </li>
                            <?php } ?>
                        </ul>
                    </td>
                <?php } ?>
            </tr></table>
        </li>
    <?php } ?>
</ul>