<?php foreach ($this->attributes as $attribute) { ?>
    <tr>
        <td>
            <?=str_repeat('—', $this->deep) ?>
            <?=$this->htmlA($this->url('moder/attrs/params', [
                'attribute_id' => $attribute['id']
            ], [], true), $this->translate($attribute['name'])) ?>
        </td>
        <td>
            <?php if ($attribute['type']) { ?>
                <?=$this->escapeHtml($attribute['type']['name']) ?>
            <?php } else { ?>
                —
            <?php } ?>
        </td>
        <td>
            <?php if ($attribute['unit']) { ?>
                <?=$this->escapeHtml($this->translate($attribute['unit']['name'])) ?>
            <?php } else { ?>
                —
            <?php } ?>
        </td>
    </tr>
    <?=$this->partial('application/moder/attrs/attribute/attributes-rows-partial', [
        'attributes' => $attribute['childs'],
        'deep'       => $this->deep + 1
    ]) ?>
<?php } ?>