<?php if (count($this->attributes)) { ?>
    <ul>
        <?php foreach ($this->attributes as $idx => $attribute) { ?>
            <li>
                <?php if ($idx < count($this->attributes)-1) { ?>
                    <?=$this->htmlA($attribute['moveDownUrl'], '<span class="fa fa-arrow-down"></span>', false) ?>
                <?php } else { ?>
                    <span class="fa fa-arrow-down" style="color:#999999"></span>
                <?php } ?>
                <?php if ($idx > 0) { ?>
                    <?=$this->htmlA($attribute['moveUpUrl'], '<span class="fa fa-arrow-up"></span>', false) ?>
                <?php } else { ?>
                    <span style="color:#999999" class="fa fa-arrow-up"></span>
                <?php } ?>
                <?=$this->htmlA($this->url('moder/attrs/params', [
                    'action'       => 'attribute',
                    'attribute_id' => $attribute['id']
                ]), $this->translate($attribute['name'])) ?>
                <?=$this->partial('application/moder/attrs/attribute/attributes-partial', [
                    'attributes' => $attribute['childAttributes']
                ]) ?>
            </li>
        <?php } ?>
    </ul>
<?php } ?>