<?php foreach ($this->attributes as $attribute) { ?>
    <tr>
        <td>
            <?=str_repeat('—', $this->deep) ?>
            <?=$this->htmlA($this->url('moder/attrs/params', [
                'attribute_id' => $attribute->id
            ], [], true), $attribute->name) ?>
        </td>
        <td>
            <?php if ($type = $attribute->findParentAttrs_Types()) { ?>
                <?=$this->escapeHtml($type->name) ?>
            <?php } else { ?>
                —
            <?php } ?>
        </td>
        <td>
            <?php if ($unit = $attribute->findParentAttrs_Units()) { ?>
                <?=$this->escapeHtml($unit->name) ?>
            <?php } else { ?>
                —
            <?php } ?>
        </td>
    </tr>
    <?=$this->partial('application/moder/attrs/attribute/attributes-rows-partial', [
        'attributes' =>  $attribute->getTable()->fetchAll(
            $attribute->getTable()->select()
                ->where('parent_id = ?', $attribute->id)
        ),
        'deep'       =>  $this->deep + 1
    ]) ?>
<?php } ?>