<?php if (count($this->options)) { ?>
    <ul>
        <?php foreach ($this->options as $option) { ?>
            <li>
                <?=$this->htmlA($this->url('moder/attrs/params', [
                    'option_id' =>  $option['id']
                ], [], true), $this->translate($option['name'])) ?>
                <?=$this->partial('application/moder/attrs/attribute/options-partial', [
                    'options' => $option['childs']
                ]) ?>
            </li>
        <?php } ?>
    </ul>
<?php } ?>