<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 142,
        'args'   => array(
            'ATTR_ITEMTYPE_NAME' => $this->itemType->name,
            'ZONE_NAME'          => $this->zone->name,
            'ZONE_ID'            => $this->zone->id,
        )
    ));
?>
<div class="row">
    <div class="col-md-6">
        <h2>Аттрибуты</h2>
        <div class="well">
            <form action="<?=$this->escape($this->url(array(
                'form'  =>  'attributes'
            )))?>" method="post">
                <?=$this->partial('attrs/zone/attributes-list-partial.phtml', array(
                    'attributes'    =>  $this->attributes,
                    'zone'          =>  $this->zone
                )) ?>
                <div>
                    <input type="submit" value="Сохарнить" />
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-6">
        <h2>Порядок аттрибутов</h2>
        <div class="well">
            <table>
                <?=$this->partial('attrs/zone/attributes-rows-partial.phtml', array(
                    'attributes' => $this->zone->findAttributes(),
                    'zone'       => $this->zone,
                    'deep'       => 0
                )) ?>
            </table>

        </div>
    </div>
</div>
