<ul class="nav nav-pills" style="margin-bottom:10px">
    <?php if ($this->stock['count'] > 0) { ?>
        <li<?=$this->stock['active'] ? ' class="active"' : ''?>>
            <?=$this->htmlA($this->url(array(
                'action' => 'brand-car',
                'type'   => null,
                'page'   => 1,
            )), '<span class="glyphicon glyphicon-list"></span> ' . $this->escape($this->title) . ' <span class="badge">'.$this->stock['count'].'</span>', false) ?>
        </li>
    <?php } ?>
    <?php if ($this->tuning['count'] > 0) { ?>
        <li<?=$this->tuning['active'] ? ' class="active"' : ''?>>
            <?=$this->htmlA($this->url(array(
                'action' => 'brand-car',
                'type'   => 'tuning',
                'page'   => 1,
            )), '<span class="glyphicon glyphicon-list"></span> ' . $this->escape($this->translate('catalogue/related-with-%1$s', $this->title)) . ' <span class="badge">'.$this->tuning['count'].'</span>', false) ?>
        </li>
    <?php } ?>
    <?php if ($this->sport['count'] > 0) { ?>
        <li<?=$this->sport['active'] ? ' class="active"' : ''?>>
            <?=$this->htmlA($this->url(array(
                'action' => 'brand-car',
                'type'   => 'sport',
                'page'   => 1,
            )), '<span class="glyphicon glyphicon-list"></span> ' . $this->escape($this->translate('catalogue/sport-of-%1$s', $this->title)) . ' <span class="badge">'.$this->sport['count'].'</span>', false) ?>
        </li>
    <?php } ?>
    <?php if ($this->pictures['count'] > 0) { ?>
        <li<?=$this->pictures['active'] ? ' class="active"' : ''?>>
            <?=$this->htmlA($this->url(array(
                'action' => 'brand-car-pictures',
                'page'   => 1,
            )), '<span class="glyphicon glyphicon-th"></span> ' . $this->escape($this->translate('catalogue/all-pictures-of-%1$s', $this->title)) . ' <span class="badge">'.$this->pictures['count'].'</span>', false) ?>
        </li>
    <?php } ?>
</ul>