<?php foreach ($this->items as $item) { ?>
    <div class="car">

        <?php if (!$this->disableTitle) { ?>
            <h3>
                <?=$this->car($item['row'])->title()?>
                <?php if ($item['designProject']) { ?>
                    <sup class="designBrand"><?=sprintf($this->translate('carlist/designed by %s'), $this->htmlA($item['designProject']['url'], $item['designProject']['brandName']))?></sup>
                <?php } ?>
                <?php if ($item['produced'] > 0) { ?>
                    <small>
                        <?php if ($item['produced'] > 1) { ?>
                            <?=$this->escape(
                                $this->translate(array(
                                    $item['produced_exactly'] ? 'carlist/produced/%1$s' : 'carlist/produced-about/%1$s',
                                    null,
                                    $item['produced']
                                ), Zend_Locale_Format::toNumber($item['produced']))
                            )?>
                        <?php } else {?>
                            <?=$this->escape($this->translate('carlist/produced/one'))?>
                        <?php } ?>
                    </small>
                <?php } ?>
            </h3>
        <?php } ?>

        <?php if ($item['langName'] && ($item['name'] != $item['langName'])) { ?>
            <h4><?=$this->escape($item['langName'])?></h4>
        <?php } ?>

        <div class="row thumbnails">
            <?php foreach ($item['pictures'] as $idx => $picture) { ?>
                <?php
                    $col = $item['largeFormat'] && $idx == 0  ? 6 : 3;
                    $colSm = $item['largeFormat'] && $idx == 0  ? 12 : 6;
                ?>
                <div class="col-lg-<?=$col?> col-md-<?=$col?> col-sm-<?=$colSm?>">
                    <?php if ($picture) { ?>
                        <?=$this->htmlA(
                            array(
                                'href'  => $picture['url'],
                                'class' => 'thumbnail'
                            ),
                            $this->htmlImg(array(
                                'src'   => $picture['src'],
                                'alt'   => $picture['name'],
                                'title' => $picture['name'],
                            )),
                            false
                        )?>
                    <?php } else { ?>
                        <div class="no-photo">&#xa0;</div>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>


        <?php if (!$this->disableDescription && strlen($item['description'])) { ?>
            <div class="text"><?=$item['description']?></div>
        <?php } ?>

        <ul class="list-inline">

            <?php if (!$this->disableDetailsLink && ($item['hasHtml'] || $item['childsCount']) && isset($item['details']['url'])) { ?>
                <li>
                    <span class="glyphicon glyphicon-align-left"></span>
                    <?=$this->htmlA($item['details']['url'], $this->translate('carlist/details') . ( $item['childsCount'] > 1 ? ' (' . $item['childsCount'] . ')' : '')) ?>
                </li>
            <?php } ?>

            <?php if (isset($item['tuning']) && $item['tuning']) { ?>
                <li>
                    <span class="glyphicon glyphicon-align-left"></span>
                    <?=$this->htmlA($item['tuning']['url'], mb_strtolower($this->translate('catalogue/related')) . ' ('.$item['tuning']['count'].')')?>
                </li>
            <?php } ?>

            <?php if (isset($item['sport']) && $item['sport']) { ?>
                <li>
                    <span class="glyphicon glyphicon-align-left"></span>
                    <?=$this->htmlA($item['sport']['url'], mb_strtolower($this->translate('catalogue/sport')) . ' ('.$item['sport']['count'].')')?>
                </li>
            <?php } ?>

            <?php if (isset($item['allPicturesUrl']) && $item['allPicturesUrl']) { ?>
                <li>
                    <span class="fa fa-th"></span>
                    <?=$this->htmlA($item['allPicturesUrl'], $this->translate('carlist/all pictures').' ('.$item['totalPictures'].')')?>
                </li>
            <?php } ?>

            <?php if (count($item['specsLinks']) > 1) { ?>
                <li>
                    <span class="glyphicon glyphicon-list-alt"></span>
                    <?=$this->escape($this->translate('carlist/specifications'))?>
                    <?php foreach ($item['specsLinks'] as $specLink) { ?>
                        <?=$this->htmlA($specLink['url'], $specLink['name'])?>
                    <?php } ?>
                </li>
            <?php } else { ?>
                <?php foreach ($item['specsLinks'] as $specLink) { ?>
                    <li>
                        <span class="glyphicon glyphicon-list-alt"></span>
                        <?=$this->htmlA($specLink['url'], $this->translate('carlist/specifications'))?>
                    </li>
                <?php } ?>
            <?php } ?>

            <?php if (isset($item['twinsGroups'])) { ?>
                <?php foreach ($item['twinsGroups'] as $twinsGroup) { ?>
                    <li>
                        <span class="glyphicon glyphicon-adjust"></span>
                        <?=$this->htmlA($twinsGroup['url'], $this->translate('carlist/twins')) ?>
                    </li>
                <?php } ?>
            <?php } ?>

            <?php foreach ($item['categories'] as $category) { ?>
                <li>
                    <span class="glyphicon glyphicon-tag"></span>
                    <?=$this->htmlA($category['url'], $category['name'])?>
                </li>
            <?php } ?>

            <?php if ($this->isCarModer) { ?>
                <li>
                    <span class="glyphicon glyphicon-cog"></span>
                    <?=$this->htmlA($item['moderUrl'], 'управление') ?>
                </li>
            <?php } ?>

            <?php if ($this->specEditor) { ?>
                <li>
                    <span class="glyphicon glyphicon-pencil"></span>
                    <?=$this->htmlA($item['specEditorUrl'], $this->translate('carlist/edit-specs')) ?>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>