<?php if ($this->pageCount > 1) { ?>
    <?php $format = '%0'.max(2, strlen($this->pageCount)).'d' ?>
    <div id="pager" style="clear:both">
        <div class="numberLinks">
            <?php if (isset($this->previous)) { ?>
                <?=$this->htmlA($this->url(array(
                    'page' => $this->previous
                )), '←' . $this->translate('previous')) ?>
            <?php } else { ?>
                ←<?=$this->escape($this->translate('previous')) ?>
            <?php } ?>
            <?php if ($this->firstPageInRange > $this->first+1) { ?>
                <?=$this->htmlA($this->url(array(
                    'page' => $this->first
                )), sprintf($format, $this->first)) ?>
                …
            <?php } ?>
            <?php foreach ($this->pagesInRange as $page) { ?>
                <?php if ($page != $this->current) { ?>
                    <?=$this->htmlA($this->url(array(
                        'page' => $page
                    )), sprintf($format, $page)) ?>
                <?php } else { ?>
                    <strong style="font-size:20px;margin:0 3px"><?php echo sprintf($format, $page) ?></strong>
                <?php } ?>
            <?php } ?>
            <?php if ($this->lastPageInRange < $this->last-1) { ?>
                …
                <?=$this->htmlA($this->url(array(
                    'page' => $this->last
                )), sprintf($format, $this->last)) ?>
            <?php } ?>
            <?php if (isset($this->next)) { ?>
                <?=$this->htmlA($this->url(array(
                    'page' => $this->next
                )), $this->translate('next') . '→') ?>
            <?php } else { ?>
                <?=$this->escape($this->translate('next')) ?>→
            <?php } ?>
        </div>
    </div>
<?php } ?>