<?php
    $classes = array('picture-preview');
    if (isset($this->colClass)) {
        $classes[] = $this->colClass;
    }
    if ($this->moderVote !== null) {
        if ($this->moderVote > 0) {
            $classes[] = 'vote-accept';
        } elseif ($this->moderVote < 0) {
            $classes[] = 'vote-remove';
        } else {
            $classes[] = 'vote-neutral';
        }
    }
?>
<div class="<?=$this->escape(implode(' ', $classes))?>">
    <div class="thumbnail">
        <?=$this->htmlA($this->url, $this->htmlImg(array(
            'src'     => $this->src,
            //'alt'     => $this->name,
            //'title'   => $this->name,
            'shuffle' => true
        )), false) ?>
        <div class="caption">
            <p>
                <?php if (($this->type == Picture::CAR_TYPE_ID) && is_array($this->name)) { ?>
                    <?=$this->htmlA($this->url, $this->car()->htmlTitle($this->name), false)?>
                <?php } else { ?>
                    <?=$this->htmlA($this->url, $this->name)?>
                <?php } ?>
            </p>
            <?php if (!$this->disableBehaviour) { ?>
                <?=$this->render('picture-behaviour.phtml')?>
            <?php } ?>
        </div>
    </div>
</div>