<p class="picture-behaviour">
    <?php if ($this->isModer) { ?>
        <span title="Status">
            <?php
                switch ($this->status) {
                    case Picture::STATUS_ACCEPTED: ?><i class="fa fa-check text-success"></i><?php break;
                    case Picture::STATUS_NEW:      ?><i class="fa fa-hourglass text-warning"></i><?php break;
                    case Picture::STATUS_INBOX:    ?><i class="fa fa-hourglass text-warning"></i><?php break;
                    case Picture::STATUS_REMOVED:  ?><i class="fa fa-trash text-danger"></i><?php break;
                    case Picture::STATUS_REMOVING: ?><i class="fa fa-trash text-danger"></i><?php break;
                }
            ?>
        </span>
    <?php } ?>

    <span title="<?=$this->escape($this->translate('Resolution'))?>">
        <?=$this->escape($this->resolution)?>
        <?php if ($this->isModer && $this->cropped) { ?>
            <i class="fa fa-scissors" style="cursor:help" title="На картинке выделена область автомобиля (<?=$this->escape($this->cropResolution)?>)"></i>
        <?php } ?>
        <?php /*<i class="fa fa-file-image-o"></i>*/?>
    </span>

    <span class="pull-right">

        <span title="<?=$this->escape($this->translate('Views'))?>">
            <?=$this->escape($this->views > 1000 ? round($this->views / 1000) . 'K' : $this->views)?>
            <i class="fa fa-eye"></i>
        </span>

        <span title="<?=$this->escape($this->translate('Comments count'))?>">
            <?php if ($this->newMsgCount > 0) { ?>
                <?=$this->htmlA(
                    $this->url. '#comments',
                    ($this->msgCount > $this->newMsgCount ? $this->msgCount - $this->newMsgCount : '') .
                    '<span class="text-danger">' . $this->escape('+'.$this->newMsgCount) .'</span> ' .
                    '<i class="fa fa-comment text-danger"></i>',
                    false
                )?>
            <?php } elseif ($this->msgCount > 0) { ?>
                <?=$this->htmlA($this->url. '#comments', $this->msgCount . ' <i class="fa fa-comment"></i>', false)?>
            <?php } else { ?>

            <?php } ?>
        </span>
    </span>
</p>