<table class="table table-condensed table-striped table-bordered" style="width:auto">
    <thead>
        <tr>
            <td></td>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <td>
                    <?=$this->escape($car['name'])?>
                </td>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <td style="padding:0">
                    <?php if ($car['topPicture']) { ?>
                        <?=$this->htmlA($this->pic($car['topPicture'])->url(), $this->image($car['topPicture'], 'file_name', array(
                            'format'  => 6,
                            'shuffle' => true
                        )), false)?>
                    <?php } ?>
                </td>
            <?php } ?>
        </tr>
        <?php foreach ($this->table->getAttributes() as $attribute) { ?>
            <tr>
                <th colspan="<?=count($this->table->getCars()) + 1?>"><?=$this->escape($attribute['name'])?></th>
            </tr>
            <?php foreach ($attribute['childs'] as $child) { ?>
                <?=$this->partial('specs-row.phtml', array(
                    'attribute' => $child,
                    'table'     => $this->table,
                    'deep'      => 0
                ))?>
            <?php } ?>
        <?php } ?>
        <tr>
            <td></td>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <td style="padding:0">
                    <?php if ($car['bottomPicture']) { ?>
                        <?=$this->htmlA($this->pic($car['bottomPicture'])->url(), $this->image($car['bottomPicture'], 'file_name', array(
                            'format'  => 6,
                            'shuffle' => true
                        )), false)?>
                    <?php } ?>
                </td>
            <?php } ?>
        </tr>
        <?php if ($this->user()->isAllowed('specifications', 'edit')) { ?>
            <td></td>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <td>
                    <?=$this->htmlA($this->url(array(
                        'module'     => 'default',
                        'controller' => 'cars',
                        'action'     => 'car-specifications-editor',
                        'car_id'     => $car['id']
                    ), 'default', true), 'ввод ттх')?>
                </td>
            <?php } ?>
        <?php } ?>
    </tbody>
</table>
<?php /*
<div class="authors">
    (count($authors) > 1 ? 'Составители' : 'Составитель'). ': ' . implode(', ', $authors) .
</div>
*/?>