<table class="table table-condensed table-striped table-bordered" style="width:auto" data-specs="1">
    <thead>
        <tr>
            <th></th>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <th><?=$this->escape($car['name'])?></th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <td style="padding:0">
                    <?php if ($car['topPicture']) { ?>
                        <?=$this->htmlA(
                            $this->pic($car['topPicture'])->url(),
                            $this->img($car['topPicture']->getFormatRequest(), array(
                                'format'  => 'picture-thumb',
                                'shuffle' => true
                            )),
                            false
                        )?>
                    <?php } ?>
                </td>
            <?php } ?>
        </tr>
        <tr>
            <td></td>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <td>
                    <?php if ($car['beginYear'] || $car['endYear']) { ?>
                        <?php if ($car['beginYear'] != $car['endYear']) { ?>
                            <?=$car['beginYear']?>–<?=$car['endYear']?>
                        <?php } else { ?>
                            <?=$car['beginYear']?>
                        <?php } ?>
                    <?php } ?>
                </td>
            <?php } ?>
        </tr>
        <?php foreach ($this->table->getAttributes() as $attribute) { ?>
            <?php if (count($attribute['childs'])) { ?>
                <tr>
                    <th colspan="<?=count($this->table->getCars()) + 1?>"><?=$this->escape($attribute['name'])?></th>
                </tr>
                <?php foreach ($attribute['childs'] as $child) { ?>
                    <?=$this->partial('specs-row.phtml', array(
                        'attribute' => $child,
                        'table'     => $this->table,
                        'deep'      => 0
                    ))?>
                <?php } ?>
            <?php } else { ?>
                <?=$this->partial('specs-row.phtml', array(
                    'attribute' => $attribute,
                    'table'     => $this->table,
                    'deep'      => 0
                ))?>
            <?php } ?>
        <?php } ?>
        <tr>
            <td></td>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <td style="padding:0">
                    <?php if ($car['bottomPicture']) { ?>
                        <?=$this->htmlA(
                            $this->pic($car['bottomPicture'])->url(),
                            $this->img($car['bottomPicture']->getFormatRequest(), array(
                                'format'  => 'picture-thumb',
                                'shuffle' => true
                            )),
                            false
                        )?>
                    <?php } ?>
                </td>
            <?php } ?>
        </tr>
        <?php if ($this->user()->isAllowed('specifications', 'edit')) { ?>
            <td></td>
            <?php foreach ($this->table->getCars() as $car) { ?>
                <td>
                    <?=$this->htmlA($this->url(array(
                        'module'     => 'default',
                        'controller' => 'cars',
                        'action'     => 'car-specifications-editor',
                        'car_id'     => $car['id']
                    ), 'default', true), $this->translate('carlist/edit-specs'))?>
                </td>
            <?php } ?>
        <?php } ?>
    </tbody>
</table>
<?php /*
<div class="authors">
    (count($authors) > 1 ? 'Составители' : 'Составитель'). ': ' . implode(', ', $authors) .
</div>
*/?>