<table class="table table-condensed table-striped table-bordered" style="width:auto" data-specs="1">
    <thead>
        <tr>
            <td></td>
            <?php foreach ($this->table->getEngines() as $engine) { ?>
                <td>
                    <?=$this->escape($engine['name'])?>
                </td>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <?php foreach ($this->table->getEngines() as $engine) { ?>
                <td style="padding:0">
                    <?php if ($engine['picture']) { ?>
                        <?=$this->htmlA(
                            $this->pic($engine['picture'])->url(),
                            $this->img($engine['picture']->getFormatRequest(), array(
                                'format'  => 'picture-thumb',
                                'shuffle' => true
                            )),
                            false
                        )?>
                    <?php } ?>
                </td>
            <?php } ?>
        </tr>
        <?php foreach ($this->table->getAttributes() as $attribute) { ?>
            <?php if (count($attribute['childs'])) { ?>
                <tr>
                    <th colspan="<?=count($this->table->getEngines()) + 1?>"><?=$this->escape($attribute['name'])?></th>
                </tr>
                <?php foreach ($attribute['childs'] as $child) { ?>
                    <?=$this->partial('specs-engine-row.phtml', array(
                        'attribute' => $child,
                        'table'     => $this->table,
                        'deep'      => 0
                    ))?>
                <?php } ?>
            <?php } else { ?>
                <?=$this->partial('specs-row.phtml', array(
                    'attribute' => $attribute,
                    'table'     => $this->table,
                    'deep'      => 0
                ))?>
            <?php } ?>
        <?php } ?>
        <?php if ($this->user()->isAllowed('specifications', 'edit')) { ?>
            <td></td>
            <?php foreach ($this->table->getEngines() as $engine) { ?>
                <td>
                    <?=$this->htmlA($this->url(array(
                        'module'     => 'default',
                        'controller' => 'cars',
                        'action'     => 'engine-spec-editor',
                        'engine_id'  => $engine['id']
                    ), 'default', true), 'ввод ттх')?>
                </td>
            <?php } ?>
        <?php } ?>
    </tbody>
</table>
<?php /*
<div class="authors">
    (count($authors) > 1 ? 'Составители' : 'Составитель'). ': ' . implode(', ', $authors) .
</div>
*/?>