<tr>
    <td style="padding-left:<?=5 + $this->deep*16?>px">
        <?=$this->escape($this->attribute['name'])?>
    </td>
    <?php foreach ($this->table->getEngines() as $engine) { ?>
        <td data-specs-attr="<?=$this->attribute['id']?>" data-specs-item="<?=$engine['id']?>">
            <?=$this->table->renderValue($this, $this->attribute, $engine) ?>
        </td>
    <?php } ?>
</tr>
<?php if (!$this->table->preventedRenderSubAttributes($this->attribute['id'])) { ?>
    <?php foreach ($this->attribute['childs'] as $child) { ?>
        <?=$this->partial('specs-engine-row.phtml', array(
            'attribute' => $child,
            'table'     => $this->table,
            'deep'      => $this->deep + 1
        ))?>
    <?php } ?>
<?php } ?>