#!/bin/bash

set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database role: ${KECYLOAK_DB_USER}"

$POSTGRES <<-EOSQL
CREATE USER ${KECYLOAK_DB_USER} WITH CREATEDB PASSWORD '${KECYLOAK_DB_PASSWORD}';
EOSQL

echo "Creating database: ${KECYLOAK_DB_NAME}"

$POSTGRES <<EOSQL
CREATE DATABASE ${KECYLOAK_DB_NAME} OWNER ${KECYLOAK_DB_USER};
EOSQL
