<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageTitle' => '',
        'pageId' => 117,
    ]);

    $this->layout()->moduleName = 'default/map/index';
?>
<div class="page-header">
    <h1><?=$this->escapeHtml($this->page(117)->name)?> <small><?=$this->escapeHtml($this->translate('map/museums-and-factories'))?></small></h1>
</div>
<div id="google-map" style="width:100%;height:600px;margin: 0 0 40px"></div>