<h1>Combinations <small><?=count($this->combinations)?></small></h1>
<table class="table table-hover table-condensed">
    <tbody>
        <?php foreach ($this->combinations as $combination) { ?>
            <tr <?=isset($combination['active']) && $combination['active'] ? ' class="success"' : ''?>>
                <td><input type="checkbox" /></td>
                <?php foreach ($combination as $id) { ?>
                    <td><?=$this->escape($this->names[$id])?></td>
                <?php } ?>
            </tr>
        <?php } ?>
    </tbody>
</table>