<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 212,
    ]);
?>

<table class="table">
    <?php foreach ($this->reasons as $reason) { ?>
        <tr>
            <td>
                <?php if ($reason['vote'] > 0) { ?>
                    <i class="fa fa-thumbs-up text-success"></i>
                <?php } else { ?>
                    <i class="fa fa-thumbs-down text-danger"></i>
                <?php } ?>
            </td>
            <td><?=$this->escapeHtml($reason['reason'])?></td>
            <td>
                <form action="<?=$this->escapeHtmlAttr($this->url('moder/picture-vote-template/params', [
                    'action' => 'delete'
                ]))?>" method="post">
                    <input type="hidden" name="id" value="<?=$reason['id']?>" />
                    <button type="submit" class="btn btn-xs btn-danger">
                        <span class="fa fa-times"></span>
                    </button>
                </form>
            </td>
        </tr>
    <?php } ?>
</table>

<?=$this->partial('application/forms/bootstrap-horizontal', [
    'form' => $this->form
])?>