<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 74,
    ));
?>
<div class="well">
    <?php foreach ($this->groups as $group) { ?>
        <div class="btn-group">
            <?php foreach ($group as $char) { ?>
                <?=$this->htmlA(array(
                    'class' => 'btn btn-default',
                    'href'  => $this->url(array('char' => $char)),
                ), $char) ?>
            <?php } ?>
        </div>
    <?php } ?>
</div>

<?php if ($this->char) { ?>
    <h3>Автомобили</h3>
    <div class="well">
        <?php foreach ($this->cars as $car) { ?>
            <?=$this->htmlA($this->url(array(
                'action' => 'car',
                'car_id' => $car->id
            )), $car->getFullName()) ?>
            <br />
        <?php } ?>
    </div>
<?php } ?>