<?php if (count($this->categories)) { ?>
    <ul class="checkbox-tree">
        <?php foreach ($this->categories as $category) { ?>
            <li<?=$category['checked'] || $category['active'] ? ' class="active"' : ''?>>
                <?php if (count($category['categories'])) { ?>
                    <i class="fa fa-plus-circle"></i>
                    <i class="fa fa-minus-circle"></i>
                    <?=$this->escape($category['name'])?>
                <?php } else { ?>
                    <label class="checkbox inline">
                        <input type="checkbox" name="category[]" value="<?=$category['id']?>" <?=$category['checked'] ? 'checked="checked"' : ''?> <?=$category['inherited'] ? 'disabled="disabled"' : ''?> />
                        <?=$this->escape($category['name'])?>
                    </label>
                <?php } ?>

                <?php if ($category['inherited']) { ?>
                    <?php if (count($category['inheritedFrom']) > 0) { ?>
                        <h6><em>
                            Inherited from
                            <?php foreach ($category['inheritedFrom'] as $car) { ?>
                                <?=$this->htmlA($car['url'], $car['name'])?>
                            <?php } ?>
                        </em></h6>
                    <?php } ?>
                <?php } else {?>
                    <?php if ($category['user']) { ?>
                        <?=$this->user($category['user'])?>
                    <?php } ?>
                <?php } ?>

                <?=$this->partial('cars/car-categories-tree.phtml', array(
                    'parent'     => $category,
                    'categories' => $category['categories'],
                ))?>
            </li>
        <?php } ?>
        <?php if (isset($this->parent) && $this->parent) { ?>
            <li>
                <label class="checkbox inline">
                    <input type="checkbox" name="category[]" value="<?=$this->parent['id']?>" <?=$this->parent['checked'] ? 'checked="checked"' : ''?> />
                    Other
                </label>
            </li>
        <?php } ?>
    </ul>
<?php } ?>