<?php
    $this->layout()->disableLayout();
?>

<?php if ($this->canUseTree) { ?>
    <h4>Структура</h4>
    <div class="btn-group">
        <?=$this->htmlA(array(
            'href'  => $this->url(array(
                'action'    => 'organize',
            )),
            'class' => 'btn btn-default',
        ), 'Турбо объединятор в группы')?>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Название</th>
                <th>Связь</th>
                <th>Папка</th>
                <th>На сайте</th>
                <?php if ($this->canMove) { ?>
                    <th>Уд.</th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <form class="car-add-parent" method="post" action="<?=$this->escape($this->url(array(
                        'action' => 'add-parent',
                    ))) ?>">
                        <div class="input-group" style="max-width:400px">
                            <span class="input-group-btn">
                                <?=$this->htmlA(array(
                                    'href' => $this->url(array(
                                        'action'    => 'car-select-parent',
                                        'brand_id'  => null,
                                        'parent_id' => null
                                    )),
                                    'class' => 'btn btn-success',
                                ), 'Выбрать ...')?>
                            </span>
                            <?=$this->formText('parent', null, array(
                                'class'             => 'form-control',
                                'placeholder'       => 'Добавить родителя ...',
                                'data-autocomplete' => $this->url(array(
                                    'action'        => 'car-autocomplete',
                                    'exclude-child' => $this->car['id']
                                ))
                            ))?>
                        </div>
                    </form>
                </td>
                <td></td>
                <td></td>
                <td></td>
                <?php if ($this->canMove) { ?>
                    <td></td>
                <?php } ?>
            </tr>
            <?php foreach ($this->parents as $car) { ?>
                <tr data-id="<?=$car['id']?>">
                    <td>
                        <i class="fa fa-arrow-up"></i>
                        <?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?>
                        <?php if ($car['duplicateRow']) { ?>
                            <br />
                            <div class="text-warning"><small>Возможно повтор: автомобиль уже унаследован через: <?=$this->escape($car['duplicateRow']->getFullName())?></small></div>
                        <?php } ?>
                    </td>
                    <td>
                        <form class="car-parent-type" method="post" action="<?=$this->escape($car['typeUrl']) ?>">
                            <?=$this->formSelect('type', $car['parent']['type'], array(
                                'class' => 'form-control input-sm'
                            ), $this->carParentTypeOptions)?>
                        </form>
                    </td>
                    <td>
                        <form class="car-parent-catname" method="post" action="<?=$this->escape($car['catnameUrl']) ?>">
                            <div class="input-group" style="max-width:200px">
                                <?=$this->formText('name', $car['parent']['name'], array(
                                    'class'       => 'form-control input-sm',
                                    'placeholder' => 'Название'
                                ))?>
                                <span class="input-group-btn" style="width:0px;"></span>
                                <?=$this->formText('catname', $car['parent']['catname'], array(
                                    'class'       => 'form-control input-sm',
                                    'placeholder' => 'часть URL'
                                ))?>
                                <span class="input-group-btn">
                                    <button class="btn btn-sm btn-default" type="submit">Ok</button>
                                </span>
                            </div>
                        </form>
                    </td>
                    <td class="urls">
                        <?php foreach ($car['publicUrls'] as $url) { ?>
                            <?=$this->htmlA($url, $url)?><br />
                        <?php } ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td>
                            <form action="<?=$this->escape($car['deleteUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-sm btn-danger">
                                    <i class="fa fa-times"></i>
                                </button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <tr class="success" data-id="<?=$this->car['id']?>">
                <td><?=$this->car()->htmlTitle($this->car->getNameData($this->language()->get()))?></td>
                <td></td>
                <td></td>
                <td class="urls">
                    <?php foreach ($this->publicUrls as $url) { ?>
                        <?=$this->htmlA($url, $url)?><br />
                    <?php } ?>
                </td>
                <?php if ($this->canMove) { ?>
                    <td></td>
                <?php } ?>
            </tr>
            <?php foreach ($this->childs as $car) { ?>
                <tr data-id="<?=$car['id']?>">
                    <td>
                        <i class="fa fa-arrow-down"></i>
                        <?php if ($car['parent']['type'] == Car_Parent::TYPE_TUNING) { ?>
                            <?=$this->escape($this->translate('catalogue/related'))?>:
                        <?php } elseif ($car['parent']['type'] == Car_Parent::TYPE_DESIGN) { ?>
                            Дизайн:
                        <?php } elseif ($car['parent']['type'] == Car_Parent::TYPE_SPORT) { ?>
                            Спорт:
                        <?php } ?>
                        <?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?>
                        <?php if ($car['duplicateRow']) { ?>
                            <br />
                            <div class="text-warning"><small>Возможно повтор: автомобиль уже содержится в подразделе: <?=$this->escape($car['duplicateRow']->getFullName())?></small></div>
                        <?php } ?>
                    </td>
                    <td>
                        <form class="car-parent-type" method="post" action="<?=$this->escape($car['typeUrl']) ?>">
                            <?=$this->formSelect('type', $car['parent']['type'], array(
                                'class' => 'form-control input-sm'
                            ), $this->carParentTypeOptions)?>
                        </form>
                    </td>
                    <td>
                        <form class="car-parent-catname" method="post" action="<?=$this->escape($car['catnameUrl']) ?>">
                            <div class="input-group" style="max-width:200px">
                                <?=$this->formText('name', $car['parent']['name'], array(
                                    'class'       => 'form-control input-sm',
                                    'placeholder' => 'Название'
                                ))?>
                                <span class="input-group-btn" style="width:0px;"></span>
                                <?=$this->formText('catname', $car['parent']['catname'], array(
                                    'class'       => 'form-control input-sm',
                                    'placeholder' => 'часть URL'
                                ))?>
                                <span class="input-group-btn">
                                    <button class="btn btn-sm btn-default" type="submit">Ok</button>
                                </span>
                            </div>
                        </form>
                    </td>
                    <td class="urls">
                        <?php foreach ($car['publicUrls'] as $url) { ?>
                            <?=$this->htmlA($url, $url)?><br />
                        <?php } ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td>
                            <form action="<?=$this->escape($car['deleteUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-sm btn-danger">
                                    <i class="fa fa-times"></i>
                                </button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>

            <?php if ($this->canMove) { ?>
                <tr>
                    <td>
                        <i class="fa fa-plus"></i>
                        <?=$this->htmlA($this->url(array(
                            'module'     => 'moder',
                            'controller' => 'cars',
                            'action'     => 'new',
                            'parent_id'     => $this->car->id
                        ), 'default', true), 'добавить автомобиль')?>
                    </td>
                    <td></td>
                    <td></td>
                    <td class="urls"></td>
                    <?php if ($this->canMove) { ?>
                        <td></td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php } ?>


<h4>Бренды, связанные с этим автомобилем</h4>
<?php if (count($this->brands) || count($this->inheritBrands)) { ?>
    <table class="table table-striped" id="carModelTable">
        <thead>
            <tr>
                <th>Бренд</th>
                <th></th>
                <th></th>
                <th>На сайте</th>
                <?php if ($this->canMove) { ?>
                    <th>Уд.</th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->brands as $brand) { ?>
                <tr>
                    <td>
                        <?=$this->htmlA($brand['moderUrl'], $brand['name']) ?>
                    </td>
                    <td>
                        <?php if ($this->canMove) { ?>
                            <form action="<?=$this->escape($brand['setBrandCarTypeUrl']) ?>" method="post" class="inline brand-car-type">
                                <?=$this->formSelect('type', $brand['type'], [
                                    'class' => 'form-control'
                                ], $this->brandCarTypeOptions)?>
                            </form>
                        <?php } else { ?>
                            <?=$this->escape($this->brandCarTypeOptions[$brand['type']])?>
                        <?php } ?>
                    </td>
                    <td>
                        <?php if ($this->canMove) { ?>
                            <form action="<?=$this->escape($brand['setBrandCarCatnameUrl']) ?>" method="post" class="inline brand-car-catname">
                                <div class="input-group" style="max-width:200px">
                                    <?=$this->formText('catname', $brand['catname'], array(
                                        'class' => 'form-control'
                                    ))?>
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="submit">Ok</button>
                                    </span>
                                </div>
                            </form>
                        <?php } else { ?>
                            <?=$this->escape($brand['catname'])?>
                        <?php } ?>
                    </td>
                    <td>
                        <?=$this->htmlA($brand['url'], $brand['url']) ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td>
                            <form action="<?=$this->escape($brand['deleteUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-times"></i></button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <?php foreach ($this->inheritBrands as $brand) { ?>
                <tr class="warning">
                    <td>
                        <?=$this->htmlA($brand['moderUrl'], $brand['name']) ?>
                        <h6><em>Inherited from <?=$this->htmlA($brand['car']['url'], $brand['car']['name'])?></em></h6>
                    </td>
                    <td>
                        <?=$this->escape($this->brandCarTypeOptions[$brand['type']])?>
                    </td>
                    <td>
                        <?=$this->escape($brand['catname'])?>
                    </td>
                    <td>
                        <?=$this->htmlA($brand['url'], $brand['url']) ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td></td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php } ?>
<?php if ($this->canMove) { ?>
    <form action="<?=$this->escape($this->url(array(
        'module'     => 'moder',
        'controller' => 'cars',
        'action'     => 'car-select-brand',
        'car_id'     => $this->car->id
    ))) ?>" method="post"><div>
        <button type="submit" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> Бренд ...</button>
    </div></form>
    <?php foreach ($this->relevantBrands as $brand) { ?>
        <form action="<?=$this->escape($this->url(array(
            'module'     => 'moder',
            'controller' => 'cars',
            'action'     => 'car-select-brand',
            'car_id'     => $this->car->id,
            'brand_id'   => $brand->id
        ))) ?>" method="post">
            <button type="submit" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> Бренд <?=$this->escape($brand->caption)?></button>
        </form>
    <?php } ?>
<?php } ?>

<h4>Проекты дизайна, связанные с этим автомобилем</h4>
<?php if ($this->designProject || $this->inheritDesignProjects) { ?>
    <table class="table table-striped" id="carDesignProjectTable">
        <thead>
            <tr>
                <th>Бренд</th>
                <th>Проект</th>
                <th>На сайте</th>
                <?php if ($this->canMove) { ?>
                    <th>Уд.</th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <?php if ($this->designProject) { ?>
                <tr>
                    <td>
                        <strong><?=$this->htmlA($this->designProject['brand']['moderUrl'], $this->designProject['brand']['name']) ?></strong>
                    </td>
                    <td>
                        <strong><?=$this->htmlA($this->designProject['moderUrl'], $this->designProject['name']) ?></strong>
                    </td>
                    <td>
                        <strong><?=$this->htmlA($this->designProject['url'], $this->designProject['url']) ?></strong>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td style="text-align:center">
                            <form style="margin:0" action="<?=$this->escape($this->designProject['removeUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-times"></i></button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <?php foreach ($this->inheritDesignProjects as $designProject) { ?>
                <tr class="warning">
                    <td>
                        <strong><?=$this->htmlA($designProject['brand']['moderUrl'], $designProject['brand']['name']) ?></strong>
                        <h6><em>Inherited from
                        <?php foreach ($designProject['cars'] as $car) { ?>
                            <?=$this->htmlA($car['url'], $car['name'])?>
                        <?php } ?>
                        </em></h6>
                    </td>
                    <td>
                        <strong><?=$this->htmlA($designProject['moderUrl'], $designProject['name']) ?></strong>
                    </td>
                    <td>
                        <strong><?=$this->htmlA($designProject['url'], $designProject['url']) ?></strong>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td></td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php } ?>