<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 178,
        'args'   => array(
            'CAR_ID'   => $this->car->id,
            'CAR_NAME' => $this->car->getFullName()
        )
    ));
?>

<div class="well">
    <form action="<?=$this->escape($this->url())?>" method="post">
        <?php foreach ($this->factories as $factory) { ?>
            <?=$this->formButton('factory_id', $factory['id'], array(
                'type'    => 'submit',
                'class'   => 'btn btn-link',
                'value'   => $factory['id'],
                'content' => $factory['name']
            ))?><br />
        <?php } ?>
    </form>
</div>