<?php if ($this->canEditTech) { ?>

    <?=$this->formModerCarEquipeAdd->render($this) ?>
    
    <?php if (count($this->equipes) > 0) { ?>
        <?/*=$this->formModerCarEquipes->render($this) */?>
    <?php } else { ?>
        <p>Ни одной модификации не задано</p>
    <?php } ?>
    
<?php } else { ?>

  <?php if (count($this->equipes) > 0) { ?>
        <table cellspacing="1" summary="" class="Vertical"><tbody>
            <tr>
                <th>Название</th>
                <?php foreach ($this->equipes as $equipe) { ?>
                    <td><?=$this->escape($equipe->caption) ?></td>
                <?php } ?>
            </tr>
            <tr>
                <th>Года выпуска</th>
                <?php foreach ($this->equipes as $equipe) { ?>
                    <td><?=$equipe->begin_year ?>-<?=$equipe->end_year ?></td>
                <?php } ?>
            </tr>
        </tbody></table>
    <?php } else { ?>
        <p>Ни одной модификации не задано</p>
    <?php } ?>
    
<?php } ?>