<?php
    $this->layout()->disableLayout();
?>
<?php if ($this->canEditMeta) { ?>
    <?=$this->form(
        'car-categories',
        array(
            'action' => $this->url(array(
                'action' => 'car-categories-save'
            ))
        ),
        $this->partial('cars/car-categories-tree.phtml', array(
            'categories' => $this->categories,
        )) .
        $this->formSubmit('submit', 'Сохранить', array(
            'class' => 'btn btn-primary'
        ))
    )?>
<?php } ?>