<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 78,
        'args'   => array(
            'CAR_ID'   => $this->car->id,
            'CAR_NAME' => $this->car->getFullName()
        )
    ));

    //$this->layout()->moduleName = 'moder/cars/car';
?>
<p>Инструмент позволяет объединить несколько картинок в автомобиль</p>

<?=$this->form->render($this)?>