<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 123,
    ]);
?>
<div class="row">
    <div class="col-sm-8 col-sm-push-4">
        <div class="well">
            <?=$this->markdown($this->translate('account/accounts/connect-failed'))?>
        </div>
    </div>
    <div class="col-sm-4 col-sm-pull-8">
        <?=$this->partial('application/account/sidebar', $this->sidebar)?>
    </div>
</div>