<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 198,
    ]);

    $cols = 2;
    $rows = ceil(count($this->users) / $cols);
?>

<div class="row">
    <div class="col-sm-8 col-sm-push-4">
        <div class="row">
            <?php for ($i=0; $i<$cols; $i++) { ?>
                <div class="col-md-6">
                    <ul class="media-list">
                        <?php foreach (array_slice($this->users, $i*$rows, $rows) as $user) { ?>
                            <li class="media">
                                <div class="media-left media-middle">
                                    <?php if (!$user->deleted) { ?>
                                        <?=$this->htmlA([
                                            'href'  => $user->getAboutUrl(),
                                            'class' => 'photo'
                                        ], $this->user($user)->avatar(), false) ?>
                                    <?php } ?>
                                </div>
                                <div class="media-body">
                                    <h4 class="media-heading"><?=$this->user($user)?></h4>
                                    <?php if ($lastOnline = $user->getDateTime('last_online')) { ?>
                                        <p><?=$this->escapeHtml($this->humanTime($lastOnline))?></p>
                                    <?php } ?>
                                </div>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            <?php } ?>
        </div>
    </div>
    <div class="col-sm-4 col-sm-pull-8">
        <?=$this->partial('application/account/sidebar', $this->sidebar)?>
    </div>
</div>