<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 137,
    ]);
?>
<div class="row">
    <div class="col-sm-8 col-sm-push-4">
        <div class="well">
            <?=$this->markdown($this->translate('account/delete/text'))?>
            <hr />
            <?=$this->partial('application/forms/bootstrap-horizontal', [
                'form' => $this->form
            ])?>
        </div>
    </div>
    <div class="col-sm-4 col-sm-pull-8">
        <?=$this->partial('application/account/sidebar', $this->sidebar)?>
    </div>
</div>