<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 55,
    ));
?>
<div class="well">
    <?php if ($email = $this->user()->get()->e_mail) { ?>
        <p>Ваш текущий адрес e-mail: <?=$this->htmlA('mailto:' . $email, $email) ?></p>
    <?php } else { ?>
        <p>Вы не указали адрес e-mail</p>
    <?php } ?>
    <p>На этой странице вы можете изменить свой адрес электронной почты (e-mail)</p>
    <p>На новый адрес будет выслано письмо с инструкциями по его подтверждению</p>
    <?=$this->form->render($this) ?>
</div>