<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 55,
    ]);
?>
<div class="row">
    <div class="col-sm-8 col-sm-push-4">
        <div class="well">
            <?php if ($email = $this->user()->get()->e_mail) { ?>
                <p>
                    <?=$this->escapeHtml($this->translate('account/email/your-current-email:'))?> 
                    <?=$this->htmlA('mailto:' . $email, $email) ?>
                </p>
            <?php } else { ?>
                <p><?=$this->escapeHtml($this->translate('account/email/your-dont-enter-email'))?></p>
            <?php } ?>
            <?=$this->markdown($this->translate('account/email/text'))?>
            <?=$this->partial('application/forms/bootstrap-horizontal', [
                'form' => $this->form
            ])?>
        </div>
    </div>
    <div class="col-sm-4 col-sm-pull-8">
        <?=$this->partial('application/account/sidebar', $this->sidebar)?>
    </div>
</div>