<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 94,
    ]);
?>
<div class="row">
    <div class="col-sm-8 col-sm-push-4">
        <?=$this->partial('application/pictures', $this->picturesData)?>
        <?=$this->paginationControl($this->paginator, null, null, [
            'route' => 'account/not-taken-pictures/page'
        ]) ?>
    </div>
    <div class="col-sm-4 col-sm-pull-8">
        <?=$this->partial('application/account/sidebar', $this->sidebar)?>
    </div>
</div>