<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 129,
    ]);
?>
<div class="row">
    <div class="col-sm-8 col-sm-push-4">
        <h2><?=$this->escapeHtml($this->translate('account/profile/personal'))?></h2>
        <div class="well">
            <?=$this->partial('application/forms/bootstrap-horizontal', [
                'form' => $this->profileForm
            ])?>
        </div>

        <h2><?=$this->escapeHtml($this->translate('account/profile/photo'))?></h2>
        <div class="well">
            <p><?=$this->translate('account/profile/use-gravatar')?></p>
            <?php if ($this->user()->get()->img) { ?>
                <?=$this->img($this->user()->get()->img) ?>
                <form action="<?=$this->escapeHtmlAttr($this->url('account/profile', [
                    'form' => 'reset-photo'
                 ]))?>" method="post">
                    <button type="submit" class="btn btn-danger">
                        <i class="fa fa-times"></i>
                        <?=$this->escapeHtml($this->translate('account/profile/photo/delete'))?>
                    </button>
                </form>
            <?php } ?>
            <?=$this->partial('application/forms/bootstrap-horizontal', [
                'form' => $this->photoForm
            ])?>
        </div>

        <h2><?=$this->escapeHtml($this->translate('account/profile/other'))?></h2>
        <div class="well">
            <p><?=$this->escapeHtml($this->translate('account/profile/votes-per-day'))?>: <?=$this->user()->get()->votes_per_day?></p>
            <p><?=$this->escapeHtml($this->translate('account/profile/votes-left'))?>: <?=$this->user()->get()->votes_left?></p>
            <?=$this->partial('application/forms/bootstrap-horizontal', [
                'form' => $this->settingsForm
            ])?>
        </div>
    </div>
    <div class="col-sm-4 col-sm-pull-8">
        <?=$this->partial('application/account/sidebar', $this->sidebar)?>
    </div>
</div>