<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 188,
    ]);

    //$this->layout()->moduleName = 'default/account/specs-conflicts';
?>

<p class="pull-right">
    Weight: <?=number_format($this->weight, 2 , '.', ' ')?>
</p>

<ul class="nav nav-pills" style="margin-bottom:10px">
    <li<?=$this->filter == '0' ? ' class="active"' : ''?>>
        <?=$this->htmlA($this->url('account/specs-conflicts'), 'Все')?>
    </li>
    <li<?=$this->filter == '-1' ? ' class="active"' : ''?>>
        <?=$this->htmlA($this->url('account/specs-conflicts/params', [
            'conflict' => -1,
        ]), 'Я не согласен')?>
    </li>
    <li<?=$this->filter == '1' ? ' class="active"' : ''?>>
        <?=$this->htmlA($this->url('account/specs-conflicts/params', [
            'conflict' => 1,
        ]), 'Не согласны со мной')?>
    </li>
    <li<?=$this->filter == 'minus-weight' ? ' class="active"' : ''?>>
        <?=$this->htmlA($this->url('account/specs-conflicts/params', [
            'conflict' => 'minus-weight',
        ]), 'Ошибки')?>
    </li>
</ul>

<table class="table">
    <thead>
        <tr>
            <th>Объект</th>
            <th>Характеристика</th>
            <th>Моё значение</th>
            <th>Другие значения</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->conflicts as $conflict) { ?>
            <tr>
                <td>
                    <?=$this->escapeHtml($conflict['object'])?>
                </td>
                <td><?=$this->escapeHtml($conflict['attribute'])?></td>
                <td>
                    <?php if ($conflict['value'] === null) { ?>
                        <em>нет</em>
                    <?php } else { ?>
                        <?=$this->escapeHtml($conflict['value'])?>
                        <?php if ($conflict['unit']) { ?>
                            <?=$this->escapeHtml($conflict['unit']['abbr'])?>
                        <?php } ?>
                    <?php } ?>

                    <?=$this->htmlA($conflict['url'], '<i class="fa fa-pencil"></i>', false)?>
                </td>
                <td>
                    <?php foreach ($conflict['values'] as $value) { ?>
                        <?php if ($value['value'] === null) { ?>
                            <em>нет</em>
                        <?php } else { ?>
                            <?=$this->escapeHtml($value['value'])?>
                            <?=$this->escapeHtml($conflict['unit']['abbr'])?>
                        <?php } ?>
                        <?=$this->user($value['user'])?>
                        <br />
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<?=$this->paginationControl($this->paginator, null, null, [
    'route' => 'account/specs-conflicts/params'
]) ?>