<?php
    $this->pageEnv([
        'layout'    => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId'    => 197
    ]);

    $this->layout()->moduleName = 'default/info/text';
?>
<p>
    <?php if ($this->prevUrl) { ?>
        <i class="fa fa-arrow-left"></i>
        <?=$this->htmlA($this->prevUrl, 'Previous revision')?>
    <?php } ?>
    <?php if ($this->nextUrl) { ?>
        <span class="pull-right">
            <?=$this->htmlA($this->nextUrl, 'Next revision')?>
            <i class="fa fa-arrow-right"></i>
        </span>
    <?php } ?>
</p>
<div class="row">
    <div class="col-md-6">
        <h3>
            Revision <?=$this->prev['revision']?>
            <?php if ($this->prevUser) { ?>
                <small><?=$this->user($this->prevUser)?></small>
            <?php } ?>
        </h3>
        <pre><?=$this->prev['text']?></pre>
    </div>
    <div class="col-md-6">
        <h3>
            Revision <?=$this->current['revision']?>
            <?php if ($this->currentUser) { ?>
                <small><?=$this->user($this->currentUser)?></small>
            <?php } ?>
        </h3>
        <pre class="diff"><?=$this->current['text']?></pre>
    </div>
</div>