<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 85,
        'args'   => [
            'BRAND_ID'   => $this->brand->id,
            'BRAND_NAME' => $this->brand->name
        ]
    ]);
?>

<?php
    $brandUrl = $this->url('catalogue', [
        'action'        => 'brand',
        'brand_catname' => $this->brand->folder
    ]);
?>
<div class="row">
    <div class="col-md-6">
        <?php if ($this->picture) { ?>
            <?=$this->img($this->picture->getFormatRequest(), [
                'format' => 'picture-thumb',
            ])?>
        <?php } ?>
        <div class="well">
            <p><?=$this->escapeHtml(sprintf($this->translate('moder/database-id-%s'), $this->brand->id))?></p>
            <p>
                <?=$this->escapeHtml($this->translate('moder/brands/vehicles-count:'))?>
                <strong><?=$this->brand->cars_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/engines-count:'))?>
                <strong></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/vehicle-pictures-count:'))?>
                <strong></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/engine-pictures-count:'))?>
                <strong><?=$this->brand->enginepictures_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/logo-pictures-count:'))?>
                <strong><?=$this->brand->logopictures_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/mixed-pictures-count:'))?>
                <strong><?=$this->brand->mixedpictures_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/unsorted-pictures-count:'))?>
                <strong><?=$this->brand->unsortedpictures_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/total-pictures-count:'))?>
                <strong></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/public-url:'))?>
                <?=$this->htmlA($brandUrl, $brandUrl) ?><br />
            </p>
            <p><?=$this->htmlA($this->url('log/params', [
                'action'   => 'index',
                'brand_id' => $this->brand->id
            ]), $this->translate('moder/log-of-events')) ?></p>
        </div>

        <h3><?=$this->escapeHtml($this->translate('moder/brands/meta-data'))?></h3>
        <div class="well">

            <?php if ($this->canEdit) { ?>
                <?=$this->partial('application/forms/bootstrap-horizontal', [
                    'form' => $this->formBrandEdit
                ])?>
            <?php } else { ?>
                <table><tbody>
                    <tr>
                        <td><?=$this->escapeHtml($this->translate('brand/name'))?></td>
                        <td><?=$this->escapeHtml($this->brand->name) ?></td>
                    </tr>
                    <tr>
                        <td><?=$this->escapeHtml($this->translate('moder/brands/meta-data/full-name'))?></td>
                        <td><?=$this->escapeHtml($this->brand->full_name) ?></td>
                    </tr>
                </tbody></table>
            <?php } ?>
        </div>

        <h3><?=$this->escapeHtml($this->translate('moder/brands/description'))?></h3>
        <div class="well">
            <?php if ($this->canEdit) { ?>
                <?=$this->partial('application/forms/markdown', [
                    'form' => $this->descriptionForm
                ])?>
            <?php } else { ?>
                <?=$this->markdown($this->description)?>
            <?php } ?>
            <?php if ($this->brand->text_id) { ?>
                <p>
                    <?=$this->htmlA([
                        'class' => 'pull-right',
                        'href'  => $this->url('info/text', [
                            'action'     => 'text',
                            'id'         => $this->brand->text_id
                        ])
                    ], 'History')?>
                </p>
            <?php } ?>
        </div>



    </div>
    <div class="col-md-6">

        <div class="tabbable">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#brand-tab-bar-1"><?=$this->escapeHtml($this->translate('moder/brands/vehicles'))?></a></li>
                <li><a data-toggle="tab" href="#brand-tab-bar-2"><?=$this->escapeHtml($this->translate('moder/brands/links'))?></a></li>
            </ul>
            <div class="tab-content">
                <div id="brand-tab-bar-1" class="tab-pane active">
                    <div class="well">
                        <?php foreach ($this->cars as $car) { ?>
                            <p>
                                <?=$this->htmlA($this->url('moder/brand-vehicle/params', [
                                    'action'     => 'item',
                                    'brand_id'   => $this->brand->id,
                                    'vehicle_id' => $car->id
                                ]), $this->car()->htmlTitle($car->getNameData($this->language())), false) ?>
                            </p>
                        <?php } ?>
                    </div>
                </div>
                <div id="brand-tab-bar-2" class="tab-pane">
                    <div class="well">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>