<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 85,
        'args'   => [
            'BRAND_ID'   => $this->brand->id,
            'BRAND_NAME' => $this->brand->caption
        ]
    ]);
    $this->layout()->moduleName = 'moder/brands/brand';
?>

<?php
    $brandUrl = $this->url('catalogue', [
        'action'        => 'brand',
        'brand_catname' => $this->brand->folder
    ]);
?>
<div class="row">
    <div class="col-md-6">
        <?php if ($this->picture) { ?>
            <?=$this->img($this->picture->getFormatRequest(), [
                'format' => 'picture-thumb',
            ])?>
        <?php } ?>
        <div class="well">
            <p><?=$this->escapeHtml(sprintf($this->translate('moder/database-id-%s'), $this->brand->id))?></p>
            <p>
                <?=$this->escapeHtml($this->translate('moder/brands/vehicles-count:'))?>
                <strong><?=$this->brand->cars_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/engines-count:'))?>
                <strong><?=$this->brand->engines_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/vehicle-pictures-count:'))?>
                <strong><?=$this->brand->carpictures_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/engine-pictures-count:'))?>
                <strong><?=$this->brand->enginepictures_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/logo-pictures-count:'))?>
                <strong><?=$this->brand->logopictures_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/mixed-pictures-count:'))?>
                <strong><?=$this->brand->mixedpictures_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/unsorted-pictures-count:'))?>
                <strong><?=$this->brand->unsortedpictures_count ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/total-pictures-count:'))?>
                <strong><?=$this->brand->getTotalPicturesCount() ?></strong><br />

                <?=$this->escapeHtml($this->translate('moder/brands/public-url:'))?>
                <?=$this->htmlA($brandUrl, $brandUrl) ?><br />
            </p>
            <p><?=$this->htmlA($this->url('log/params', [
                'action'   => 'index',
                'brand_id' => $this->brand->id
            ]), $this->translate('moder/log-of-events')) ?></p>
        </div>

        <h3><?=$this->escapeHtml($this->translate('moder/brands/meta-data'))?></h3>
        <div class="well">

            <?php if ($this->canEdit) { ?>
                <?=$this->partial('application/forms/bootstrap-horizontal', [
                    'form' => $this->formBrandEdit
                ])?>
            <?php } else { ?>
                <table><tbody>
                    <tr>
                        <td><?=$this->escapeHtml($this->translate('moder/brands/meta-data/name'))?></td>
                        <td><?=$this->escapeHtml($this->brand->caption) ?></td>
                    </tr>
                    <tr>
                        <td><?=$this->escapeHtml($this->translate('moder/brands/meta-data/full-name'))?></td>
                        <td><?=$this->escapeHtml($this->brand->full_caption) ?></td>
                    </tr>
                </tbody></table>
            <?php } ?>
        </div>

        <h3><?=$this->escapeHtml($this->translate('moder/brands/description'))?></h3>
        <div class="well">
            <?php if ($this->canEdit) { ?>
                <?=$this->partial('application/forms/bootstrap-horizontal', [
                    'form' => $this->descriptionForm
                ])?>
            <?php } else { ?>
                <?=$this->markup($this->description)?>
            <?php } ?>
            <?php if ($this->brand->text_id) { ?>
                <p>
                    <?=$this->htmlA([
                        'class' => 'pull-right',
                        'href'  => $this->url('info/text', [
                            'action'     => 'text',
                            'id'         => $this->brand->text_id
                        ])
                    ], 'History')?>
                </p>
            <?php } ?>
        </div>

        <h3><?=$this->escapeHtml($this->translate('moder/brands/logo'))?></h3>
        <div class="well">
            <?php if ($this->canLogo) { ?>
                <?=$this->markdown($this->translate('moder/brands/logo/description'))?>
            <?php } ?>
            <?=$this->img($this->brand->img, ['style' => 'max-width:100%']) ?>
            <?php if ($this->canLogo) { ?>
                <?=$this->partial('application/forms/bootstrap-horizontal', [
                    'form' => $this->formLogo
                ])?>
            <?php } ?>
        </div>

    </div>
    <div class="col-md-6">

        <div class="tabbable">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#brand-tab-bar-1"><?=$this->escapeHtml($this->translate('moder/brands/vehicles'))?></a></li>
                <li><a data-toggle="tab" href="#brand-tab-bar-2"><?=$this->escapeHtml($this->translate('moder/brands/links'))?></a></li>
            </ul>
            <div class="tab-content">
                <div id="brand-tab-bar-1" class="tab-pane active">
                    <div class="well">
                        <?php foreach ($this->cars as $car) { ?>
                            <p>
                                <?=$this->htmlA($this->url('moder/cars/params', [
                                    'action' => 'car',
                                    'car_id' => $car->id
                                ]), $car->getFullName($this->language())) ?>
                            </p>
                        <?php } ?>
                    </div>
                </div>
                <div id="brand-tab-bar-2" class="tab-pane">
                    <div class="well">
                        <?php if ($this->canEdit) { ?>
                            <form action="<?=$this->escapeHtmlAttr($this->url(null, [
                                'action' => 'save-links'
                            ], [], true)) ?>" method="post">
                                <table class="table table-condensed table-striped">
                                    <thead>
                                        <tr>
                                            <th><?=$this->escapeHtml($this->translate('moder/brands/links/text'))?></th>
                                            <th><?=$this->escapeHtml($this->translate('moder/brands/links/address'))?></th>
                                            <th><?=$this->escapeHtml($this->translate('moder/brands/links/type'))?></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->links as $link) { ?>
                                            <tr>
                                                <td><?=$this->formText(
                                                    (new Zend\Form\Element\Text('link['.$link['id'].'][caption]'))
                                                        ->setAttributes([
                                                            'value' => $link['caption'],
                                                            'class' => 'form-control'
                                                        ])
                                                ) ?></td>
                                                <td><?=$this->formText(
                                                    (new Zend\Form\Element\Text('link['.$link['id'].'][url]'))
                                                        ->setAttributes([
                                                            'value' => $link['url'],
                                                            'class' => 'form-control'
                                                        ])
                                                ) ?></td>
                                                <td>
                                                    <?=$this->formSelect(
                                                        (new Zend\Form\Element\Select('link['.$link['id'].'][type]'))
                                                            ->setAttributes([
                                                                'value' => $link['type'],
                                                                'options' => [
                                                                    'default'  => 'moder/brands/links/type/interest-link',
                                                                    'official' => 'moder/brands/links/type/official',
                                                                    'club'     => 'moder/brands/links/type/club'
                                                                ],
                                                                'class' => 'form-control'
                                                            ])
                                                    ) ?>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                        <tr>
                                            <td><?=$this->formText((new Zend\Form\Element\Text('new[caption]'))
                                                ->setAttributes(['class' => 'form-control'])
                                            ) ?></td>
                                            <td><?=$this->formText((new Zend\Form\Element\Text('new[url]'))
                                                ->setAttributes(['class' => 'form-control'])
                                            ) ?></td>
                                            <td>
                                                <?=$this->formSelect(
                                                    (new Zend\Form\Element\Select('new[type]'))
                                                        ->setAttributes([
                                                            'value' => '',
                                                            'options' => [
                                                                'default'  => 'moder/brands/links/type/interest-link',
                                                                'official' => 'moder/brands/links/type/official',
                                                                'club'     => 'moder/brands/links/type/club'
                                                            ],
                                                            'class' => 'form-control'
                                                        ])
                                                ) ?>
                                            </td>
                                        </tr>
                                        <tr><td colspan="3">
                                            <input class="btn btn-primary" type="submit" value="<?=$this->escapeHtmlAttr($this->translate('submit'))?>" />
                                        </td></tr>
                                    </tbody>
                                </table>
                            </form>
                        <?php } else { ?>
                            <table class="table table-condensed table-stripped"><tbody>
                                <tr>
                                    <th><?=$this->escapeHtml($this->translate('moder/brands/links/text'))?></th>
                                    <th><?=$this->escapeHtml($this->translate('moder/brands/links/address'))?></th>
                                    <th><?=$this->escapeHtml($this->translate('moder/brands/links/type'))?></th>
                                </tr>
                                <?php foreach ($this->brand->findLinks() as $link) { ?>
                                    <tr>
                                        <td><?=$this->escapeHtml($link->caption)?></td>
                                        <td><?=$this->escapeHtml($link->url)?></td>
                                        <td><?=$this->escapeHtml($link->type)?></td>
                                    </tr>
                                <?php } ?>
                            </tbody></table>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>