<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => true
        ),
        'pageId' => 45,
        'args'   => array(
            'THEME_NAME' => $this->theme->caption,
            'THEME_ID'   => $this->theme->id,
        )
    ));
?>
<?php if ($this->user()->logedIn()) { ?>
    <?php if ($this->needWait) { ?>
        <p class="alert alert-block alert-warning">Для добавления нового сообщения вам необходимо подождать некоторое время</p>
    <?php } ?>
    <?=$this->formTopicNew->render($this) ?>
<?php } else { ?>
    <div class="alert alert-block alert-error">
        <p>Добавлять топики могут только зарегистрированные пользователи.</p>
        <p>Если Вы уже зарегистрированны на сайте, то Вам необходимо осуществить вход на сайт.</p>
        <p>Если Вы ещё не зарегистрированы, сделайте это сейчас <a href="/registration/">на странице регистрации</a>.
    </div>
<?php } ?>