<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 177,
        'args'   => [
            'FACTORY_ID'   => $this->factory->id,
            'FACTORY_NAME' => $this->factory->name
        ]
    ]);
    $this->layout()->moduleName = 'moder/factory/edit';
?>
<div class="row">
    <div class="col-md-8">
        <div class="well">
            <p><?=$this->escapeHtml(sprintf($this->translate('moder/database-id-%s'), $this->factory->id))?></p>
            <p><?=$this->htmlA($this->url('log/params', [
                'action'     => 'index',
                'factory_id' => $this->factory->id
            ]), $this->translate('moder/log-of-events')) ?></p>

            <?php
                $url = $this->url('factories/factory', [
                    'action' => 'factory',
                    'id'     => $this->factory->id
                ]);
            ?>
            <p>
                <?=$this->escapeHtml($this->translate('moder/factoreis/puclic-url:'))?>
                <?=$this->htmlA($url, $url)?>
            </p>
        </div>

        <div class="well">
            <?php if ($this->canEdit) { ?>
                <?=$this->partial('application/forms/bootstrap-horizontal', [
                    'form' => $this->formModerFactoryEdit
                ])?>
            <?php } ?>
        </div>

        <h3><?=$this->escapeHtml($this->translate('moder/factoreis/factory/short-description'))?></h3>
        <div class="well">
            <?php if ($this->canEdit) { ?>
                <?=$this->partial('application/forms/markdown', [
                    'form' => $this->descriptionForm
                ])?>
            <?php } else { ?>
                <?=$this->markup($this->description)?>
            <?php } ?>
            <?php if ($this->factory->text_id) { ?>
                <p>
                    <?=$this->htmlA([
                        'class' => 'pull-right',
                        'href'  => $this->url('info/text', [
                            'action' => 'text',
                            'id'     => $this->factory->text_id
                        ])
                    ], $this->translate('moder/markdown/history'))?>
                </p>
            <?php } ?>
        </div>
    </div>
    <div class="col-md-4">
        <h3><?=$this->escapeHtml($this->translate('moder/factoreis/factory/vehicles'))?></h3>
        <div class="well">
            <?php  foreach ($this->cars as $car) { ?>
                <?=$this->htmlA($this->url('moder/cars/params', [
                    'action' => 'car',
                    'car_id' => $car->id
                ]), $car->getFullName($this->language())) ?><br />
            <?php } ?>
        </div>
    </div>
</div>