<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 175,
    ]);
?>
<div class="row">
    <div class="col-lg-4 col-md-4">
        <h2><?=$this->escapeHtml($this->translate('moder/factories/filter'))?></h2>
        <div class="well">
            <?=$this->partial('application/forms/bootstrap-vertical', [
                'form' => $this->form
            ])?>
        </div>

        <ul class="list-unstyled">
            <?php if ($this->user()->isAllowed('factory', 'add')) { ?>
                <li>
                    <i class="fa fa-plus"></i>
                    <?=$this->htmlA($this->url('moder/factories/params', [
                        'action'     => 'add',
                    ]), $this->translate('moder/factories/add'))?>
                </li>
            <?php } ?>
        </ul>
    </div>
    <div class="col-lg-8 col-md-8">
        <h2>
            <?=$this->escapeHtml($this->translate('moder/factories/title'))?>
            <?php if ($count = $this->paginator->getTotalItemCount()) {?>
                <small><?=$this->escapeHtml(sprintf($this->translatePlural('%1$s factories', '%1$s factories', $count), $count))?></small>
            <?php } ?>
        </h2>
        <?php foreach ($this->factories as $factory) { ?>
            <div class="car">
                <h3><?=$this->escapeHtml($factory['name'])?></h3>
                <div class="row thumbnails">
                    <?php foreach ($factory['pictures'] as $picture) { ?>
                        <div class="col-lg-3 col-md-3 col-sm-6">
                            <?php if ($picture->image_id) { ?>
                                <?=$this->htmlA(
                                    [
                                        'href'  => $this->pic($picture)->url(),
                                        'class' =>'thumbnail'
                                    ],
                                    $this->img($picture->getFormatRequest(), [
                                        'format' => 'picture-thumb',
                                    ]),
                                    false
                                )?>
                            <?php } ?>
                        </div>
                    <?php } ?>
                </div>
                <ul class="list-inline">
                    <li>
                        <i class="fa fa-cog"></i>
                        <?=$this->htmlA($factory['moderUrl'], $this->translate('moder/edit-object'))?>
                    </li>
                </ul>
            </div>
        <?php } ?>
        <?=$this->paginationControl($this->paginator) ?>
    </div>
</div>