<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 101,
        'args'   => [
            'ATTR_NAME' => $this->attribute->name
        ]
    ]);
?>

<div class="row">
    <div class="col-md-6">
        <h2><?=$this->escapeHtml($this->translate('moder/attrs/parameters'))?></h2>
        <div class="well">
            <?=$this->partial('application/forms/bootstrap-vertical', [
                'form' => $this->formAttributeEdit
            ])?>
        </div>

        <h2><?=$this->escapeHtml($this->translate('moder/attrs/parameters/options-list'))?></h2>
        <div class="well">
            <?=$this->partial('application/moder/attrs/attribute/options-partial', [
                'options' => $this->options
            ]) ?>
        </div>

        <h2><?=$this->escapeHtml($this->translate('moder/attrs/parameters/options-list/add'))?></h2>
        <div class="well">
            <?=$this->partial('application/forms/bootstrap-vertical', [
                'form' => $this->formListOption
            ])?>
        </div>
    </div>
    <div class="col-md-6">
        <?php if (count($this->attributes)) { ?>
            <h2><?=$this->escapeHtml($this->translate('moder/attrs/attributes'))?></h2>
            <div class="well">
                <table class="table">
                    <tr>
                        <th><?=$this->escapeHtml($this->translate('attrs/attribute/name'))?></th>
                        <th><?=$this->escapeHtml($this->translate('attrs/attribute/type'))?></th>
                        <th><?=$this->escapeHtml($this->translate('attrs/attribute/unit'))?></th>
                    </tr>
                    <?=$this->partial('application/moder/attrs/attribute/attributes-rows-partial', [
                        'attributes' => $this->attributes,
                        'deep'       => 0
                    ]) ?>
                </table>
            </div>
        <?php } ?>

        <h2><?=$this->escapeHtml($this->translate('moder/attrs/attribute/add-subattribute'))?></h2>
        <div class="well">
            <?=$this->partial('application/forms/bootstrap-vertical', [
                'form' => $this->formAttributeNew
            ])?>
        </div>
    </div>
</div>