<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 100,
    ]);
?>
<div class="row">
    <div class="col-md-6">
        <h2><?=$this->escapeHtml($this->translate('moder/attrs/zones'))?></h2>
        <div class="well">
            <ul>
                <?php foreach ($this->zones as $zone) { ?>
                    <li><?=$this->htmlA($this->url('moder/attrs/params', [
                        'action'  => 'zone',
                        'zone_id' => $zone['id']
                    ], [], true), $zone['name']) ?></li>
                <?php } ?>
            </ul>
        </div>
    </div>
    <div class="col-md-6">
        <h2><?=$this->escapeHtml($this->translate('moder/attrs/attributes'))?></h2>
        <div class="well">
            <?=$this->partial('application/moder/attrs/attribute/attributes-partial', [
                'attributes' => $this->attributes
            ]) ?>
        </div>
    </div>
</div>