<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 142,
        'args'   => [
            'ZONE_NAME' => $this->zone['name'],
            'ZONE_ID'   => $this->zone['id'],
        ]
    ]);
?>
<div class="row">
    <div class="col-md-6">
        <h2><?=$this->escapeHtml($this->translate('moder/attrs/attributes'))?></h2>
        <div class="well">
            <form action="<?=$this->escapeHtmlAttr($this->url('moder/attrs/params', [
                'form'  =>  'attributes'
            ], [], true))?>" method="post">
                <?=$this->partial('application/moder/attrs/zone/attributes-list-partial', [
                    'attributes' => $this->allAttributes
                ]) ?>
                <div>
                    <input type="submit" value="<?=$this->escapeHtmlAttr('submit')?>" />
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-6">
        <h2><?=$this->escapeHtml($this->translate('moder/attrs/attributes-order'))?></h2>
        <div class="well">
            <table>
                <?=$this->partial('application/moder/attrs/zone/attributes-rows-partial', [
                    'attributes' => $this->attributes,
                    'deep'       => 0
                ]) ?>
            </table>
        </div>
    </div>
</div>
