<?php
    $this->pageEnv(array(
        'layout'    => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageTitle' => '',
        'pageId'    => 1
    ));
    $this->layout()->moduleName = 'default/index';
?>
<div class="row">
    <div class="col-md-6">
        <?php if ($this->carOfDayName) { ?>
            <h2>
                <?=$this->escape($this->carOfDayName)?>
                <small><?=$this->escape($this->translate('car-of-day')) ?></small>
            </h2>

            <?php if ($this->carOfDayPictures) { ?>
                <div class="row thumbnails">
                    <?php foreach ($this->carOfDayPictures as $idx => $picture) { ?>
                        <?php if ($idx == 0) { ?>
                            <?php if ($picture) { ?>
                                <div class="col-sm-8">
                                    <?=$this->htmlA(array(
                                        'href'  => $picture['url'],
                                        'class' => 'thumbnail'
                                    ), $this->htmlImg(array(
                                        'src'   => $picture['src'],
                                        'title' => $picture['name'],
                                        'alt'   => $picture['name'],
                                    )), false)?>
                                </div>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                    <div class="col-sm-4">
                        <?php foreach ($this->carOfDayPictures as $idx => $picture) { ?>
                            <?php if ($idx == 1 || $idx == 2) { ?>
                                <?php if ($picture) { ?>
                                    <?=$this->htmlA(array(
                                        'href'  => $picture['url'],
                                        'class' => 'thumbnail'
                                    ), $this->htmlImg(array(
                                        'src'   => $picture['src'],
                                        'title' => $picture['name'],
                                        'alt'   => $picture['name'],
                                    )), false)?>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                    </div>
                </div>
                <div class="row thumbnails">
                    <div class="col-md-12">
                        <div class="row">
                            <?php foreach ($this->carOfDayPictures as $idx => $picture) { ?>
                                <?php if ($idx > 2) { ?>
                                    <?php if ($picture) { ?>
                                        <div class="col-sm-4">
                                            <?=$this->htmlA(array(
                                                'href'  => $picture['url'],
                                                'class' => 'thumbnail'
                                            ), $this->htmlImg(array(
                                                'src'   => $picture['src'],
                                                'title' => $picture['name'],
                                                'alt'   => $picture['name'],
                                            )), false)?>
                                        </div>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <?php if ($this->carOfDayLinks) { ?>
                    <p><?=implode(' &#xa0; ', $this->carOfDayLinks)?></p>
                <?php } ?>
            <?php } ?>
        <?php } ?>

        <div class="page-header-small">
            <h3><?=$this->escape($this->pageData['new']['name']) ?> <small><?=$this->htmlA($this->pageData['new']['url'], $this->translate('all-link'))?></small></h3>
        </div>
        <?=$this->partial('pictures.phtml', $this->newPictures)?>
        <p>
            <span class="fa fa-th"></span>
            <?=$this->htmlA($this->url(array(
                'module'     => 'default',
                'controller' => 'new',
                'action'     => 'index'
            ), 'new', true), $this->translate('All new pictures') . ' …') ?>
        </p>
    </div>
    <div class="col-md-6">
        <?=$this->brandsHtml ?>

        <div class="row">

            <div class="col-md-6">
                <h4><?=$this->escape($this->pageData['twins']['name']) ?> <small><?=$this->htmlA($this->pageData['twins']['url'], $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->twinsBlock['brands'] as $brand) { ?>
                        <?=$this->htmlA($brand['url'], $brand['name']) ?>
                        <span class="count">(<?=$brand['count'] - $brand['new_count'] ?><?php if ($brand['new_count'] > 0) { ?><span>+<?=$brand['new_count'] ?></span><?php } ?>)</span>,
                    <?php } ?>
                    <?php if ($more = $this->twinsBlock['more_count']) { ?>
                        …
                        <?=$this->escape($this->translate('and'))?>
                        <?=$this->htmlA(
                            '/twins/',
                            $this->translate(array('brands/more-companies', null, $more), $more)
                        )?>
                    <?php } ?>
                </p>
                <?php if ($this->language()->is('ru')) { ?>
                    <p>Вы знаете, что Daewoo Matiz имеет аж целых <a href="/twins/group87/">пять клонов</a>? А знаете, что <a href="http://www.autowp.ru/twins/group5/">общего у Lotus и Kia</a>? Уверены, что вам покажется интересным этот раздел.</p>
                <?php } ?>
            </div>

            <div class="col-md-6">
                <h4><?=$this->escape($this->pageData['category']['name']) ?> <small><?=$this->htmlA($this->pageData['category']['url'], $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->categories as $category) { ?>
                        <?=$this->htmlA($category['url'], $category['short_name'])?>&#xa0;<span class="count">(<?=$category['cars_count']-$category['new_cars_count'] ?><?php if ($category['new_cars_count'] > 0) { ?><span>+<?=$category['new_cars_count'] ?></span><?php } ?>)</span>,
                    <?php } ?>
                </p>
                <?php if ($this->language()->is('ru')) { ?>
                    <p>А знаете ли вы, какая техника помогала блюсти правопорядок на улицах мировых городов в разное время? А на каких автомобилях ездил Папа Римский? Нет? Тогда вам точно в этот раздел.</p>
                <?php } ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h4><?=$this->escape($this->pageData['mosts']['name']) ?> <small><?=$this->htmlA($this->pageData['mosts']['url'], $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->mosts as $url => $name) { ?>
                        <?=$this->htmlA($url, $this->translate($name)) ?>,
                    <?php } ?>
                    …
                </p>
                <?php if ($this->language()->is('ru')) { ?>
                    <p>Хотите знать, какой автомобиль был самым быстрым? Хотите знать, сколько весит самый могучий карьерный самосвал? Заходите и узнаете!</p>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

<?php if (count($this->specsCars) > 0) { ?>
    <h4>
        <?=$this->escape($this->translate('carlist/specifications'))?>
        <small><?=$this->htmlA($this->pageData['statistics']['url'], $this->pageData['statistics']['name'])?></small>
    </h4>
    <?=$this->partial('index/partial/specs-cars.phtml', $this->specsCars)?>
<?php } ?>