<?php
    $this->pageEnv(array(
        'layout'    => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageTitle' => '',
        'pageId'    => 1
    ));
    $this->layout()->moduleName = 'default/index';
?>
<div class="row">
    <div class="col-lg-6 col-md-6">
        <?php if ($this->carOfDay) { ?>
            <h2><?=$this->escape($this->carOfDay->getFullName())?> <small><?=$this->escape($this->translate('car-of-day'))?></small></h2>

            <?php if ($this->carOfDayPictures) { ?>
                <div class="row thumbnails">
                    <?php foreach ($this->carOfDayPictures as $idx => $picture) { ?>
                        <?php if ($idx == 0) { ?>
                            <?php if ($picture) { ?>
                                <div class="col-lg-8 col-md-8 col-sm-8">
                                    <?php if ($picture->image_id) { ?>
                                        <?php if ($image = $this->img($picture->getFormatRequest(), array(
                                            'format' => 'picture-thumb-medium',
                                            'title'  => $picture->getCaption(array(
                                                'language' => $this->language()->get()
                                            ))
                                        ))) { ?>
                                            <?php if ($image->exists()) { ?>
                                                <?=$this->htmlA(array(
                                                    'href'  => $this->pic($picture)->url(),
                                                    'class' => 'thumbnail'
                                                ), $image, false)?>
                                            <?php } ?>
                                        <?php } ?>
                                    <?php } ?>
                                </div>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-6">
                        <?php foreach ($this->carOfDayPictures as $idx => $picture) { ?>
                            <?php if ($idx == 1 || $idx == 2) { ?>
                                <?php if ($picture) { ?>
                                    <?php if ($image = $this->img($picture->getFormatRequest(), array(
                                        'format' => 'picture-thumb',
                                        'title'  => $picture->getCaption(array(
                                            'language' => $this->language()->get()
                                        ))
                                    ))) { ?>
                                        <?php if ($image->exists()) { ?>
                                            <?=$this->htmlA(array(
                                                'href'  => $this->pic($picture)->url(),
                                                'class' => 'thumbnail'
                                            ), $image, false)?>
                                        <?php } ?>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                    </div>
                </div>
                <div class="row thumbnails">
                    <div class="col-lg-12 col-md-12">
                        <div class="row">
                            <?php foreach ($this->carOfDayPictures as $idx => $picture) { ?>
                                <?php if ($idx > 2) { ?>
                                    <?php if ($picture) { ?>
                                        <div class="col-lg-4 col-md-4 col-sm-4 col-6">
                                            <?php if ($image = $this->img($picture->getFormatRequest(), array(
                                                'format' => 'picture-thumb',
                                                'title'  => $picture->getCaption(array(
                                                    'language' => $this->language()->get()
                                                ))
                                            ))) { ?>
                                                <?php if ($image->exists()) { ?>
                                                    <?=$this->htmlA(array(
                                                        'href'  => $this->pic($picture)->url(),
                                                        'class' => 'thumbnail'
                                                    ), $image, false)?>
                                                <?php } ?>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <?php if ($this->carOfDayLinks) { ?>
                    <p><?=implode(' &#xa0; ', $this->carOfDayLinks)?></p>
                <?php } ?>
            <?php } ?>
        <?php } ?>

        <div class="page-header-small">
            <h3><?=$this->escape($this->page(51)->name) ?> <small><?=$this->htmlA('/new/', $this->translate('all-link'))?></small></h3>
        </div>
        <?=$this->pictures($this->newPictures) ?>
        <p>
            <span class="glyphicon glyphicon-th"></span>
            <?=$this->htmlA($this->url(array(
                'module'     => 'default',
                'controller' => 'new',
                'action'     => 'index'
            ), 'new', true), $this->translate('All new pictures') . ' …') ?>
        </p>
    </div>
    <div class="col-lg-6 col-md-6">
        <?=$this->brandsHtml ?>

        <div class="row">

            <div class="col-lg-6 col-md-6">
                <h4><?=$this->escape($this->page(25)->name) ?> <small><?=$this->htmlA('/twins/', $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->twinsBlock['brands'] as $brand) { ?>
                        <?=$this->htmlA($brand['url'], $brand['name']) ?>
                        <span class="count">(<?=$brand['count'] - $brand['new_count'] ?><?php if ($brand['new_count'] > 0) { ?><span>+<?=$brand['new_count'] ?></span><?php } ?>)</span>,
                    <?php } ?>
                    <?php if ($more = $this->twinsBlock['more_count']) { ?>
                        …
                        <?=$this->escape($this->translate('and'))?>
                        <?=$this->htmlA(
                            '/twins/',
                            $this->translate(array('brands/more-companies', null, $more), $more)
                        )?>
                    <?php } ?>
                </p>
                <?php if ($this->language()->is('ru')) { ?>
                    <p>Вы знаете, что Daewoo Matiz имеет аж целых <a href="/twins/group87/">пять клонов</a>? А знаете, что <a href="http://www.autowp.ru/twins/group5/">общего у Lotus и Kia</a>? Уверены, что вам покажется интересным этот раздел.</p>
                <?php } ?>
            </div>

            <div class="col-lg-6 col-md-6">
                <h4><?=$this->escape($this->page(22)->name) ?> <small><?=$this->htmlA('/category/', $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->categories as $category) { ?>
                        <?=$this->htmlA($category['url'], $category['short_name'])?>&#xa0;<span class="count">(<?=$category['cars_count']-$category['new_cars_count'] ?><?php if ($category['new_cars_count'] > 0) { ?><span>+<?=$category['new_cars_count'] ?></span><?php } ?>)</span>,
                    <?php } ?>
                </p>
                <?php if ($this->language()->is('ru')) { ?>
                    <p>А знаете ли вы какая техника помогала блюсти правопорядок на улицах мировых городов в разное время? А на каких автомобилях ездил Папа Римский? Нет? Тогда вам точно в этот раздел.</p>
                <?php } ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6 col-md-6">
                <h4><?=$this->escape($this->page(21)->name) ?> <small><?=$this->htmlA('/most/', $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->mosts as $url => $name) { ?>
                        <?=$this->htmlA($url, $name) ?>,
                    <?php } ?>
                    …
                </p>
                <?php if ($this->language()->is('ru')) { ?>
                    <p>Хотите знать, какой автомобиль был самым быстрым? Хотите знать, сколько весит самый могучий карьерный самосвал? Заходите и узнаете!</p>
                <?php } ?>
            </div>
        </div>
    </div>
</div>