<?php
    $this->layout()->assign(array(
        'blankPage' => true,
        'needLeft'  => false,
        'needRight' => false
    ));
?>
<h1>Произошла ошибка</h1>
<ul>
    <?php foreach ($this->exceptions as $exception) { ?>
        <li>
            <h2><?=$this->escape($exception->getMessage()) ?></h2>
            <pre><?=$this->escape($exception->getTraceAsString()) ?></pre>
        </li>
    <?php } ?>
</ul>