<?php
    $this->layout()->assign(array(
        'blankPage' => true,
        'needLeft'  => false,
        'needRight' => false
    ));

    $this->breadcrumbs()->reset();
    $this->pageTitle()->set('');
?>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="jumbotron">
            <h1>404 Not found</h1>
            <p>Запрашиваемая Вами веб-страница не найдена. Возможно, что вы ошиблись в строке набора адреса или документ, запрашиваемый вами, был переименован.</p>
            <p>Если Вы считаете, что произошла ошибка, пожалуйста, сообщите нам об этом по электронной почте <a href="mailto:autowp@yandex.ru">autowp@yandex.ru</a>.</p>
            <p>Вы можете:</p>
            <p>
                <a class="btn btn-primary" href="javascript:history.back()">вернуться назад</a>
                <a class="btn" href="http://www.autowp.ru/">перейти на главную страницу</a>
            </p>
        </div>
    </div>
</div>