<div class="comments">
    <?php foreach ($this->messages as $message) { ?>
        <div class="message">
            <div>
                <?php if ($message['author']) { ?>
                    <?=$this->user($message['author'])?>
                <?php } else { ?>
                    <?=$this->escapeHtml($this->translate('account/personal-message/system-notification'))?>
                <?php } ?>
            </div>
            <div class="photo">
                <?php if ($message['author'] && !$message['author']->deleted) { ?>
                    <?=$this->htmlA($message['authorUrl'], $this->user($message['author'])->avatar(), false)?>
                <?php } ?>
            </div>
            <div class="content">
                <div class="text">
                    <p><?=$this->userText($message['contents'])?></p>
                </div>
                <div>
                    <?php if ($message['isNew']) { ?>
                        <span class="label label-info">новое</span>
                    <?php } ?>
                    <?php if ($message['canDelete']) { ?>
                        <?=$this->htmlA([
                            'href'         => '#',
                            'class'        => 'pull-right',
                            'data-trigger' => 'delete-pm',
                            'data-id'      => $message['id']
                        ], '<i class="fa fa-trash"></i> ' . $this->escapeHtml($this->translate('account/personal-message/delete')), false)?>
                    <?php } ?>
                    <?php if ($message['canReply']) { ?>
                        <i class="fa fa-reply"></i>
                        <?=$this->htmlA([
                            'href'         => '#',
                            'data-trigger' => 'show-pm-dialog',
                            'data-user-id' => $message['author']->id
                        ], $this->translate('account/personal-message/reply')) ?>
                        &nbsp;
                        <?php if ($message['allMessagesLink']) { ?>
                            <i class="fa fa-comments-o"></i>
                            <?=$this->htmlA($this->url('account/personal-messages/user', [
                                'user_id' => $message['author']->id
                            ]), $this->translate('account/personal-message/entire-dialog')) ?>
                            <small>(<?=$message['dialogCount']?>)</small>
                            &nbsp;
                        <?php } ?>
                    <?php } ?>
                    <?php if ($message['date']) { ?>
                        <i class="fa fa-clock-o"></i>
                        <?=$this->escapeHtml($this->user()->humanTime($message['date']))?>
                    <?php } ?>
                </div>
            </div>
        </div>
    <?php } ?>
</div>