<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 32,
        'args'   => array(
            'ARTICLE_NAME'    => $this->article->name,
            'ARTICLE_CATNAME' => $this->article->catname,
        )
    ));
?>
<div class="well">
    <div class="article clearfix"><?=$this->article->findParentHtmls()->html ?></div>
</div>

<?php if (count($this->links)) { ?>
    <div class="well">
        <?php foreach ($this->links as $link) { ?>
            <?=$this->htmlA(array('href' => $link['url']), $link['name']) ?>
        <?php } ?>
    </div>
<?php } ?>

<?php if ($this->article->enabled) { ?>
    <div style="text-align:left;margin-bottom:20px;clear:both">
        <?=$this->action('comments', 'comments', 'default', array(
            'type'    => Comment_Message::ARTICLES_TYPE_ID,
            'item_id' => $this->article->id
        )) ?>
    </div>
<?php } ?>