<div class="well">
    <ul class="nav nav-pills nav-stacked">
        <?php foreach ($this->brandList as $brand) { ?>
            <?php
                $selected = in_array($brand['id'], $this->selected_brand_ids) ? ' class="selected"' : '';
            ?>
            <li<?=$selected ? ' class="active"' : ''?>>
                <?=$this->htmlA($this->url(array(
                    'action'        => 'index',
                    'brand_catname' => $brand['catname']
                ), 'articles', true), $brand['name']) ?>
            </li>
        <?php } ?>
    </ul>
</div>