export * from './articles.service';
import { ArticlesService } from './articles.service';
export * from './articles.serviceInterface';
export * from './autowp.service';
import { AutowpService } from './autowp.service';
export * from './autowp.serviceInterface';
export * from './contacts.service';
import { ContactsService } from './contacts.service';
export * from './contacts.serviceInterface';
export * from './donations.service';
import { DonationsService } from './donations.service';
export * from './donations.serviceInterface';
export * from './items.service';
import { ItemsService } from './items.service';
export * from './items.serviceInterface';
export * from './messaging.service';
import { MessagingService } from './messaging.service';
export * from './messaging.serviceInterface';
export * from './pictures.service';
import { PicturesService } from './pictures.service';
export * from './pictures.serviceInterface';
export * from './statistics.service';
import { StatisticsService } from './statistics.service';
export * from './statistics.serviceInterface';
export * from './votings.service';
import { VotingsService } from './votings.service';
export * from './votings.serviceInterface';
export const APIS = [ArticlesService, AutowpService, ContactsService, DonationsService, ItemsService, MessagingService, PicturesService, StatisticsService, VotingsService];
