/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GoautowpArticle } from '../model/models';
import { GoautowpArticlesResponse } from '../model/models';
import { RpcStatus } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ArticlesGetItemByCatnameRequestParams {
    catname: string;
}

export interface ArticlesGetListRequestParams {
    limit: string;
    page: string;
}


export interface ArticlesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    articlesGetItemByCatname(requestParameters: ArticlesGetItemByCatnameRequestParams, extraHttpRequestParams?: any): Observable<GoautowpArticle>;

    /**
     * 
     * 
* @param requestParameters
     */
    articlesGetList(requestParameters: ArticlesGetListRequestParams, extraHttpRequestParams?: any): Observable<GoautowpArticlesResponse>;

}
