/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GoautowpFeedback } from '../model/models';
import { GoautowpIP } from '../model/models';
import { GoautowpReCaptchaConfig } from '../model/models';
import { GoautowpTimezones } from '../model/models';
import { RpcStatus } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AutowpCreateFeedbackRequestParams {
    feedback: GoautowpFeedback;
}

export interface AutowpGetIPRequestParams {
    ip: string;
    fields: Array<string>;
}


export interface AutowpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    autowpCreateFeedback(requestParameters: AutowpCreateFeedbackRequestParams, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
* @param requestParameters
     */
    autowpGetIP(requestParameters: AutowpGetIPRequestParams, extraHttpRequestParams?: any): Observable<GoautowpIP>;

    /**
     * 
     * 
*/
    autowpGetReCaptchaConfig(extraHttpRequestParams?: any): Observable<GoautowpReCaptchaConfig>;

    /**
     * 
     * 
*/
    autowpGetTimezones(extraHttpRequestParams?: any): Observable<GoautowpTimezones>;

}
