/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GoautowpContact } from '../model/models';
import { GoautowpContactItems } from '../model/models';
import { RpcStatus } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ContactsCreateContactRequestParams {
    contact: GoautowpContact;
}

export interface ContactsDeleteContactRequestParams {
    userId: string;
}

export interface ContactsGetContactRequestParams {
    userId: string;
}


export interface ContactsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    contactsCreateContact(requestParameters: ContactsCreateContactRequestParams, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
* @param requestParameters
     */
    contactsDeleteContact(requestParameters: ContactsDeleteContactRequestParams, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
* @param requestParameters
     */
    contactsGetContact(requestParameters: ContactsGetContactRequestParams, extraHttpRequestParams?: any): Observable<GoautowpContact>;

    /**
     * 
     * 
*/
    contactsGetContacts(extraHttpRequestParams?: any): Observable<GoautowpContactItems>;

}
