/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GoautowpDonationsTransactionsResponse } from '../model/models';
import { RpcStatus } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DonationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    donationsGetTransactions(extraHttpRequestParams?: any): Observable<GoautowpDonationsTransactionsResponse>;

}
