/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GoautowpBrandIcons } from '../model/models';
import { GoautowpBrandVehicleTypeItems } from '../model/models';
import { GoautowpSpecsItems } from '../model/models';
import { GoautowpVehicleTypeItems } from '../model/models';
import { RpcStatus } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ItemsGetBrandVehicleTypesRequestParams {
    brandId: number;
}


export interface ItemsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    itemsGetBrandIcons(extraHttpRequestParams?: any): Observable<GoautowpBrandIcons>;

    /**
     * 
     * 
* @param requestParameters
     */
    itemsGetBrandVehicleTypes(requestParameters: ItemsGetBrandVehicleTypesRequestParams, extraHttpRequestParams?: any): Observable<GoautowpBrandVehicleTypeItems>;

    /**
     * 
     * 
*/
    itemsGetSpecs(extraHttpRequestParams?: any): Observable<GoautowpSpecsItems>;

    /**
     * 
     * 
*/
    itemsGetVehicleTypes(extraHttpRequestParams?: any): Observable<GoautowpVehicleTypeItems>;

}
