/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GoautowpVote } from '../model/models';
import { GoautowpVoting } from '../model/models';
import { GoautowpVotingVariantVotes } from '../model/models';
import { RpcStatus } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface VotingsGetVotingRequestParams {
    id: number;
}

export interface VotingsGetVotingVariantVotesRequestParams {
    id: number;
}

export interface VotingsVoteRequestParams {
    vote: GoautowpVote;
}


export interface VotingsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    votingsGetVoting(requestParameters: VotingsGetVotingRequestParams, extraHttpRequestParams?: any): Observable<GoautowpVoting>;

    /**
     * 
     * 
* @param requestParameters
     */
    votingsGetVotingVariantVotes(requestParameters: VotingsGetVotingVariantVotesRequestParams, extraHttpRequestParams?: any): Observable<GoautowpVotingVariantVotes>;

    /**
     * 
     * 
* @param requestParameters
     */
    votingsVote(requestParameters: VotingsVoteRequestParams, extraHttpRequestParams?: any): Observable<object>;

}
