version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    # - cyclop
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    # - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    # - gocognit
    - goconst
    - gocritic
    # - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard_v2
    - goprintffuncname
    - gosec
    # - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    # - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    # - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    # - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    # - recvcheck
    # - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    # - tagliatelle
    - testableexamples
    - testifylint
    # - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    # - wrapcheck
    # - wsl
    - wsl_v5
    - zerologlint
  settings:
    gomoddirectives:
      replace-allow-list:
        - github.com/doug-martin/goqu/v9
    mnd:
      ignored-numbers:
        - "2"
        - "2.0"
    varnamelen:
      min-name-length: 2
      ignore-names:
        - i
        - j
        - k
    goconst:
      ignore-tests: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - spec_grpc.pb.go
      - spec.pb.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: lax
    paths:
      - spec_grpc.pb.go
      - spec.pb.go
      - third_party$
      - builtin$
      - examples$
  settings:
    golines:
      max-len: 120
