autowp-migrations:
  dsn: mysql://root:password@tcp(mysql)/autowp_test?charset=utf8mb4&parseTime=true&loc=UTC
duplicate_finder:
  rabbitmq: amqp://guest:guest@rabbitmq:5672/
  queue: duplicate_finder
autowp-dsn: root:password@tcp(mysql:3306)/autowp_test?charset=utf8mb4&parseTime=true&loc=UTC
file_storage:
  s3:
    endpoints:
      - http://minio:9000
oauth:
  secret: example_secret
rabbitmq: amqp://guest:guest@autowp_test_rabbitmq:5672/
traffic-dsn: postgres://traffic:password@autowp_test_traffic_postgres:5432/traffic?sslmode=disable
traffic-migrations:
  dsn: postgres://traffic:password@autowp_test_traffic_postgres/traffic?sslmode=disable
