<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 68,
    ]);
?>

<?=$this->htmlA([
    'href' => $this->url('moder/pages/params', [
        'action' => 'item'
    ]),
    'class' => 'btn btn-success'
], $this->translate('moder/pages/new'))?>

<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th colspan="2">move</th>
            <th>N</th>
            <th><?=$this->escapeHtml($this->translate('moder/pages/name'))?></th>
            <th>Breadcrumbs</th>
            <th>IsGroup?</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?=$this->partial('application/moder/pages/list', [
            'items' => $this->items,
            'level' => 0
        ])?>
    </tbody>
</table>