<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 103,
    ]);
?>
<div class="well">
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->filter
    ])?>
    <table class="specs-log">
        <thead>
            <tr>
               <th>Дата</th>
               <th>Пользователь</th>
               <th>Объект</th>
               <th>Аттрибут</th>
               <th>Значение</th>
               <th>Редактор</th>
            </tr>
        </thead>
        <?php foreach ($this->items as $idx => $item) { ?>
            <tr class="<?=$idx%2 ? 'odd' : 'even'?>">
                <td><?=$this->escapeHtml($this->humanTime($item['date'])) ?></td>
                <td><?=$this->user($item['user']) ?></td>
                <td>
                    <?php if ($item['itemType']) { ?>
                        <?=$this->escapeHtml($item['itemType']['name']) ?>
                    <?php } ?>
                    <?php if ($this->isModerator) { ?>
                        <?=$this->htmlA($item['object']['moderUrl'], $item['object']['name']) ?>
                    <?php } else { ?>
                        <?=$this->escapeHtml($item['object']['name']) ?>
                    <?php } ?>
                </td>
                <td class="attribute">
                    <?php foreach ($item['path'] as $j => $node) { ?>
                        <?php if ($j) { ?> / <?php } ?>
                        <span><?=$this->escapeHtml($node)?></span>
                    <?php } ?>
                </td>
                <td style="text-align:center">
                    <?=$this->escapeHtml($item['value'])?>
                    <?php if ($item['unit']) { ?>
                        <span class="unit"><?=$this->escapeHtml($item['unit']->abbr) ?></span>
                    <?php } ?>
                </td>
                <td class="link">
                    <?=$this->htmlA($item['object']['editorUrl'], 'в редактор') ?>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>
<?=$this->paginationControl($this->paginator) ?>