<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 103,
    ]);
?>
<div class="well">
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->filter
    ])?>
    <table class="specs-log table">
        <thead>
            <tr>
               <th><?=$this->escapeHtml($this->translate('specifications-editor/log/date'))?></th>
               <th><?=$this->escapeHtml($this->translate('specifications-editor/log/user'))?></th>
               <th><?=$this->escapeHtml($this->translate('specifications-editor/log/object'))?></th>
               <th><?=$this->escapeHtml($this->translate('specifications-editor/log/attribute'))?></th>
               <th><?=$this->escapeHtml($this->translate('specifications-editor/log/value'))?></th>
               <th><?=$this->escapeHtml($this->translate('specifications-editor/log/editor'))?></th>
            </tr>
        </thead>
        <?php foreach ($this->items as $idx => $item) { ?>
            <tr class="<?=$idx%2 ? 'odd' : 'even'?>">
                <td><?=$this->escapeHtml($this->humanTime($item['date'])) ?></td>
                <td><?=$this->user($item['user']) ?></td>
                <td>
                    <?php if ($this->isModerator) { ?>
                        <?=$this->htmlA($item['object']['moderUrl'], $item['object']['name']) ?>
                    <?php } else { ?>
                        <?=$this->escapeHtml($item['object']['name']) ?>
                    <?php } ?>
                </td>
                <td class="attribute">
                    <?php foreach ($item['path'] as $j => $node) { ?>
                        <?php if ($j) { ?> / <?php } ?>
                        <span><?=$this->escapeHtml($this->translate($node))?></span>
                    <?php } ?>
                </td>
                <td style="text-align:center">
                    <?=$this->escapeHtml($item['value'])?>
                    <?php if ($item['unit']) { ?>
                        <span class="unit"><?=$this->escapeHtml($item['unit']['abbr']) ?></span>
                    <?php } ?>
                </td>
                <td class="link">
                    <?=$this->htmlA($item['object']['editorUrl'], $this->translate('specifications-editor/log/to-editor')) ?>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>
<?=$this->paginationControl($this->paginator, null, null, [
    'route' => 'cars/params'
]) ?>