<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 102,
        'args'   => [
            'CAR_NAME' => $this->car()->textTitle($this->car->getNameData($this->language()))
        ]
    ]);

    $this->layout()->moduleName = 'default/cars/car-specifications-editor';
?>

<ul class="nav nav-pills" style="margin-bottom: 20px">
    <?php if ($this->user()->inheritsRole('cars-moder')) { ?>
        <li>
            <a href="<?=$this->escapeHtmlAttr($this->url('moder/cars/params', [
                'action' => 'car',
                'car_id' => $this->car->id
            ]))?>">
                <i class="fa fa-cog"></i>
                <?=$this->escapeHtml($this->translate('moder/edit-object'))?>
                <?=$this->car()->htmlTitle($this->car->getNameData($this->language()))?>
            </a>
        </li>
    <?php } ?>
    <li>
        <a href="/cars/attrs-change-log">
            <i class="fa fa-list"></i>
            <?=$this->escapeHtml($this->translate('specifications-editor/log'))?>
        </a>
    </li>
</ul>


<?php if ($this->user()->get()->specs_weight < 1) { ?>
    <div class="alert alert-danger">
        <?=$this->markdown($this->translate('specifications-editor/errors-alert'))?>
    </div>
<?php } ?>



<ul class="nav nav-tabs" id="myTab">
    <?php foreach ($this->tabs as $id => $tab) { ?>
        <li<?=$tab['active'] ? ' class="active"' : ''?>>
            <?=$this->htmlA(
                [
                    'href'          => '#'.$id,
                    'data-toggle'   => 'tab',
                    'data-load'     => isset($tab['data-load']) ? $tab['data-load'] : null,
                    'data-activate' => $tab['active'] ? '1' : null
                ],
                ($tab['icon'] ? '<span class="'.$tab['icon'].'"></span> ' : '') .
                $this->escapeHtml($this->translate($tab['title'])) .
                ($tab['count'] ? ' <span class="badge">'.$tab['count'].'</span>' : ''),
                false
            )?>
        </li>
    <?php } ?>
</ul>

<div class="tab-content well">
    <div class="tab-pane<?=$this->tabs['info']['active'] ? ' active' : ''?>" id="info">
        <?=$this->markdown($this->translate('specifications-editor/description'))?>
    </div>
    <div class="tab-pane<?=$this->tabs['engine']['active'] ? ' active' : ''?>" id="engine">
        <h2><?=$this->escapeHtml($this->translate('specifications-editor/engine'))?></h2>

        <?php if ($this->user()->isAllowed('specifications', 'edit-engine')) { ?>
            <?php if ($this->engine) { ?>
                <p><?=$this->htmlA($this->url('moder/engines/params', [
                    'action'    => 'engine',
                    'engine_id' => $this->engine->id
                ]), $this->engine->caption)?></p>
                <?php if ($this->engineInherited) { ?>
                    <?php foreach ($this->engineInheritedFrom as $car) { ?>
                        <h6><em>
                            <?=$this->escapeHtml($this->translate('specifications-editor/engine/inherited-from'))?>
                            <?=$this->htmlA($car['url'], $car['name'])?>
                        </em></h6>
                    <?php } ?>
                <?php } ?>
                <form id="select-engine" method="post" action="<?=$this->escapeHtmlAttr($this->url('cars/params', [
                    'action' => 'select-car-engine',
                    'car_id' => $this->car->id
                ], [], true))?>">
                    <input type="submit" value="<?=$this->escapeHtmlAttr($this->translate('specifications-editor/engine/select-another'))?>" class="btn btn-primary" />
                </form>
                <form id="select-engine" method="post" action="<?=$this->escapeHtmlAttr($this->url('cars/params', [
                    'action' => 'cancel-car-engine',
                    'car_id' => $this->car->id
                ], [], true))?>">
                    <input type="submit" value="<?=$this->escapeHtmlAttr($this->translate('specifications-editor/engine/cancel'))?>" class="btn btn-warning" />
                </form>
                <?php if (!$this->engineInherited) { ?>
                    <form id="inherit-car-engine" method="post" action="<?=$this->escapeHtmlAttr($this->url('cars/params', [
                        'action' => 'inherit-car-engine',
                        'car_id' => $this->car->id
                    ], [], true))?>">
                        <input type="submit" value="<?=$this->escapeHtml($this->translate('specifications-editor/engine/inherit'))?>" class="btn btn-warning" />
                    </form>
                <?php } ?>
            <?php } else { ?>
                <p><?=$this->escapeHtml($this->translate('specifications-editor/engine/not-selected'))?></p>
                <form id="select-engine" method="post" action="<?=$this->escapeHtmlAttr($this->url('cars/params', [
                    'action' => 'select-car-engine',
                    'car_id' => $this->car->id
                ], [], true))?>">
                    <input type="submit" value="<?=$this->escapeHtml($this->translate('specifications-editor/engine/select'))?>" class="btn btn-primary" />
                </form>
                <?php if (!$this->engineInherited) { ?>
                    <form id="inherit-car-engine" method="post" action="<?=$this->escapeHtmlAttr($this->url('cars/params', [
                        'action' => 'inherit-car-engine',
                        'car_id' => $this->car->id
                    ], [], true))?>">
                        <input type="submit" value="<?=$this->escapeHtml($this->translate('specifications-editor/engine/inherit'))?>" class="btn btn-warning" />
                    </form>
                <?php } else { ?>
                    <form id="inherit-car-engine" method="post" action="<?=$this->escapeHtmlAttr($this->url('cars/params', [
                        'action' => 'cancel-car-engine',
                        'car_id' => $this->car->id
                    ], [], true))?>">
                        <input type="submit" value="<?=$this->escapeHtml($this->translate('specifications-editor/engine/dont-inherit'))?>" class="btn btn-warning" />
                    </form>
                <?php } ?>
            <?php } ?>
        <?php } else { ?>
            <?php if ($this->engine) { ?>
                <p><?=$this->escapeHtml($this->engine->caption)?></p>
                <?php if ($this->engineInherited) { ?>
                    <?php foreach ($this->engineInheritedFrom as $car) { ?>
                        <h6><em>Inherited from <?=$this->escapeHtml($car['name'])?></em></h6>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
        <?php } ?>
    </div>
    <div class="tab-pane<?=$this->tabs['spec']['active'] ? ' active' : ''?>" id="spec">
        <?=$this->partial('application/cars/partial/form', [
            'form'    => $this->form,
            'data'    => $this->formData,
            'service' => $this->service
        ])?>
    </div>
    <div class="tab-pane<?=$this->tabs['result']['active'] ? ' active' : ''?>" id="result"></div>
    <?php if ($this->isSpecsAdmin) { ?>
        <div class="tab-pane<?=$this->tabs['admin']['active'] ? ' active' : ''?>" id="admin">
            <p><?=$this->htmlA($this->url('cars/params', [
                'action'       => 'specs-admin',
                'item_type_id' => 1,
                'item_id'      => $this->car->id
            ], [], true), 'Admin')?></p>
            <form action="<?=$this->escapeHtmlAttr($this->url('cars/params', [
                'action' => 'refresh-inheritance'
            ], [], true))?>" method="post">
                <button type="submit" class="btn btn-default">Refresh inheritance</button>
            </form>
        </div>
    <?php } ?>
</div>