<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 1,
    ]);
?>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <?=$this->partial('application/cars', $this->childListData)?>

        <?php if (isset($this->paginator)) { ?>
            <?=$this->paginationControl($this->paginator) ?>
        <?php } ?>
    </div>
</div>