<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 111,
        'args'   => [
            'ENGINE_NAME' => $this->engine->name
        ]
    ]);

    $this->layout()->moduleName = 'default/cars/engine-spec-editor';
?>
<div class="well">
    <?=$this->partial('application/cars/partial/form', [
        'form'    => $this->form,
        'data'    => $this->formData,
        'service' => $this->service
    ])?>
</div>