<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 102,
        'args'   => [
            'CAR_NAME' => $this->car->getFullName()
        ]
    ]);
?>
<form action="" method="post">
    <?php if (!$this->brand) { ?>
        <?php
            $columns = 6;
            $rows = ceil(count($this->brands) / $columns);
        ?>
        <div class="row">
            <div class="col-md-2">
                <?php foreach ($this->brands as $idx => $brand) { ?>
                    <button type="submit" name="brand" class="btn btn-link" value="<?=$this->escapeHtmlAttr($brand['catname'])?>">
                        <?=$this->escapeHtml($brand['name'])?>
                    </button><br />
                    <?php if ($idx && ($idx % $rows == 0)) { ?></div><div class="col-md-2"><?php } ?>
                <?php } ?>
            </div>
        </div>
    <?php } else { ?>
        <input type="hidden" name="brand" value="<?=$this->escapeHtmlAttr($this->brand['catname'])?>" />
        <?=$this->partial('application/cars/select-car-engine-walk-tree', [
            'engines' => $this->engines
        ])?>
    <?php } ?>
</form>