<?php foreach ($this->engines as $idx => $engine) { ?>
    <button name="engine" type="submit" value="<?=$engine['id']?>" class="btn btn-link">
        <?=$this->escapeHtml($engine['name'])?>
    </button><br />
    <?php if (count($engine['childs'])) { ?>
        <div style="margin-left:2em">
            <?=$this->partial('application/cars/select-car-engine-walk-tree', [
                'engines' => $engine['childs']
            ])?>
        </div>
    <?php } ?>
<?php } ?>