<table class="table table-stripped">
    <thead>
        <tr>
            <th><?=$this->escapeHtml($this->translate('specifications-editor/admin/date'))?></th>
            <th><?=$this->escapeHtml($this->translate('specifications-editor/admin/user'))?></th>
            <th><?=$this->escapeHtml($this->translate('specifications-editor/admin/parameter'))?></th>
            <th><?=$this->escapeHtml($this->translate('specifications-editor/admin/value'))?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->values as $value) { ?>
            <tr>
                <td><?=$this->escapeHtml($this->humanTime($value['date']))?></td>
                <td>
                    <?php if ($value['user']) { ?>
                        <?=$this->user($value['user'])?>
                    <?php } ?>
                </td>
                <td>
                    <?php if ($value['attribute']) {
                        echo $this->escapeHtml($value['attribute']['name']);
                        if ($value['unit']) {
                            echo ', ' . $this->escapeHtml($value['unit']['name']);
                        }
                    } ?>
                </td>
                <td>
                    <?=$this->escapeHtml($value['userValue'])?>
                    /
                    <?=$this->escapeHtml($value['value'])?>
                </td>
                <td>
                    <form action="<?=$this->escapeHtmlAttr($value['deleteUrl'])?>" method="post">
                        <button type="submit" class="btn btn-danger btn-xs">
                            <i class="fa fa-times"></i>
                        </button>
                    </form>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<form action="<?=$this->escapeHtmlAttr($this->url('cars/params', [
    'action' => 'move'
], [], true))?>" method="post">
    <input type="text" name="to_item_id" placeholder="id" />
    <button type="submit"><?=$this->escapeHtml($this->translate('specifications-editor/admin/move'))?></button>
</form>
