<h4>
    <?=$this->escapeHtml($this->translate('index/brands'))?>
    <small><?=$this->htmlA($this->url('brands'), $this->translate('all-link'))?></small>
</h4>
<?php
    $items = [];
    foreach ($this->brands as $brand) {
        $items[] =  $this->htmlA($brand['url'], $brand['name']) .
                    '&#xa0;<span class="count">('.
                        ($brand['cars_count'] - $brand['new_cars_count']).
                        ($brand['new_cars_count'] > 0
                            ? '<span data-href="'.$this->escapeHtmlAttr($brand['new_cars_url']).'" data-toggle="popover" data-container="body" class="popover-handler" title="'.$this->escapeHtmlAttr(sprintf($this->translate('brands/new-cars-of-brand'), $brand['name'])).'">+'.$brand['new_cars_count'].'</span>'
                            : ''
                        ).
                    ')</span>';
    }
?>
<p style="font-size:18px" class="index-brands">
    <?=implode(' ', $items) ?>
    <?php if (($more = $this->totalBrands - count($this->brands)) > 0) { ?>
        …&#xa0;<?=$this->escapeHtml($this->translate('and'))?>&#xa0;<?=$this->htmlA(
            $this->url('brands'),
            sprintf($this->translatePlural('brands/more-companies', 'brands/more-companies', $more), $more)
        )?>
    <?php } ?>
</p>