<h4><?=$this->escapeHtml($this->page(22)->name) ?> <small><?=$this->htmlA('/category', $this->translate('all-link'))?></small></h4>
<p>
    <?php foreach ($this->categories as $category) {
        $new = $category['new_cars_count'];
        $old = $category['cars_count'] - $new;
        echo $this->htmlA(
            $category['url'],
            $category['short_name']
        ) .
        '&#xa0;' .
        '<span class="count">(' .
            $old . ($new > 0 ? '<span data-href="'.$this->escapeHtmlAttr($category['new_cars_url']).'" data-toggle="popover" data-container="body" class="popover-handler">+' . $new . '</span>' : '') .
        ')</span> ';
    } ?>
</p>
<?php if (in_array($this->language(), ['ru', 'zh', 'fr', 'be'])) { ?>
    <?=$this->markdown($this->translate('index/categories/description'))?>
<?php } ?>