<?php if ($this->itemOfDay['name']) { ?>
    <h2 class="mb-3">
        <?=$this->car()->htmlTitle($this->itemOfDay['name'])?>
        <small>
            <?php if ($this->itemOfDay['itemTypeId'] == Application\Model\Item::VEHICLE) { ?>
                <?=$this->escapeHtml($this->translate('car-of-day')) ?>
            <?php } else { ?>
                <?=$this->escapeHtml($this->translate('theme-of-day')) ?>
            <?php } ?>
            <?php if ($this->itemOfDay['userId']) { ?>
                <span style="white-space:nowrap">by <?=$this->user($this->itemOfDay['userId'])?></span>
            <?php } ?>
        </small>
    </h2>

    <?php if ($this->itemOfDay['pictures']) { ?>
        <div class="row">
            <?php foreach ($this->itemOfDay['pictures'] as $idx => $picture) { ?>
                <?php if ($idx == 0 && $picture) { ?>
                    <div class="col-sm-6">
                        <?=$this->htmlA([
                            'href'  => $picture['url'],
                            'class' => 'd-block rounded mb-4'
                        ], $this->htmlImg([
                            'src'   => $picture['large']['src'],
                            'class' => 'rounded w-100 border border-light',
                            'title' => $picture['name'],
                            'alt'   => $picture['name'],
                            'sizes' => "auto"
                        ]), false)?>
                    </div>
                <?php } ?>
            <?php } ?>
            <!-- 
            <div class="col-sm-6">
                <?php for ($row=0; $row<2; $row++) { ?>
                    <div class="row">
                        <?php for ($col=0; $col<2; $col++) { ?>
                            <div class="col">
                                <?php
                                    $idx = 1 + $row*2 + $col;
                                    $picture = isset($this->itemOfDay['pictures'][$idx]) ? $this->itemOfDay['pictures'][$idx] : null;

                                ?>
                                <?php if ($picture) { ?>
                                    <?=$this->htmlA([
                                        'href'  => $picture['url'],
                                        'class' => 'd-block rounded mb-4'
                                    ], $this->htmlImg([
                                        'src'   => $picture['thumb']['src'],
                                        'class' => 'rounded w-100 border border-light',
                                        'title' => $picture['name'],
                                        'alt'   => $picture['name'],
                                        'style' => 'max-width: 100%;'
                                    ]), false)?>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
            -->
        </div>
        <p>
            <?php foreach ($this->itemOfDay['links'] as $i => $item) { ?>
                <?php if ($i) { ?> &#xa0; <?php } ?>
                <span class="fa fa-<?=$item['icon']?>"></span>
                <?=$this->htmlA($item['url'], $item['text'] . (isset($item['count']) ? ' ('.$item['count'].')' : ''))?>
            <?php } ?>

            <?php if ($this->itemOfDay['links']) { ?> &#xa0; <?php } ?>
            <span class="fa fa-trophy"></span>
            <?=$this->htmlA('/ng/donate/vod', $this->translate('donate/vod/wants-to-select?'))?>
        </p>
    <?php } ?>
<?php } ?>
