<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 74,
    ]);
?>
<div class="well">
    <?php foreach ($this->groups as $group) { ?>
        <div class="btn-group">
            <?php foreach ($group as $char) { ?>
                <?=$this->htmlA([
                    'class' => 'btn btn-default',
                    'href'  => $this->url('moder/cars/params', ['char' => $char], [], true),
                ], $char) ?>
            <?php } ?>
        </div>
    <?php } ?>
</div>

<?php if ($this->char) { ?>
    <h3><?=$this->escapeHtml($this->page(74)->name)?></h3>
    <div class="well">
        <?php foreach ($this->cars as $car) { ?>
            <?=$this->htmlA($this->url('moder/cars/params', [
                'action'  => 'car',
                'item_id' => $car->id
            ], [], true), $this->car()->htmlTitle($car->getNameData($this->language())), false) ?>
            <br />
        <?php } ?>
    </div>
<?php } ?>