<?php if ($this->canUseTree) { ?>
    <?php if ($this->car['is_group']) { ?>
        <div class="btn-group">
            <?=$this->htmlA([
                'href'  => $this->url(null, [
                    'action' => 'organize',
                ], [], true),
                'class' => 'btn btn-default',
            ], $this->translate('moder/vehicle/catalogue/turbo-group-creator'))?>
        </div>
    <?php } ?>
    <table class="table">
        <thead>
            <tr>
                <th><?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/title/name'))?></th>
                <th><?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/title/link'))?></th>
                <th><?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/title/catname'))?></th>
                <th><?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/title/public'))?></th>
                <?php if ($this->canMove) { ?>
                    <th><?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/title/remove'))?></th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <form class="car-add-parent" method="post" action="<?=$this->escapeHtmlAttr($this->url(null, [
                        'action' => 'add-parent',
                    ], [], true)) ?>">
                        <div class="input-group" style="max-width:400px">
                            <span class="input-group-btn">
                                <?=$this->htmlA([
                                    'href' => $this->url(null, [
                                        'action'    => 'car-select-parent',
                                        'brand_id'  => null,
                                        'parent_id' => null
                                    ], [], true),
                                    'class' => 'btn btn-success',
                                ], $this->translate('moder/vehicle/catalogue/select'))?>
                            </span>
                            <input type="text" name="parent" class="form-control" placeholder="<?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/select-placeholder'))?>" data-autocomplete="<?=$this->escapeHtmlAttr($this->url(null, [
                                'action' => 'car-autocomplete',
                                'car_id' => $this->car['id']
                            ], [], true))?>" />
                        </div>
                    </form>
                </td>
                <td></td>
                <td></td>
                <td></td>
                <?php if ($this->canMove) { ?>
                    <td></td>
                <?php } ?>
            </tr>
            <?php foreach ($this->brands as $brand) { ?>
                <tr>
                    <td>
                        <i class="fa fa-arrow-up"></i>
                        <?=$this->htmlA($brand['brand']['moderUrl'], $brand['brand']['name']) ?>
                    </td>
                    <td colspan="2">
                        <?=$this->htmlA($brand['editUrl'], $this->escapeHtml($brand['name']) . ' <span class="fa fa-pencil"></span>', false)?>
                    </td>
                    <td>
                        <?=$this->htmlA($brand['url'], $brand['url']) ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td>
                            <form action="<?=$this->escapeHtmlAttr($brand['deleteUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <?php foreach ($this->parents as $car) { ?>
                <?php foreach ($car['inheritBrands'] as $brand) { ?>
                    <tr class="warning">
                        <td>
                            <i class="fa fa-arrow-up"></i>
                            <?=$this->htmlA($brand['moderUrl'], $brand['name']) ?>
                        </td>
                        <td colspan="2"></td>
                        <td>
                            <?=$this->htmlA($brand['url'], $brand['url']) ?>
                        </td>
                        <?php if ($this->canMove) { ?>
                            <td></td>
                        <?php } ?>
                    </tr>
                    <?php if ($parentCar = $brand['car']) { ?>
                        <tr class="warning">
                            <td>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <i class="fa fa-arrow-up"></i>
                                <?=$this->htmlA($parentCar['url'], $parentCar['name'])?>
                            </td>
                            <td>
                                <?=$this->escapeHtml($this->carParentTypeOptions[$parentCar['type']])?>
                            </td>
                            <td></td>
                            <td>
                                <?php foreach ($parentCar['publicUrls'] as $url) { ?>
                                    <?=$this->htmlA($url, $url)?><br />
                                <?php } ?>
                            </td>
                            <?php if ($this->canMove) { ?>
                                <td></td>
                            <?php } ?>
                        </tr>
                    <?php } ?>
                <?php } ?>
                <tr data-id="<?=$car['id']?>">
                    <td>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <i class="fa fa-arrow-up"></i>
                        <?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?>
                        <?php if ($car['duplicateRow']) { ?>
                            <br />
                            <div class="text-warning"><small>
                                <?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/possible-duplicate-parent'))?>
                                <?=$this->car()->htmlTitle($car['duplicateRow']->getNameData($this->language()))?>
                            </small></div>
                        <?php } ?>
                    </td>
                    <td>
                        <form class="car-parent-type" method="post" action="<?=$this->escapeHtmlAttr($car['typeUrl']) ?>">
                            <?=$this->formElement(
                                (new Zend\Form\Element\Select('type'))
                                    ->setAttribute('class', 'form-control input-sm')
                                    ->setValueOptions($this->carParentTypeOptions)
                                    ->setValue($car['parent']['type'])
                            )?>
                        </form>
                    </td>
                    <td>
                        <form class="car-parent-catname" method="post" action="<?=$this->escapeHtmlAttr($car['catnameUrl']) ?>">
                            <div class="input-group" style="max-width:200px">
                                <?=$this->formElement(
                                    (new Zend\Form\Element\Text('name', [
                                        'value_options' => $this->carParentTypeOptions
                                    ]))
                                        ->setAttribute('class', 'form-control input-sm')
                                        ->setAttribute('placeholder', $this->translate('moder/vehicle/catalogue/parent-name-placeholder'))
                                        ->setValue($car['parent']['name'])
                                )?>
                                <span class="input-group-btn" style="width:0px;"></span>
                                <?=$this->formElement(
                                    (new Zend\Form\Element\Text('catname'))
                                        ->setAttribute('class', 'form-control input-sm')
                                        ->setAttribute('placeholder', $this->translate('moder/vehicle/catalogue/parent-catname-placeholder'))
                                        ->setValue($car['parent']['catname'])
                                )?>
                                <span class="input-group-btn">
                                    <button class="btn btn-sm btn-default" type="submit">Ok</button>
                                </span>
                            </div>
                        </form>
                    </td>
                    <td class="urls">
                        <?php foreach ($car['publicUrls'] as $url) { ?>
                            <?=$this->htmlA($url, $url)?><br />
                        <?php } ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td>
                            <form action="<?=$this->escapeHtmlAttr($car['deleteUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-sm btn-danger">
                                    <i class="fa fa-times"></i>
                                </button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <tr class="success" data-id="<?=$this->car['id']?>">
                <td colspan="3">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="fa fa-arrow-right"></i>
                    <?=$this->car()->htmlTitle($this->car->getNameData($this->language()))?>
                </td>
                <td class="urls">
                    <?php foreach ($this->publicUrls as $url) { ?>
                        <?=$this->htmlA($url, $url)?><br />
                    <?php } ?>
                </td>
                <?php if ($this->canMove) { ?>
                    <td></td>
                <?php } ?>
            </tr>
            <?php foreach ($this->childs as $car) { ?>
                <tr data-id="<?=$car['id']?>">
                    <td>
                        <i class="fa fa-arrow-down"></i>
                        <?php if ($car['parent']['type'] == Application\Model\DbTable\Vehicle\ParentTable::TYPE_TUNING) { ?>
                            <?=$this->escapeHtml($this->translate('moder/vehicle/link-type-prefix/related'))?>
                        <?php } elseif ($car['parent']['type'] == Application\Model\DbTable\Vehicle\ParentTable::TYPE_DESIGN) { ?>
                            <?=$this->escapeHtml($this->translate('moder/vehicle/link-type-prefix/design'))?>
                        <?php } elseif ($car['parent']['type'] == Application\Model\DbTable\Vehicle\ParentTable::TYPE_SPORT) { ?>
                            <?=$this->escapeHtml($this->translate('moder/vehicle/link-type-prefix/sport'))?>
                        <?php } ?>
                        <?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?>
                        <?php if ($car['duplicateRow']) { ?>
                            <br />
                            <div class="text-warning"><small>
                                <?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/possible-duplicate-child'))?>
                                <?=$this->car()->htmlTitle($car['duplicateRow']->getNameData($this->language()))?>
                            </small></div>
                        <?php } ?>
                    </td>
                    <td>
                        <form class="car-parent-type" method="post" action="<?=$this->escapeHtmlAttr($car['typeUrl']) ?>">
                            <?=$this->formElement(
                                (new Zend\Form\Element\Select('type', [
                                    'value_options' => $this->carParentTypeOptions
                                ]))
                                    ->setAttribute('class', 'form-control input-sm')
                                    ->setValue($car['parent']['type'])
                            )?>
                        </form>
                    </td>
                    <td>
                        <form class="car-parent-catname" method="post" action="<?=$this->escapeHtmlAttr($car['catnameUrl']) ?>">
                            <div class="input-group" style="max-width:200px">
                                <?=$this->formElement(
                                    (new Zend\Form\Element\Text('name'))
                                        ->setAttribute('class', 'form-control input-sm')
                                        ->setValue($car['parent']['name'])
                                        ->setAttribute('placeholder', $this->translate('moder/vehicle/catalogue/parent-name-placeholder'))
                                )?>
                                <span class="input-group-btn" style="width:0px;"></span>
                                <?=$this->formElement(
                                    (new Zend\Form\Element\Text('catname'))
                                        ->setAttribute('class', 'form-control input-sm')
                                        ->setValue($car['parent']['catname'])
                                        ->setAttribute('placeholder', $this->translate('moder/vehicle/catalogue/parent-catname-placeholder'))
                                )?>
                                <span class="input-group-btn">
                                    <button class="btn btn-sm btn-default" type="submit">Ok</button>
                                </span>
                            </div>
                        </form>
                    </td>
                    <td class="urls">
                        <?php foreach ($car['publicUrls'] as $url) { ?>
                            <?=$this->htmlA($url, $url)?><br />
                        <?php } ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td>
                            <form action="<?=$this->escapeHtmlAttr($car['deleteUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-sm btn-danger">
                                    <i class="fa fa-times"></i>
                                </button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>

            <?php if ($this->canMove) { ?>
                <tr>
                    <td>
                        <i class="fa fa-plus"></i>
                        <?=$this->htmlA($this->url('moder/cars/params', [
                            'action'    => 'new',
                            'parent_id' => $this->car->id
                        ]), $this->translate('moder/vehicle/catalogue/add-vehicle'))?>
                    </td>
                    <td></td>
                    <td></td>
                    <td class="urls"></td>
                    <?php if ($this->canMove) { ?>
                        <td></td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php } ?>

<?php if ($this->canMove) { ?>
    <form action="<?=$this->escapeHtmlAttr($this->url('moder/cars/params', [
        'action' => 'car-select-brand',
        'car_id' => $this->car->id
    ], [], true)) ?>" method="post"><div>
        <button type="submit" class="btn btn-xs btn-success">
            <i class="fa fa-plus"></i>
            <?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/add-brand'))?>
        </button>
    </div></form>
    <?php foreach ($this->relevantBrands as $brand) { ?>
        <form action="<?=$this->escapeHtmlAttr($this->url('moder/brand-vehicle/params', [
            'action'     => 'add',
            'brand_id'   => $brand->id,
            'vehicle_id' => $this->car->id
        ])) ?>" method="post">
            <button type="submit" class="btn btn-xs btn-success">
                <i class="fa fa-plus"></i>
                <?=$this->escapeHtml(sprintf($this->translate('moder/vehicle/catalogue/add-brand-%s'), $brand->name))?>
            </button>
        </form>
    <?php } ?>
<?php } ?>