<?php if ($this->canUseTree) { ?>
    <?php if ($this->car['is_group']) { ?>
        <?=$this->htmlA([
            'href'  => $this->url(null, [
                'action'       => 'organize',
                'item_type_id' => $this->car['item_type_id']
            ], [], true),
            'class' => 'btn btn-default',
        ], $this->translate('moder/vehicle/catalogue/turbo-group-creator'))?>
    <?php } ?>
    <table class="table">
        <thead>
            <tr>
                <th><?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/title/name'))?></th>
                <th><?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/title/link'))?></th>
                <th><?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/title/public'))?></th>
                <?php if ($this->canMove) { ?>
                    <th><?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/title/remove'))?></th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <?php if ($this->car['item_type_id'] != Application\Model\DbTable\Item\Type::TWINS) { ?>
                <tr>
                    <td colspan="3">
                        <form class="car-add-parent" method="post" action="<?=$this->escapeHtmlAttr($this->url(null, [
                            'action' => 'add-parent',
                        ], [], true)) ?>">
                            <div class="input-group" style="max-width:400px">
                                <span class="input-group-btn">
                                    <?=$this->htmlA([
                                        'href' => $this->url(null, [
                                            'action'  => 'car-select-parent',
                                            'item_id' => $this->car['id']
                                        ]),
                                        'class' => 'btn btn-success',
                                    ], $this->translate('moder/vehicle/catalogue/select'))?>
                                </span>
                                <input type="text" name="parent" class="form-control" placeholder="<?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/select-placeholder'))?>" data-autocomplete="<?=$this->escapeHtmlAttr($this->url(null, [
                                    'action'  => 'car-autocomplete',
                                    'item_id' => $this->car['id']
                                ], [], true))?>" />
                            </div>
                        </form>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td></td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <?php foreach ($this->parents as $car) { ?>
                <tr data-id="<?=$car['id']?>">
                    <td>
                        <i class="fa fa-arrow-up"></i>
                        <?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?>
                        <?php if ($car['duplicateRow']) { ?>
                            <br />
                            <div class="text-warning"><small>
                                <?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/possible-duplicate-parent'))?>
                                <?=$this->car()->htmlTitle($car['duplicateRow']->getNameData($this->language()))?>
                            </small></div>
                        <?php } ?>
                    </td>
                    <td>
                        <?=$this->htmlA(
                            $car['editUrl'],
                            $this->escapeHtml($car['parent']['name']) . ' <span class="fa fa-pencil"></span>',
                            false
                        )?>
                    </td>
                    <td class="urls">
                        <?php foreach ($car['publicUrls'] as $url) { ?>
                            <?=$this->htmlA($url, $url)?><br />
                        <?php } ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td>
                            <form action="<?=$this->escapeHtmlAttr($car['deleteUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-sm btn-danger">
                                    <i class="fa fa-times"></i>
                                </button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <tr class="success" data-id="<?=$this->car['id']?>">
                <td colspan="2">
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="fa fa-arrow-right"></i>
                    <?=$this->car()->htmlTitle($this->car->getNameData($this->language()))?>
                </td>
                <td class="urls">
                    <?php foreach ($this->publicUrls as $url) { ?>
                        <?=$this->htmlA($url, $url)?><br />
                    <?php } ?>
                </td>
                <?php if ($this->canMove) { ?>
                    <td></td>
                <?php } ?>
            </tr>
            <?php foreach ($this->childs as $car) { ?>
                <tr data-id="<?=$car['id']?>">
                    <td>
                        <i class="fa fa-arrow-down"></i>
                        <?php if ($car['parent']['type'] == Application\Model\DbTable\Vehicle\ParentTable::TYPE_TUNING) { ?>
                            <?=$this->escapeHtml($this->translate('moder/vehicle/link-type-prefix/related'))?>
                        <?php } elseif ($car['parent']['type'] == Application\Model\DbTable\Vehicle\ParentTable::TYPE_DESIGN) { ?>
                            <?=$this->escapeHtml($this->translate('moder/vehicle/link-type-prefix/design'))?>
                        <?php } elseif ($car['parent']['type'] == Application\Model\DbTable\Vehicle\ParentTable::TYPE_SPORT) { ?>
                            <?=$this->escapeHtml($this->translate('moder/vehicle/link-type-prefix/sport'))?>
                        <?php } ?>
                        <?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?>
                        <?php if ($car['duplicateRow']) { ?>
                            <br />
                            <div class="text-warning"><small>
                                <?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/possible-duplicate-child'))?>
                                <?=$this->car()->htmlTitle($car['duplicateRow']->getNameData($this->language()))?>
                            </small></div>
                        <?php } ?>
                    </td>
                    <td>
                        <?=$this->htmlA(
                            $car['editUrl'],
                            $this->escapeHtml($car['parent']['name']) . ' <span class="fa fa-pencil"></span>',
                            false
                        )?>
                    </td>
                    <td class="urls">
                        <?php foreach ($car['publicUrls'] as $url) { ?>
                            <?=$this->htmlA($url, $url)?><br />
                        <?php } ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td>
                            <form action="<?=$this->escapeHtmlAttr($car['deleteUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-sm btn-danger">
                                    <i class="fa fa-times"></i>
                                </button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>

            <?php if ($this->canMove) { ?>
                <?php if ($this->car['item_type_id'] == Application\Model\DbTable\Item\Type::CATEGORY) { ?>
                    <tr>
                        <td colspan="2">
                            <i class="fa fa-plus"></i>
                            <?=$this->htmlA(
                                $this->url('moder/cars/params', [
                                    'action'       => 'new',
                                    'parent_id'    => $this->car->id,
                                    'item_type_id' => Application\Model\DbTable\Item\Type::CATEGORY
                                ]),
                                $this->translate('moder/vehicle/catalogue/add-category')
                            )?>
                        </td>
                        <td class="urls"></td>
                        <?php if ($this->canMove) { ?>
                            <td></td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <i class="fa fa-plus"></i>
                            <?=$this->htmlA(
                                $this->url('moder/cars/params', [
                                    'action'       => 'new',
                                    'parent_id'    => $this->car->id,
                                    'item_type_id' => Application\Model\DbTable\Item\Type::ENGINE
                                ]),
                                $this->translate('moder/vehicle/catalogue/add-engine')
                            )?>
                        </td>
                        <td class="urls"></td>
                        <?php if ($this->canMove) { ?>
                            <td></td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <i class="fa fa-plus"></i>
                            <?=$this->htmlA(
                                $this->url('moder/cars/params', [
                                    'action'       => 'new',
                                    'parent_id'    => $this->car->id,
                                    'item_type_id' => Application\Model\DbTable\Item\Type::VEHICLE
                                ]),
                                $this->translate('moder/vehicle/catalogue/add-vehicle')
                            )?>
                        </td>
                        <td class="urls"></td>
                        <?php if ($this->canMove) { ?>
                            <td></td>
                        <?php } ?>
                    </tr>
                <?php } else { ?>
                    <tr>
                        <td colspan="2">
                            <i class="fa fa-plus"></i>
                            <?=$this->htmlA(
                                $this->url('moder/cars/params', [
                                    'action'       => 'new',
                                    'parent_id'    => $this->car->id,
                                    'item_type_id' => $this->car['item_type_id'],
                                ]),
                                $this->translate(
                                    $this->car['item_type_id'] == Application\Model\DbTable\Item\Type::ENGINE
                                        ? 'moder/vehicle/catalogue/add-engine'
                                        : 'moder/vehicle/catalogue/add-vehicle'
                                )
                            )?>
                        </td>
                        <td class="urls"></td>
                        <?php if ($this->canMove) { ?>
                            <td></td>
                        <?php } ?>
                    </tr>
                <?php } ?>
            <?php } ?>
        </tbody>
    </table>
<?php } ?>

<?php if ($this->canMove && $this->canAddBrand) { ?>
    <form action="<?=$this->escapeHtmlAttr($this->url('moder/cars/params', [
        'action'  => 'car-select-brand',
        'item_id' => $this->car->id
    ], [], true)) ?>" method="post"><div>
        <button type="submit" class="btn btn-xs btn-success">
            <i class="fa fa-plus"></i>
            <?=$this->escapeHtml($this->translate('moder/vehicle/catalogue/add-brand'))?>
        </button>
    </div></form>
    <?php foreach ($this->relevantBrands as $brand) { ?>
        <form action="<?=$this->escapeHtmlAttr($this->url('moder/cars/params', [
            'action'    => 'add-parent',
            'parent_id' => $brand->id,
            'item_id'   => $this->car->id
        ])) ?>" method="post">
            <button type="submit" class="btn btn-xs btn-success">
                <i class="fa fa-plus"></i>
                <?=$this->escapeHtml(sprintf($this->translate('moder/vehicle/catalogue/add-brand-%s'), $brand->name))?>
            </button>
        </form>
    <?php } ?>
<?php } ?>