<?php if (count($this->factories)) { ?>
    <table class="table"><tbody>
        <?php foreach ($this->factories as $factory) { ?>
            <tr>
                <td>
                    <?=$this->htmlA($factory['url'], $factory['name']) ?>
                    <?php if ($factory['inherited'] && count($factory['inheritedFrom'])) { ?>
                        <h6><em>
                            <?=$this->escapeHtml($this->translate('moder/vehicle/factories/inherited-from'))?>
                            <?php foreach ($factory['inheritedFrom'] as $car) { ?>
                                <?=$this->htmlA($car['url'], $car['name'])?>
                            <?php } ?>
                        </em></h6>
                    <?php } ?>
                </td>
                <?php if ($this->canEditFactory && !$factory['inherited']) { ?>
                    <td>
                        <form action="<?=$this->escapeHtmlAttr($factory['removeUrl']) ?>" method="post">
                            <button type="submit" class="btn btn-danger btn-xs">
                                <i class="fa fa-times"></i>
                                <?=$this->escapeHtml($this->translate('moder/vehicle/factories/remove'))?>
                            </button>
                        </form>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>
    </tbody></table>
<?php } else { ?>
    <p><?=$this->escapeHtml($this->translate('moder/vehicle/factories/factory-not-selected'))?></p>
<?php } ?>
<?php if ($this->canEditFactory) { ?>
    <p><?=$this->htmlA($this->url('moder/cars/params', [
        'action'  => 'car-select-factory',
        'item_id' => $this->car->id
    ]), $this->translate('moder/vehicle/factories/select-factory')) ?></p>
<?php } ?>