<?php if (count($this->twinsGroups)) { ?>
    <table class="table"><tbody>
        <?php foreach ($this->twinsGroups as $twinsGroup) { ?>
            <tr>
                <td>
                    <?=$this->htmlA($twinsGroup['url'], $twinsGroup['name']) ?>
                    <?php if ($twinsGroup['inherited'] && count($twinsGroup['inheritedFrom'])) { ?>
                        <h6><em>
                            <?=$this->escapeHtml($this->translate('moder/vehicle/twins/inherited-from'))?>
                            <?php foreach ($twinsGroup['inheritedFrom'] as $car) { ?>
                                <?=$this->htmlA($car['url'], $car['name'])?>
                            <?php } ?>
                        </em></h6>
                    <?php } ?>
                </td>
                <?php if ($this->canEditTwins && !$twinsGroup['inherited']) { ?>
                    <td>
                        <form action="<?=$this->escapeHtmlAttr($twinsGroup['removeUrl']) ?>" method="post">
                            <button type="submit" class="btn btn-danger btn-xs">
                                <i class="fa fa-times"></i>
                                <?=$this->escapeHtml($this->translate('moder/vehicle/twins/remove'))?>
                            </button>
                        </form>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>
    </tbody></table>
<?php } else { ?>
    <p><?=$this->escapeHtml($this->translate('moder/vehicle/twins/group-not-selected'))?></p>
<?php } ?>
<?php if ($this->canEditTwins) { ?>
    <p><?=$this->htmlA($this->url('moder/cars/params', [
        'action' => 'car-select-twins-group',
        'car_id' => $this->car->id
    ]), $this->translate('moder/vehicle/twins/select-or-create')) ?></p>
<?php } ?>