<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 144,
        'args'   => [
            'CAR_ID'   => $this->car->id,
            'CAR_NAME' => $this->car->getFullName($this->language())
        ]
    ]);
?>
<div class="well">
    <?php
        $columns = 4;
        $count = count($this->brands);
        $perOne = ceil($count / $columns);
        $width = round(100*$perOne/$count);
        $idx = 0;
    ?>
    <table style="width:100%" class="brand-selector"><tbody><tr>
        <td valign="top" style="width:<?=(100-$width*($columns-1)) ?>%">
            <?php foreach ($this->brands as $brand) { ?>
                <?php if ($idx && ($idx%$perOne == 0)) { ?>
                    </td><td valign="top" style="width:<?=$width ?>%">
                <?php } ?>
                <form action="<?=$this->escapeHtmlAttr($this->url('moder/brand-vehicle/params', [
                    'action'     => 'add',
                    'brand_id'   => $brand->id,
                    'vehicle_id' => $this->car->id
                ]))?>" method="post">
                    <button type="submit" class="btn btn-link"><?=$this->escapeHtml($brand->caption)?></button>
                </form>
                <?php $idx++ ?>
            <?php } ?>
        </td>
    </tr></tbody></table>
</div>