<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 145,
        'args'   => [
            'CAR_ID'   => $this->car->id,
            'CAR_NAME' => $this->car()->textTitle($this->car->getNameData($this->language()))
        ]
    ]);

    $this->layout()->moduleName = 'moder/cars/car-select-parent';
?>

<ul class="nav nav-pills" style="margin-bottom:10px">
    <?php if ($this->showBrandsTab) { ?>
        <li<?=$this->tab == 'brands' ? ' class="active"' : ''?>>
            <?=$this->htmlA($this->url(null, [
                'tab' => 'brands'
            ], [], true), '<i class="fa fa-list"></i> Brands', false) ?>
        </li>
    <?php } ?>
    <li<?=$this->tab == 'categories' ? ' class="active"' : ''?>>
        <?=$this->htmlA($this->url(null, [
            'tab' => 'categories'
        ], [], true), '<i class="fa fa-tag"></i> Categories', false) ?>
    </li>
    <?php if ($this->showTwinsTab) { ?>
        <li<?=$this->tab == 'twins' ? ' class="active"' : ''?>>
            <?=$this->htmlA($this->url(null, [
                'tab' => 'twins'
            ], [], true), '<i class="fa fa-adjust"></i> Twins', false) ?>
        </li>
    <?php } ?>
    <?php if ($this->showFactoriesTab) { ?>
        <li<?=$this->tab == 'factories' ? ' class="active"' : ''?>>
            <?=$this->htmlA($this->url(null, [
                'tab' => 'factories'
            ], [], true), '<i class="fa fa-cogs"></i> ' . $this->escapeHtml($this->translate('moder/vehicle/tabs/factories')), false) ?>
        </li>
    <?php } ?>
</ul>

<?php if ($this->tab == 'brands') { ?>
    <div class="well">
        <?php if (!$this->brand) { ?>
            <?php
                $columns = 6;
                $count = count($this->brands);
                $perOne = ceil($count / $columns);
                $width = round(100*$perOne/$count);
                $idx = 0;
            ?>
            <table class="table" class="brand-selector"><tbody><tr>
                <td style="width:<?=(100-$width*($columns-1)) ?>%">
                    <?php foreach ($this->brands as $brand) { ?>
                        <?php if ($idx && ($idx%$perOne == 0)) { ?>
                            </td><td style="width:<?=$width ?>%">
                        <?php } ?>
                        <?=$this->htmlA($this->url(null, [
                            'brand_id' => $brand['id']
                        ], [], true), $brand['name']) ?><br />
                        <?php $idx++ ?>
                    <?php } ?>
                </td>
            </tr></tbody></table>
        <?php } else { ?>
            <ul>
                <?=$this->partial('application/moder/cars/partial/car-select-parent', [
                    'cars' => $this->cars
                ])?>
            </ul>
        <?php } ?>
    </div>
<?php } ?>

<?php if ($this->tab == 'categories') { ?>
    <ul>
        <?=$this->partial('application/moder/cars/partial/car-select-parent', [
            'cars' => $this->cars
        ])?>
    </ul>
<?php } ?>

<?php if ($this->tab == 'twins') { ?>
    <div class="well">
        <?php if (!$this->brand) { ?>
            <?php
                $columns = 6;
                $count = count($this->brands);
                $perOne = ceil($count / $columns);
                $width = round(100*$perOne/$count);
                $idx = 0;
            ?>
            <table class="table" class="brand-selector"><tbody><tr>
                <td style="width:<?=(100-$width*($columns-1)) ?>%">
                    <?php foreach ($this->brands as $brand) { ?>
                        <?php if ($idx && ($idx%$perOne == 0)) { ?>
                            </td><td style="width:<?=$width ?>%">
                        <?php } ?>
                        <?=$this->htmlA($this->url(null, [
                            'brand_id' => $brand['id']
                        ], [], true), $brand['name']) ?><br />
                        <?php $idx++ ?>
                    <?php } ?>
                </td>
            </tr></tbody></table>
        <?php } else { ?>
            <ul>
                <?=$this->partial('application/moder/cars/partial/car-select-parent', [
                    'cars' => $this->cars
                ])?>
            </ul>
        <?php } ?>
    </div>
<?php } ?>

<?php if ($this->tab == 'factories') { ?>
    <div class="well">
        <ul>
            <?=$this->partial('application/moder/cars/partial/car-select-parent', [
                'cars' => $this->cars
            ])?>
        </ul>
    </div>
<?php } ?>