<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 146,
        'args'   => [
            'CAR_ID'   => $this->car->id,
            'CAR_NAME' => $this->car->getFullName()
        ]
    ]);
?>

<div class="well">
    <?php if ($this->brand) { ?>
        <ul class="selector">
            <?php foreach ($this->groups as $group) { ?>
                <li>
                    <?=$this->htmlA($this->url(null, [
                        'twins_group_id' => $group->id
                    ], [], true), $group->name) ?>
                </li>
            <?php } ?>
        </ul>
    <?php } else { ?>
        <?php
            $columns = 6;
            $count = count($this->brands);
            $perOne = ceil($count / $columns);
            $width = round(100*$perOne/$count);
            $idx = 0;
        ?>
        <table width="100%" class="brand-selector"><tbody><tr>
            <td valign="top" style="width:<?=(100-$width*($columns-1)) ?>%">
                <?php foreach ($this->brands as $brand) { ?>
                    <?php if ($idx && ($idx%$perOne == 0)) { ?>
                        </td><td valign="top" style="width:<?=$width ?>%">
                    <?php } ?>
                    <?=$this->htmlA($this->url(null, [
                        'brand_id' => $brand->id
                    ], [], true), $brand->caption) ?><br />
                    <?php $idx++ ?>
                <?php } ?>
            </td>
        </tr></tbody></table>
    <?php } ?>
</div>
<div class="well">
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->formTwinsGroupAdd
    ])?>
</div>