<?php if ($this->canEditMeta) { ?>
    <form method="post" action="<?=$this->escapeHtmlAttr($this->url(null, [
        'action' => 'car-categories-save'
    ], [], true))?>" id="car-categories">
        <?=$this->partial('application/moder/cars/car-categories-tree', [
            'categories' => $this->categories,
        ])?>
        <input type="submit" value="<?=$this->escapeHtmlAttr($this->translate('sumbit'))?>" class="btn btn-primary" />
    </form>
<?php } ?>