<?php if ($this->canUseTree) { ?>
    <h4>Структура</h4>
    <div class="btn-group">
        <?=$this->htmlA([
            'href'  => $this->url(null, [
                'action' => 'organize',
            ], [], true),
            'class' => 'btn btn-default',
        ], 'Турбо объединятор в группы')?>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Название</th>
                <th>Связь</th>
                <th>Папка</th>
                <th>На сайте</th>
                <?php if ($this->canMove) { ?>
                    <th>Уд.</th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <form class="car-add-parent" method="post" action="<?=$this->escapeHtmlAttr($this->url(null, [
                        'action' => 'add-parent',
                    ], [], true)) ?>">
                        <div class="input-group" style="max-width:400px">
                            <span class="input-group-btn">
                                <?=$this->htmlA([
                                    'href' => $this->url(null, [
                                        'action'    => 'car-select-parent',
                                        'brand_id'  => null,
                                        'parent_id' => null
                                    ], [], true),
                                    'class' => 'btn btn-success',
                                ], 'Выбрать ...')?>
                            </span>
                            <input type="text" name="parent" class="form-control" placeholder="Добавить родителя ..." data-autocomplete="<?=$this->escapeHtmlAttr($this->url(null, [
                                'action'        => 'car-autocomplete',
                                'exclude-child' => $this->car['id']
                            ], [], true))?>" />
                        </div>
                    </form>
                </td>
                <td></td>
                <td></td>
                <td></td>
                <?php if ($this->canMove) { ?>
                    <td></td>
                <?php } ?>
            </tr>
            <?php foreach ($this->parents as $car) { ?>
                <tr data-id="<?=$car['id']?>">
                    <td>
                        <i class="fa fa-arrow-up"></i>
                        <?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?>
                        <?php if ($car['duplicateRow']) { ?>
                            <br />
                            <div class="text-warning"><small>Возможно повтор: автомобиль уже унаследован через: <?=$this->escapeHtml($car['duplicateRow']->getFullName())?></small></div>
                        <?php } ?>
                    </td>
                    <td>
                        <form class="car-parent-type" method="post" action="<?=$this->escapeHtmlAttr($car['typeUrl']) ?>">
                            <?=$this->formElement(
                                (new Zend\Form\Element\Select('type'))
                                    ->setAttribute('class', 'form-control input-sm')
                                    ->setValueOptions($this->carParentTypeOptions)
                                    ->setValue($car['parent']['type'])
                            )?>
                        </form>
                    </td>
                    <td>
                        <form class="car-parent-catname" method="post" action="<?=$this->escapeHtmlAttr($car['catnameUrl']) ?>">
                            <div class="input-group" style="max-width:200px">
                                <?=$this->formElement(
                                    (new Zend\Form\Element\Text('name', [
                                        'value_options' => $this->carParentTypeOptions
                                    ]))
                                        ->setAttribute('class', 'form-control input-sm')
                                        ->setAttribute('placeholder', 'Название')
                                        ->setValue($car['parent']['name'])
                                )?>
                                <span class="input-group-btn" style="width:0px;"></span>
                                <?=$this->formElement(
                                    (new Zend\Form\Element\Text('catname'))
                                        ->setAttribute('class', 'form-control input-sm')
                                        ->setAttribute('placeholder', 'часть URL')
                                        ->setValue($car['parent']['catname'])
                                )?>
                                <span class="input-group-btn">
                                    <button class="btn btn-sm btn-default" type="submit">Ok</button>
                                </span>
                            </div>
                        </form>
                    </td>
                    <td class="urls">
                        <?php foreach ($car['publicUrls'] as $url) { ?>
                            <?=$this->htmlA($url, $url)?><br />
                        <?php } ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td>
                            <form action="<?=$this->escapeHtmlAttr($car['deleteUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-sm btn-danger">
                                    <i class="fa fa-times"></i>
                                </button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <tr class="success" data-id="<?=$this->car['id']?>">
                <td><?=$this->car()->htmlTitle($this->car->getNameData($this->language()))?></td>
                <td></td>
                <td></td>
                <td class="urls">
                    <?php foreach ($this->publicUrls as $url) { ?>
                        <?=$this->htmlA($url, $url)?><br />
                    <?php } ?>
                </td>
                <?php if ($this->canMove) { ?>
                    <td></td>
                <?php } ?>
            </tr>
            <?php foreach ($this->childs as $car) { ?>
                <tr data-id="<?=$car['id']?>">
                    <td>
                        <i class="fa fa-arrow-down"></i>
                        <?php if ($car['parent']['type'] == Car_Parent::TYPE_TUNING) { ?>
                            <?=$this->escapeHtml($this->translate('catalogue/related'))?>:
                        <?php } elseif ($car['parent']['type'] == Car_Parent::TYPE_DESIGN) { ?>
                            Дизайн:
                        <?php } elseif ($car['parent']['type'] == Car_Parent::TYPE_SPORT) { ?>
                            Спорт:
                        <?php } ?>
                        <?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?>
                        <?php if ($car['duplicateRow']) { ?>
                            <br />
                            <div class="text-warning"><small>Возможно повтор: автомобиль уже содержится в подразделе: <?=$this->escapeHtml($car['duplicateRow']->getFullName())?></small></div>
                        <?php } ?>
                    </td>
                    <td>
                        <form class="car-parent-type" method="post" action="<?=$this->escapeHtmlAttr($car['typeUrl']) ?>">
                            <?=$this->formElement(
                                (new Zend\Form\Element\Select('type', [
                                    'value_options' => $this->carParentTypeOptions
                                ]))
                                    ->setAttribute('class', 'form-control input-sm')
                                    ->setValue($car['parent']['type'])
                            )?>
                        </form>
                    </td>
                    <td>
                        <form class="car-parent-catname" method="post" action="<?=$this->escapeHtmlAttr($car['catnameUrl']) ?>">
                            <div class="input-group" style="max-width:200px">
                                <?=$this->formElement(
                                    (new Zend\Form\Element\Text('name'))
                                        ->setAttribute('class', 'form-control input-sm')
                                        ->setValue($car['parent']['name'])
                                        ->setAttribute('placeholder', 'название')
                                )?>
                                <span class="input-group-btn" style="width:0px;"></span>
                                <?=$this->formElement(
                                    (new Zend\Form\Element\Text('catname'))
                                        ->setAttribute('class', 'form-control input-sm')
                                        ->setValue($car['parent']['catname'])
                                        ->setAttribute('placeholder', 'часть URL')
                                )?>
                                <span class="input-group-btn">
                                    <button class="btn btn-sm btn-default" type="submit">Ok</button>
                                </span>
                            </div>
                        </form>
                    </td>
                    <td class="urls">
                        <?php foreach ($car['publicUrls'] as $url) { ?>
                            <?=$this->htmlA($url, $url)?><br />
                        <?php } ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td>
                            <form action="<?=$this->escapeHtmlAttr($car['deleteUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-sm btn-danger">
                                    <i class="fa fa-times"></i>
                                </button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>

            <?php if ($this->canMove) { ?>
                <tr>
                    <td>
                        <i class="fa fa-plus"></i>
                        <?=$this->htmlA($this->url('moder/cars/params', [
                            'action'    => 'new',
                            'parent_id' => $this->car->id
                        ]), 'добавить автомобиль')?>
                    </td>
                    <td></td>
                    <td></td>
                    <td class="urls"></td>
                    <?php if ($this->canMove) { ?>
                        <td></td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php } ?>


<h4>Бренды, связанные с этим автомобилем</h4>
<?php if (count($this->brands) || count($this->inheritBrands)) { ?>
    <table class="table table-striped" id="carModelTable">
        <thead>
            <tr>
                <th>Бренд</th>
                <th></th>
                <th></th>
                <th>На сайте</th>
                <?php if ($this->canMove) { ?>
                    <th>Уд.</th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->brands as $brand) { ?>
                <tr>
                    <td>
                        <?=$this->htmlA($brand['moderUrl'], $brand['name']) ?>
                    </td>
                    <td>
                        <?php if ($this->canMove) { ?>
                            <form action="<?=$this->escapeHtmlAttr($brand['setBrandCarTypeUrl']) ?>" method="post" class="inline brand-car-type">
                                <?=$this->formElement(
                                    (new Zend\Form\Element\Select('type', [
                                        'value_options' => $this->brandCarTypeOptions
                                    ]))
                                        ->setAttribute('class', 'form-control input-sm')
                                        ->setValue($brand['type'])
                                )?>
                            </form>
                        <?php } else { ?>
                            <?=$this->escapeHtml($this->brandCarTypeOptions[$brand['type']])?>
                        <?php } ?>
                    </td>
                    <td>
                        <?php if ($this->canMove) { ?>
                            <form action="<?=$this->escapeHtmlAttr($brand['setBrandCarCatnameUrl']) ?>" method="post" class="inline brand-car-catname">
                                <div class="input-group" style="max-width:200px">
                                    <?=$this->formElement(
                                        (new Zend\Form\Element\Text('catname'))
                                            ->setAttribute('class', 'form-control input-sm')
                                            ->setValue($brand['catname'])
                                    )?>
                                    <span class="input-group-btn">
                                        <button class="btn btn-default btn-sm" type="submit">Ok</button>
                                    </span>
                                </div>
                            </form>
                        <?php } else { ?>
                            <?=$this->escapeHtml($brand['catname'])?>
                        <?php } ?>
                    </td>
                    <td>
                        <?=$this->htmlA($brand['url'], $brand['url']) ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td>
                            <form action="<?=$this->escapeHtmlAttr($brand['deleteUrl']) ?>" method="post">
                                <button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-times"></i></button>
                            </form>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            <?php foreach ($this->inheritBrands as $brand) { ?>
                <tr class="warning">
                    <td>
                        <?=$this->htmlA($brand['moderUrl'], $brand['name']) ?>
                        <h6><em>Inherited from <?=$this->htmlA($brand['car']['url'], $brand['car']['name'])?></em></h6>
                    </td>
                    <td>
                        <?=$this->escapeHtml($this->brandCarTypeOptions[$brand['type']])?>
                    </td>
                    <td>
                        <?=$this->escapeHtml($brand['catname'])?>
                    </td>
                    <td>
                        <?=$this->htmlA($brand['url'], $brand['url']) ?>
                    </td>
                    <?php if ($this->canMove) { ?>
                        <td></td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php } ?>
<?php if ($this->canMove) { ?>
    <form action="<?=$this->escapeHtmlAttr($this->url('moder/cars/params', [
        'action' => 'car-select-brand',
        'car_id' => $this->car->id
    ], [], true)) ?>" method="post"><div>
        <button type="submit" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> Бренд ...</button>
    </div></form>
    <?php foreach ($this->relevantBrands as $brand) { ?>
        <form action="<?=$this->escapeHtmlAttr($this->url('moder/cars/params', [
            'action'   => 'car-select-brand',
            'car_id'   => $this->car->id,
            'brand_id' => $brand->id
        ], [], true)) ?>" method="post">
            <button type="submit" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> Бренд <?=$this->escapeHtml($brand->caption)?></button>
        </form>
    <?php } ?>
<?php } ?>