<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 131,
    ]);
?>
<ul class="nav nav-pills">
    <li>
        <?=$this->htmlA('/moder/cars/index/vehicle_type_id/empty/vehicle_childs_type_id/19', 'Buses without type')?>
    </li>
    <li>
        <?=$this->htmlA('/moder/cars/index/vehicle_type_id/empty/vehicle_childs_type_id/17', 'Truck without type')?>
    </li>
</ul>
<div class="row">
    <div class="col-lg-4 col-md-4">
        <h2><?=$this->escapeHtml($this->translate('moder/vehicles/filter'))?></h2>
        <div class="well">
            <?=$this->partial('application/forms/bootstrap-vertical', [
                'form' => $this->form
            ])?>
        </div>
    </div>
    <div class="col-lg-8 col-md-8">
        <h2>
            <?=$this->escapeHtml($this->page(131)->name)?>
            <?php if ($count = $this->paginator->getTotalItemCount()) {?>
                <small><?=$this->escapeHtml(sprintf($this->translatePlural('%1$s vehicles', '%1$s vehicles', $count), $count))?></small>
            <?php } ?>
        </h2>
        <?=$this->partial('application/cars', $this->listData)?>
        <?=$this->paginationControl($this->paginator, null, null, [
            'route' => 'moder/cars/params'
        ]) ?>
    </div>
</div>