<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 163,
        'args'   => [
            'NEW_ITEM_OF_TYPE' => $this->translate('item/type/'.$this->itemTypeId.'/new-item')
        ]
    ]);

    $this->layout()->moduleName = 'moder/cars/new';
?>
<?php if ($this->parentCar) { ?>
    <p>
        <?=$this->escapeHtml($this->translate('moder/vehicle/add/as-submodel'))?>
        <?=$this->car()->htmlTitle($this->parentCar->getNameData($this->language()))?>
    </p>
<?php } ?>
<?=$this->partial('application/forms/bootstrap-horizontal', [
    'form' => $this->form
])?>