<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 163,
    ]);
    
    $this->layout()->moduleName = 'moder/cars/new';
?>
<?php if ($this->parentCar) { ?>
    <p>
        <?=$this->escapeHtml($this->translate('moder/vehicle/add/as-submodel'))?>
        <?=$this->car($this->parentCar)->title()?>
    </p>
<?php } ?>
<?=$this->partial('application/forms/bootstrap-horizontal', [
    'form' => $this->form
])?>