<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 163,
    ]);
?>
<?php if ($this->parentCar) { ?>
    <p>В автомобиль <?=$this->car($this->parentCar)->title()?></p>
<?php } ?>
<?=$this->partial('application/forms/bootstrap-horizontal', [
    'form' => $this->form
])?>