<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 78,
        'args'   => [
            'CAR_ID'   => $this->car->id,
            'CAR_NAME' => $this->car->getFullName($this->language())
        ]
    ]);

    $this->layout()->moduleName = 'moder/cars/organize-pictures';
?>
<?=$this->markdown($this->translate('moder/vehicle/pictures/turbo-group-creator'))?>
<?=$this->partial('application/forms/bootstrap-horizontal', [
    'form' => $this->form
])?>