<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 125,
    ));
?>
<?=$this->htmlA(array(
    'class' => 'btn btn-success',
    'href' => $this->url(array(
        'action' => 'new'
    ))
), 'Новый')?>

<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>N</th>
            <th>Название</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php
            printPagesRecuirsiveTree($this, new Category());
        ?>
    </tbody>
</table>

<?php
    function printPagesRecuirsiveTree($view, $pages, $parentId = null, $level = 0)
    {
        $offset = (int)$level*20;

        $select = $pages->select(true)
            ->order('short_name');
        if ($parentId)
            $select->where('parent_id = ?', $parentId);
        else
        {
            $select->where('parent_id IS NULL');
        }
        $rows = $pages->fetchAll($select);
        foreach ($rows as $idx => $page) {
            ?>
            <tr class="data-row">
                <td><?=$page->id ?></td>
                <td style="padding-left:<?=$offset?>px"><?=$view->escape($page->name) ?></td>
                <td>
                    <div class="btn-group">
                        <?=$view->htmlA(array(
                            'class' => "btn btn-xs btn-success",
                            'href'  => $view->url(array(
                                'action'    => 'new',
                                'parent_id' => $page->id
                            ))
                        ), 'Добавить') ?>
                        <?=$view->htmlA(array(
                            'class' => "btn btn-xs btn-default",
                            'href'  => $view->url(array(
                                'action' => 'edit',
                                'id'     => $page->id
                            ))
                        ), 'Изменить') ?>
                    </div>
                </td>
            </tr>
            <?php
            printPagesRecuirsiveTree($view, $pages, $page->id, $level+1);
        }
    }
?>