<?php

return [
    'tables' => [
        'acl_roles' => [], //TODO: rename to acl_role
        'acl_roles_parents' => [], //TODO: rename to acl_role_parent
        'acl_resources' => [], //TODO: rename to acl_resources
        'acl_resources_privileges' => [], //TODO: rename to acl_resource_privilege
        'acl_roles_privileges_allowed' => [], //TODO: rename to acl_role_privilege_allowed
        'acl_roles_privileges_denied' => [], //TODO: rename to acl_role_privilege_denied
        'articles' => [],
        'attrs_attributes' => [],
        'attrs_list_options' => [],
        'attrs_types' => [],
        'attrs_units' => [],
        'attrs_user_values' => [],
        'attrs_user_values_float' => [],
        'attrs_user_values_int' => [],
        'attrs_user_values_list' => [],
        'attrs_user_values_string' => [],
        'attrs_values' => [],
        'attrs_values_float' => [],
        'attrs_values_int' => [],
        'attrs_values_list' => [],
        'attrs_values_string' => [],
        'attrs_zone_attributes' => [],
        'attrs_zones' => [],
        'brand_alias' => [], //TODO: rename to item_alias
        'car_types'   => [], //TODO: rename to vehicle_type
        'car_types_parents' => [], //TODO: rename to vehicle_type_parent
        'combination_modification' => [],
        'contact' => [],
        'df_distance' => [],
        'df_hash' => [],
        'htmls' => [],
        'item' => [],
        'item_language' => [],
        'item_parent' => [],
        'item_parent_cache' => [],
        'item_parent_language' => [],
        'item_point' => [],
        'links' => [],
        'log_events' => [],
        'log_events_articles' => [],
        'log_events_item' => [],
        'log_events_pictures' => [],
        'log_events_user' => [],
        'login_state' => [],
        'modification' => [],
        'modification_group' => [],
        'modification_picture' => [],
        'of_day' => [],
        'pages' => [], //TODO: rename to page
        'perspectives' => [],
        'perspectives_groups' => [],
        'perspectives_pages' => [],
        'pictures' => [], //TODO: rename to picture
        'pictures_moder_votes' => [],
        'picture_item' => [],
        'picture_moder_vote_template' => [],
        'picture_view' => [],
        'picture_vote' => [],
        'picture_vote_summary' => [],
        'spec' => [],
        'telegram_brand' => [],
        'telegram_chat' => [],
        'user_account' => [],
        'user_item_subscribe' => [],
        'user_password_remind' => [],
        'user_remember' => [],
        'user_renames' => [],

        'vehicle_vehicle_type' => [], //TODO: rename to item_vehicle_type
    ]
];
