/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AttrConflictsRequestFilter = {
    All: 'ALL',
    DoNotAgreeWithMe: 'DO_NOT_AGREE_WITH_ME',
    IDisagree: 'I_DISAGREE',
    MinusWeight: 'MINUS_WEIGHT'
} as const;
export type AttrConflictsRequestFilter = typeof AttrConflictsRequestFilter[keyof typeof AttrConflictsRequestFilter];

