/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPathTreePictureItem } from './goautowpPathTreePictureItem';
import { GoautowpPicturesPages } from './goautowpPicturesPages';
import { GoautowpPictureItems } from './goautowpPictureItems';
import { GoautowpPicturesVoteSummary } from './goautowpPicturesVoteSummary';
import { GoautowpPictureRights } from './goautowpPictureRights';
import { GoautowpAPIImage } from './goautowpAPIImage';
import { GoautowpPictureModerVotes } from './goautowpPictureModerVotes';
import { TypeLatLng } from './typeLatLng';
import { GoautowpDfDistances } from './goautowpDfDistances';
import { TypeDate } from './typeDate';
import { GoautowpPictureStatus } from './goautowpPictureStatus';
import { GoautowpPictureSiblings } from './goautowpPictureSiblings';


export interface GoautowpPicture { 
    id: string;
    identity: string;
    width: number;
    height: number;
    image: GoautowpAPIImage;
    point: TypeLatLng;
    copyrightsTextId: number;
    thumbMedium: GoautowpAPIImage;
    thumbLarge: GoautowpAPIImage;
    nameText: string;
    nameHtml: string;
    ownerId: string;
    status: GoautowpPictureStatus;
    cropped: boolean;
    cropResolution: string;
    resolution: string;
    views: number;
    votes: GoautowpPicturesVoteSummary;
    commentsCountTotal: number;
    commentsCountNew: number;
    moderVoteVote: number;
    moderVoteCount: number;
    path: Array<GoautowpPathTreePictureItem>;
    pictureItems: GoautowpPictureItems;
    imageGallery: GoautowpAPIImage;
    imageGalleryFull: GoautowpAPIImage;
    dfDistances: GoautowpDfDistances;
    acceptedCount: number;
    addDate: Date;
    copyrights: string;
    exif: string;
    isLast: boolean;
    moderVoted: boolean;
    pictureModerVotes: GoautowpPictureModerVotes;
    replaceable: GoautowpPicture;
    rights: GoautowpPictureRights;
    siblings: GoautowpPictureSiblings;
    specialName: string;
    takenDate: TypeDate;
    changeStatusUserId: string;
    ip: string;
    dpiX: number;
    dpiY: number;
    previewLarge: GoautowpAPIImage;
    subscribed: boolean;
    paginator: GoautowpPicturesPages;
}
export namespace GoautowpPicture {
}


