/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemParentListOptions } from './goautowpItemParentListOptions';
import { GoautowpItemVehicleTypeListOptions } from './goautowpItemVehicleTypeListOptions';
import { GoautowpPictureItemListOptions } from './goautowpPictureItemListOptions';
import { GoautowpItemListOptions } from './goautowpItemListOptions';


export interface GoautowpItemParentCacheListOptions { 
    itemId: string;
    parentId: string;
    itemsByItemId: GoautowpItemListOptions;
    itemsByParentId: GoautowpItemListOptions;
    pictureItemsByItemId: GoautowpPictureItemListOptions;
    pictureItemsByParentId: GoautowpPictureItemListOptions;
    itemParentByItemId: GoautowpItemParentListOptions;
    itemParentCacheAncestorByItemId: GoautowpItemParentCacheListOptions;
    itemVehicleTypeByItemId: GoautowpItemVehicleTypeListOptions;
}

