/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIUser } from './goautowpAPIUser';


export interface GoautowpContact { 
    contactUserId: string;
    user: GoautowpAPIUser;
}

