/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpAPIForumsTheme { 
    id: string;
    name: string;
    topicsCount: number;
    messagesCount: number;
    disableTopics: boolean;
    description: string;
}

