/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPages } from './goautowpPages';
import { GoautowpArticle } from './goautowpArticle';


export interface GoautowpArticlesResponse { 
    items: Array<GoautowpArticle>;
    paginator: GoautowpPages;
}

