/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GoautowpPictureItemsRequestOrder = {
    None: 'NONE',
    FrontPerspectivesFirst: 'FRONT_PERSPECTIVES_FIRST'
} as const;
export type GoautowpPictureItemsRequestOrder = typeof GoautowpPictureItemsRequestOrder[keyof typeof GoautowpPictureItemsRequestOrder];

