/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GoautowpItemType = {
    ItemTypeUnknown: 'ITEM_TYPE_UNKNOWN',
    ItemTypeVehicle: 'ITEM_TYPE_VEHICLE',
    ItemTypeEngine: 'ITEM_TYPE_ENGINE',
    ItemTypeCategory: 'ITEM_TYPE_CATEGORY',
    ItemTypeTwins: 'ITEM_TYPE_TWINS',
    ItemTypeBrand: 'ITEM_TYPE_BRAND',
    ItemTypeFactory: 'ITEM_TYPE_FACTORY',
    ItemTypeMuseum: 'ITEM_TYPE_MUSEUM',
    ItemTypePerson: 'ITEM_TYPE_PERSON',
    ItemTypeCopyright: 'ITEM_TYPE_COPYRIGHT'
} as const;
export type GoautowpItemType = typeof GoautowpItemType[keyof typeof GoautowpItemType];

