/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIBanItem } from './goautowpAPIBanItem';


export interface GoautowpAPITrafficTopItem { 
    ip: string;
    count: number;
    ban: GoautowpAPIBanItem;
    inWhitelist: boolean;
    whoisUrl: string;
}

