/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttrAttributeTypeID } from './attrAttributeTypeID';


export interface GoautowpAttrAttributeType { 
    id: AttrAttributeTypeID;
    name: string;
}
export namespace GoautowpAttrAttributeType {
}


