/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemParentListOptions } from './goautowpItemParentListOptions';
import { GoautowpItemVehicleTypeListOptions } from './goautowpItemVehicleTypeListOptions';
import { GoautowpPictureItemListOptions } from './goautowpPictureItemListOptions';
import { GoautowpItemType } from './goautowpItemType';
import { GoautowpItemParentCacheListOptions } from './goautowpItemParentCacheListOptions';


export interface GoautowpItemListOptions { 
    typeId: GoautowpItemType;
    previewPictures: GoautowpPictureItemListOptions;
    noParent: boolean;
    catname: string;
    name: string;
    id: string;
    isConcept: boolean;
    isNotConcept: boolean;
    isNotConceptInherited: boolean;
    descendant: GoautowpItemParentCacheListOptions;
    ancestor: GoautowpItemParentCacheListOptions;
    parent: GoautowpItemParentListOptions;
    engineId: string;
    child: GoautowpItemParentListOptions;
    parentTypesOf: GoautowpItemType;
    isGroup: boolean;
    excludeSelfAndChilds: string;
    autocomplete: string;
    suggestionsTo: string;
    typeIds: Array<GoautowpItemType>;
    pictureItems: GoautowpPictureItemListOptions;
    dateless: boolean;
    dateful: boolean;
    relatedGroupsOf: string;
    nameExclude: string;
    specId: string;
    beginYear: number;
    endYear: number;
    text: string;
    noVehicleType: boolean;
    itemVehicleType: GoautowpItemVehicleTypeListOptions;
}
export namespace GoautowpItemListOptions {
}


