/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPages } from './goautowpPages';
import { GoautowpAPIItem } from './goautowpAPIItem';


export interface GoautowpAPIItemList { 
    items: Array<GoautowpAPIItem>;
    paginator: GoautowpPages;
}

