/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpAPIImage { 
    id: number;
    src: string;
    width: number;
    height: number;
    filesize: number;
    cropLeft: number;
    cropTop: number;
    cropWidth: number;
    cropHeight: number;
}

