/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpNullPicture } from './goautowpNullPicture';


export interface GoautowpPreviewPictures { 
    largeFormat: boolean;
    pictures: Array<GoautowpNullPicture>;
    totalPictures: number;
}

