/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAttrUnit } from './goautowpAttrUnit';


export interface GoautowpAttrUnitsResponse { 
    items: Array<GoautowpAttrUnit>;
}

