/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPerspective } from './goautowpPerspective';


export interface GoautowpPerspectiveGroup { 
    id: number;
    name: string;
    perspectives: Array<GoautowpPerspective>;
}

