/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpPictureRights { 
    move: boolean;
    accept: boolean;
    unaccept: boolean;
    restore: boolean;
    normalize: boolean;
    flop: boolean;
    crop: boolean;
    'delete': boolean;
}

