/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPublicRoute } from './goautowpPublicRoute';
import { GoautowpDesign } from './goautowpDesign';
import { GoautowpItemLinks } from './goautowpItemLinks';
import { GoautowpPictureItems } from './goautowpPictureItems';
import { TypeLatLng } from './typeLatLng';
import { GoautowpAltName } from './goautowpAltName';
import { GoautowpItemParents } from './goautowpItemParents';
import { GoautowpRelatedGroupPicture } from './goautowpRelatedGroupPicture';
import { GoautowpItemType } from './goautowpItemType';
import { GoautowpAPIImage } from './goautowpAPIImage';
import { GoautowpPreviewPictures } from './goautowpPreviewPictures';
import { GoautowpChildsCount } from './goautowpChildsCount';
import { GoautowpSpecsContributor } from './goautowpSpecsContributor';
import { GoautowpItemOfDayPicture } from './goautowpItemOfDayPicture';


export interface GoautowpAPIItem { 
    id: string;
    catname: string;
    nameOnly: string;
    nameText: string;
    nameHtml: string;
    nameDefault: string;
    descendantsCount: number;
    engineItemId: string;
    itemTypeId: GoautowpItemType;
    description: string;
    isConcept: boolean;
    isConceptInherit: boolean;
    specId: number;
    specInherit: boolean;
    fullText: string;
    descendantPicturesCount: number;
    inboxPicturesCount: number;
    acceptedPicturesCount: number;
    exactPicturesCount: number;
    childsCount: number;
    parentsCount: number;
    descendantTwinsGroupsCount: number;
    fullName: string;
    logo: GoautowpAPIImage;
    logo120: GoautowpAPIImage;
    mostsActive: boolean;
    commentsAttentionsCount: number;
    isCompilesItemOfDay: boolean;
    brandicon: GoautowpAPIImage;
    attrZoneId: string;
    engineInherit: boolean;
    location: TypeLatLng;
    hasChildSpecs: boolean;
    hasSpecs: boolean;
    produced: number;
    producedExactly: boolean;
    otherNames: Array<string>;
    design: GoautowpDesign;
    specsRoute: Array<string>;
    isGroup: boolean;
    childsCounts: Array<GoautowpChildsCount>;
    publicRoutes: Array<GoautowpPublicRoute>;
    pictureItems: GoautowpPictureItems;
    altNames: Array<GoautowpAltName>;
    route: Array<string>;
    links: GoautowpItemLinks;
    hasText: boolean;
    categories: Array<GoautowpAPIItem>;
    twins: Array<GoautowpAPIItem>;
    canEditSpecs: boolean;
    itemParentChilds: GoautowpItemParents;
    commentsCount: number;
    previewPictures: GoautowpPreviewPictures;
    engineVehicles: Array<GoautowpAPIItem>;
    relatedGroupPictures: Array<GoautowpRelatedGroupPicture>;
    itemOfDayPictures: Array<GoautowpItemOfDayPicture>;
    beginYear: number;
    endYear: number;
    beginMonth: number;
    endMonth: number;
    beginModelYear: number;
    endModelYear: number;
    beginModelYearFraction: string;
    endModelYearFraction: string;
    body: string;
    name: string;
    today: boolean;
    engineVehiclesCount: number;
    itemLanguageCount: number;
    linksCount: number;
    specificationsCount: number;
    subscription: boolean;
    specsContributors: Array<GoautowpSpecsContributor>;
}
export namespace GoautowpAPIItem {
}


