/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIItem } from './goautowpAPIItem';
import { GoautowpPicturesList } from './goautowpPicturesList';
import { GoautowpItemParentType } from './goautowpItemParentType';


export interface GoautowpItemParent { 
    itemId: string;
    parentId: string;
    type: GoautowpItemParentType;
    catname: string;
    item: GoautowpAPIItem;
    parent: GoautowpAPIItem;
    duplicateParent: GoautowpAPIItem;
    duplicateChild: GoautowpAPIItem;
    childDescendantPictures: GoautowpPicturesList;
}
export namespace GoautowpItemParent {
}


