/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPulseGrid } from './goautowpPulseGrid';
import { GoautowpPulseLegend } from './goautowpPulseLegend';


export interface GoautowpPulseResponse { 
    grid: Array<GoautowpPulseGrid>;
    legend: Array<GoautowpPulseLegend>;
    labels: Array<string>;
}

