/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpAPIMessageSummary { 
    inboxCount: number;
    inboxNewCount: number;
    sentCount: number;
    systemCount: number;
    systemNewCount: number;
}

