/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemVehicleTypeListOptions } from './goautowpItemVehicleTypeListOptions';
import { GoautowpPictureListOptions } from './goautowpPictureListOptions';
import { GoautowpPictureItemType } from './goautowpPictureItemType';
import { GoautowpItemListOptions } from './goautowpItemListOptions';
import { GoautowpItemParentCacheListOptions } from './goautowpItemParentCacheListOptions';


export interface GoautowpPictureItemListOptions { 
    pictureId: string;
    itemId: string;
    typeId: GoautowpPictureItemType;
    pictures: GoautowpPictureListOptions;
    perspectiveId: number;
    excludePerspectiveId: Array<number>;
    excludeAncestorOrSelfId: string;
    item: GoautowpItemListOptions;
    itemParentCacheAncestor: GoautowpItemParentCacheListOptions;
    itemVehicleType: GoautowpItemVehicleTypeListOptions;
    hasNoPerspectiveId: boolean;
    pictureItemByPictureId: GoautowpPictureItemListOptions;
    hasArea: boolean;
}
export namespace GoautowpPictureItemListOptions {
}


