/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPictureFields } from './goautowpPictureFields';
import { GoautowpPictureListOptions } from './goautowpPictureListOptions';
import { GoautowpPicturesRequestOrder } from './goautowpPicturesRequestOrder';


export interface GoautowpPicturesRequest { 
    options: GoautowpPictureListOptions;
    limit: number;
    page: number;
    paginator: boolean;
    fields: GoautowpPictureFields;
    language: string;
    order: GoautowpPicturesRequestOrder;
}
export namespace GoautowpPicturesRequest {
}


