/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAttrZone } from './goautowpAttrZone';


export interface GoautowpAttrZonesResponse { 
    items: Array<GoautowpAttrZone>;
}

