/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpVotingVariant } from './goautowpVotingVariant';


export interface GoautowpVoting { 
    id: number;
    beginDate: Date;
    endDate: Date;
    canVote: boolean;
    multivariant: boolean;
    name: string;
    text: string;
    variants: Array<GoautowpVotingVariant>;
}

