/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpDfDistanceListOptions } from './goautowpDfDistanceListOptions';
import { GoautowpDfDistanceFields } from './goautowpDfDistanceFields';


export interface GoautowpDfDistanceRequest { 
    limit: number;
    options: GoautowpDfDistanceListOptions;
    fields: GoautowpDfDistanceFields;
}

