/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttrAttributeTypeID } from './attrAttributeTypeID';


export interface GoautowpAttrValueValue { 
    valid: boolean;
    intValue: number;
    floatValue: number;
    stringValue: string;
    boolValue: boolean;
    listValue: Array<string>;
    type: AttrAttributeTypeID;
    isEmpty: boolean;
}
export namespace GoautowpAttrValueValue {
}


