/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpAPIMessage { 
    id: string;
    text: string;
    isNew: boolean;
    canDelete: boolean;
    canReply: boolean;
    date: Date;
    allMessagesLink: boolean;
    dialogCount: number;
    authorId: string;
    toUserId: string;
    dialogWithUserId: string;
}

