/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemLinkListOptions } from './goautowpItemLinkListOptions';


export interface GoautowpItemLinksRequest { 
    options: GoautowpItemLinkListOptions;
}

