/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * `NullValue` is a singleton enumeration to represent the null value for the `Value` type union.  The JSON representation for `NullValue` is JSON `null`.   - NULL_VALUE: Null value.
 */
export const ProtobufNullValue = {
    NullValue: 'NULL_VALUE'
} as const;
export type ProtobufNullValue = typeof ProtobufNullValue[keyof typeof ProtobufNullValue];

