/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PulseRequestPeriod = {
    Default: 'DEFAULT',
    Year: 'YEAR',
    Month: 'MONTH'
} as const;
export type PulseRequestPeriod = typeof PulseRequestPeriod[keyof typeof PulseRequestPeriod];

