/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleType } from './vehicleType';


export interface VehicleTypeItems { 
    items?: Array<VehicleType>;
}

