<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => true
        ],
        'pageId' => 159,
        'args'   => [
            'MUSEUM_ID'   => $this->museum->id,
            'MUSEUM_NAME' => $this->museum->name
        ]
    ]);

    $this->layout()->moduleName = 'default/museums/museum';
    if ($this->point) {
        $this->layout()->moduleOptions = [
            'lat' => $this->point->y(),
            'lng' => $this->point->x(),
        ];
    }
?>

<?php if ($this->user()->inheritsRole('museum-moder')) { ?>
    <p>
        <i class="fa fa-cog"></i>
        <?=$this->htmlA($this->url('moder/cars/params', [
            'action'  => 'car',
            'item_id' => $this->museum['id']
        ]), $this->translate('moder/edit-object'))?>
    </p>
<?php } ?>

<div id="google-map"></div>

<div class="well">
    <?=$this->markdown($this->description) ?>
    
    <?php if (count($this->links)) { ?>
        <p>
            <?=$this->escapeHtml($this->translate('museums/museum/website:'))?>
            <?php foreach ($this->links as $link) { ?>
                <?=$this->htmlA($link->url, $link->name ? $link->name : $link->url)?><br />
            <?php } ?>
        </p>
    <?php } ?>
</div>

<?php if ($this->pictures && count($this->pictures['items']) > 0) { ?>
    <h3><?=$this->escapeHtml($this->translate('factories/factory/pictures'))?></h3>
    <?=$this->partial('application/pictures', $this->pictures)?>
<?php } ?>

<div id="comments">
    <?=$this->comments([
        'type'    => Application\Model\DbTable\Comment\Message::MUSEUMS_TYPE_ID,
        'item_id' => $this->museum->id
    ]) ?>
</div>