<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => true
        ],
        'pageId' => 159,
        'args'   => [
            'MUSEUM_ID'   => $this->museum->id,
            'MUSEUM_NAME' => $this->museum->name
        ]
    ]);

    $this->layout()->moduleName = 'default/museums/museum';
    if ($this->point) {
        $this->layout()->moduleOptions = [
            'lat' => $this->point->y(),
            'lng' => $this->point->x(),
        ];
    }
?>

<div id="google-map"></div>

<div class="well">
    <?php if ($this->museum->address) { ?>
        <p>
            <?=$this->escapeHtml($this->translate('museums/museum/address:'))?>
            <?=$this->escapeHtml($this->museum->address)?>
        </p>
    <?php } ?>

    <?php if ($this->museum->url) { ?>
        <p>
            <?=$this->escapeHtml($this->translate('museums/museum/website'))?>
            <?=$this->htmlA($this->museum->url, $this->museum->url)?>
        </p>
    <?php } ?>

    <?=$this->museum->description ?>
</div>

<div id="comments">
    <?=$this->comments([
        'type'    => Comment_Message::MUSEUMS_TYPE_ID,
        'item_id' => $this->museum->id
    ]) ?>
</div>