<?php
    $this->pageEnv(array(
        'layout'    => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => true
        ),
        'pageId'    => 174
    ));
?>
<table class="table"><tbody>
    <?php foreach ($this->items as $item) { ?>
        <tr>
            <td><?=$this->escape($item['short_name'])?></td>
            <td><?=$this->escape($item['name'])?></td>
        </tr>
    <?php } ?>
</tbody></table>