<?php
    $this->form->setAttribute(
        'class',
        $this->form->getAttribute('class') . ' form-horizontal'
    );
?>
<?=$this->form()->openTag($this->form)?>
<fieldset>
    <?php if ($legend = $this->form->getAttribute('legend')) { ?>
        <legend><?=$this->escapeHtml($this->translate($legend))?></legend>
    <?php } ?>
    <?=$this->partial('application/moder/cars/partial/languages-form-elements', [
        'form' => $this->form
    ])?>
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <?=$this->formElement(
                (new Zend\Form\Element\Submit('submit'))
                    ->setAttribute('class', 'btn btn-primary')
                    ->setValue($this->translate('submit'))
            )?>
        </div>
    </div>
</fieldset>
<?=$this->form()->closeTag($this->form)?>