<?php foreach ($this->form->getIterator() as $key => $element) { ?>
    <?php if (!$element instanceof Zend\Form\Element\Multicheckbox) { ?>
        <?php
            $element->setLabelAttributes(array_replace([
                'class' => 'col-md-2 control-label'
            ], $element->getLabelAttributes()))
        ?>
    <?php } ?>
    <?php if ($element instanceof Zend\Form\Element\Textarea) { ?>
        <?php 
            $prefix = $this->prefix . '-' . $key;
        ?>
        <div class="form-group<?=$element->getMessages() ? ' has-error' : ''?>">
            <?=$this->formLabel($element)?>
            <div class="col-md-10">
                <div data-module="markdown-edit-tabbar">
                    <ul id="<?=$prefix?>-markdown" class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#<?=$prefix?>-markdown-edit" id="<?=$prefix?>-markdown-tab" role="tab" data-toggle="tab" aria-expanded="true" aria-controls="edit">
                                <?=$this->escapeHtml($this->translate('moder/markdown/edit'))?>
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#<?=$prefix?>-markdown-preview" class="tab-preview" id="<?=$prefix?>-markdown-tab" role="tab" data-toggle="tab" aria-expanded="false" aria-controls="preview">
                                <?=$this->escapeHtml($this->translate('moder/markdown/preview'))?>
                            </a>
                        </li>
                    </ul>
                    <div id="<?=$prefix?>-content" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="<?=$prefix?>-markdown-edit" aria-labelledby="edit-tab">
                            <?=$this->formElement(
                                $element
                                    ->setAttribute('class', $element->getAttribute('class') . ' form-control')
                            )?>
                            <?php foreach ($element->getMessages() as $error) { ?>
                                <p class="help-block"><?=$this->escapeHtml($error)?></p>
                            <?php } ?>
                        </div>
                        <div role="tabpanel" class="tab-pane tab-pane-preview fade" id="<?=$prefix?>-markdown-preview" aria-labelledby="preview-tab" style="padding:7px 13px">
                        </div>
                    </div>
                    <?php if ($textId = $element->getAttribute('text-id')) { ?>
                        <p>
                            <?=$this->htmlA([
                                'class' => 'pull-right',
                                'href'  => $this->url('info/text', [
                                    'action' => 'text',
                                    'id'     => $textId
                                ])
                            ], $this->translate('moder/markdown/history'))?>
                        </p>
                    <?php } ?>
                </div>
            </div>
        </div>
    <?php } else { ?>
        <div class="form-group<?=$element->getMessages() ? ' has-error' : ''?>">
            <?=$this->formLabel($element)?>
            <div class="col-md-10">
                <?=$this->formElement(
                    $element
                        ->setAttribute('class', $element->getAttribute('class') . ' form-control')
                )?>
                <?php foreach ($element->getMessages() as $error) { ?>
                    <p class="help-block"><?=$this->escapeHtml($error)?></p>
                <?php } ?>
            </div>
        </div>
    <?php } ?>
<?php } ?>