<?php if (count($this->attributes)) { ?>
    <ul>
        <?php foreach ($this->attributes as $idx => $attribute) { ?>
            <li>
                <?php if ($idx < count($this->attributes)-1) { ?>
                    <?=$this->htmlA($this->url(array(
                        'action'        =>  'attribute-down',
                        'attribute_id'  =>  $attribute->id
                    )), '↓') ?>
                <?php } else { ?>
                    <span style="color:#999999">↓</span>
                <?php } ?>
                <?php if ($idx > 0) { ?>
                    <?=$this->htmlA($this->url(array(
                        'action'        =>  'attribute-up',
                        'attribute_id'  =>  $attribute->id
                    )), '↑') ?>
                <?php } else { ?>
                    <span style="color:#999999">↑</span>
                <?php } ?>
                <?=$this->htmlA($this->url(array(
                    'action'        =>  'attribute',
                    'attribute_id'  =>  $attribute->id
                )), $attribute->name) ?>
                <?=$this->partial('attrs/attribute/attributes-partial.phtml', array(
                    'attributes' => $attribute->getTable()->fetchAll(
                        $attribute->getTable()->select()
                            ->where('parent_id = ?', $attribute->id)
                            ->order('position')
                    )
                )) ?>
            </li>
        <?php } ?>
    </ul>
<?php } ?>