<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 114,
    ));
?>
<table>
    <thead>
        <tr>
            <td>Кто?</td>
            <td>Где?</td>
            <td>Что?</td>
            <td>Когда?</td>
        </tr>
    </thead>
    <?php foreach ($this->items as $item) { ?>
        <tr>
            <td><?=$this->user($item['user']) ?></td>
            <td><?=$this->escape($item['type']->name)?> <?=$this->htmlA($item['itemUrl'], $item['itemName'])?></td>
            <td>
                <?=$this->escape($item['attr'])?>: <?=$this->escape($item['value'])?>
                <?php if ($item['unit']) { ?>
                    <?=$this->escape($item['unit']->abbr)?>
                <?php } ?>
            </td>
            <td><?=$item['date']?></td>
        </tr>
    <?php } ?>
</table>

<?=$this->paginator?>