<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ]
    ]);
?>
<table class="table table-bordered table-striped">
    <caption>Пользователи</caption>
    <thead>
        <tr>
            <th>id</th>
            <th></th>
            <th>Логин</th>
            <th>E-mail</th>
            <th>Имя</th>
            <th>Роль</th>
            <th>Профиль</th>
            <th>Последний заход</th>
            <th>Регистрация</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator->getCurrentItems() as $user) { ?>
            <tr>
                <td><?=$user->id?></td>
                <td>
                    <?php if ($user->img) { ?>
                        <?=$this->img($user->img)?>
                    <?php } ?>
                </td>
                <td>
                    <?=$this->escapeHtml($user->login)?>
                </td>
                <td><?=$this->escapeHtml($user->e_mail)?></td>
                <td><?=$this->escapeHtml($user->name)?></td>
                <td><?=$this->escapeHtml($user->role)?></td>
                <td><?=$this->user($user)?></td>
                <td>
                    <?php if ($date = $user->getDateTime('last_online')) { ?>
                        <?=$this->humanTime($date)?>
                    <?php } ?>
                </td>
                <td>
                    <?php if ($date = $user->getDateTime('reg_date')) { ?>
                        <?=$this->humanTime($date)?>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<?=$this->paginationControl($this->paginator, null, null, [
    'route'     => 'moder/users/params',
    'urlParams' => []
]) ?>