<?php
    $this->element->setAttrib(
        'class',
        $this->element->getAttrib('class') . ' form-horizontal'
    );
?>
<fieldset>
    <?php foreach ($this->element->getElements() as $element) { ?>
        <?php
            $errors = $element->getMessages();
        ?>
        <div class="control-group<?=$errors ? ' error' : ''?>">
            <label class="control-label" for="<?=$element->getId()?>"><?=$this->escape($element->getLabel())?></label>
            <div class="controls docs-input-sizes">
                <?=$element?>
                <?php foreach ($errors as $error) { ?>
                    <span class="help-inline"><?=$this->escape($error)?></span>
                <?php } ?>
            </div>
        </div>
    <?php } ?>
    <div class="form-actions">
        <?=$this->formSubmit('submit', 'Сохранить', array(
            'class'    =>    'btn btn-primary'
        ))?>
    </div>
</fieldset>