<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 33,
        'args'   => [
            'BRAND_CATNAME'  => $this->brand['catname'],
            'BRAND_NAME'     => $this->brand['name'],
            'CAR_CATNAME'    => $this->carCatname,
            'CAR_NAME'       => $this->carFullName,
            'SHORT_CAR_NAME' => $this->carShortName
        ],
        'breadcrumbsReplace' => [
            'pageId'      => 33,
            'breadcrumbs' => $this->breadcrumbs
        ]
    ]);
?>

<?php $this->pageTitle()->setAutoEscape(false)->captureStart('SET') ?>
    <?=$this->car()->htmlTitle($this->car)?>
    <?php if ($this->design) { ?>
        <sup class="design-brand"><?=sprintf($this->translate('carlist/designed by %s'), $this->htmlA($this->design['url'], $this->design['name']))?></sup>
    <?php } ?>
    <?php if ($this->car['produced'] > 0) { ?>
        <small class="produced">
            <?php if ($this->car['produced'] > 1) { ?>
                <?=$this->escapeHtml(
                    sprintf(
                        $this->translatePlural(
                            $this->car['produced_exactly'] ? 'carlist/produced/%1$s' : 'carlist/produced-about/%1$s',
                            $this->car['produced_exactly'] ? 'carlist/produced/%1$s' : 'carlist/produced-about/%1$s',
                            $this->car['produced']
                        ),
                        $this->car['produced']
                    )
                )?>
            <?php } else {?>
                <?=$this->escapeHtml($this->translate('carlist/produced/one'))?>
            <?php } ?>
        </small>
    <?php } ?>
<?php $this->pageTitle()->captureEnd() ?>

<?php if (isset($this->otherNames)) { ?>
    <?php foreach ($this->otherNames as $name) { ?>
        <p><?=$this->escapeHtml($name)?></p>
    <?php } ?>
<?php } ?>

<?php if ($this->user()->inheritsRole('moder')) { ?>
    <p>
        <i class="fa fa-cog"></i>
        <?=$this->htmlA('/ng/moder/items/item/' . $this->car['id'], $this->translate('moder/edit-object'))?>

        <?php if ($this->user()->isAllowed('car', 'add') && $this->car['is_group']) { ?>
            <i class="fa fa-plus"></i>
            <?=$this->htmlA(
                '/ng/moder/items/new?item_type_id='.$this->car['item_type_id'].'&parent_id=' . $this->car['id'],
                mb_strtolower($this->translate('item/type/'.$this->car['item_type_id'].'/add-sub-item'))
            )?>
        <?php } ?>

        <?php if ($this->canAcceptPicture && $this->inboxCount) { ?>
            <i class="fa fa-th"></i>
            <?=$this->htmlA('/ng/moder/pictures?' . http_build_query([
                'item_id' => $this->car['id'],
                'status'  => 'inbox'
            ]), $this->translate('catalogue/vehicle/inbox') . ' ('.$this->inboxCount.')')?>
        <?php } ?>

        <?php if ($this->requireAttention) { ?>
            <i class="fa fa-comment"></i>
            <?=$this->htmlA($this->url('ng', ['path' => 'moder/comments'], [
                'query' => [
                    'pictures_of_item_id' => $this->car['id'],
                    'moderator_attention' => 1
                ]
            ]), $this->translate('catalogue/vehicle/comments') . ' ('.$this->requireAttention.')')?>
        <?php } ?>
    </p>
<?php } ?>

<?php if (!isset($this->modgroup)) { ?>
    <?=$this->partial('application/catalogue/partial/brand-item-menu', [
        'title' => $this->carFullName,
        'stock' => [
            'count'  => $this->stockCount,
            'active' => $this->type == Application\Model\ItemParent::TYPE_DEFAULT
        ],
        'tuning' => [
            'count'  => $this->tuningCount,
            'active' => $this->type == Application\Model\ItemParent::TYPE_TUNING
        ],
        'sport' => [
            'count'  => $this->sportCount,
            'active' => $this->type == Application\Model\ItemParent::TYPE_SPORT
        ],
        'pictures' => [
            'count'  => $this->picturesCount,
            'active' => false
        ],
    ]) ?>
<?php } ?>

<?php if ($this->hasHtml) { ?>
    <div class="text">
        <?=$this->markdown($this->car['text']) ?>
    </div>
<?php } elseif ($this->car['description']) { ?>
    <div class="text">
        <?=$this->markdown($this->car['description']) ?>
    </div>
<?php } ?>

<?=$this->render('application/catalogue/partial/modification-filter')?>

<?php if (!isset($this->modgroup)) { ?>
    <?=$this->partial('application/cars', $this->childListData)?>

    <?php if ($this->currentPicturesCount) { ?>
        <h3><?=$this->escapeHtml(sprintf($this->translate('catalogue/other-pictures-of-%1$s'), $this->carFullName)) ?></h3>

        <div class="row thumbnails">
            <?php foreach ($this->currentPictures as $picture) { ?>
                <div class="col-md-3">
                    <?=$this->htmlA([
                        'href'  => $picture['url'],
                        'class' => 'thumbnail'
                    ], $this->htmlImg($picture['src'], [
                        'format'  => 'picture-thumb',
                        'alt'     => $picture['name'],
                        'title'   => $picture['name'],
                        'shuffle' => true
                    ]), false)?>
                </div>
            <?php } ?>
        </div>

        <?php if ($this->currentPicturesCount > 4) { ?>
            <i class="fa fa-th"></i>
            <?=$this->htmlA($this->currentPicturesUrl, $this->translate('carlist/all pictures').' ('.$this->currentPicturesCount.')')?>
        <?php } ?>
    <?php } ?>

    <?php if (isset($this->paginator)) { ?>
        <?=$this->paginationControl($this->paginator) ?>
    <?php } ?>

<?php } else { ?>

    <?php foreach ($this->modifications as $modification) { ?>
        <?php /* if (!$modification['totalPictures']) { continue; } */ ?>
        <h3>
            <?=$this->car()->htmlTitle(array_replace($this->car, $modification['nameParams']))?>
        </h3>

        <div class="row thumbnails">
            <?php foreach ($modification['pictures'] as $picture) { ?>
                <div class="col-md-3">
                    <?php if ($picture) { ?>
                        <?=$this->htmlA([
                            'href'  => $picture['url'],
                            'class' => 'thumbnail'
                        ], $this->htmlImg($picture['src'], [
                            'format'  => 'picture-thumb',
                            /*'alt'     => $picture['name'],
                            'title'   => $picture['name'],*/
                            'shuffle' => true
                        ]), false)?>
                    <?php } else { ?>
                        &nbsp;
                    <?php } ?>
                </div>
            <?php } ?>
        </div>

        <ul class="list-inline">

            <?php if (isset($modification['url']) && $modification['url']) { ?>
                <li>
                    <span class="fa fa-th"></span>
                    <?=$this->htmlA($modification['url'], $this->translate('carlist/all pictures').' ('.$modification['totalPictures'].')')?>
                </li>
            <?php } ?>

            <?php if ($this->isCarModer) { ?>
                <li>
                    <i class="fa fa-cog"></i>
                    <?=$this->htmlA('#' /*$item['moderUrl']*/, $this->translate('moder/edit-object')) ?>
                </li>
            <?php } ?>

        </ul>
    <?php } ?>
<?php } ?>