<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 36,
        'args'   => [
            'BRAND_CATNAME'  => $this->brand['catname'],
            'BRAND_NAME'     => $this->brand['name'],
            'CAR_CATNAME'    => $this->carCatname,
            'CAR_NAME'       => $this->carFullName,
            'SHORT_CAR_NAME' => $this->carShortName
        ],
        'breadcrumbsReplace' => [
            'pageId'      => 33,
            'breadcrumbs' => $this->breadcrumbs
        ]
    ]);
?>
<?=$this->partial('application/specs', [
    'table' => $this->specs,
])?>
<?php if (count($this->contributors)) { ?>
    <p>
        <?=$this->escapeHtml($this->translate('catalogue/specifications/contributors:'))?>
        <?php foreach ($this->contributors as $contributor) { ?>
            <?=$this->user($contributor)?>
        <?php } ?>
    </p>
<?php } ?>

<?=$this->markdown($this->translate('catalogue/specifications/disclaimer'))?>