<?php
    if ($this->cartype) {
        $this->pageEnv([
            'layout' => [
                'blankPage' => false,
                'needLeft'  => true,
                'needRight' => false
            ],
            'pageId' => 138,
            'args'   => [
                'BRAND_CATNAME'    => $this->brand['catname'],
                'BRAND_NAME'       => $this->brand['name'],
                'CAR_TYPE_NAME'    => $this->translate($this->cartype->name),
                'CAR_TYPE_CATNAME' => $this->cartype->catname
            ]
        ]);
    } else {
        $this->pageEnv([
            'layout'    => [
                'blankPage' => false,
                'needLeft'  => true,
                'needRight' => false
            ],
            'pageId'    => 14,
            'args'      => [
                'BRAND_CATNAME'  => $this->brand['catname'],
                'BRAND_NAME'     => $this->brand['name'],
            ]
        ]);
    }
?>

<ul class="nav nav-pills">
    <?php foreach ($this->cartypes as $cartype) { ?>
        <li<?=$this->cartype && $this->cartype->id == $cartype['id'] ? ' class="active"' : '' ?>>
            <?=$this->htmlA(
                $cartype['url'],
                $this->escapeHtml($this->translate($cartype['name'])) . ' <small>('.$cartype['carsCount'].')</small>',
                false
            ) ?>
        </li>
    <?php } ?>
</ul>

<?=$this->partial('application/cars', $this->listData)?>
<?=$this->paginationControl($this->paginator) ?>