<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => $this->engine ? 168 : 38,
        'args'   => [
            'BRAND_NAME'    => $this->brand['name'],
            'BRAND_CATNAME' => $this->brand['catname'],
            'ENGINE_NAME'   => $this->engine ? $this->engine->name : null
        ]
    ]);
?>
<?php if ($this->user()->inheritsRole('moder')) { ?>
    <p>
        <?php if ($this->engine) { ?>
            <i class="fa fa-cog"></i>
            <?=$this->htmlA($this->url('moder/engines/params', [
                'action'    => 'engine',
                'engine_id' => $this->engine->id
            ]), $this->translate('moder/edit-object'))?>
        <?php } ?>
        <?php if ($this->user()->isAllowed('engine', 'add')) { ?>
            <i class="fa fa-plus"></i>
            <?php if ($this->engine) { ?>
                <?=$this->htmlA($this->url('moder/engines/params', [
                    'action'    => 'add',
                    'parent_id' => $this->engine->id
                ]), $this->translate('catalogue/engine/add-engine'))?>
            <?php } else { ?>
                <?=$this->htmlA($this->url('moder/engines/params', [
                    'action'   => 'add',
                    'brand_id' => $this->brand['id']
                ]), $this->translate('catalogue/engine/add-engine'))?>
            <?php } ?>
        <?php } ?>
    </p>
<?php } ?>

<?php if ($this->engine) { ?>
    <?=$this->partial('application/catalogue/partial/brand-engine-menu', [
        'title' => $this->engine->name,
        'tree'  => [
            'count'  => $this->childsCount,
            'active' => true
        ],
        'cars'  => [
            'count'  => $this->carsCount,
            'active' => false
        ],
        'specs' => [
            'count'  => $this->specsCount,
            'active' => false
        ],
        'pictures' => [
            'count'  => $this->picturesCount,
            'active' => false
        ],
    ]) ?>
<?php } ?>
<?php foreach ($this->engines as $engine) { ?>
    <div>
        <h3><?=$this->escapeHtml($engine['name'])?></h3>
        <div class="row thumbnails">
            <?php foreach ($engine['pictures'] as $picture) { ?>
                <div class="col-lg-3 col-md-3 col-sm-6">
                    <?=$this->htmlA([
                        'href'  => $picture['url'],
                        'class' => 'thumbnail'
                    ], $this->img($picture['img'], [
                        'format'  => 'picture-thumb',
                        'alt'     => $picture['name'],
                        'title'   => $picture['name'],
                        'shuffle' => true
                    ]), false)?>
                </div>
            <?php } ?>
        </div>
        <?php if (count($engine['cars'])) { ?>
            <p><?=$this->escapeHtml($this->translate('catalogue/engine/mounted-on:'))?></p>
            <ul>
                <?php foreach ($engine['cars'] as $car) { ?>
                    <li><?=$this->htmlA($car['url'], $this->car()->htmlTitle($car['name']), false)?></li>
                <?php } ?>
            </ul>
        <?php } ?>
        <ul class="list-inline">
            <?php if ($engine['detailsUrl']) { ?>
                <li>
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($engine['detailsUrl'], $this->translate('carlist/details') . ' (' . $engine['childsCount'] . ')')?>
                </li>
            <?php } ?>
            <?php if ($engine['moderUrl']) { ?>
                <li>
                    <i class="fa fa-cog"></i>
                    <?=$this->htmlA($engine['moderUrl'], $this->translate('moder/edit-object'))?>
                </li>
            <?php } ?>
            <?php if ($engine['specsUrl']) { ?>
                <li>
                    <i class="fa fa-list-alt"></i>
                    <?=$this->htmlA($engine['specsUrl'], $this->translate('carlist/specifications'))?>
                </li>
            <?php } ?>
            <?php if ($engine['specsEditUrl']) { ?>
                <li>
                    <i class="fa fa-pencil"></i>
                    <?=$this->htmlA($engine['specsEditUrl'], $this->translate('carlist/edit-specs'))?>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>
<?=$this->paginationControl($this->paginator) ?>