<?php
    $this->pageEnv([
        'layout'    => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId'    => 208,
        'args'      => [
            'BRAND_CATNAME' => $this->brand['catname'],
            'BRAND_NAME'    => $this->brand['name'],
        ]
    ]);
?>

<?=$this->partial('application/cars', $this->listData)?>
<?=$this->paginationControl($this->paginator) ?>