<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 190,
        'args'   => [
            'PICTURE_ID'    => $this->picture['identity'],
            'PICTURE_NAME'  => $this->pic()->textTitle($this->picture['name']),
            'BRAND_NAME'    => $this->brand['name'],
            'BRAND_CATNAME' => $this->brand['catname'],
        ]
    ]);
?>
<?=$this->partial('application/picture/picture', $this->picture)?>