<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ],
        'pageId' => 191,
        'args'   => [
            'PICTURE_ID'    => $this->picture['identity'] ? $this->picture['identity'] : $this->picture['id'],
            'PICTURE_NAME'  => $this->pic()->textTitle($this->picture['name']),
            'BRAND_NAME'    => $this->brand['name'],
            'BRAND_CATNAME' => $this->brand['catname'],
        ]
    ]);
?>
<?=$this->partial('application/picture/picture', $this->picture)?>