<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 41,
        'args'   => [
            'BRAND_NAME'    => $this->brand['name'],
            'BRAND_CATNAME' => $this->brand['catname'],
        ]
    ]);
?>
<?=$this->partial('application/pictures', $this->picturesData)?>
<?=$this->paginationControl($this->paginator) ?>