<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 15,
        'args'   => [
            'BRAND_NAME'    => $this->brand['name'],
            'BRAND_CATNAME' => $this->brand['catname'],
        ]
    ]);
?>

<div class="row" data-module="car-list">
    <?php foreach ($this->picturesData['items'] as $item) { ?>
        <?=$this->partial('application/picture', array_replace($item, [
            'isModer'          => $this->picturesData['isModer'],
            'disableBehaviour' => $this->picturesData['disableBehaviour'],
            'colClass'         => 'col-6 col-sm-4 col-md-3 col-xl-2'
        ]))?>
    <?php } ?>
</div>

<?=$this->paginationControl($this->paginator) ?>
