<?php
    $this->layout()->disableLayout();
?>
<?php if (count($this->generations)) { ?>
    <?php foreach ($this->generations as $generation) { ?>
        <div>
            <?=$this->htmlA(array(
                'href' => '#',
                'class' => 'arrow'
            ), '<span class="glyphicon glyphicon-plus-sign"></span> ' . $this->escape($generation['name']), false) ?>
            <div style="margin:0 0 4px 18px;display:none">
                <?php foreach ($generation['cars'] as $car) { ?>
                    <?=$this->htmlA($car['url'], $car['name']) ?><br />
                <?php } ?>
            </div>
        </div>
    <?php } ?>

    <?php if (count($this->cars)) { ?>
        <div>
            <?=$this->htmlA(array(
                'href' => '#',
                'class' => 'arrow'
            ), '<span class="glyphicon glyphicon-plus-sign"></span> не вошедшие в поколения', false) ?>
            <div style="margin:0 0 4px 18px;display:none">
                <?php foreach ($this->cars as $car) { ?>
                    <?=$this->htmlA($car['url'], $car['name']) ?><br />
                <?php } ?>
            </div>
        </div>
    <?php } ?>
<?php } else { ?>
    <?php foreach ($this->cars as $car) { ?>
        <?=$this->htmlA($car['url'], $car['name']) ?><br />
    <?php } ?>
<?php } ?>
<?=$this->htmlA($this->url, 'другая модификация') ?>