<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => false,
        'needRight' => false
    ));
    $this->page(30)->initPage();
    $this->pageTitle('Выбор бренда');

    $columns = 6;
    $count = count($this->brands);
    $perOne = ceil($count / $columns);
    $idx = 0;
?>
<div class="row">
    <div class="col-lg-2">
        <?php foreach ($this->brands as $brand) { ?>
            <?php if ($idx && ($idx%$perOne == 0)) { ?>
                </div><div class="col-lg-2">
            <?php } ?>
            <?=$this->htmlA($this->url(array(
                'brand_id' => $brand->id
            )), $brand->caption) ?><br />
            <?php $idx++ ?>
        <?php } ?>
    </div>
</div>