<?php foreach ($this->cars as $car) { ?>
    <?php if ($car['haveChilds']) { ?>
        <div>
            <?=$this->htmlA(array(
                'href'      => '#',
                'class'     => 'arrow',
                'data-load' => $car['loadUrl']
            ), '<span class="glyphicon glyphicon-plus-sign"></span> ' . $this->escape($car['name']), false) ?>
            <div style="margin:0 0 4px 18px;display:none">
                <?php if (!$car['isGroup']) { ?>
                    <?=$this->htmlA($car['url'], $car['name']) ?><br />
                <?php } ?>
                <div class="loading"><em>Loading ...</em></div>
                <?php if ($car['isGroup']) { ?>
                    <?=$this->htmlA($car['url'], 'другая модификация') ?>
                <?php } ?>
            </div>
        </div>
    <?php } else { ?>
        <?=$this->htmlA($car['url'], $car['name']) ?><br />
    <?php } ?>
<?php } ?>