<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => false,
        'needRight' => false
    ));
    $this->pageTitle('Выбор бренда');

    $this->layout()->moduleName = 'default/upload/select-in-brand';
?>

<div class="select-in-brand">
    <?php if (count($this->cars) > 0) { ?>
        <div style="margin: 5px 0">
            <?=$this->partial('upload/select-in-brand-cars.phtml', array(
                'cars' => $this->cars
            ))?>
        </div>
    <?php } ?>

    <?php if (count($this->haveConcepts)) { ?>
        <div style="margin: 5px 0">
            <?=$this->htmlA(array(
                'href'      => '#',
                'class'     => 'arrow',
                'data-load' => $this->conceptsUrl
            ), '<span class="glyphicon glyphicon-plus-sign"></span> Концепты и прототипы', false) ?>
            <div style="margin:0 0 4px 18px;display:none">
                <div class="loading"><em>Loading ...</em></div>
            </div>
        </div>
    <?php } ?>

    <?php if ($this->haveEngines) { ?>
        <div style="margin: 5px 0">
            <?=$this->htmlA(array(
                'href'      => '#',
                'class'     => 'arrow',
                'data-load' => $this->enginesUrl
            ), '<span class="glyphicon glyphicon-plus-sign"></span> Двигатели', false)?>
            <div style="margin:0 0 4px 18px;display:none">
                <div class="loading"><em>Loading ...</em></div>
            </div>
        </div>
    <?php } ?>

    <div style="margin: 5px 0">
        <?=$this->htmlA($this->url(array(
            'action' => 'index',
            'type'   => Picture::LOGO_TYPE_ID
        )), 'логотип ' . $this->brand->caption) ?><br />
        <?=$this->htmlA($this->url(array(
            'action' => 'index',
            'type'   => Picture::MIXED_TYPE_ID
        )), 'разное (несколько автомобилей на одной картинке)') ?><br />
        <?=$this->htmlA($this->url(array(
            'action' => 'index',
            'type'   => Picture::UNSORTED_TYPE_ID
        )), 'несортировано (автомобиль или двигатель, которого нет на сайте)') ?>
    </div>
</div>
