<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 89,
    ));
?>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="well">
            <?=$this->form->render($this) ?>
        </div>
        <?=$this->markdown($this->translate('feedback/donate-text'))?>
    </div>
</div>