<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 53,
    ));
?>
<div class="well">
    <h2>Успешная регистрация</h2>
    <p>На электронный адрес, указанный при регистрации, отправлено письмо с инструкциями для подтверждения адреса email.</p>
</div>