<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => true,
            'needLeft'  => false,
            'needRight' => false
        ),
        'title'     => 'Maintenance',
        'pageTitle' => 'Maintenance',
    ));
?>
<div class="row"><div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">

    <div class="well">

        <p>Форум закрыт на техническое обслуживание</p>
        <p>Forums temporary unavailable due maintenance</p>

    </div>

</div></div>