<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 75,
    ));
?>

<table class="table table-condensed table-striped">
    <?php foreach ($this->events as $event) { ?>
        <tr>
            <td>
                <?php if ($event['date']) { ?>
                    <?=$this->escape($this->humanTime($event['date']))?>
                <?php } ?>
            </td>
            <td>
                <?php if ($event['user']) { ?>
                    <?=$this->user($event['user'])?>
                <?php } ?>
            </td>
            <td><?=$event['desc']?></td>
        </tr>
    <?php } ?>
</table>

<?=$this->paginationControl($this->paginator) ?>