<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 123,
    ));
?>
<?php if (count($this->accounts)) { ?>
    <div class="well">
        <?php foreach ($this->accounts as $account) { ?>
            <p>
                <?php if ($account['canRemove']) { ?>
                    <form action="<?=$this->escape($account['removeUrl'])?>" method="post">
                        <button type="submit" class="btn btn-xs btn-danger" title="Удалить">
                            <i class="fa fa-times"></i>
                        </button>
                        &#xa0;
                        <i class="<?=$account['icon']?>"></i>
                        <?php if ($account['link']) { ?>
                            <?=$this->htmlA($account['link'], $account['name'])?>
                        <?php } else { ?>
                            <?=$this->escape($account['name'])?>
                        <?php } ?>
                    </form>
                <?php } else { ?>
                    <?=$this->htmlImg(array(
                        'src' => $account['icon']
                    ))?>
                    <?php if ($account['link']) { ?>
                        <?=$this->htmlA($account['link'], $account['name'])?>
                    <?php } else { ?>
                        <?=$this->escape($account['name'])?>
                    <?php } ?>
                <?php } ?>
            </p>
        <?php } ?>
    </div>
<?php } ?>
<?=$this->addAccountForm->render($this)?>