<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 49,
    ));

    $this->layout()->moduleName = 'default/account/pm';
?>
<?=$this->partial('account/partial/personal-messages.phtml', array(
    'messages' => $this->messages
))?>
<?=$this->paginationControl($this->paginator) ?>