<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 80,
    ));

    $this->layout()->moduleName = 'default/account/pm';
?>
<?php if ($this->paginator->count()) { ?>
    <form action="<?=$this->escape($this->url(array(
        'controller' => 'account',
        'action'     => 'clear-sent-messages'
    )))?>" method="post">
        <input type="submit" value="<?=$this->escape($this->translate('account/personal-message/delete-all-sent'))?>" class="btn btn-danger" />
    </form>
<?php } ?>
<?=$this->partial('account/partial/personal-messages.phtml', array(
    'messages' => $this->messages
))?>
<?=$this->paginationControl($this->paginator) ?>