<?php
    $items = array(
        array(
            'active' => $this->page(129)->onPath,
            'url'    => $this->url(array(
                'action' => 'profile',
            )),
            'icon'   => 'user',
            'name'   => $this->page(129)->name,
        ),
        array(
            'active' => $this->page(55)->onPath,
            'url'    => $this->url(array(
                'action' => 'email'
            )),
            'icon'   => 'envelope',
            'name'   => $this->page(55)->name,
        ),
        array(
            'active' => $this->page(133)->onPath,
            'url'    => $this->url(array(
                'action' => 'access'
            )),
            'icon'   => 'lock',
            'name'   => $this->page(133)->name,
        ),
        array(
            'active' => $this->page(123)->onPath,
            'url'    => $this->url(array(
                'action' => 'accounts'
            )),
            'icon'   => 'asterisk',
            'name'   => $this->page(123)->name,
        ),
        array(
            'active' => $this->page(130)->onPath,
            'url'    => $this->url(array(
                'action'   => 'pictures',
                'user_id'  => $this->user()->get()->id,
                'identity' => $this->user()->get()->identity
            ), 'users'),
            'icon'   => 'th',
            'name'   => $this->page(130)->name,
            'count'    => $this->picsCount,
        ),
        array(
            'active' => $this->page(94)->onPath,
            'url'    => $this->url(array(
                'action' => 'not-taken-pictures'
            )),
            'icon'   => 'th',
            'name'   => $this->page(94)->name,
            'count'    => $this->notTakenPicturesCount,
        ),
        array(
            'active' => $this->page(57)->onPath,
            'url'    => $this->url(array(
                'action' => 'forums'
            )),
            'icon'   => 'bookmark',
            'name'   => $this->page(57)->name,
            'count'    => $this->subscribesCount,
        ),
        array(
            'name'   => $this->page(49)->name,
        ),
        array(
            'active' => $this->page(128)->onPath,
            'url'    => $this->url(array(
                'controller' => 'account',
                'action'     => 'personal-messages-inbox'
            ), 'account', true),
            'icon'   => 'folder-close',
            'name'   => $this->page(128)->name,
            'count'    => $this->pmCount,
            'newCount' => $this->newPmCount
        ),
        array(
            'active' => $this->page(80)->onPath,
            'url'    => $this->url(array(
                'controller' => 'account',
                'action'     => 'personal-messages-sent'
            ), 'account', true),
            'icon'   => 'folder-close',
            'name'   => $this->page(80)->name,
            'count'    => $this->omCount,
        ),
        array(
            'active' => $this->page(81)->onPath,
            'url'    => $this->url(array(
                'controller' => 'account',
                'action'     => 'personal-messages-system'
            ), 'account', true),
            'icon'   => 'folder-close',
            'name'   => $this->page(81)->name,
            'count'    => $this->smCount,
            'newCount' => $this->newSmCount
        ),
    );
?>
<div class="well">
    <ul class="nav nav-pills nav-stacked">
        <?php foreach ($items as $item) { ?>
            <?php
                $badge = '';
                if (isset($item['count'])) {
                    $classes = array('badge', 'pull-right');
                    if ($item['count'] == 0) {
                        $text = $this->translate('count 0');
                    } else {
                        $newCount = isset($item['newCount']) ? $item['newCount'] : 0;
                        $text = $item['count'] - $newCount;
                        if ($newCount) {
                            $classes[] = 'alert-danger';
                            $text .= '+' . $newCount;
                        }
                    }

                    $badge = '<span class="'.implode(' ', $classes).'">' . $text . '</span>';
                }

                $icon = '';
                if (isset($item['icon'])) {
                    $icon = '<span class="glyphicon glyphicon-'.$item['icon'].'"></span> ';
                }
                $active = isset($item['active']) && $item['active'];
            ?>
            <li<?=$active ? ' class="active"' : ''?>>
                <?php if (isset($item['url'])) { ?>
                    <?=$this->htmlA(
                        $item['url'],
                        $badge . $icon . $this->escape($item['name']),
                        false
                    )?>
                <?php } else { ?>
                    <?=$badge . $icon . $this->escape($item['name'])?>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>
</div>