<?php if ($this->element instanceof Zend\Form\Element\Multicheckbox) { ?>
    <?=$this->formElement($this->element)?>
<?php } elseif ($this->element instanceof Zend\Form\Element\Checkbox) { ?>
    <div class="checkbox<?=$this->element->getMessages() ? ' has-error' : ''?>">
        <label>
            <?=$this->formElement($this->element)?>
        </label>
    </div>
<?php } else { ?>
    <?=$this->formElement(
        $this->element
            ->setAttribute('class', $this->element->getAttribute('class') . ' form-control')
    )?>
<?php } ?>