<?php
    $this->form->setAttribute(
        'class',
        $this->form->getAttribute('class') . ' spec-editor-form'
    );
?>
<?=$this->form()->openTag($this->form)?>
<?php if ($this->form->getMessages()) { ?>
    <p class="alert alert-danger">
        <i class="fa fa-exclamation-triangle"></i>
        <?=$this->escapeHtml($this->translate('specifications-editor/not-save'))?>
    </p>
<?php } ?>
<table class="table table-condensed">
    <thead>
        <tr>
            <th class="col-lg-3 col-sm-3"><?=$this->escapeHtml($this->translate('specifications-editor/parameter'))?></th>
            <th class="col-lg-4 col-sm-4"><?=$this->escapeHtml($this->translate('specifications-editor/your-value'))?></th>
            <th class="col-lg-2 col-sm-2"><?=$this->escapeHtml($this->translate('specifications-editor/actual-value'))?></th>
            <th class="col-lg-3 col-sm-3"><?=$this->escapeHtml($this->translate('specifications-editor/all-values'))?></th>
        </tr>
    </thead>
    <tbody>
        <?=$this->partial('application/cars/partial/form-elements', [
            'form'               => $this->form,
            'allValues'          => $this->data['allValues'],
            'actualValues'       => $this->data['actualValues'],
            'editableAttributes' => $this->data['editableAttributes'],
            'deep'               => 0,
            'parents'            => [],
            'service'            => $this->service
        ])?>
        <tr><td>
            <input type="submit" value="<?=$this->escapeHtmlAttr($this->translate('specifications-editor/save'))?>" class="btn btn-success" />
        </td></tr>
    </tbody>
</table>
<?=$this->form()->closeTag($this->form)?>