/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const APIBrandsListLineCategory = {
    Default: 'DEFAULT',
    Number: 'NUMBER',
    Cyrillic: 'CYRILLIC',
    Latin: 'LATIN'
} as const;
export type APIBrandsListLineCategory = typeof APIBrandsListLineCategory[keyof typeof APIBrandsListLineCategory];

