/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AttrAttributeTypeID = {
    Unknown: 'UNKNOWN',
    String: 'STRING',
    Integer: 'INTEGER',
    Float: 'FLOAT',
    Text: 'TEXT',
    Boolean: 'BOOLEAN',
    List: 'LIST',
    Tree: 'TREE'
} as const;
export type AttrAttributeTypeID = typeof AttrAttributeTypeID[keyof typeof AttrAttributeTypeID];

