/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const CommentVoteVoteValue = {
    Unknown: 'UNKNOWN',
    Positive: 'POSITIVE',
    Negative: 'NEGATIVE'
} as const;
export type CommentVoteVoteValue = typeof CommentVoteVoteValue[keyof typeof CommentVoteVoteValue];

