/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpStatsValue } from './goautowpStatsValue';


export interface GoautowpStatsResponse { 
    values: Array<GoautowpStatsValue>;
}

