/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemType } from './goautowpItemType';
import { GoautowpPathTreeItemParent } from './goautowpPathTreeItemParent';


export interface GoautowpPathTreeItem { 
    catname: string;
    itemTypeId: GoautowpItemType;
    parents: Array<GoautowpPathTreeItemParent>;
}
export namespace GoautowpPathTreeItem {
}


