/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAttrAttributeType } from './goautowpAttrAttributeType';


export interface GoautowpAttrAttributeTypesResponse { 
    items: Array<GoautowpAttrAttributeType>;
}

