/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPictureItemsRequestOrder } from './goautowpPictureItemsRequestOrder';
import { GoautowpPictureItemListOptions } from './goautowpPictureItemListOptions';
import { GoautowpPictureItemFields } from './goautowpPictureItemFields';


export interface GoautowpPictureItemsRequest { 
    options: GoautowpPictureItemListOptions;
    fields: GoautowpPictureItemFields;
    language: string;
    limit: number;
    order: GoautowpPictureItemsRequestOrder;
}
export namespace GoautowpPictureItemsRequest {
}


