/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemsRequestOrder } from './goautowpItemsRequestOrder';
import { GoautowpItemListOptions } from './goautowpItemListOptions';
import { GoautowpItemFields } from './goautowpItemFields';


export interface GoautowpItemsRequest { 
    language: string;
    fields: GoautowpItemFields;
    options: GoautowpItemListOptions;
    limit: number;
    order: GoautowpItemsRequestOrder;
    page: number;
}
export namespace GoautowpItemsRequest {
}


