/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPictureItem } from './goautowpPictureItem';


export interface GoautowpPictureItems { 
    items: Array<GoautowpPictureItem>;
}

