/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPages } from './goautowpPages';
import { GoautowpPicture } from './goautowpPicture';


export interface GoautowpPicturesList { 
    items: Array<GoautowpPicture>;
    paginator: GoautowpPages;
}

