/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemListOptions } from './goautowpItemListOptions';
import { GoautowpItemParentCacheListOptions } from './goautowpItemParentCacheListOptions';
import { GoautowpItemParentType } from './goautowpItemParentType';


export interface GoautowpItemParentListOptions { 
    parentId: string;
    parent: GoautowpItemListOptions;
    itemParentParentByChild: GoautowpItemParentListOptions;
    itemId: string;
    type: GoautowpItemParentType;
    strictType: boolean;
    item: GoautowpItemListOptions;
    itemParentCacheItemByChild: GoautowpItemParentCacheListOptions;
    catname: string;
}
export namespace GoautowpItemParentListOptions {
}


