/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPages } from './goautowpPages';
import { GoautowpLogEvent } from './goautowpLogEvent';


export interface GoautowpLogEvents { 
    items: Array<GoautowpLogEvent>;
    paginator: GoautowpPages;
}

