/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPages } from './goautowpPages';
import { GoautowpNewboxGroup } from './goautowpNewboxGroup';
import { TypeDate } from './typeDate';


export interface GoautowpNewbox { 
    groups: Array<GoautowpNewboxGroup>;
    prevDate: TypeDate;
    prevCount: number;
    currentDate: TypeDate;
    currentCount: number;
    nextDate: TypeDate;
    nextCount: number;
    paginator: GoautowpPages;
}

