/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPicturesRequest } from './goautowpPicturesRequest';


export interface GoautowpPreviewPicturesRequest { 
    perspectivePageId: number;
    pictures: GoautowpPicturesRequest;
    onlyExactlyPictures: boolean;
}

