/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPicturePathRequest } from './goautowpPicturePathRequest';
import { GoautowpPictureModerVoteRequest } from './goautowpPictureModerVoteRequest';
import { GoautowpDfDistanceRequest } from './goautowpDfDistanceRequest';
import { GoautowpPictureItemsRequest } from './goautowpPictureItemsRequest';
import { GoautowpPicturesRequest } from './goautowpPicturesRequest';


export interface GoautowpPictureFields { 
    nameText: boolean;
    nameHtml: boolean;
    image: boolean;
    thumbMedium: boolean;
    thumbLarge: boolean;
    views: boolean;
    votes: boolean;
    commentsCount: boolean;
    moderVote: boolean;
    path: GoautowpPicturePathRequest;
    pictureItem: GoautowpPictureItemsRequest;
    imageGalleryFull: boolean;
    imageGallery: boolean;
    dfDistance: GoautowpDfDistanceRequest;
    acceptedCount: boolean;
    copyrights: boolean;
    exif: boolean;
    isLast: boolean;
    moderVoted: boolean;
    pictureModerVotes: GoautowpPictureModerVoteRequest;
    replaceable: GoautowpPicturesRequest;
    rights: boolean;
    siblings: GoautowpPicturesRequest;
    specialName: boolean;
    taken: boolean;
    previewLarge: boolean;
    subscribed: boolean;
    paginator: GoautowpPicturesRequest;
}

