/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemParentListOptions } from './goautowpItemParentListOptions';
import { GoautowpItemParentFields } from './goautowpItemParentFields';
import { GoautowpItemParentsRequestOrder } from './goautowpItemParentsRequestOrder';


export interface GoautowpItemParentsRequest { 
    options: GoautowpItemParentListOptions;
    order: GoautowpItemParentsRequestOrder;
    limit: number;
    page: number;
    fields: GoautowpItemParentFields;
    language: string;
}
export namespace GoautowpItemParentsRequest {
}


