/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttrAttributeTypeID } from './attrAttributeTypeID';


export interface GoautowpAttrAttribute { 
    id: string;
    parentId: string;
    name: string;
    description: string;
    typeId: AttrAttributeTypeID;
    unitId: string;
    isMultiple: boolean;
    precision: number;
}
export namespace GoautowpAttrAttribute {
}


