/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GoautowpItemsRequestOrder = {
    Default: 'DEFAULT',
    NameNat: 'NAME_NAT',
    Name: 'NAME',
    ChildsCount: 'CHILDS_COUNT',
    Age: 'AGE',
    IdDesc: 'ID_DESC',
    IdAsc: 'ID_ASC'
} as const;
export type GoautowpItemsRequestOrder = typeof GoautowpItemsRequestOrder[keyof typeof GoautowpItemsRequestOrder];

