/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GoautowpPicturesRequestOrder = {
    OrderNone: 'ORDER_NONE',
    OrderAddDateDesc: 'ORDER_ADD_DATE_DESC',
    OrderAddDateAsc: 'ORDER_ADD_DATE_ASC',
    OrderResolutionDesc: 'ORDER_RESOLUTION_DESC',
    OrderResolutionAsc: 'ORDER_RESOLUTION_ASC',
    OrderFilesizeDesc: 'ORDER_FILESIZE_DESC',
    OrderFilesizeAsc: 'ORDER_FILESIZE_ASC',
    OrderComments: 'ORDER_COMMENTS',
    OrderViews: 'ORDER_VIEWS',
    OrderModerVotes: 'ORDER_MODER_VOTES',
    OrderDfDistanceSimilarity: 'ORDER_DF_DISTANCE_SIMILARITY',
    OrderRemovingDate: 'ORDER_REMOVING_DATE',
    OrderLikes: 'ORDER_LIKES',
    OrderDislikes: 'ORDER_DISLIKES',
    OrderStatus: 'ORDER_STATUS',
    OrderAcceptDatetimeDesc: 'ORDER_ACCEPT_DATETIME_DESC',
    OrderPerspectives: 'ORDER_PERSPECTIVES',
    OrderFrontPerspectives: 'ORDER_FRONT_PERSPECTIVES'
} as const;
export type GoautowpPicturesRequestOrder = typeof GoautowpPicturesRequestOrder[keyof typeof GoautowpPicturesRequestOrder];

