/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpDonationsTransaction { 
    sum: number;
    currency: string;
    date: Date;
    contributor: string;
    purpose: string;
    userId: string;
}

