/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIBrandsListItem } from './goautowpAPIBrandsListItem';


export interface GoautowpAPIBrandsListCharacter { 
    character: string;
    id: string;
    items: Array<GoautowpAPIBrandsListItem>;
}

