/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpCommentMessageFields { 
    preview: boolean;
    route: boolean;
    text: boolean;
    vote: boolean;
    userVote: boolean;
    replies: boolean;
    status: boolean;
    isNew: boolean;
}

