/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIItem } from './goautowpAPIItem';


export interface GoautowpItemParentCache { 
    itemId: string;
    parentId: string;
    parentItem: GoautowpAPIItem;
}

