/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpAlphaResponse { 
    numbers: Array<string>;
    latin: Array<string>;
    cyrillic: Array<string>;
    han: Array<string>;
    other: Array<string>;
}

