/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GoautowpCommentsType = {
    Unknown: 'UNKNOWN',
    PicturesTypeId: 'PICTURES_TYPE_ID',
    ItemTypeId: 'ITEM_TYPE_ID',
    VotingsTypeId: 'VOTINGS_TYPE_ID',
    ArticlesTypeId: 'ARTICLES_TYPE_ID',
    ForumsTypeId: 'FORUMS_TYPE_ID'
} as const;
export type GoautowpCommentsType = typeof GoautowpCommentsType[keyof typeof GoautowpCommentsType];

