/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIBrandSection } from './goautowpAPIBrandSection';


export interface GoautowpAPIBrandSections { 
    sections: Array<GoautowpAPIBrandSection>;
}

