/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentVoteVoteValue } from './commentVoteVoteValue';
import { GoautowpAPIUser } from './goautowpAPIUser';


export interface GoautowpCommentVote { 
    value: CommentVoteVoteValue;
    user: GoautowpAPIUser;
}
export namespace GoautowpCommentVote {
}


