/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPathTreeItem } from './goautowpPathTreeItem';


export interface GoautowpPathTreeItemParent { 
    catname: string;
    item: GoautowpPathTreeItem;
}

