/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPerspectiveGroup } from './goautowpPerspectiveGroup';


export interface GoautowpPerspectivePage { 
    id: number;
    name: string;
    groups: Array<GoautowpPerspectiveGroup>;
}

