/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemParentCache } from './goautowpItemParentCache';


export interface GoautowpItemParentCaches { 
    items: Array<GoautowpItemParentCache>;
}

