/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpAPIForumsTopic { 
    id: string;
    name: string;
    status: string;
    oldMessages: number;
    newMessages: number;
    createdAt: Date;
    userId: string;
    themeId: string;
    subscription: boolean;
}

