/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPictureItemType } from './goautowpPictureItemType';
import { GoautowpItemParentCaches } from './goautowpItemParentCaches';
import { GoautowpAPIItem } from './goautowpAPIItem';
import { GoautowpPicture } from './goautowpPicture';


export interface GoautowpPictureItem { 
    pictureId: string;
    itemId: string;
    type: GoautowpPictureItemType;
    cropLeft: number;
    cropTop: number;
    cropWidth: number;
    cropHeight: number;
    perspectiveId: number;
    item: GoautowpAPIItem;
    itemParentCacheAncestors: GoautowpItemParentCaches;
    picture: GoautowpPicture;
}
export namespace GoautowpPictureItem {
}


