/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPictureItemListOptions } from './goautowpPictureItemListOptions';
import { GoautowpDfDistanceListOptions } from './goautowpDfDistanceListOptions';
import { GoautowpCommentTopicListOptions } from './goautowpCommentTopicListOptions';
import { GoautowpPictureModerVoteListOptions } from './goautowpPictureModerVoteListOptions';
import { TypeDate } from './typeDate';
import { GoautowpPictureStatus } from './goautowpPictureStatus';


export interface GoautowpPictureListOptions { 
    id: string;
    identity: string;
    status: GoautowpPictureStatus;
    statuses: Array<GoautowpPictureStatus>;
    pictureItem: GoautowpPictureItemListOptions;
    ownerId: string;
    acceptedInDays: number;
    addDate: TypeDate;
    acceptDate: TypeDate;
    addedFrom: TypeDate;
    commentTopic: GoautowpCommentTopicListOptions;
    hasNoComments: boolean;
    hasPoint: boolean;
    hasNoPoint: boolean;
    hasNoPictureItem: boolean;
    replacePicture: GoautowpPictureListOptions;
    hasNoReplacePicture: boolean;
    pictureModerVote: GoautowpPictureModerVoteListOptions;
    hasNoPictureModerVote: boolean;
    dfDistance: GoautowpDfDistanceListOptions;
    hasSpecialName: boolean;
}
export namespace GoautowpPictureListOptions {
}


