/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpVotingVariant { 
    id: number;
    isMax: boolean;
    isMin: boolean;
    name: string;
    percent: number;
    text: string;
    votes: number;
}

