/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpMostsRating } from './goautowpMostsRating';
import { GoautowpMostsVehicleType } from './goautowpMostsVehicleType';
import { GoautowpYearsRange } from './goautowpYearsRange';


export interface GoautowpMostsMenu { 
    years: Array<GoautowpYearsRange>;
    ratings: Array<GoautowpMostsRating>;
    vehicleTypes: Array<GoautowpMostsVehicleType>;
}

