/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GoautowpGetMessagesRequestOrder = {
    Default: 'DEFAULT',
    VoteDesc: 'VOTE_DESC',
    VoteAsc: 'VOTE_ASC',
    DateDesc: 'DATE_DESC',
    DateAsc: 'DATE_ASC'
} as const;
export type GoautowpGetMessagesRequestOrder = typeof GoautowpGetMessagesRequestOrder[keyof typeof GoautowpGetMessagesRequestOrder];

