/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpUserFields { 
    email: boolean;
    timezone: boolean;
    language: boolean;
    votesPerDay: boolean;
    votesLeft: boolean;
    img: boolean;
    gravatarLarge: boolean;
    photo: boolean;
    regDate: boolean;
    picturesAdded: boolean;
    picturesAcceptedCount: boolean;
    lastIp: boolean;
    lastOnline: boolean;
    login: boolean;
}

