/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPages } from './goautowpPages';
import { GoautowpAttrConflict } from './goautowpAttrConflict';


export interface GoautowpAttrConflictsResponse { 
    items: Array<GoautowpAttrConflict>;
    paginator: GoautowpPages;
}

