/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpBrandVehicleType } from './goautowpBrandVehicleType';


export interface GoautowpBrandVehicleTypeItems { 
    items: Array<GoautowpBrandVehicleType>;
}

