/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpAPITopBrandsListItem { 
    id: string;
    catname: string;
    name: string;
    itemsCount: number;
    newItemsCount: number;
}

