/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemParentType } from './goautowpItemParentType';


export interface GoautowpChildsCount { 
    type: GoautowpItemParentType;
    count: number;
}
export namespace GoautowpChildsCount {
}


