/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpInboxBrand } from './goautowpInboxBrand';
import { TypeDate } from './typeDate';


export interface GoautowpInbox { 
    brands: Array<GoautowpInboxBrand>;
    prevDate: TypeDate;
    prevCount: number;
    currentDate: TypeDate;
    currentCount: number;
    nextDate: TypeDate;
    nextCount: number;
}

