/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPages } from './goautowpPages';
import { GoautowpItemParent } from './goautowpItemParent';


export interface GoautowpItemParents { 
    items: Array<GoautowpItemParent>;
    paginator: GoautowpPages;
}

