/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPictureStatus } from './goautowpPictureStatus';
import { GoautowpPicture } from './goautowpPicture';


export interface GoautowpGalleryResponse { 
    count: number;
    items: Array<GoautowpPicture>;
    page: number;
    pages: number;
    status: GoautowpPictureStatus;
}
export namespace GoautowpGalleryResponse {
}


