/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpMessage { 
    readonly id: string;
    text: string;
    readonly isNew: boolean;
    readonly canDelete: boolean;
    readonly canReply: boolean;
    readonly date: Date;
    readonly allMessagesLink: boolean;
    readonly dialogCount: number;
    readonly authorId: string;
    toUserId: string;
    readonly dialogWithUserId: string;
}

