/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpArticle { 
    id: string;
    name: string;
    authorId: string;
    catname: string;
    date: Date;
    html: string;
    previewUrl: string;
    description: string;
}

