/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIAccountsAccount } from './goautowpAPIAccountsAccount';


export interface GoautowpAPIAccountsResponse { 
    items: Array<GoautowpAPIAccountsAccount>;
}

