/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAttrConflictValue } from './goautowpAttrConflictValue';


export interface GoautowpAttrConflict { 
    itemId: string;
    attributeId: string;
    values: Array<GoautowpAttrConflictValue>;
}

