/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIBanItem } from './goautowpAPIBanItem';
import { GoautowpAPIIPRights } from './goautowpAPIIPRights';


export interface GoautowpIP { 
    address: string;
    hostname: string;
    blacklist: GoautowpAPIBanItem;
    rights: GoautowpAPIIPRights;
}

