/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpBrandVehicleType { 
    id: number;
    name: string;
    catname: string;
    itemsCount: string;
}

