/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemParentCacheListOptions } from './goautowpItemParentCacheListOptions';


export interface GoautowpItemLinkListOptions { 
    id: string;
    itemId: string;
    type: string;
    itemParentCacheDescendant: GoautowpItemParentCacheListOptions;
}

