/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPITopFactoriesListItem } from './goautowpAPITopFactoriesListItem';


export interface GoautowpAPITopFactoriesList { 
    items: Array<GoautowpAPITopFactoriesListItem>;
}

