/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPicturesPagesPage } from './goautowpPicturesPagesPage';


export interface GoautowpPicturesPages { 
    pageCount: number;
    first: string;
    current: string;
    next: string;
    previous: string;
    pagesInRange: Array<GoautowpPicturesPagesPage>;
    totalItemCount: number;
    last: string;
}

