/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpAboutDataResponse { 
    developer: string;
    frTranslator: string;
    zhTranslator: string;
    beTranslator: string;
    ptBrTranslator: string;
    contributors: Array<string>;
    totalPictures: number;
    picturesSize: number;
    totalUsers: number;
    totalItems: number;
    totalComments: number;
}

