/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemsRequest } from './goautowpItemsRequest';
import { GoautowpItemParentCacheRequest } from './goautowpItemParentCacheRequest';
import { GoautowpPicturesRequest } from './goautowpPicturesRequest';


export interface GoautowpPictureItemFields { 
    item: GoautowpItemsRequest;
    itemParentCacheAncestor: GoautowpItemParentCacheRequest;
    picture: GoautowpPicturesRequest;
}

