/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GoautowpItemParentType = {
    ItemTypeDefault: 'ITEM_TYPE_DEFAULT',
    ItemTypeTuning: 'ITEM_TYPE_TUNING',
    ItemTypeSport: 'ITEM_TYPE_SPORT',
    ItemTypeDesign: 'ITEM_TYPE_DESIGN'
} as const;
export type GoautowpItemParentType = typeof GoautowpItemParentType[keyof typeof GoautowpItemParentType];

