/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemParentCacheFields } from './goautowpItemParentCacheFields';
import { GoautowpItemParentCacheListOptions } from './goautowpItemParentCacheListOptions';


export interface GoautowpItemParentCacheRequest { 
    fields: GoautowpItemParentCacheFields;
    options: GoautowpItemParentCacheListOptions;
}

