/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIItemLink } from './goautowpAPIItemLink';


export interface GoautowpItemLinks { 
    items: Array<GoautowpAPIItemLink>;
}

