/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIImage } from './goautowpAPIImage';
import { TypeLatLng } from './typeLatLng';


export interface GoautowpMapPoint { 
    location: TypeLatLng;
    id: string;
    name: string;
    url: Array<string>;
    image: GoautowpAPIImage;
}

