/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPages } from './goautowpPages';
import { GoautowpMessage } from './goautowpMessage';


export interface GoautowpMessagingGetMessagesResponse { 
    items: Array<GoautowpMessage>;
    paginator: GoautowpPages;
}

