/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GoautowpPictureStatus = {
    PictureStatusUnknown: 'PICTURE_STATUS_UNKNOWN',
    PictureStatusAccepted: 'PICTURE_STATUS_ACCEPTED',
    PictureStatusRemoving: 'PICTURE_STATUS_REMOVING',
    PictureStatusRemoved: 'PICTURE_STATUS_REMOVED',
    PictureStatusInbox: 'PICTURE_STATUS_INBOX'
} as const;
export type GoautowpPictureStatus = typeof GoautowpPictureStatus[keyof typeof GoautowpPictureStatus];

