/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpItemLanguage { 
    itemId: string;
    language: string;
    name: string;
    textId: number;
    text: string;
    fullTextId: number;
    fullText: string;
}

