/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemParentType } from './goautowpItemParentType';


export interface GoautowpAPITreeItem { 
    id: string;
    nameHtml: string;
    childs: Array<GoautowpAPITreeItem>;
    type: GoautowpItemParentType;
}
export namespace GoautowpAPITreeItem {
}


