/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAttrValueValue } from './goautowpAttrValueValue';


export interface GoautowpChartDataDataset { 
    name: string;
    values: { [key: string]: GoautowpAttrValueValue; };
}

