/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpPictureModerVote { 
    pictureId: string;
    userId: string;
    vote: number;
    reason: string;
}

