/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GoautowpItemParentsRequestOrder = {
    None: 'NONE',
    Auto: 'AUTO',
    CategoriesFirst: 'CATEGORIES_FIRST'
} as const;
export type GoautowpItemParentsRequestOrder = typeof GoautowpItemParentsRequestOrder[keyof typeof GoautowpItemParentsRequestOrder];

