/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPITopPersonsListItem } from './goautowpAPITopPersonsListItem';


export interface GoautowpAPITopPersonsList { 
    items: Array<GoautowpAPITopPersonsListItem>;
}

