/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpDonationsTransaction } from './goautowpDonationsTransaction';


export interface GoautowpDonationsTransactionsResponse { 
    items: Array<GoautowpDonationsTransaction>;
}

