/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpPicture } from './goautowpPicture';


export interface GoautowpPictureSiblings { 
    prev: GoautowpPicture;
    next: GoautowpPicture;
    prevNew: GoautowpPicture;
    nextNew: GoautowpPicture;
}

