/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpVODDataDate } from './goautowpVODDataDate';


export interface GoautowpVODDataResponse { 
    dates: Array<GoautowpVODDataDate>;
    sum: number;
}

