/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemLinksRequest } from './goautowpItemLinksRequest';
import { GoautowpItemParentsRequest } from './goautowpItemParentsRequest';
import { GoautowpItemsRequest } from './goautowpItemsRequest';
import { GoautowpPictureItemsRequest } from './goautowpPictureItemsRequest';
import { GoautowpPreviewPicturesRequest } from './goautowpPreviewPicturesRequest';


export interface GoautowpItemFields { 
    nameOnly: boolean;
    nameDefault: boolean;
    nameHtml: boolean;
    nameText: boolean;
    description: boolean;
    fullText: boolean;
    hasText: boolean;
    previewPictures: GoautowpPreviewPicturesRequest;
    descendantsCount: boolean;
    descendantPicturesCount: boolean;
    childsCount: boolean;
    descendantTwinsGroupsCount: boolean;
    inboxPicturesCount: boolean;
    fullName: boolean;
    logo120: boolean;
    mostsActive: boolean;
    commentsAttentionsCount: boolean;
    isCompilesItemOfDay: boolean;
    brandicon: boolean;
    attrZoneId: boolean;
    location: boolean;
    acceptedPicturesCount: boolean;
    hasChildSpecs: boolean;
    hasSpecs: boolean;
    otherNames: boolean;
    design: boolean;
    specsRoute: boolean;
    childsCounts: boolean;
    publicRoutes: boolean;
    pictureItems: GoautowpPictureItemsRequest;
    altNames: boolean;
    route: boolean;
    links: GoautowpItemLinksRequest;
    categories: GoautowpItemsRequest;
    twins: GoautowpItemsRequest;
    canEditSpecs: boolean;
    itemParentChilds: GoautowpItemParentsRequest;
    commentsCount: boolean;
    engineVehicles: GoautowpItemsRequest;
    routeBrandId: string;
    relatedGroupPictures: boolean;
    itemOfDayPictures: boolean;
    meta: boolean;
    engineVehiclesCount: boolean;
    itemLanguageCount: boolean;
    linksCount: boolean;
    logo: boolean;
    parentsCount: boolean;
    exactPicturesCount: boolean;
    specificationsCount: boolean;
    subscription: boolean;
    specsContributors: boolean;
}

