/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpDfDistance } from './goautowpDfDistance';


export interface GoautowpDfDistances { 
    items: Array<GoautowpDfDistance>;
}

