/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpItemFields } from './goautowpItemFields';
import { GoautowpPicturesRequest } from './goautowpPicturesRequest';


export interface GoautowpItemParentFields { 
    item: GoautowpItemFields;
    parent: GoautowpItemFields;
    duplicateParent: GoautowpItemFields;
    duplicateChild: GoautowpItemFields;
    childDescendantPictures: GoautowpPicturesRequest;
}

