/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAttrValueValue } from './goautowpAttrValueValue';


export interface GoautowpAttrUserValue { 
    attributeId: string;
    itemId: string;
    userId: string;
    value: GoautowpAttrValueValue;
    valueText: string;
    updateDate: Date;
}

