/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIImage } from './goautowpAPIImage';


export interface GoautowpAPIUser { 
    id: string;
    name: string;
    deleted: boolean;
    longAway: boolean;
    green: boolean;
    route: Array<string>;
    identity: string;
    avatar: GoautowpAPIImage;
    gravatar: string;
    lastOnline: Date;
    specsWeight: number;
    email: string;
    timezone: string;
    language: string;
    votesPerDay: string;
    votesLeft: string;
    img: GoautowpAPIImage;
    gravatarLarge: string;
    photo: GoautowpAPIImage;
    regDate: Date;
    picturesAdded: number;
    picturesAcceptedCount: number;
    lastIp: string;
    login: string;
}

