/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpModeratorAttention } from './goautowpModeratorAttention';
import { GoautowpCommentsType } from './goautowpCommentsType';
import { GoautowpPictureStatus } from './goautowpPictureStatus';


export interface GoautowpAPICommentsMessage { 
    id: string;
    typeId: GoautowpCommentsType;
    itemId: string;
    parentId: string;
    createdAt: Date;
    deleted: boolean;
    moderatorAttention: GoautowpModeratorAttention;
    isNew: boolean;
    authorId: string;
    ip: string;
    text: string;
    vote: number;
    preview: string;
    route: Array<string>;
    userVote: number;
    replies: Array<GoautowpAPICommentsMessage>;
    pictureStatus: GoautowpPictureStatus;
}
export namespace GoautowpAPICommentsMessage {
}


