/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIImage } from './goautowpAPIImage';


export interface GoautowpItemOfDayPicture { 
    name: string;
    thumb: GoautowpAPIImage;
    route: Array<string>;
}

