/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIBrandsListLineCategory } from './aPIBrandsListLineCategory';
import { GoautowpAPIBrandsListCharacter } from './goautowpAPIBrandsListCharacter';


export interface GoautowpAPIBrandsListLine { 
    category: APIBrandsListLineCategory;
    characters: Array<GoautowpAPIBrandsListCharacter>;
}
export namespace GoautowpAPIBrandsListLine {
}


