/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpPages { 
    pageCount: number;
    first: number;
    current: number;
    next: number;
    previous: number;
    firstPageInRange: number;
    lastPageInRange: number;
    pagesInRange: Array<number>;
    totalItemCount: number;
    last: number;
}

