/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoautowpAPIItem } from './goautowpAPIItem';
import { GoautowpPicture } from './goautowpPicture';


export interface GoautowpNewboxGroup { 
    item: GoautowpAPIItem;
    pictures: Array<GoautowpPicture>;
    totalPictures: number;
    type: string;
}

