/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GoautowpModeratorAttention = {
    None: 'NONE',
    Required: 'REQUIRED',
    Complete: 'COMPLETE'
} as const;
export type GoautowpModeratorAttention = typeof GoautowpModeratorAttention[keyof typeof GoautowpModeratorAttention];

