/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoautowpAPIBrandSection { 
    name: string;
    routerLink: Array<string>;
    count: number;
    groups: Array<GoautowpAPIBrandSection>;
}

