/**
 * spec.proto
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GoautowpPictureItemType = {
    PictureItemUnknown: 'PICTURE_ITEM_UNKNOWN',
    PictureItemContent: 'PICTURE_ITEM_CONTENT',
    PictureItemAuthor: 'PICTURE_ITEM_AUTHOR',
    PictureItemCopyrights: 'PICTURE_ITEM_COPYRIGHTS'
} as const;
export type GoautowpPictureItemType = typeof GoautowpPictureItemType[keyof typeof GoautowpPictureItemType];

