<?php
    $classes = array('picture-preview');
    if (isset($this->colClass)) {
        $classes[] = $this->colClass;
    }
    if ($this->moderVote !== null) {
        if ($this->moderVote > 0) {
            $classes[] = 'vote-accept';
        } elseif ($this->moderVote < 0) {
            $classes[] = 'vote-remove';
        } else {
            $classes[] = 'vote-neutral';
        }
    }
?>
<div class="<?=$this->escape(implode(' ', $classes))?>" data-id="<?=$this->id?>">
    <div class="thumbnail clearfix">
        <?=$this->htmlA($this->url, $this->htmlImg(array(
            'src'     => $this->src,
            'alt'     => $this->name,
            'title'   => $this->name,
            'shuffle' => true
        )), false) ?>
        <div class="caption">
            <p><?=$this->htmlA($this->url, $this->name)?></p>
            <?php if (!$this->disableBehaviour) { ?>
                <?=$this->render('picture-behaviour.phtml')?>
            <?php } ?>
        </div>
        <button type="button" class="btn btn-default btn-sm pull-left" data-toggle="button" aria-pressed="false" autocomplete="off">
            <i class="fa fa-check"></i>
        </button>
        <?php if ($this->type == Picture::CAR_TYPE_ID) { ?>
            <div style="margin-left: 35px;">
                <?=$this->action('picture-perspective', 'pictures', 'moder', array(
                    'picture_id' => $this->id,
                    'tiny'       => true
                )) ?>
            </div>
        <?php } ?>
    </div>
</div>