<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => false,
        'needRight' => true
    ));
    $this->page(42)->initPage();
?>
<?php foreach ($this->themes as $theme) { ?>
    <div class="row">
        <div class="col-lg-6">
            <div class="well">
                <p><span class="glyphicon glyphicon-th-list"></span> <strong><?=$this->htmlA(array(
                    'href' => $theme['url'],
                    'title' => 'Перейти в форум "'.$theme['name'].'"'
                ), $theme['name']) ?></strong></p>
                <?php if ($theme['description']) { ?>
                    <p><?=$this->escape($theme['description']) ?></p>
                <?php } ?>
                <p>Тем: <?=$theme['topics'] ?>, Сообщений: <?=$theme['messages'] ?></p>
                <?php if (count($theme['subthemes'])) { ?>
                    Подфорумы:
                    <?php foreach ($theme['subthemes'] as $idx => $subtheme) {
                        if ($idx) {
                            print ', ';
                        }
                        print $this->htmlA($subtheme['url'], $subtheme['name']);
                    } ?>
                <?php } else { ?>
                    <p><?=$this->htmlA($theme['url'], 'Зайти в форум …') ?></p>
                <?php } ?>
            </div>
        </div>
        <?php if ($topic = $theme['lastTopic']) { ?>
            <div class="col-lg-6">
                <div class="well transparent">
                    <?php if ($lastMessage = $theme['lastMessage']) { ?>
                        <p><span class="glyphicon glyphicon-comment"></span> Последнее сообщение в теме «<?=$this->htmlA($this->url(array(
                            'controller' => 'topic',
                            'action'     => 'topic',
                            'topic_id'   => $topic->id
                        )), $topic->caption) ?>»</p>
                        <p>
                            <?php if ($date = $lastMessage->getDate('add_datetime')) { ?>
                                <?=$this->pastTimeIndicator($date)?>
                            <?php } ?>
                            <?php if ($lastMessageAuthor = $lastMessage->findParentUsersByAuthor()) { ?>
                                <?=$this->user($lastMessageAuthor) ?>
                            <?php } ?>
                            <?=$this->htmlA(array(
                                'href'  => $this->url(array(
                                    'controller' => 'topic',
                                    'action'     => 'topic-message',
                                    'message_id' => $lastMessage->id
                                )),
                                'title' => 'Перейти к последнему сообщению'
                            ), '<img src="/img/forums/icon_latest_reply.gif" alt="-&gt;" style="width:18px;height:9px" />', false) ?>
                        </p>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>