<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => true
        ),
        'pageId' => 42,
    ));
?>

<?php foreach ($this->themes as $theme) { ?>
    <div class="row">
        <div class="col-md-6">
            <div class="well">
                <p><span class="glyphicon glyphicon-th-list"></span> <strong><?=$this->htmlA(array(
                    'href'  => $theme['url'],
                    'title' => $this->translate('forums/go-to-theme-%1$s', $this->translate($theme['name']))
                ), $this->translate($theme['name'])) ?></strong></p>
                <?php if ($theme['description']) { ?>
                    <p><?=$this->escape($theme['description']) ?></p>
                <?php } ?>
                <p>
                    <?=$this->escape($this->translate(['%1$s topics', null, $theme['topics']], $theme['topics']))?>,
                    <?=$this->escape($this->translate(['%1$s messages', null, $theme['messages']], $theme['messages']))?>
                </p>
                <?php if (count($theme['subthemes'])) { ?>
                    <?=$this->escape($this->translate('forums/subforums'))?>:
                    <?php foreach ($theme['subthemes'] as $idx => $subtheme) {
                        if ($idx) {
                            print ', ';
                        }
                        print $this->htmlA($subtheme['url'], $this->translate($subtheme['name']));
                    } ?>
                <?php } else { ?>
                    <p><?=$this->htmlA($theme['url'], $this->translate('forums/go-to-theme')) ?></p>
                <?php } ?>
            </div>
        </div>
        <?php if ($theme['lastTopic']) { ?>
            <div class="col-md-6">
                <div class="well transparent">
                    <?php if ($lastMessage = $theme['lastMessage']) { ?>
                        <p>
                            <span class="glyphicon glyphicon-comment"></span>
                            <?=$this->translate('forums/last-message-in-topic-%1$s', $this->htmlA($lastMessage['url'], $theme['lastTopic']['name']))?>
                        </p>
                        <p>
                            <?php if ($lastMessage['date']) { ?>
                                <?=$this->pastTimeIndicator($lastMessage['date'])?>
                            <?php } ?>
                            <?php if ($lastMessage['author']) { ?>
                                <?=$this->user($lastMessage['author']) ?>
                            <?php } ?>
                            <?=$this->htmlA(array(
                                'href'  => $lastMessage['message-url'],
                                'title' => $this->translate('forums/go-to-last-message')
                            ), '<span class="glyphicon glyphicon-share-alt"></span>', false) ?>
                        </p>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>