<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 68,
    ));
?>

<a href="/moder/pages/new-page/" class="btn btn-success">Новый</a>

<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th colspan="2">move</th>
            <th>N</th>
            <th>Название</th>
            <th>Breadcrumbs</th>
            <th>IsGroup?</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php
            printPagesRecuirsiveTree($this, new Pages());
        ?>
    </tbody>
</table>

<?php
    function printPagesRecuirsiveTree($view, $pages, $parentId = null, $level = 0)
    {
        $offset = (int)$level*20;

        $select = $pages->select()
                        ->order('position');
        if ($parentId)
            $select->where('parent_id = ?', $parentId);
        else
        {
            $select->where('parent_id IS NULL');
        }
        $rows = $pages->fetchAll($select);
        foreach ($rows as $idx => $page) {
            ?>
            <tr class="data-row">
                <td>
                    <?php if ($idx > 0) { ?>
                        <form action="<?=$view->escape($view->url(array(
                            'module'     => 'moder',
                            'controller' => 'pages',
                            'action'     => 'move-up-page',
                            'page_id'    => $page->id
                        ))) ?>" style="margin:0">
                            <div><button type="submit" class="btn btn-default btn-xs">↑</button></div>
                        </form>
                    <?php } ?>
                </td>
                <td>
                    <?php if ($idx < count($rows)-1) { ?>
                        <form action="<?=$view->escape($view->url(array(
                            'module'     => 'moder',
                            'controller' => 'pages',
                            'action'     => 'move-down-page',
                            'page_id'    => $page->id
                        ))) ?>" style="margin:0">
                            <div><button type="submit" class="btn btn-default btn-xs">↓</button></div>
                        </form>
                    <?php } ?>
                </td>
                <td><?=$page->id ?></td>
                <td style="padding-left:<?=$offset?>px"><?=$view->escape($page->name) ?></td>
                <td><?=$view->escape($page->breadcrumbs) ?></td>
                <td><?=$view->escape($page->is_group_node ? 'да' : 'нет') ?></td>
                <td>
                    <form class="btn-group" action="<?=$view->escape($view->url(array(
                        'action'  => 'remove-page',
                        'page_id' => $page->id
                    )))?>">
                        <?=$view->htmlA(array(
                            'class' => "btn btn-xs btn-success",
                            'href'  => $view->url(array(
                                'action'    => 'new-page',
                                'parent_id' => $page->id
                            ))
                        ), '<i class="fa fa-plus"></i>', false) ?>
                        <?=$view->htmlA(array(
                            'class' => "btn btn-default btn-xs",
                            'href'  => $view->url(array(
                                'action'  => 'edit-page',
                                'page_id' => $page->id
                            ))
                        ), '<i class="fa fa-pencil"></i>', false) ?>
                        <button class="btn btn-xs btn-danger" type="submit">
                            <i class="fa fa-times"></i>
                        </button>
                    </form>
                </td>
            </tr>
            <?php
            printPagesRecuirsiveTree($view, $pages, $page->id, $level+1);
        }
    }
?>