<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 79,
    ));
?>
<div class="row"><div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 login-page">
    <?=$this->render('login/menu.phtml')?>
    <div class="well">
        <?=$this->form->render($this) ?>
    </div>

    <?php if ($this->errorMessage) { ?>
        <p class="alert alert-block alert-error"><?=$this->escape($this->errorMessage) ?></p>
    <?php } ?>

    <p>Если вы забыли свой логин или пароль, вы можете воспользоваться <a href="/restorepassword/">формой восстановления по e-mail</a></p>
    <p>Если вы ещё не зарегистрированы на сайте, то можете <a href="/registration/">сделать это сейчас</a></p>

</div></div>