<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 79,
    ));
?>
<div class="row"><div class="col-md-8 col-md-offset-2 login-page">
    <?=$this->render('login/menu.phtml')?>
    <div class="well">
        <?=$this->form->render($this) ?>
    </div>

    <?php if ($this->errorMessage) { ?>
        <p class="alert alert-block alert-error"><?=$this->escape($this->errorMessage) ?></p>
    <?php } ?>

    <p><?=$this->translate('login/if-you-lose-password')?></p>
    <p><?=$this->translate('login/if-you-not-registered')?></p>

</div></div>