<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 79,
    ));
?>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <p class="alert alert-block alert-success">
            <?=$this->escape($this->translate('login/success-text'))?>
        </p>
    </div>
</div>