<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 153,
        'args'   => [
            'BRAND_NAME'    => $this->brand['name'],
            'BRAND_CATNAME' => $this->brand['catname']
        ]
    ]);
?>
<?=$this->partial('application/twins/partial/list', [
    'groups'  => $this->groups,
    'canEdit' => $this->canEdit
])?>
<?=$this->paginationControl($this->paginator, null, null, [
    'route'     => 'twins/brand',
    'urlParams' => [
        'brand_catname' => $this->brand['catname']
    ]
]) ?>