<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 26,
        'args'   => [
            'TWINS_GROUP_NAME' => $this->group['name'],
            'TWINS_GROUP_ID'   => $this->group['id']
        ]
    ]);
?>
<?=$this->partial('application/cars', $this->cars)?>

<ul class="carLinks">
    <?php if ($this->hasSpecs) {?>
        <li>
            <i class="fa fa-list-alt"></i>
            <?=$this->htmlA($this->specsUrl, $this->translate('carlist/specifications'))?>
        </li>
    <?php } ?>

    <?php if ($this->picturesCount) { ?>
        <li>
            <i class="fa fa-th"></i>
            <?=$this->htmlA($this->picturesUrl, $this->translate('carlist/all pictures') . ' ('.$this->picturesCount.')')?>
        </li>
    <?php } ?>
</ul>

<?php if (strlen($this->description)){ ?>
    <h3><?=$this->escapeHtml($this->translate('twins/group/description'))?></h3>
    <div class="well"><?=$this->markdown($this->description) ?></div>
<?php } ?>

<?=$this->comments([
    'type'    => Autowp\Comments\Model\DbTable\Message::TWINS_TYPE_ID,
    'item_id' => $this->group['id']
]) ?>