<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 25,
    ]);
?>
<div class="row">
    <div class="col-sm-8 col-sm-push-4">
        <?=$this->partial('application/twins/partial/list', [
            'groups'  => $this->groups,
            'canEdit' => $this->canEdit
        ])?>
        <?=$this->paginationControl($this->paginator, null, null, [
            'route' => 'twins/page'
        ]) ?>
    </div>
    <div class="col-sm-4 col-sm-pull-8">
        <?=$this->partial('application/twins/partial/sidebar', [
            'brands'  => $this->brands
        ])?>
    </div>
</div>