<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 28,
        'args'   => [
            'TWINS_GROUP_NAME' => $this->group['name'],
            'TWINS_GROUP_ID'   => $this->group['id']
        ]
    ]);
?>
<?=$this->partial('application/pictures', $this->picturesData)?>
<?=$this->paginationControl($this->paginator, null, null, [
    'route'     => 'twins/group/pictures/page',
    'urlParams' => [
        'id' => $this->group['id']
    ]
]) ?>