<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 183,
        'args'   => [
            'PICTURE_NAME'     => $this->pic()->textTitle($this->name ? $this->name : []),
            'TWINS_GROUP_NAME' => $this->group['name'],
            'TWINS_GROUP_ID'   => $this->group['id']
        ]
    ]);
?>
<?=$this->render('application/picture/picture')?>