<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 28,
        'args'   => [
            'TWINS_GROUP_NAME' => $this->group['name'],
            'TWINS_GROUP_ID'   => $this->group['id']
        ]
    ]);
?>
<div class="row">
    <div class="col-sm-8 col-sm-push-4">
        <?=$this->partial('application/pictures', $this->picturesData)?>
        <?=$this->paginationControl($this->paginator, null, null, [
            'route'     => 'twins/group/pictures/page',
            'urlParams' => [
                'id' => $this->group['id']
            ]
        ]) ?>
    </div>
    <div class="col-sm-4 col-sm-pull-8">
        <?=$this->partial('application/twins/partial/sidebar', [
            'brands'  => $this->brands
        ])?>
    </div>
</div>