<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 27,
        'args'   => [
            'TWINS_GROUP_NAME' => $this->group['name'],
            'TWINS_GROUP_ID'   => $this->group['id']
        ]
    ]);
?>
<?=$this->partial('application/specs', [
    'table' => $this->specs,
])?>