<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 161,
    ]);

    $this->layout()->moduleName = 'default/pulse';
?>
<div id="pulse-graph" style="height:600px;background:#333;margin-bottom:10px" data-values="<?=$this->escapeHtmlAttr(Zend\Json\Json::encode($this->grid))?>"></div>
<p class="legend">
    <?php foreach ($this->legend as $legend) { ?>
        <span style="color:<?=$legend['color']?>" data-id="<?=$legend['user']->id?>"><?=$this->user($legend['user'])?></span>
    <?php } ?>
</p>