<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => true
        ],
        'pageId' => 157,
        'args'   => [
            'VOTING_NAME' => $this->voting->name,
            'VOTING_ID'   => $this->voting->id
        ]
    ]);

    $this->layout()->moduleName = 'default/voting/voting';
?>
<div class="well">
    <p><?=nl2br($this->escapeHtml($this->voting->text))?></p>
    <hr />

    <?php if ($this->canVote) { ?>
        <form action="<?=$this->escapeHtmlAttr($this->url('votings/vote', [
            'id' => $this->voting->id
        ]))?>" method="post">
            <ul class="unstyled">
                <?php foreach ($this->variants as $variant) { ?>
                    <li>
                        <?php if ($this->voting->multivariant) { ?>
                            <label class="checkbox inline">
                                <input type="checkbox" name="variant[]" value="<?=$variant['id']?>" />
                                <?=$this->escapeHtml($variant['name'])?>
                            </label>
                        <?php } else { ?>
                            <label class="radio inline">
                                <input type="radio" name="variant[]" value="<?=$variant['id']?>" />
                                <?=$this->escapeHtml($variant['name'])?>
                            </label>
                        <?php } ?>

                        <?php if ($variant['text']) { ?>
                            <p class="text-info"><?=nl2br($this->escapeHtml($variant['text']))?></p>
                        <?php } ?>
                    </li>
                <?php } ?>
            </ul>
            <input type="submit" class="btn btn-primary" value="<?=$this->escapeHtmlAttr($this->translate('votings/do-vote'))?>" />
        </form>
    <?php } else { ?>
        <?php foreach ($this->variants as $variant) { ?>
            <?php if ($variant['votes']) { ?>
                <p class="pull-right"><?=$this->htmlA([
                    'class' => 'who-vote',
                    'href'  => $this->url('votings/voting-variant-votes', [
                        'id' => $variant['id']
                    ])
                ], $this->translate('votings/who-voted'))?></p>
            <?php } ?>
            <?=$this->escapeHtml($variant['name'])?>
            <?php if ($variant['text']) { ?>
                <p class="text-info"><?=nl2br($this->escapeHtml($variant['text']))?></p>
            <?php } ?>
            <div style="clear:both" class="progress">
                <div class="progress-bar<?=$variant['isMax'] ? ' progress-bar-success' : ''?><?=$variant['isMin'] ? ' progress-bar-danger' : ''?>" style="width:<?=$variant['percent']?>%"><?=$variant['votes'] > 0 ? $variant['votes'] : ''?></div>
            </div>
        <?php } ?>
    <?php } ?>
</div>
<?php if (!$this->canVote && $this->user()->inheritsRole('moder')) { ?>
    <p class="pull-right">
        <?php if ($this->filter) { ?>
            <?=$this->htmlA($this->url('votings/voting', [
                'id'     => $this->voting->id,
                'filter' => null
            ]), $this->translate('votings/voting/voters/show-all'))?>
        <?php } else { ?>
            <?=$this->htmlA($this->url('votings/voting', [
                'id'     => $this->voting->id,
                'filter' => 1
            ]), $this->translate('votings/voting/voters/show-contributors'))?>
        <?php } ?>
    </p>
<?php } ?>
<p>
    <?=$this->escapeHtml(sprintf(
        $this->translate('votings/voting/voters/during-%s-%s'),
        $this->dateFormat($this->voting->getDateTime('begin_date'), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, $this->language()),
        $this->dateFormat($this->voting->getDateTime('end_date'), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, $this->language())
    ))?>
</p>

<div id="comments">
    <?=$this->comments([
        'type'    => \Application\Comments::VOTINGS_TYPE_ID,
        'item_id' => $this->voting->id
    ]) ?>
</div>