<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 29
    ]);

    $this->layout()->moduleName = 'default/upload/index';
    $this->layout()->moduleOptions = [
        'cropMsg'      => $this->translate('upload/picture/crop'),
        'croppedToMsg' => $this->translate('upload/picture/cropped-to'),
        'cropSaveUrl'  => $this->url(null, [
            'controller' => 'upload',
            'action'     => 'crop-save',
        ])
    ];
?>

<?php if ($this->selected) { ?>
    <div class="well">
        <?=$this->markdown($this->translate('upload/description'))?>
        <div style="margin:20px 0">
            <p style="margin:10px">
                <strong><?=$this->escapeHtml($this->selectedName) ?></strong>
                [<?=$this->htmlA($this->url(null, [
                    'action' => 'select-brand'
                ]), $this->translate('upload/select-another')) ?>]
            </p>
            <?=$this->partial('application/forms/bootstrap-horizontal', [
                'form' => $this->form
            ])?>
        </div>

        <div class="progress-area"></div>
    </div>
    
    <div class="pictures"></div>
<?php } else { ?>
    <div class="well">
        <?=$this->markdown($this->translate('upload/description'))?>
        <p style="margin:10px"><?=$this->htmlA([
            'class' => 'btn btn-primary btn-lg',
            'href'  => $this->url(null, [
                'action' => 'select-brand'
            ], [], true)
        ], '<i class="fa fa-upload"></i> ' . $this->escapeHtml($this->translate('upload/add-picture')), false) ?></p>
    </div>
<?php } ?>