<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 30
    ]);
    $columns = 6;
    $count = count($this->brands);
    $perOne = ceil($count / $columns);
    $idx = 0;
?>
<div class="row">
    <div class="col-md-2">
        <?php foreach ($this->brands as $brand) { ?>
            <?php if ($idx && ($idx%$perOne == 0)) { ?>
                </div><div class="col-md-2">
            <?php } ?>
            <?=$this->htmlA($this->url('upload/params', [
                'brand_id' => $brand['id']
            ], [], true), $brand['name']) ?><br />
            <?php $idx++ ?>
        <?php } ?>
    </div>
</div>