<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 30
    ]);

    $this->layout()->moduleName = 'default/upload/select-in-brand';
?>

<div class="select-in-brand">
    <?php if (count($this->vehicles) > 0) { ?>
        <div style="margin: 5px 0">
            <?=$this->partial('application/upload/select-in-brand-items', [
                'cars' => $this->vehicles
            ])?>
        </div>
    <?php } ?>

    <?php if (count($this->engines) > 0) { ?>
        <h5><?=$this->escapeHtml($this->translate('item/type/2/name-plural'))?></h5>
        <div style="margin: 5px 0">
            <?=$this->partial('application/upload/select-in-brand-items', [
                'cars' => $this->engines
            ])?>
        </div>
    <?php } ?>

    <?php if ($this->haveConcepts) { ?>
        <div style="margin: 5px 0">
            <?=$this->htmlA([
                'href'      => '#',
                'class'     => 'arrow',
                'data-load' => $this->conceptsUrl
            ], '<i class="fa fa-plus-circle"></i> ' . $this->escapeHtml($this->translate('upload/select/concepts')), false) ?>
            <div style="margin:0 0 4px 18px;display:none">
                <div class="loading"><em>Loading ...</em></div>
            </div>
        </div>
    <?php } ?>

    <div style="margin: 5px 0">
        <?=$this->htmlA($this->url('upload/params', [
            'action'         => 'index',
            'item_id'        => $this->brand['id'],
            'perspective_id' => 22
        ], [], true), $this->translate('upload/select/logo')) ?><br />
        <?=$this->htmlA($this->url('upload/params', [
            'action'         => 'index',
            'item_id'        => $this->brand['id'],
            'perspective_id' => 25
        ], [], true), $this->translate('upload/select/mixed-long')) ?><br />
        <?=$this->htmlA($this->url('upload/params', [
            'action'  => 'index',
            'item_id' => $this->brand['id']
        ], [], true), $this->translate('upload/select/unsorted-long')) ?>
    </div>
</div>
