<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 30
    ]);

    $this->layout()->moduleName = 'default/upload/select-in-brand';
?>

<div class="select-in-brand">
    <?php if (count($this->cars) > 0) { ?>
        <div style="margin: 5px 0">
            <?=$this->partial('application/upload/select-in-brand-items', [
                'cars' => $this->cars
            ])?>
        </div>
    <?php } ?>

    <?php if ($this->haveConcepts) { ?>
        <div style="margin: 5px 0">
            <?=$this->htmlA([
                'href'      => '#',
                'class'     => 'arrow',
                'data-load' => $this->conceptsUrl
            ], '<i class="fa fa-plus-circle"></i> ' . $this->escapeHtml($this->translate('upload/select/concepts')), false) ?>
            <div style="margin:0 0 4px 18px;display:none">
                <div class="loading"><em>Loading ...</em></div>
            </div>
        </div>
    <?php } ?>

    <?php if ($this->haveEngines) { ?>
        <div style="margin: 5px 0">
            <?=$this->htmlA([
                'href'      => '#',
                'class'     => 'arrow',
                'data-load' => $this->enginesUrl
            ], '<i class="fa fa-plus-circle"></i> ' . $this->escapeHtml($this->translate('upload/select/engines')), false)?>
            <div style="margin:0 0 4px 18px;display:none">
                <div class="loading"><em>Loading ...</em></div>
            </div>
        </div>
    <?php } ?>

    <div style="margin: 5px 0">
        <?=$this->htmlA($this->url('upload/params', [
            'action' => 'index',
            'type'   => Application\Model\DbTable\Picture::LOGO_TYPE_ID
        ], [], true), $this->translate('upload/select/logo')) ?><br />
        <?=$this->htmlA($this->url('upload/params', [
            'action' => 'index',
            'type'   => Application\Model\DbTable\Picture::MIXED_TYPE_ID
        ], [], true), $this->translate('upload/select/mixed-long')) ?><br />
        <?=$this->htmlA($this->url('upload/params', [
            'action' => 'index',
            'type'   => Application\Model\DbTable\Picture::UNSORTED_TYPE_ID
        ], [], true), $this->translate('upload/select/unsorted-long')) ?>
    </div>
</div>
