<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 30
    ]);
    $this->pageTitle('Выбор бренда');

    $this->layout()->moduleName = 'default/upload/select-in-brand';
?>

<div class="select-in-brand">
    <?php if (count($this->cars) > 0) { ?>
        <div style="margin: 5px 0">
            <?=$this->partial('application/upload/select-in-brand-cars', [
                'cars' => $this->cars
            ])?>
        </div>
    <?php } ?>

    <?php if ($this->haveConcepts) { ?>
        <div style="margin: 5px 0">
            <?=$this->htmlA([
                'href'      => '#',
                'class'     => 'arrow',
                'data-load' => $this->conceptsUrl
            ], '<i class="fa fa-plus-circle"></i> Концепты и прототипы', false) ?>
            <div style="margin:0 0 4px 18px;display:none">
                <div class="loading"><em>Loading ...</em></div>
            </div>
        </div>
    <?php } ?>

    <?php if ($this->haveEngines) { ?>
        <div style="margin: 5px 0">
            <?=$this->htmlA([
                'href'      => '#',
                'class'     => 'arrow',
                'data-load' => $this->enginesUrl
            ], '<i class="fa fa-plus-circle"></i> Двигатели', false)?>
            <div style="margin:0 0 4px 18px;display:none">
                <div class="loading"><em>Loading ...</em></div>
            </div>
        </div>
    <?php } ?>

    <div style="margin: 5px 0">
        <?=$this->htmlA($this->url('upload/params', [
            'action' => 'index',
            'type'   => Picture::LOGO_TYPE_ID
        ], [], true), 'логотип ' . $this->brand['name']) ?><br />
        <?=$this->htmlA($this->url('upload/params', [
            'action' => 'index',
            'type'   => Picture::MIXED_TYPE_ID
        ], [], true), 'разное (несколько автомобилей на одной картинке)') ?><br />
        <?=$this->htmlA($this->url('upload/params', [
            'action' => 'index',
            'type'   => Picture::UNSORTED_TYPE_ID
        ], [], true), 'несортировано (автомобиль или двигатель, которого нет на сайте)') ?>
    </div>
</div>
