<?php
    $blankPage = isset($this->layout()->blankPage) ? $this->layout()->blankPage : $this->blankPage;
    $needLeft  = isset($this->sidebar);
    $needRight = isset($this->layout()->needRight) ? $this->layout()->needRight : $this->needRight;
    $isAdminPage = isset($this->layout()->isAdminPage) ? $this->layout()->isAdminPage : $this->isAdminPage;

    $mainMenu = '';
    if (!$blankPage) {
        $mainMenu = $this->mainMenu();
    }

    $this->gulpRev([
        'stylesheets' => [
            'application.css'
        ]
    ]);

    $moduleOptions = isset($this->layout()->moduleOptions)
        ? $this->layout()->moduleOptions
        : null;

    $module = null;
    if (isset($this->layout()->moduleName)) {
        $module = $this->layout()->moduleName;
    }
?>
<?=$this->doctype() . PHP_EOL ?>
<html dir="ltr" lang="<?=$this->language()?>"<?=$module ? ' data-page-module="'.$this->escapeHtmlAttr($module).'"' : ''?><?=$moduleOptions ? ' data-page-module-options="'.$this->escapeHtmlAttr(Zend\Json\Json::encode($moduleOptions)).'"' : ''?>>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <?=$this->favicons()?>
        <?php
            echo $this->headMeta()
                ->appendName('keywords', $this->translate('layout/meta/keywords'))
                ->appendName('description', $this->translate('layout/meta/description'))
                ->appendProperty('fb:app_id', '258693154144687')
                ->appendProperty('og:site_name', 'WheelsAge.org')
                ->appendName('twitter:site', '@autowp');
            echo $this->headTitle();
            echo $this->headLink();
            echo $this->headScript()
                ->appendFile(
                    'http://html5shim.googlecode.com/svn/trunk/html5.js',
                    'text/javascript',
                    ['conditional' => 'lt IE 9']
                );

            echo $this->headStyle();
        ?>

    </head>
    <body>
        <?php if (!$isAdminPage) { ?>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-24654784-1', <?=\Zend\Json\Json::encode($this->hostManager()->getCookieDomain($this->language()))?>);
ga('send', 'pageview');
</script>
        <?php } ?>

        <?php if (!$blankPage && $this->user()->inheritsRole('moder')) { ?>
            <?=$this->moderMenu()?>
        <?php } ?>

        <?php
            $spanLeft = $needLeft ? 4 : 0;
            $spanRight = $needRight ? 4 : 0;
            $spanCenter = 12 - $spanLeft - $spanRight;
        ?>

        <?php if (!$blankPage) { ?>
            <?=$mainMenu ?>
        <?php }  ?>

        <div class="container">

            <div class="row">
                <div class="col-sm-<?=$spanCenter?> col-sm-push-<?=$spanLeft?>">
                    <?=$this->breadcrumbs() ?>
                    <?=$this->pageTitle() ?>

                    <?=$this->layout()->content ?>
                </div>
                <?php if ($needLeft) { ?>
                    <div class="col-sm-<?=$spanLeft?> col-sm-pull-<?=$spanCenter?>">
                        <?php if (isset($this->sidebar)) { ?>
                            <?=$this->sidebar ?>
                        <?php } ?>
                    </div>
                <?php } ?>
                <?php if ($needRight) { ?>
                    <div class="col-sm-<?=$spanRight?>">
                        <?=$this->sidebar()?>
                    </div>
                <?php } ?>
            </div>

            <?php if ((!$blankPage) && (!$isAdminPage) ) { ?>
                <div class="bottom-line"><p><strong>
                    <?=$this->escapeHtml($this->translate('layout/brand'))?> '2005&ndash;<?=$this->escapeHtml($this->translate('present-time-abbr'))?>
                </strong></p></div>

                <footer class="footer">
                    <div class="row">
                        <div class="col-md-6">
                            <p class="links">
                                <a href="https://twitter.com/autowp_ru" title="Twitter" data-toggle="tooltip" data-placement="top"><i class="fa fa-twitter"></i></a>
                                <a href="https://www.facebook.com/WheelsAge" title="Facebook" data-toggle="tooltip" data-placement="top"><i class="fa fa-facebook"></i></a>
                                <a href="https://vk.com/wheelsage" title="VK" data-toggle="tooltip" data-placement="top"><i class="fa fa-vk" aria-hidden="true"></i></a>
                                <a href="https://github.com/autowp/autowp" title="GitHub" data-toggle="tooltip" data-placement="top"><i class="fa fa-github"></i></a>
                                <a href="https://play.google.com/store/apps/details?id=com.autowp.wallpaper" title="Android wallpaper" data-toggle="tooltip" data-placement="top"><i class="fa fa-android"></i></a>
                                <a href="/ng/telegram" title="Telegram" data-toggle="tooltip" data-placement="top"><i class="fa fa-telegram"></i></a>
                                <a href="/ng/feedback" title="<?=$this->escapeHtmlAttr($this->translate('feedback/title'))?>" data-toggle="tooltip" data-placement="top"><i class="fa fa-comment"></i></a>
                            </p>
                            <p>
                                <?=$this->htmlA('/ng/about', $this->page(136)->name)?>
                                •
                                <?=$this->htmlA('/ng/donate', $this->page(196)->name)?>
                            </p>
                        </div>
                        <div class="col-md-6">
                            <div class="copyrights">
                                <?=$this->markdown($this->translate('layout/footer'))?>
                            </div>
                        </div>
                    </div>
                    <p class="language-picker">
                        <?php foreach ($this->languagePicker() as $item) { ?>
                            <?php if ($item['language'] != $this->language()) { ?>
                                <a href="<?=$this->escapeHtmlAttr($item['url'])?>">
                                    <i class="<?=$this->escapeHtmlAttr($item['flag'])?>"></i>
                                    <?=$this->escapeHtml($item['name'])?>
                                </a>
                            <?php } ?>
                        <?php } ?>
                        <?=$this->htmlA(
                            'https://github.com/autowp/autowp/tree/master/module/Application/language',
                            $this->translate('layout/language-contributing')
                        )?>
                    </p>
                </footer>
            <?php } ?>
        </div>
        <?=$this->gulpRev()->script('application.js')?>
    </body>
</html>