<?php
    $blankPage = isset($this->layout()->blankPage) ? $this->layout()->blankPage : $this->blankPage;
    $needLeft  = isset($this->layout()->needLeft)  ? $this->layout()->needLeft  : $this->needLeft;
    $needRight = isset($this->layout()->needRight) ? $this->layout()->needRight : $this->needRight;
    $isAdminPage = isset($this->layout()->isAdminPage) ? $this->layout()->isAdminPage : $this->isAdminPage;

    $moderMenu = '';
    if (false && !$blankPage && $this->user()->logedIn() && $this->acl()->inheritsRole($this->user()->get()->role, 'moder')) {
        $moderMenu = $this->action('moder-menu', 'index', 'moder');
    }

    $mainMenu = '';
    if (false && !$blankPage) {
        $mainMenu = $this->action('main-menu', 'layout', 'default');
    }

?>
<?=$this->doctype() . PHP_EOL ?>
<html dir="ltr" lang="<? /*=$this->language()->get() */?>">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="theme-color" content="#ede9de">
        <meta name="msapplication-navbutton-color" content="#ede9de">
        <meta name="apple-mobile-web-app-status-bar-style" content="#ede9de">
        <?php
            echo $this->headMeta()
                ->appendName('keywords', $this->translate('layout/meta/keywords'))
                ->appendName('description', $this->translate('layout/meta/description'));
            echo $this->headTitle();
            echo $this
                ->headLink(array('rel' => 'shortcut icon', 'href' => '/favicon.ico', 'type' => 'image/x-icon'), 'PREPEND')
                ->appendStylesheet('/css/styles.css', 'screen');
            echo $this->headScript()
                ->appendFile(
                    'http://html5shim.googlecode.com/svn/trunk/html5.js',
                    'text/javascript',
                    array('conditional' => 'lt IE 9')
                )
                ->appendFile(
                    '/vendor/scottjehl/Respond/dest/respond.min.js',
                    'text/javascript',
                    array('conditional' => 'lt IE 9')
                );

            echo $this->headStyle();
        ?>

    </head>
    <body>
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-KGMHT4"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KGMHT4');</script>

        <?=$moderMenu ?>

        <?php
            $spanLeft = $needLeft ? 4 : 0;
            $spanRight = $needRight ? 4 : 0;
            $spanCenter = 12 - $spanLeft - $spanRight;
        ?>

        <?php if (!$blankPage) { ?>
            <?=$mainMenu ?>
        <?php }  ?>

        <div class="container">

            <div class="row">
                <div class="col-sm-<?=$spanCenter?> col-sm-push-<?=$spanLeft?>">
                    <?/*=$this->action('flash-messages', 'layout', 'default') */?>
                    <?/*=$this->breadcrumbs()*/ ?>
                    <?/*=$this->pageTitle()*/ ?>
                    <?=$this->layout()->content ?>
                </div>
                <?php if ($needLeft) { ?>
                    <div class="col-sm-<?=$spanLeft?> col-sm-pull-<?=$spanCenter?>">
                        <?=$this->layout()->sidebar ?>
                    </div>
                <?php } ?>
                <?php if ($needRight) { ?>
                    <div class="col-sm-<?=$spanRight?>">
                        <?=$this->action('sidebar-right', 'layout', 'default') ?>
                    </div>
                <?php } ?>
            </div>

            <?php if ((!$blankPage) && (!$isAdminPage) ) { ?>
                <div class="bottom-line"><p><strong>AutoWP.ru '2005&ndash;<?=$this->escapeHtml($this->translate('present-time-abbr'))?></strong></p></div>

                <footer class="footer">
                    <div class="row">
                        <div class="col-md-6">
                            <p class="links">
                                <a href="https://twitter.com/autowp_ru" title="Twitter" data-toggle="tooltip" data-placement="top"><i class="fa fa-twitter"></i></a>
                                <a href="https://www.facebook.com/AutoWP/" title="Facebook" data-toggle="tooltip" data-placement="top"><i class="fa fa-facebook"></i></a>
                                <a href="https://github.com/autowp/autowp" title="GitHub" data-toggle="tooltip" data-placement="top"><i class="fa fa-github"></i></a>
                                <a href="https://play.google.com/store/apps/details?id=com.autowp.wallpaper" title="Android wallpaper" data-toggle="tooltip" data-placement="top"><i class="fa fa-android"></i></a>
                                <a href="/feedback/" title="<?=$this->escapeHtml($this->translate('feedback/title'))?>" data-toggle="tooltip" data-placement="top"><i class="fa fa-comment"></i></a>
                            </p>
                            <p>
                                <?=$this->htmlA('/about', $this->page(136)->name)?>
                                •
                                <?=$this->htmlA('/donate', $this->page(196)->name)?>
                            </p>
                        </div>
                        <div class="col-md-6">
                            <p class="copyrights"><?=$this->translate('layout/footer')?></p>
                        </div>
                    </div>
                </footer>
            <?php } ?>
        </div>

        <script type="text/javascript" src="/js/application.js"></script>
        <script type="text/javascript">
require(['application'], function(App) {
    App.init();
    <?php
        $moduleOptions = isset($this->layout()->moduleOptions)
            ? $this->layout()->moduleOptions
            : null;
    ?>
    <?php if (isset($this->layout()->moduleName)) { ?>
        require([<?=Zend_Json::encode($this->layout()->moduleName)?>], function(Module) {
            Module.init(<?=Zend_Json::encode($moduleOptions)?>);
        });
    <?php } ?>
});
        </script>
    </body>
</html>