<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ],
        'pageId' => 77,
    ]);

    $this->layout()->moduleName = 'moder/traffic/whitelist';
    $this->layout()->moduleOptions = [
        'hostByAddrUrl' => $this->url('moder/traffic/host-by-addr')
    ];
?>

<ul class="nav nav-pills">
    <li>
        <?=$this->htmlA($this->url('moder/traffic'), 'Traffic')?>
    </li>
    <li class="active">
        <?=$this->htmlA($this->url('moder/traffic/whitelist'), 'Whitelist')?>
    </li>
</ul>
<table class="table table-striped table-condensed">
    <tbody>
        <?php foreach ($this->rows as $row) { ?>
            <tr>
                <td><?=$this->escapeHtml($row['ip']) ?></td>
                <td>
                    <?php foreach ($row['users'] as $user) { ?>
                        <?=$this->user($user) ?>
                    <?php } ?>
                </td>
                <td class="host-name"><?=$this->escapeHtml($row['ip']) ?></td>
                <td><?=$this->escapeHtml($row['description'])?></td>
                <td><?=$this->htmlA('http://nic.ru/whois/?query='.$row['ip'], 'whois') ?></td>
                <td>
                    <form class="form-inline" style="margin:0" method="post" action="<?=$this->escapeHtmlAttr($this->deleteUrl)?>">
                        <input type="hidden" name="ip" value="<?=$this->escapeHtmlAttr($row['ip'])?>" />
                        <button type="submit" class="btn btn-xs btn-danger">
                            <i class="fa fa-times"></i>
                        </button>
                    </form>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>