<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => false,
        'needRight' => false
    ));

    if (($current = $this->paginator->getCurrentPageNumber()) < $this->paginator->count() ) {
        $this->headLink(array(
            'rel'  => 'prefetch',
            'href' => $this->url(array(
                'page' => $this->paginator->getCurrentPageNumber()+1
            ), 'new', true)
        ));
        $this->headLink(array(
            'rel'  => 'prerender',
            'href' => $this->url(array(
                'page' => $this->paginator->getCurrentPageNumber()+1
            ), 'new', true)
        ));
    }
?>
<div class="row">
    <div class="col-lg-4">
        <h3 style="text-align:left"><?php if ($this->prevDate) { ?>
            &#x2190;
            <?=$this->htmlA($this->url(array(
                'date' => $this->prevDate->toString($this->urlDateFormat)
            ), 'new', true, true), $this->humanDate($this->prevDate)) ?>
            <small>(<?=$this->translate(array('%1$s picures', null, $this->prevCount), $this->prevCount);?>)</small>
        <?php } ?></h3>
    </div>
    <div class="col-lg-4">
        <h3 style="text-align:center">
            <?=$this->humanDate($this->date)?>
            <small>(<?=$this->translate(array('%1$s picures', null, $this->count), $this->count);?>)</small>
        </h3>
    </div>
    <div class="col-lg-4">
        <h3 style="text-align:right"><?php if ($this->nextDate) { ?>
            <?=$this->htmlA($this->url(array(
                'date' => $this->nextDate->toString($this->urlDateFormat)
            ), 'new', true, true), $this->humanDate($this->nextDate)) ?>
            <small>(<?=$this->translate(array('%1$s picures', null, $this->nextCount), $this->nextCount);?>)</small>
            &#x2192;
        <?php } ?></h3>
    </div>
</div>
<?=$this->pictures($this->paginator->getCurrentItems(), array(
    'scheme' => '631'
)) ?>
<?=$this->paginationControl($this->paginator) ?>
