<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageTitle' => $this->title,
        'pageId' => 23,
        'args'   => array(
            'CATEGORY_SHORT_NAME' => $this->categoryLang ? $this->categoryLang->short_name : $this->category->short_name,
            'CATEGORY_NAME'       => $this->categoryLang ? $this->categoryLang->name : $this->category->name,
            'CATEGORY_CATNAME'    => $this->category->catname
        ),
        'breadcrumbsReplace' => array(
            'pageId'      => 23,
            'breadcrumbs' => $this->breadcrumbs
        )
    ));
?>
<div class="row">
    <div class="col-lg-4 col-md-4">
        <div class="well nav-tree">
            <?=$this->partial('category/menu.phtml', array(
                'categories' => $this->categories,
                'category'   => $this->category,
                'isOther'    => $this->isOther,
                'deep'       => 1
            ))?>
        </div>
    </div>
    <div class="col-lg-8 col-md-8">
        <?=$this->partial('cars.phtml', $this->listData)?>
        <?=$this->paginationControl($this->paginator) ?>

        <?php if (count($this->contributors)) { ?>
            <p>
                Составители:
                <?php foreach ($this->contributors as $contributor) { ?>
                    <?=$this->user($contributor)?>
                <?php } ?>
            </p>
        <?php } ?>
    </div>
</div>