<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => false,
        'needRight' => false
    ));
    $this->page(22)->initPage();

    $categoryName = $this->categoryLang ? $this->categoryLang->name : $this->category->name;
    $this->headTitle($categoryName, 'SET');
    $this->pageTitle($categoryName, 'SET');
    $this->breadcrumbs(
        $this->url(array(
            'category_catname' => $this->category->catname
        ), 'category'),
        $this->categoryLang ? $this->categoryLang->short_name : $this->category->short_name
    );
?>
<div class="row">
    <div class="col-lg-4">
        <div class="well nav-tree">
            <?=$this->partial('category/menu.phtml', array(
                'categories' => $this->categories,
                'category'   => $this->category,
                'isOther'    => $this->isOther,
                'deep'       => 1
            ))?>
        </div>
    </div>
    <div class="col-lg-8">
        <?=$this->cars($this->paginator->getCurrentItems()) ?>
        <?=$this->paginationControl($this->paginator) ?>

        <?php if (count($this->contributors)) { ?>
            <p>
                Составители:
                <?php foreach ($this->contributors as $contributor) { ?>
                    <?=$this->user($contributor)?>
                <?php } ?>
            </p>
        <?php } ?>
    </div>
</div>