<ul class="nav nav-list">
	<?php foreach ($this->categories as $category) { ?>
		<li<?=$category['active'] ? ' class="active"' : '' ?>>
			<?=$this->htmlA(
				$category['url'], 
				$this->escape($category['short_name']) . 
					'&#xa0;<span class="count">('.($category['cars_count'] - $category['new_cars_count']) . ($category['new_cars_count'] > 0 ? '<span>+'.$category['new_cars_count'].'</span>' : '') .')</span>', 
				false
			)?>
			<?php if (isset($category['categories']) && $category['categories'] && $category['active']) { ?>
				<?=$this->partial('category/menu.phtml', array(
					'categories'	=>	$category['categories'],
					'category'		=>	$this->category,
					'isOther'		=>	$this->isOther
				))?>
			<?php } ?>
		</li>
	<?php } ?>
</ul>