<div data-module="comments" data-comments-item-id="<?=$this->itemId?>" data-comments-type="<?=$this->type?>" class="comments">
    <?php if (count($this->comments)) { ?>
        <h2><?=$this->escapeHtml($this->translate('comments/title'))?></h2>
        <?=$this->partial('application/comments/messages', [
            'messages'          => $this->comments,
            'canRemoveComments' => $this->canRemoveComments,
            'canAddComments'    => $this->canAddComments,
            'canViewIp'         => $this->user()->isAllowed('user', 'ip'),
            'canMoveMessage'    => false,
            'moveMessageUrl'    => $this->moveMessageUrl,
            'moveMessageRoute'  => $this->moveMessageRoute
        ])?>
    <?php } ?>

    <?php if ($this->canAddComments) { ?>
        <div class="form-holder">
            <?=$this->partial('application/forms/comment', [
                'form' => $this->form
            ])?>
        </div>
    <?php } else { ?>
        <p class="alert alert-block alert-info">
            <?=$this->markdown($this->translate('comments/what-to-do-for-write-comments'))?>
        </p>
    <?php } ?>
</div>