<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => true
        ],
        'pageId' => 105,
    ]);
?>

<?=$this->markdown(sprintf($this->translate('comments/need-wait-text'), $this->nextMessageTime))?>

<h2><?=$this->escape($this->translate('comments/form-title'))?></h2>
<?=$this->partial('application/forms/comment', [
    'form' => $this->form
])?>