<?php
    $isModer = $this->user()->inheritsRole('moder');

    $deep = isset($this->deep) ? $this->deep : 1;
?>
<?php foreach ($this->messages as $comment) { ?>
    <?php
        $moderAttention = $comment['moderator_attention'] == Autowp\Comments\Attention::REQUIRED;
        $classes = ['message'];
        if ($moderAttention) {
            $classes[] = 'moderator-attention';
        }
        if ($comment['deleted']) {
            $classes[] = 'deleted';
        }
    ?>
    <div class="<?=implode(' ', $classes)?>" data-id="<?=(int)$comment['id']?>" id="msg<?=(int)$comment['id']?>">
        <div>
            <?php if ($comment['datetime']) { ?>
                <div class="float-right">
                    <?=$this->pastTimeIndicator($comment['datetime']);?>
                </div>
            <?php } ?>
            <?=$comment['author'] ? $this->user($comment['author']) : $this->escapeHtml($this->translate('comments/author/anonymous'))?>
        </div>
        <div class="photo">
            <?php if ($comment['author'] && !$comment['author']['deleted']) { ?>
                <?=$this->htmlA([
                    'href'  => $this->url('ng', ['path' => '']) . 'users/' . ($comment['author']['identity'] ? $comment['author']['identity'] : 'user' . $comment['author']['id']),
                    'class' => 'photo'
                ], $this->user($comment['author'])->avatar(), false) ?>
            <?php } ?>
        </div>
        <div class="content">

            <?php if ($this->canRemoveComments || !$comment['deleted']) { ?>
                <div class="text">
                    <?=$this->userText($comment['message']) ?>
                </div>
            <?php } ?>

            <?php if ($this->canRemoveComments || $comment['deleted']) { ?>
                <p class="alert alert-warning deleted-message">
                    <?=$this->escapeHtml($this->translate('comments/message-deleted-by-admin'))?>
                </p>
            <?php } ?>

            <div>
                <span class="vote" data-id="<?=$comment['id']?>">
                    <?php if ($this->user()->logedIn()) { ?>
                        <?=$this->htmlA([
                            'href'  => '#',
                            'class' => 'vote-up' . ($comment['userVote'] > 0 ? ' active' : '')
                        ], '<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>', false)?>
                        <?=$this->htmlA([
                            'href'  => '#',
                            'class' => 'value' . ($comment['vote'] == 0 ? ' zero' : '')
                        ], ($comment['vote'] > 0 ? '+' : '') . $comment['vote'])?>
                        <?=$this->htmlA([
                            'href'  => '#',
                            'class' => 'vote-down' . ($comment['userVote'] < 0 ? ' active' : '')
                        ], '<i class="fa fa-thumbs-o-down" aria-hidden="true"></i>', false)?>
                    <?php } else { ?>
                        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                        <span class="value"><?=$comment['vote'] ?></span>
                        <i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
                    <?php } ?>
                </span>

                <?php if ($this->user()->logedIn() && $deep < 21) { ?>
                    <button class="btn btn-sm btn-primary reply">
                        <i class="fa fa-reply" aria-hidden="true"></i>
                        <span class="d-none d-md-inline">
                            <?=$this->escapeHtml($this->translate('comments/reply'))?>
                        </span>
                    </button>
                <?php } ?>

                <?php if ($moderAttention && $isModer) { ?>
                    <button class="btn btn-sm btn-success resolve">
                        <i class="fa fa-reply" aria-hidden="true"></i>
                        <?=$this->escapeHtml($this->translate('comments/reply'))?> &amp; resolve
                    </button>
                <?php } ?>

                <?php if ($this->canRemoveComments) { ?>
                    <?=$this->htmlA([
                        'href'  => '#',
                        'class' => 'btn btn-danger btn-sm float-right comment-remove-button',
                    ], '<i class="fa fa-trash" aria-hidden="true"></i></span> <span class="d-none d-md-inline">' . $this->escapeHtml($this->translate('comments/message/delete')) . '</span>', false) ?>
                    <?=$this->htmlA([
                        'href'  => '#',
                        'class' => 'btn btn-success btn-sm float-right comment-restore-button',
                    ], '<i class="fa fa-arrow-up" aria-hidden="true"></i> ' . $this->escapeHtml($this->translate('comments/message/restore')), false) ?>
                <?php } ?>

                <?php if ($this->canMoveMessage) { ?>
                    <?=$this->htmlA([
                        'href'  => $this->url($this->moveMessageRoute, array_replace($this->moveMessageUrl, [
                            'id' => $comment['id']
                        ])),
                        'class' => 'btn btn-secondary btn-sm float-right',
                    ], '<i class="fa fa-arrows" aria-hidden="true"></i> ' . $this->escapeHtml($this->translate('comments/message/move')), false) ?>
                <?php } ?>

                <?php if ($this->canViewIp && $comment['ip']) { ?>
                    <i class="float-right fa fa-eye" data-toggle="tooltip" title="<?=$comment['ip'] ?>" style="margin-right:20px" aria-hidden="true"></i>
                <?php } ?>

                <?php if ($moderAttention) { ?>
                    <div class="moderator-attention-sign">
                        <i class="fa fa-info-circle" aria-hidden="true"></i>
                        <?=$this->escapeHtml($this->translate('comments/it-requires-attention-of-moderators'))?>
                    </div>
                <?php } ?>

            </div>
        </div>
        <?php if ($deep < 21) { ?>
            <div class="replies">
                <?=$this->partial('application/comments/messages', [
                    'messages'          => $comment['messages'],
                    'canRemoveComments' => $this->canRemoveComments,
                    'canAddComments'    => $this->canAddComments,
                    'canViewIp'         => $this->canViewIp,
                    'canMoveMessage'    => $this->canMoveMessage,
                    'moveMessageUrl'    => $this->moveMessageUrl,
                    'moveMessageRoute'  => $this->moveMessageRoute,
                    'deep'              => $deep + 1
                ])?>
            </div>
        <?php } ?>
    </div>
<?php } ?>
