<?php
    $this->form->setAttribute(
        'class',
        $this->form->getAttribute('class') . ' form-horizontal'
    );
?>
<?=$this->form()->openTag($this->form)?>
<fieldset>
    <?php if ($legend = $this->form->getAttribute('legend')) { ?>
        <legend><?=$this->escapeHtml($this->translate($legend))?></legend>
    <?php } ?>
    <?=$this->partial('application/forms/bootstrap-horizontal-elements', [
        'form' => $this->form
    ])?>
    <?php
        $submitFound = false;
    ?>
    <?php foreach ($this->form->getElements() as $element) { ?>
        <?php if ($element instanceof Zend\Form\Element\Submit) { ?>
            <?php
                $element->setAttribute(
                    'class',
                    $element->getAttribute('class') . ($element->getAttribute('class') ? ' ' : '') . 'btn'
                );
                if (!$submitFound) {
                    $element->setAttribute(
                        'class',
                        $element->getAttribute('class') . ' btn-primary'
                    );
                    $submitFound = true;
                }
            ?>
            <div class="form-group">
                <div class="col-md-2"></div>
                <div class="col-md-10">
                    <?=$this->formElement($element)?>
                </div>
            </div>
        <?php } ?>
    <?php } ?>
    <?php /* if ($desc = $this->element->getDescription()) { ?>
        <p><?=$this->escapeHtml($desc)?></p>
    <?php } */ ?>
    <?php if (!$submitFound && !$this->element instanceof Zend\Form\SubForm) { ?>
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <?=$this->formElement(
                    (new Zend\Form\Element\Submit('submit'))
                        ->setAttribute('class', 'btn btn-primary')
                        ->setValue($this->translate('sumbit'))
                )?>
            </div>
        </div>
    <?php } ?>
</fieldset>
<?=$this->form()->closeTag($this->form)?>