<?php foreach ($this->form->getIterator() as $element) { ?>
    <?php if ($element instanceof Zend\Form\Element\File) { ?>
        <?=$this->formElement(
            $element
                ->setAttribute('class', $element->getAttribute('class') . ' form-control')
        )?>
        <?php foreach ($element->getMessages() as $error) { ?>
            <p class="help-block"><?=$this->escapeHtml($error)?></p>
        <?php } ?>
    <?php } elseif ($element instanceof Zend\Form\Element\Multicheckbox) { ?>
        <?=$this->formElement($element)?>
        <?php foreach ($element->getMessages() as $error) { ?>
            <p class="help-block"><?=$this->escapeHtml($error)?></p>
        <?php } ?>
    <?php } elseif ($element instanceof Zend\Form\Element\Checkbox) { ?>
        <div class="checkbox<?=$element->getMessages() ? ' has-error' : ''?>">
            <label>
                <?=$this->formElement($element)?>
                <?=$this->escapeHtml($this->translate($element->getLabel()))?>
            </label>
            <?php foreach ($element->getMessages() as $error) { ?>
                <p class="help-block"><?=$this->escapeHtml($error)?></p>
            <?php } ?>
        </div>
    <?php } elseif ($element instanceof Zend\Form\Element\Hidden) { ?>
        <?=$this->formElement($element)?>
    <?php } elseif (!$element instanceof Zend\Form\Element\Submit) { ?>
        <?=$this->formElement(
            $element
                ->setAttribute('class', $element->getAttribute('class') . ' form-control')
        )?>
        <?php foreach ($element->getMessages() as $error) { ?>
            <p class="help-block"><?=$this->escapeHtml($error)?></p>
        <?php } ?>
    <?php } ?>
<?php } ?>