<?php
    $this->form->setAttribute(
        'class',
        $this->form->getAttribute('class') . ' form-horizontal'
    );
?>
<?=$this->form()->openTag($this->form)?>
<fieldset>
    <?php if ($legend = $this->form->getAttribute('legend')) { ?>
        <legend><?=$this->escapeHtml($this->translate($legend))?></legend>
    <?php } ?>
    <?php foreach ($this->form->getElements() as $element) { ?>
        <?php
            $errors = $element->getMessages();
        ?>
        <div class="form-group<?=$errors ? ' has-error' : ''?>">
            <?php if ($element instanceof Zend\Form\Element\Checkbox) { ?>
                <div class="col-md-offset-3 col-md-9">
                    <div class="checkbox">
                        <label>
                            <?=$this->formElement($element)?>
                            <?=$this->escapeHtml($this->translate($element->getLabel()))?>
                        </label>
                    </div>
                    <?php foreach ($errors as $error) { ?>
                        <p class="help-block"><?=$this->escapeHtml($error)?></p>
                    <?php } ?>
                </div>
            <?php } else { ?>
                <label class="col-md-3 control-label">
                    <?=$this->escapeHtml($this->translate($element->getLabel()))?>
                </label>
                <div class="col-md-9">
                    <?=$this->formElement(
                        $element->setAttribute('class', $element->getAttribute('class') . ' form-control')
                    )?>
                    <?php foreach ($errors as $error) { ?>
                        <p class="help-block"><?=$this->escapeHtml($error)?></p>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
    <div class="form-group">
        <div class="col-md-9 col-md-offset-3">
            <button type="submit" class="btn btn-primary">
                <i class="fa fa-sign-in"></i>
                <?=$this->escapeHtml($this->translate('login/sign-in'))?>
            </button>
        </div>
    </div>
</fieldset>
<?=$this->form()->closeTag($this->form)?>