<?=$this->form()->openTag($this->form)?>
<?=$this->markdown($this->translate('moder/markdown/description'))?>
<?php foreach ($this->form->getElements() as $element) { ?>
    <div data-module="markdown-edit-tabbar">
        <ul id="myTabs-markdown" class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#markdown-edit" id="markdown-tab" role="tab" data-toggle="tab" aria-expanded="true" aria-controls="edit">
                    <?=$this->escapeHtml($this->translate('moder/markdown/edit'))?>
                </a>
            </li>
            <li role="presentation">
                <a href="#markdown-preview" class="tab-preview" id="markdown-tab" role="tab" data-toggle="tab" aria-expanded="false" aria-controls="preview">
                    <?=$this->escapeHtml($this->translate('moder/markdown/preview'))?>
                </a>
            </li>
        </ul>
        <div id="myTabContent" class="tab-content">
            <div role="tabpanel" class="tab-pane fade active in" id="markdown-edit" aria-labelledby="edit-tab">
                <div class="form-group<?=$element->getMessages() ? ' has-error' : ''?>">
                    <?=$this->formElement(
                        $element->setAttribute('class', $element->getAttribute('class') . ' form-control')
                    )?>
                    <?php foreach ($element->getMessages() as $error) { ?>
                        <p class="help-block"><?=$this->escapeHtml($error)?></p>
                    <?php } ?>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane tab-pane-preview fade" id="markdown-preview" aria-labelledby="preview-tab" style="padding:7px 13px">

            </div>
        </div>
    </div>
<?php } ?>
<input type="submit" class="btn btn-primary" value="<?=$this->escapeHtmlAttr($this->translate('submit'))?>">
<?=$this->form()->closeTag($this->form)?>