<?php if (count($this->attributes)) { ?>
    <ul>
        <?php foreach ($this->attributes as $attribute) { ?>
            <li>
                <label>
                    <?=$this->formCheckbox('attribute_id[]', $this->zone->hasAttribute($attribute) ? $attribute->id : '', array(
                        'id'    =>  'attribute_id_' . $attribute->id
                    ), array($attribute->id, '')) ?>
                    <?=$this->escape($attribute->name) ?>
                </label>
                <?=$this->partial('attrs/zone/attributes-list-partial.phtml', array(
                    'attributes'    =>  $attribute->getTable()->fetchAll(
                        $attribute->getTable()->select()
                            ->where('parent_id = ?', $attribute->id)
                    ),
                    'zone'          =>  $this->zone,
                )) ?>
            </li>
        <?php } ?>
    </ul>
<?php } ?>