<h4>
    <?=$this->escape($this->translate('index/brands'))?>
    <small><?=$this->htmlA($this->url(array(
        'controller' => 'brands',
        'action'     => 'index',
    ), 'default', true), $this->translate('all-link'))?></small>
</h4>
<?php
    $items = array();
    foreach ($this->brands as $brand) {
        $items[] =  $this->htmlA($brand['url'], $brand['name']) .
                    '&#xa0;<span class="count">('.
                        ($brand['cars_count'] - $brand['new_cars_count']).
                        ($brand['new_cars_count'] > 0
                            ?
                                $this->htmlA(array(
                                    'class' => 'popover-handler',
                                    'title' => sprintf($this->translate('brands/new-cars-of-brand'), $brand['name']), //$brand['new_cars_title'],
                                    'href'  => $brand['new_cars_url']
                                ), '+'.$brand['new_cars_count'])
                            : ''
                        ).
                    ')</span>';
    }
?>
<p style="font-size:18px">
    <?=implode(' ', $items) ?>
    <?php if (($more = $this->totalBrands - count($this->brands)) > 0) { ?>
        …&#xa0;<?=$this->escape($this->translate('and'))?>&#xa0;<?=$this->htmlA(
            $this->url(array(
                'controller' => 'brands',
                'action'     => 'index',
            ), 'default', true),
            $this->translate(array('brands/more-companies', null, $more), $more)
        )?>
    <?php } ?>
</p>