<?php foreach ($this->picturesGroups as $n => &$group) { ?>
    <?=$this->headerBlock($group['caption']) ?>
    <div id="picturesgroup<?=$n ?>">
        <?=$this->pictureList($group['pictureList'], 2) ?>
    </div>
    <table style="width:100%"><tr>
        <td style="text-align:left">
            <span id="picturesgroup_prev_<?=$n?>" class="picturesgroup_prev page1">← <?=$this->translate('forward') ?></span>
        </td>
        <td style="text-align:right">
            <span id="picturesgroup_next_<?=$n?>" class="picturesgroup_next page1"><?=$this->translate('back') ?> →</span>
        </td>
    </tr></table>
    <?php if ($n == 1) { ?>
        <p style="text-align:right;margin-bottom:10px">
            <?=$this->htmlA($this->url(array(
                'module' => 'default',
                'controller' => 'new',
                'action'    => 'index'
            ), 'new', true), $this->translate('All new pictures') . ' …') ?>
        </p>
    <?php } ?>
<?php } ?>