<?php
    $cols = 2;
    $items = count($this->items);
    $rows = ceil($items / $cols);
?>
<?php for ($i=0; $i<$rows; $i++) { ?>
    <div class="row">
        <?php foreach (array_slice($this->items, $i*$rows, $cols) as $item) { ?>
            <div class="col-md-6">
                <div class="car" style="margin-bottom: 2em">

                    <h3>
                        <?=$this->car($item['row'])->title()?>
                        <?php if ($item['designProject']) { ?>
                            <sup class="designBrand"><?=sprintf($this->translate('carlist/designed by %s'), $this->htmlA($item['designProject']['url'], $item['designProject']['brandName']))?></sup>
                        <?php } ?>
                    </h3>

                    <div class="row thumbnails">
                        <?php foreach ($item['pictures'] as $picture) { ?>
                            <div class="col-sm-4">
                                <?php if ($picture) { ?>
                                    <?=$this->htmlA(
                                        array(
                                            'href'  => $picture['url'],
                                            'class' =>'thumbnail'
                                        ),
                                        $this->htmlImg(array(
                                            'src'   => $picture['src'],
                                            'alt'   => $picture['name'],
                                            'title' => $picture['name'],
                                        )),
                                        false
                                    )?>
                                <?php } else { ?>
                                    <div class="no-photo">&#xa0;</div>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>


                    <ul class="list-inline">

                        <?php if (!$this->disableDetailsLink && ($item['hasHtml'] || $item['childsCount']) && isset($item['details']['url'])) { ?>
                            <li>
                                <i class="fa fa-align-left"></i>
                                <?=$this->htmlA($item['details']['url'], $this->translate('carlist/details') . ( $item['childsCount'] > 1 ? ' (' . $item['childsCount'] . ')' : '')) ?>
                            </li>
                        <?php } ?>

                        <?php if (isset($item['tuning']) && $item['tuning']) { ?>
                            <li>
                                <i class="fa fa-align-left"></i>
                                <?=$this->htmlA($item['tuning']['url'], $this->translate('catalogue/related') . ' ('.$item['tuning']['count'].')')?>
                            </li>
                        <?php } ?>

                        <?php if (isset($item['sport']) && $item['sport']) { ?>
                            <li>
                                <i class="fa fa-align-left"></i>
                                <?=$this->htmlA($item['sport']['url'], 'Спорт ('.$item['sport']['count'].')')?>
                            </li>
                        <?php } ?>

                        <?php if (isset($item['allPicturesUrl']) && $item['allPicturesUrl']) { ?>
                            <li>
                                <span class="fa fa-th"></span>
                                <?=$this->htmlA($item['allPicturesUrl'], $this->translate('carlist/all pictures').' ('.$item['totalPictures'].')')?>
                            </li>
                        <?php } ?>

                        <?php if (count($item['specsLinks']) > 1) { ?>
                            <li>
                                <i class="fa fa-list-alt"></i>
                                <?=$this->escape($this->translate('carlist/specifications'))?>
                                <?php foreach ($item['specsLinks'] as $specLink) { ?>
                                    <?=$this->htmlA($specLink['url'], $specLink['name'])?>
                                <?php } ?>
                            </li>
                        <?php } else { ?>
                            <?php foreach ($item['specsLinks'] as $specLink) { ?>
                                <li>
                                    <i class="fa fa-list-alt"></i>
                                    <?=$this->htmlA($specLink['url'], $this->translate('carlist/specifications'))?>
                                </li>
                            <?php } ?>
                        <?php } ?>

                        <?php if (isset($item['twinsGroups'])) { ?>
                            <?php foreach ($item['twinsGroups'] as $twinsGroup) { ?>
                                <li>
                                    <i class="fa fa-adjust"></i>
                                    <?=$this->htmlA($twinsGroup['url'], $this->translate('carlist/twins')) ?>
                                </li>
                            <?php } ?>
                        <?php } ?>

                        <?php foreach ($item['categories'] as $category) { ?>
                            <li>
                                <i class="fa fa-tag"></i>
                                <?=$this->htmlA($category['url'], $category['name'])?>
                            </li>
                        <?php } ?>

                        <?php if ($this->isCarModer) { ?>
                            <li>
                                <i class="fa fa-cog"></i>
                                <?=$this->htmlA($item['moderUrl'], 'управление') ?>
                            </li>
                        <?php } ?>

                        <?php if ($this->specEditor) { ?>
                            <li>
                                <i class="fa fa-pencil"></i>
                                <?=$this->htmlA($item['specEditorUrl'], $this->translate('carlist/edit-specs')) ?>
                            </li>
                        <?php } ?>
                    </ul>

                    <?php if (count($item['contributors'])) { ?>
                        <p>
                            <?=$this->escape($this->translate(count($item['contributors']) > 1 ? 'contributors' : 'contributor'))?>:
                            <?php foreach ($item['contributors'] as $contributor) { ?>
                                <?=$this->user($contributor)?>
                            <?php } ?>
                        </p>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>