<?php if ($this->pageCount > 1) { ?>
    <?php
        $format = '%0'.max(2, strlen($this->pageCount)).'d';
        $urlParams = isset($this->urlParams) ? $this->urlParams : [];
        $route = isset($this->route) ? $this->route : null;
        $reuse = !isset($this->urlParams);
    ?>
    <div>
        <p>
            <?php if (isset($this->previous)) { ?>
                <?=$this->htmlA(
                    $this->url(
                        $route,
                        array_replace($urlParams, ['page' => $this->previous]),
                        null,
                        $reuse
                    ),
                    '←' . $this->translate('previous')
                )?>
            <?php } else { ?>
                ←<?=$this->escapeHtml($this->translate('previous')) ?>
            <?php } ?>

            <?php if (isset($this->next)) { ?>
                <?=$this->htmlA(
                    $this->url(
                        $route,
                        array_replace($urlParams, ['page' => $this->next]),
                        null,
                        $reuse
                    ),
                    $this->translate('next').'→'
                )?>
            <?php } else { ?>
                <?=$this->escapeHtml($this->translate('next')) ?>→
            <?php } ?>
        </p>
        <p>
            <?php if ($this->first < $this->firstPageInRange) { ?>
                <?=$this->htmlA(
                    $this->url(
                        $route,
                        array_replace($urlParams, ['page' => $this->first]),
                        null,
                        $reuse
                    ),
                    sprintf($format, $this->first)
                )?>
                <?php if ($this->first < $this->firstPageInRange - 1) { ?>…<?php } ?>
            <?php } ?>
            <?php foreach ($this->pagesInRange as $page) { ?>
                <?php if ($page != $this->current) { ?>
                    <?=$this->htmlA(
                        $this->url(
                            $route,
                            array_replace($urlParams, ['page' => $page]),
                            null,
                            $reuse
                        ),
                        sprintf($format, $page)
                    )?>
                <?php } else { ?>
                    <strong style="font-size:20px;margin:0 3px"><?=sprintf($format, $page) ?></strong>
                <?php } ?>
            <?php } ?>
            <?php if ($this->last > $this->lastPageInRange) { ?>
                <?php if ($this->last > $this->lastPageInRange + 1) { ?>…<?php } ?>
                <?=$this->htmlA(
                    $this->url(
                        $route,
                        array_replace($urlParams, ['page' => $this->last]),
                        null,
                        $reuse
                    ),
                    sprintf($format, $this->last)
                )?>
            <?php } ?>
        </p>
    </div>
<?php } ?>