<?php if ($this->items) { ?>
    <div id="moderatorMenuContainer" style="z-index:100">
        <div class="btn-group dropup" >
            <button data-toggle="dropdown" class="btn btn-default dropdown-toggle">Меню&#xa0;модератора <span class="caret"></span></button>
            <ul class="dropdown-menu pull-right">
                <?php foreach ($this->items as $item) { ?>
                    <li><?=$this->htmlA(
                        $item['href'],
                        (isset($item['icon']) ? '<i class="fa-fw '.$item['icon'].'"></i> ' : '') . $this->escape($item['label']) . (isset($item['count']) ? ' <span class="badge">'.$item['count'].'</span>' : ''),
                        false
                    ) ?></li>
                <?php } ?>
                <li class="divider"></li>
                <li><a href="/moder/"><i class="fa fa-cog"></i> Страница&#xa0;модератора</a></li>
            </ul>
        </div>
    </div>
<?php } ?>