<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Body</th>
            <th>Type</th>
            <th>Count</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->rows as $row) { ?>
            <tr>
                <td><?=$this->escape($row['id'])?></td>
                <td><?=$this->htmlA($this->url(array(
                    'controller' => 'cars',
                    'action'     => 'car',
                    'car_id'     => $row['id']
                )), $row['caption'])?></td>
                <td><?=$this->escape($row['body'])?></td>
                <td><?=$this->escape($row['t'])?></td>
                <td><?=$this->escape($row['c'])?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>