<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 134,
    ));
?>
<div class="row">
    <div class="col-lg-8 col-offset-2">
        <div class="well">
            <p>Введите новый пароль</p>
            <?=$this->form->render($this) ?>
        </div>
    </div>
</div>