<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => true
        ),
        'pageId' => 135,
    ));
?>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
        <div class="well">
            <p>Новый пароль успешно сохранён.</p>
            <p>Не забывайте его</p>
        </div>
    </div>
</div>