<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 67,
    ]);
?>
<div class="row">
    <div class="col-md-6">
        <?php if ($this->user()->inheritsRole('cars-moder')) { ?>
            <h3><?=$this->escapeHtml($this->page(131)->name)?></h3>
            <div class="well">
                <ul class="list-unstyled">
                    <li>
                        <i class="fa fa-align-left"></i>
                        <?=$this->htmlA($this->url('moder/cars'), $this->page(131)->name)?>
                    </li>

                    <li>
                        <i class="fa fa-sort-alpha-asc"></i>
                        <?=$this->htmlA($this->url('moder/cars', [
                            'action' => 'alpha'
                        ]), $this->page(74)->name)?>
                    </li>

                    <?php if ($this->user()->isAllowed('car', 'add')) { ?>
                        <li>
                            <i class="fa fa-plus"></i>
                            <?=$this->htmlA($this->url('moder/cars/params', [
                                'action'       => 'new',
                                'item_type_id' => Application\Model\DbTable\Item\Type::VEHICLE
                            ]), $this->translate('item/type/1/new-item'))?>
                        </li>
                        <li>
                            <i class="fa fa-plus"></i>
                            <?=$this->htmlA($this->url('moder/cars/params', [
                                'action'       => 'new',
                                'item_type_id' => Application\Model\DbTable\Item\Type::ENGINE
                            ]), $this->translate('item/type/2/new-item'))?>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        <?php } ?>
        
        <h3><?=$this->escapeHtml($this->page(175)->name)?></h3>
        <div class="well">
            <ul class="list-unstyled">
                <li>
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($this->url('moder/factories'), $this->page(175)->name)?>
                </li>
                <?php if ($this->user()->isAllowed('factory', 'add')) { ?>
                    <li>
                        <i class="fa fa-plus"></i>
                        <?=$this->htmlA($this->url('moder/factories', [
                            'action' => 'add',
                        ]), $this->page(176)->name)?>
                    </li>
                <?php } ?>
            </ul>
        </div>
        
        <h3>Task list</h3>
        <ul>
            <li>
                Accept/remove <a href="/moder/pictures/index/status/new/">old style moderation-less pictures</a>
            </li>
            <li>
                <a href="/moder/cars/index/name/4x2/no_parent/0/order/1">4x2 to 4×2</a>,
                <a href="/moder/cars/index/name/6x2/no_parent/0/order/1">6x2 to 6×2</a>,
                etc
            </li>
            <li>
                "<a href="/moder/pictures/index/status/custom1/type_id/3">Mixed</a>" to pictures with few cars
            </li>
            <li>
                Split <a href="/moder/index/too-big-cars">too big cars</a>
            </li>
            <li>
                Move years to model years in North America
            </li>
            <li>
                Dash in soviet vehicle names, e.g <a href="/moder/cars/index/name/%D0%92%D0%90%D0%97/no_name/%D0%92%D0%90%D0%97-/no_parent/0/order/1">ВАЗ</a>
            </li>
            <li>
                Missed type in sidebar menu of <a href="/moder/cars/index/vehicle_type_id/empty/vehicle_childs_type_id/17/">Trucks</a>
                and <a href="/moder/cars/index/vehicle_type_id/empty/vehicle_childs_type_id/19/">Buses</a>
            </li>
        </ul>
    </div>
    <div class="col-md-6">
        <?php if ($this->addBrandForm) { ?>
            <div class="well">
                <?=$this->partial('application/forms/bootstrap-horizontal', [
                    'form' => $this->addBrandForm
                ])?>
            </div>
        <?php } ?>
        <h2><?=$this->escapeHtml($this->translate('moder/index/other-tools'))?></h2>
        <div class="well">
            <?php foreach ($this->menu as $url => $name) { ?>
                <?=$this->htmlA($url, $this->translate($name)) ?>
                <br />
            <?php } ?>
        </div>
    </div>
</div>