<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 67,
    ]);
?>
<div class="row">
    <div class="col-md-6">
        <?php if ($this->user()->inheritsRole('cars-moder')) { ?>
            <h3><?=$this->escapeHtml($this->page(131)->name)?></h3>
            <div class="well">
                <ul class="list-unstyled">
                    <li>
                        <i class="fa fa-align-left"></i>
                        <?=$this->htmlA($this->url('moder/cars'), $this->page(131)->name)?>
                    </li>

                    <li>
                        <i class="fa fa-sort-alpha-asc"></i>
                        <?=$this->htmlA($this->url('moder/cars', [
                            'action' => 'alpha'
                        ]), $this->page(74)->name)?>
                    </li>

                    <?php if ($this->user()->isAllowed('car', 'add')) { ?>
                        <li>
                            <i class="fa fa-plus"></i>
                            <?=$this->htmlA($this->url('moder/cars', [
                                'action' => 'new',
                            ]), $this->page(163)->name)?>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        <?php } ?>
        <h3><?=$this->escapeHtml($this->page(82)->name)?></h3>
        <div class="well">
            <ul class="list-unstyled">
                <li>
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($this->url('moder/engines'), $this->page(82)->name)?>
                </li>
                <?php if ($this->user()->isAllowed('engine', 'add')) { ?>
                    <li>
                        <i class="fa fa-plus"></i>
                        <?=$this->htmlA($this->url('moder/engines', [
                            'action' => 'add',
                        ]), $this->page(170)->name)?>
                    </li>
                <?php } ?>
            </ul>
        </div>
        <h3><?=$this->escapeHtml($this->page(175)->name)?></h3>
        <div class="well">
            <ul class="list-unstyled">
                <li>
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($this->url('moder/factories'), $this->page(175)->name)?>
                </li>
                <?php if ($this->user()->isAllowed('factory', 'add')) { ?>
                    <li>
                        <i class="fa fa-plus"></i>
                        <?=$this->htmlA($this->url('moder/factories', [
                            'action' => 'add',
                        ]), $this->page(176)->name)?>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>
    <div class="col-md-6">
        <?php if ($this->addBrandForm) { ?>
            <div class="well">
                <?=$this->partial('application/forms/bootstrap-horizontal', [
                    'form' => $this->addBrandForm
                ])?>
            </div>
        <?php } ?>
        <h2>Другие инструменты</h2>
        <div class="well">
            <?php foreach ($this->menu as $url => $name) { ?>
                <?=$this->htmlA($url, $this->translate($name)) ?>
                <br />
            <?php } ?>
        </div>
    </div>
</div>