<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Body</th>
            <th>Type</th>
            <th>Count</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->rows as $row) { ?>
            <tr>
                <td><?=$this->escapeHtml($row['id'])?></td>
                <td><?=$this->htmlA($this->url('moder/cars/params', [
                    'action'  => 'car',
                    'item_id' => $row['id']
                ]), $row['name'])?></td>
                <td><?=$this->escapeHtml($row['body'])?></td>
                <td><?=$this->escapeHtml($row['t'])?></td>
                <td><?=$this->escapeHtml($row['c'])?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>