<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 125,
    ]);
?>
<?=$this->htmlA([
    'class' => 'btn btn-success',
    'href' => $this->url(null, [
        'action' => 'item'
    ])
], $this->translate('moder/categories/new'))?>

<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>N</th>
            <th><?=$this->escapeHtml($this->translate('category/name'))?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?=$this->partial('application/moder/category/list', [
            'items' => $this->categories,
            'level' => 0
        ])?>
    </tbody>
</table>