<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ],
        'pageId' => $this->category->id ? 126 : 127,
    ]);
?>
<div class="well">
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->form
    ])?>
</div>