<?php foreach ($this->items as $page) { ?>
    <tr class="data-row">
        <td><?=$page['id'] ?></td>
        <td style="padding-left:<?=$this->level*20?>px"><?=$this->escapeHtmlAttr($page['name']) ?></td>
        <td>
            <div class="btn-group">
                <?php if ($this->canEdit) { ?>
                    <?=$this->htmlA([
                        'class' => "btn btn-xs btn-success",
                        'href'  => $this->url('moder/category/params', [
                            'action'    => 'item',
                            'parent_id' => $page['id']
                        ])
                    ], $this->translate('moder/categories/add')) ?>
                <?php } ?>
                <?=$this->htmlA([
                    'class' => "btn btn-xs btn-default",
                    'href'  => $this->url('moder/category/params', [
                        'action' => 'item',
                        'id'     => $page['id']
                    ])
                ], $this->translate('moder/categories/edit')) ?>
            </div>
        </td>
    </tr>
    <?=$this->partial('application/moder/category/list', [
        'items'   => $page['childs'],
        'level'   => $this->level + 1,
        'canEdit' => $this->canEdit,
    ])?>
<?php } ?>