<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 125,
        'args'   => array(
        )
    ));

    //$this->layout()->moduleName = 'moder/cars/car';
?>
<p>Инструмент позволяет объединить несколько автомобилей в одну новую группу</p>

<?=$this->form->render($this)?>