<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 125,
        'args'   => []
    ]);

    //$this->layout()->moduleName = 'moder/cars/car';
?>
<?=$this->markdown($this->translate('moder/vehicle/catalogue/turbo-group-creator/text'))?>

<?=$this->form->render($this)?>