<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => true
        ],
        'pageId' => 196,
    ]);
?>
<?=$this->markdown($this->translate('donate/text'))?>
<br />

<p class="text-center"><i class="fa fa-paypal fa-5x"></i></p>

<?php if ($this->language() == 'ru') { ?>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" class="text-center">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="APTV6TLLJ4W32">
        <input type="image" src="https://www.paypalobjects.com/ru_RU/RU/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal">
        <img alt="" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form>
<?php } elseif ($this->language() == 'fr') { ?>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" class="text-center">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="KKGS9MRL545FQ">
        <input type="image" src="https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal">
        <img alt="" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form>
<?php } else { ?>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" class="text-center">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="PHRAPAMQWV4SJ">
        <input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal">
        <img alt="" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form>
<?php } ?>

<div style="margin:50px auto;width:524px">
    <iframe frameborder="0" allowtransparency="true" scrolling="no" src="<?=$this->escapeHtml('https://money.yandex.ru/embed/donate.xml?' . http_build_query([
        'account'                    => '41001161017513',
        'quickpay'                   => 'donate',
        'payment-type-choice'        => 'on',
        'mobile-payment-type-choice' => 'on',
        'default-sum'                => '100',
        'targets'                    => $this->translate('donate/target'),
        'target-visibility'          => 'on',
        'project-name'               => $this->translate('donate/project'),
        'project-site'               => $this->serverUrl('/'),
        'button-text'                => '01',
        'comment'                    => 'on',
        'hint'                       => $this->translate('donate/comment-hint'),
        'successURL'                 => $this->serverUrl('/donate/success')
    ], HTTP_URL_REPLACE))?>" width="524" height="187"></iframe>
</div>