<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => true
        ],
        'pageId' => 196,
    ]);
?>
<table class="table">
    <thead>
        <tr>
            <td>Дата</td>
            <td>Жертвователь</td>
            <td>Сумма</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->items as $item) { ?>
            <tr>
                <td>
                    <?=$this->escapeHtml($this->humanDate($item['date']))?>
                </td>
                <td>
                    <?php if ($item['user_id']) { ?>
                        <?=$this->user($item['user_id'])?>
                    <?php } ?>
                </td>
                <td>
                    <?=number_format($item['sum'], 2)?> <?=$item['currency']?>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>
