<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 196
    ]);
    
    $this->layout()->moduleName = 'default/donate/select-item';
?>

<?php if ($this->brand) { ?>
    <div class="select-in-brand">
        <?php if (count($this->vehicles) > 0) { ?>
            <div style="margin: 5px 0">
                <?=$this->partial('application/donate/vod-select-item-items', [
                    'cars' => $this->vehicles
                ])?>
            </div>
        <?php } ?>
    
        <?php if ($this->haveConcepts) { ?>
            <div style="margin: 5px 0">
                <?=$this->htmlA([
                    'href'      => '#',
                    'class'     => 'arrow',
                    'data-load' => $this->conceptsUrl
                ], '<i class="fa fa-plus-circle"></i> ' . $this->escapeHtml($this->translate('upload/select/concepts')), false) ?>
                <div style="margin:0 0 4px 18px;display:none">
                    <div class="loading"><em>Loading ...</em></div>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } else { ?>
    <?php 
        $columns = 6;
        $count = count($this->brands);
        $perOne = ceil($count / $columns);
        $idx = 0;
    ?>
    <div class="row">
        <div class="col-md-2">
            <?php foreach ($this->brands as $brand) { ?>
                <?php if ($idx && ($idx%$perOne == 0)) { ?>
                    </div><div class="col-md-2">
                <?php } ?>
                <?=$this->htmlA($this->url('donate/vod/select-item/params', [
                    'brand_id' => $brand['id']
                ], [], true), $brand['name']) ?><br />
                <?php $idx++ ?>
            <?php } ?>
        </div>
    </div>
<?php } ?>