<?php
    $lastType = null;
?>
<?php foreach ($this->cars as $car) { ?>
    <?php if ($lastType != $car['type']) { ?>
        <?php
            $lastType = $car['type'];
        ?>
        <div class="text-muted">
            <?php
                switch ($car['type']) {
                    case Application\Model\ItemParent::TYPE_TUNING: print $this->escapeHtml($this->translate('catalogue/related')); break;
                    case Application\Model\ItemParent::TYPE_SPORT:  print 'Sport'; break;
                }
            ?>
        </div>
    <?php } ?>
    <?php if ($car['haveChilds']) { ?>
        <div>
            <?=$this->htmlA([
                'href'      => '#',
                'class'     => 'arrow',
                'data-load' => $car['loadUrl']
            ], '<i class="fa fa-plus-circle"></i> ' . $this->car()->htmlTitle($car), false) ?>
            <?php if ($car['isGroup'] && $car['isComplies']) { ?>
                <?=$this->htmlA($car['url'], $this->translate('[выбрать]')) ?>
            <?php } ?>
            <div style="margin:0 0 4px 18px;display:none">
                <?php if (!$car['isGroup']) { ?>
                    <?php if ($car['isComplies']) { ?>
                        <?=$this->htmlA($car['url'], $this->car()->htmlTitle($car), false) ?>
                    <?php } else { ?>
                        <span class="text-muted"><?=$this->car()->htmlTitle($car)?></span>
                    <?php } ?>
                    <br />
                <?php } ?>
                <div class="loading"><em>Loading ...</em></div>
            </div>
        </div>
    <?php } else { ?>
        <?php if ($car['isComplies']) { ?>
            <?=$this->htmlA($car['url'], $this->car()->htmlTitle($car), false) ?>
        <?php } else { ?>
            <span class="text-muted"><?=$this->car()->htmlTitle($car)?></span>
        <?php } ?>
        <br />
    <?php } ?>
<?php } ?>