create table voting (
  id           INT GENERATED BY DEFAULT AS IDENTITY primary key,
  name         varchar(255)  not null,
  multivariant bool          not null,
  begin_date   timestamptz   not null,
  end_date     timestamptz   not null,
  votes        int default 0 not null,
  text         text          null
);

create table voting_variant (
  id        INT GENERATED BY DEFAULT AS IDENTITY primary key,
  voting_id int            not null references voting (id),
  name      varchar(255)   not null,
  votes     int  default 0 not null,
  position  int            not null,
  text      text           null,
  constraint voting_variant_unique_position unique (voting_id, position),
  constraint voting_variant_unique_voting_id unique (voting_id, name)
);

create index voting_variant_voting_id_2 on voting_variant (voting_id);

create table voting_variant_vote (
  voting_variant_id int         not null references voting_variant (id),
  user_id           int         not null,
  timestamp         timestamptz null default NOW(),
  primary key (voting_variant_id, user_id)
);

create index voting_variant_vote_user_id on voting_variant_vote (user_id);
create index voting_variant_vote_voting_variant_id on voting_variant_vote (voting_variant_id);
