create table image_dir (
  dir   varchar(255) not null primary key,
  count int not null
);

INSERT INTO image_dir (dir, count) VALUES ('brand', 0);
INSERT INTO image_dir (dir, count) VALUES ('format', 0);
INSERT INTO image_dir (dir, count) VALUES ('museum', 0);
INSERT INTO image_dir (dir, count) VALUES ('picture', 0);
INSERT INTO image_dir (dir, count) VALUES ('user', 0);

create table image (
  id          INT GENERATED BY DEFAULT AS IDENTITY primary key,
  filepath    varchar(511)              not null,
  filesize    int                       not null,
  width       int                       not null,
  height      int                       not null,
  date_add    timestamptz default NOW() not null,
  dir         varchar(255) not null references image_dir (dir),
  crop_left   smallint default 0        not null,
  crop_top    smallint default 0        not null,
  crop_width  smallint default 0        not null,
  crop_height smallint default 0        not null,
  s3          bool  default false       not null,
  exif        jsonb                     null,
  constraint image_unique_filename unique (filepath, dir)
);

create table formated_image
(
  image_id          int not null,
  format            varchar(255)  not null,
  formated_image_id int null references image (id),
  status            int default 0 not null,
  primary key (image_id, format)
);

create table item (
  id                        INT GENERATED BY DEFAULT AS IDENTITY  primary key,
  name                      varchar(255)     default ''  not null,
  begin_year                int             null,
  end_year                  smallint             null,
  body                      varchar(20)                  not null,
  spec_id                   int                  null references spec (id),
  spec_inherit              bool       default true   not null,
  produced                  int                  null,
  produced_exactly          bool             not null,
  is_concept                bool default false not null,
  _car_type_id              int                  null,
  today                     bool             null,
  add_datetime              timestamptz null,
  begin_month               smallint             null,
  end_month                 smallint             null,
  begin_order_cache         timestamp                         null,
  end_order_cache           timestamp                         null,
  begin_model_year          smallint            null,
  end_model_year            smallint                     null,
  is_group                  bool default false   not null,
  vehicle_type_inherit      bool       default false   not null,
  is_concept_inherit        bool       default true   not null,
  engine_inherit            bool       default true   not null,
  item_type_id              int              default 1   not null references item_type (id),
  engine_item_id            int                  null references item (id),
  catname                   varchar(255)                 null,
  full_name                 varchar(255)                 null,
  position                  smallint          default 0   not null,
  logo_id                   int                 null references image (id),
  begin_model_year_fraction varchar(1)                   null,
  end_model_year_fraction   varchar(1)                   null,
  constraint item_unique_caption unique (name, begin_year, body, end_year, begin_model_year, end_model_year, is_group, spec_id),
  constraint item_unique_catname unique (catname, item_type_id)
);

create index item_engine_item_id on item (engine_item_id);
create index item_full_caption_order on item (name, body, begin_year, end_year);
create index item_item_type_id on item (item_type_id);
create index item_logo_id on item (logo_id);
create index item_primary_and_sorting on item (id, begin_order_cache);

create table language (
  code varchar(5) not null primary key
);

INSERT INTO language (code) VALUES ('be');
INSERT INTO language (code) VALUES ('de');
INSERT INTO language (code) VALUES ('en');
INSERT INTO language (code) VALUES ('es');
INSERT INTO language (code) VALUES ('fr');
INSERT INTO language (code) VALUES ('he');
INSERT INTO language (code) VALUES ('it');
INSERT INTO language (code) VALUES ('jp');
INSERT INTO language (code) VALUES ('pt');
INSERT INTO language (code) VALUES ('pt-br');
INSERT INTO language (code) VALUES ('ru');
INSERT INTO language (code) VALUES ('uk');
INSERT INTO language (code) VALUES ('xx');
INSERT INTO language (code) VALUES ('zh');

create table users (
  id                 INT GENERATED BY DEFAULT AS IDENTITY primary key,
  login              varchar(20)                    null unique,
  password           varchar(50)                    null,
  e_mail             varchar(50)                    null,
  name               varchar(50)                    not null,
  reg_date           timestamptz                      null,
  last_online        timestamptz                      null,
  icq                varchar      default ''   not null,
  url                varchar(50)      default ''    not null,
  own_car            varchar(100)     default ''    not null,
  dream_car          varchar(100)     default ''    not null,
  forums_topics      int      default 0   not null,
  forums_messages    int      default 0   not null,
  pictures_added     int      default 0   not null,
  pictures_total     int              default 0     not null,
  e_mail_checked     bool default false   not null,
  hide_e_mail        bool                            null,
  authority          float            default 0     null,
  pictures_ratio     double precision               null,
  email_to_check     varchar(50)                    null,
  email_check_code   varchar(32)                    null,
  messaging_interval int      default 10  not null,
  last_message_time  timestamptz                      null,
  deleted            bool default false   not null,
  identity           varchar(50)                    null unique,
  img                int                    null,
  votes_per_day      int      default 1   not null,
  votes_left         int      default 0   not null,
  timezone           varchar(50)      default 'UTC' not null,
  specs_volume       int              default 0     not null,
  specs_volume_valid bool          default false     not null,
  specs_positives    int                            null,
  specs_negatives    int                            null,
  specs_weight       double precision           default 0     not null,
  last_ip            inet                  null,
  language           varchar(5)       default 'ru'  not null references language (code),
  uuid               uuid                     null unique,
  green              bool default false   not null
);

create index users_email_check_code on users (email_check_code);
create index users_last_ip on users (last_ip);
create index users_pictures_total on users (pictures_total);
create index users_specs_volume on users (specs_volume);

create table attrs_user_values (
  attribute_id int       not null references attrs_attributes (id),
  item_id      int       not null references item (id),
  user_id      int       not null references users (id),
  add_date     timestamptz null default NOW(),
  update_date  timestamptz null default NOW(),
  conflict     int default 0 not null,
  weight       double precision default 0 null,
  primary key (attribute_id, item_id, user_id)
);

create index attrs_user_values_update_date on attrs_user_values (update_date);

create table attrs_user_values_float (
  attribute_id int not null references attrs_attributes (id),
  item_id      int  not null references item (id),
  value        double precision  null,
  user_id      int  not null references users (id),
  primary key (attribute_id, item_id, user_id)
);

create table attrs_user_values_int (
  attribute_id int not null references attrs_attributes (id),
  item_id      int not null references item (id),
  value        int          null,
  user_id      int not null references users (id),
  primary key (attribute_id, item_id, user_id)
);

create table attrs_user_values_list (
  attribute_id int              not null references attrs_attributes (id),
  item_id      int              not null references item (id),
  user_id      int              not null references users (id),
  value        int              null references attrs_list_options (id),
  ordering     int  default 0 not null,
  primary key (attribute_id, item_id, user_id, ordering)
);

create table attrs_user_values_string (
  attribute_id int not null references attrs_attributes (id),
  item_id      int  not null references item (id),
  value        varchar(255) null,
  user_id      int  not null references users (id),
  primary key (attribute_id, item_id, user_id)
);

create table attrs_values (
  attribute_id int                       not null references attrs_attributes (id),
  item_id      int                       not null references item (id),
  conflict     bool default false        not null,
  update_date  timestamptz not null default NOW(),
  primary key (attribute_id, item_id)
);

create table attrs_values_float (
  attribute_id int not null references attrs_attributes (id),
  item_id      int not null references item (id),
  value        double precision       null,
  primary key (attribute_id, item_id)
);

create index IX_attrs_values_float_value on attrs_values_float (attribute_id, value, item_id);

create table attrs_values_int (
  attribute_id int not null references attrs_attributes (id),
  item_id      int not null references item (id),
  value        int null,
  primary key (attribute_id, item_id)
);

create table attrs_values_list (
  attribute_id int not null references attrs_attributes (id),
  item_id      int not null references item (id),
  value        int null references attrs_list_options (id),
  ordering     int default 0 not null,
  primary key (attribute_id, item_id, ordering)
);

create table attrs_values_string (
  attribute_id int not null references attrs_attributes (id),
  item_id      int not null references item (id),
  value        varchar(255) null,
  primary key (attribute_id, item_id)
);

create table comment_message (
  id                  INT GENERATED BY DEFAULT AS IDENTITY primary key,
  parent_id           int                  null references comment_message (id) on delete set null,
  type_id             int             not null references comment_type (id),
  item_id             int                  not null,
  author_id           int                  null references users (id),
  datetime            timestamptz                    not null,
  message             text                     not null,
  moderator_attention smallint             not null,
  vote                int              default 0   not null,
  deleted             bool default false not null,
  deleted_by          int                  null references users (id),
  replies_count       int      default 0 not null,
  ip                  inet                null,
  delete_date         timestamptz                    null
);

create index comment_message_author_date on comment_message (author_id, datetime);
create index comment_message_author_vote on comment_message (author_id, vote);
create index comment_message_datetime_sort on comment_message (datetime);
create index comment_message_delete_date on comment_message (delete_date);
create index comment_message_moderator_attention on comment_message (moderator_attention);
create index comment_message_type_id on comment_message (type_id, item_id);

create table comment_topic (
  type_id     int                       not null references comment_type (id),
  item_id     int                           not null,
  last_update timestamptz not null default NOW(),
  messages    int default 0               not null,
  primary key (type_id, item_id)
);

create index comment_topic_item_id on comment_topic (item_id);

create table comment_topic_subscribe (
  item_id int not null,
  type_id int not null references comment_type (id),
  user_id int not null references users (id) on delete cascade,
  sent    bool default false not null,
  primary key (item_id, type_id, user_id)
);

create table comment_topic_view (
  type_id   int not null references comment_type (id),
  item_id   int not null,
  user_id   int not null references users (id) on delete cascade,
  timestamp timestamptz not null default NOW(),
  primary key (type_id, item_id, user_id)
);

create table comment_vote (
  comment_id int not null references comment_message (id) on delete cascade,
  user_id    int not null references users (id) on delete cascade,
  vote       smallint not null,
  add_date   timestamptz not null default NOW(),
  primary key (comment_id, user_id)
);

create table contact (
  user_id         int not null references users (id) on delete cascade,
  contact_user_id int not null references users (id) on delete cascade,
  timestamp       timestamptz not null,
  primary key (user_id, contact_user_id)
);

create table textstorage_text (
  id           INT GENERATED BY DEFAULT AS IDENTITY primary key,
  text         text    not null,
  last_updated timestamptz not null,
  revision     int default 1 not null
);

create table textstorage_revision (
  text_id   int          not null references textstorage_text (id),
  revision  int          not null,
  text      text         not null,
  timestamp timestamptz  not null,
  user_id   int null references users (id),
  primary key (text_id, revision)
);

create type picture_status as enum ('new', 'accepted', 'removing', 'removed', 'inbox');

create table pictures (
  id                    INT GENERATED BY DEFAULT AS IDENTITY primary key,
  width                 smallint default 0                            not null,
  height                smallint default 0                            not null,
  filesize              int      default 0                            not null,
  owner_id              int                                  null references users (id),
  add_date              timestamptz         default NOW()              not null,
  status                picture_status not null,
  removing_date         date                                                     null,
  change_status_user_id int                                              null references users (id),
  accept_datetime       timestamptz                                                null,
  name                  varchar(255)                                             null,
  identity              varchar(10)                                              not null unique,
  replace_picture_id    int                                              null references pictures (id) on delete set null,
  image_id              int                                              null references image (id),
  ip                    inet                                            null,
  copyrights_text_id    int                                                      null references textstorage_text (id),
  point                 geography(Point,4326) null,
  dpi_x                 int                                                      null,
  dpi_y                 int                                                      null,
  content_count         int               default 0                              not null,
  taken_year            smallint                                                 null,
  taken_month           smallint                                                  null,
  taken_day             smallint                                                  null
);

create index pictures_accept_datetime on pictures (status, accept_datetime);
create index pictures_status on pictures (status);
create index pictures_date_and_id_ordering on pictures (status, add_date, id);
create index pictures_id on pictures (id, status);
create index pictures_owner_id on pictures (owner_id, status);
create index pictures_width on pictures (width, height, add_date, id);

create table df_distance (
  src_picture_id int not null references pictures (id) on delete cascade,
  dst_picture_id int not null references pictures (id) on delete cascade,
  distance       smallint not null,
  hide           bool not null,
  primary key (src_picture_id, dst_picture_id)
);

create table df_hash (
  picture_id int not null primary key references pictures (id) on delete cascade,
  hash       bigint not null
);

create table forums_themes (
  id             INT GENERATED BY DEFAULT AS IDENTITY primary key,
  parent_id      int                  null references forums_themes (id),
  folder         varchar(30)      default ''  not null unique,
  name           varchar(50)      default ''  not null unique,
  position       smallint default 0 not null,
  description    text                         not null,
  topics         int      default 0 not null,
  messages       int      default 0 not null,
  is_moderator   bool default false not null,
  disable_topics bool default false null
);

INSERT INTO forums_themes (id, parent_id, folder, name, position, description, topics, messages, is_moderator, disable_topics) VALUES
  (2, null, 'all_other', 'forums/theme/all-other', 5, 'forums/theme/all-other/description', 427, 13953, false, false),
  (3, null, 'wallpapers', 'forums/theme/photos', 3, '', 38, 6812, false, false),
  (5, null, 'this_cite', 'forums/theme/this-cite', 2, '', 231, 15356, false, false),
  (4, 5, 'classifier', 'forums/theme/classifier', 4, '', 66, 7984, false, false),
  (6, 16, 'germany', 'forums/theme/german-cars', 7, 'forums/theme/german-cars/description', 156, 1614, false, false),
  (7, 16, 'italy', 'forums/theme/italian-cars', 8, 'forums/theme/italian-cars/description', 37, 295, false, false),
  (8, 16, 'france', 'forums/theme/french-cars', 13, 'forums/theme/french-cars/description', 20, 195, false, false),
  (9, 16, 'japan', 'forums/theme/japan-cars', 10, 'forums/theme/japan-cars/description', 171, 1133, false, false),
  (10, 16, 'korea', 'forums/theme/korean-cars', 12, 'forums/theme/korean-cars/description', 12, 138, false, false),
  (11, 16, 'china', 'forums/theme/chinese-cars', 15, 'forums/theme/chinese-cars/description', 23, 310, false, false),
  (12, 16, 'russian', 'forums/theme/russian-cars', 14, 'forums/theme/russian-cars/description', 124, 2162, false, false),
  (13, 16, 'usa', 'forums/theme/american-cars', 9, 'forums/theme/american-cars/description', 160, 1178, false, false),
  (14, 16, 'english', 'forums/theme/british-cars', 11, 'forums/theme/british-cars/description', 27, 221, false, false),
  (15, null, 'moder', 'forums/theme/moderators', 1, '', 81, 4084, true, false),
  (16, null, 'cars', 'forums/theme/cars', 4, '', 686, 7349, false, true);

create table forums_theme_parent (
  forum_theme_id int                not null references forums_themes (id),
  parent_id      int                not null references forums_themes (id),
  level          smallint default 0 not null,
  primary key (forum_theme_id, parent_id)
);

insert into forums_theme_parent (forum_theme_id, parent_id, level)
values  (2, 2, 0),
        (3, 3, 0),
        (4, 4, 1),
        (4, 5, 0),
        (5, 5, 0),
        (6, 6, 1),
        (6, 16, 0),
        (7, 7, 1),
        (7, 16, 0),
        (8, 8, 1),
        (8, 16, 0),
        (9, 9, 1),
        (9, 16, 0),
        (10, 10, 1),
        (10, 16, 0),
        (11, 11, 1),
        (11, 16, 0),
        (12, 12, 1),
        (12, 16, 0),
        (13, 13, 1),
        (13, 16, 0),
        (14, 14, 1),
        (14, 16, 0),
        (15, 15, 0),
        (16, 16, 0);

CREATE TYPE forums_topic_status AS ENUM ('normal', 'closed', 'deleted');

create table forums_topics (
  id           INT GENERATED BY DEFAULT AS IDENTITY primary key,
  theme_id     int                          default null               null references forums_themes (id),
  name         varchar(100)                         default ''                not null,
  author_id    int                                         not null references users (id),
  add_datetime timestamptz                            default NOW() not null,
  _messages    int                          default 0               not null,
  views        int                          default 0               not null,
  status       forums_topic_status default 'normal'          not null,
  author_ip    inet                                                  null
);

create table item_language (
  item_id      int not null references item (id) on delete cascade,
  language     varchar(5)   not null references language (code),
  name         varchar(255) null,
  text_id      int          null references textstorage_text (id),
  full_text_id int          null references textstorage_text (id),
  primary key (item_id, language)
);

create type item_link_type as enum ('default', 'official', 'helper', 'club');

create table item_link (
  id      INT GENERATED BY DEFAULT AS IDENTITY primary key,
  type    item_link_type default 'default' not null,
  url     varchar(150) not null,
  name    varchar(250) not null,
  item_id int not null references item (id)
);

create table item_parent (
  item_id        int                 not null references item (id),
  parent_id      int                 not null references item (id),
  is_primary     bool       default false   not null,
  catname        varchar(150)                 not null,
  type           smallint          default 0   not null,
  timestamp      timestamptz                    null,
  "~name"        varchar(100)                 null,
  manual_catname bool default false not null,
  primary key (item_id, parent_id),
  constraint item_parent_unique_catname unique (parent_id, catname)
);

create table item_parent_cache (
  item_id   int not null references item (id) on delete cascade,
  parent_id int not null references item (id) on delete cascade,
  diff      int     default 0 not null,
  tuning    bool default false not null,
  sport     bool default false not null,
  design    bool default false not null,
  primary key (item_id, parent_id)
);

create table item_parent_language (
  item_id   int       not null references item (id),
  parent_id int       not null references item (id),
  language  varchar(5)        not null references language (code),
  name      varchar(255)      not null,
  is_auto   bool default false not null,
  primary key (item_id, parent_id, language)
);

create table item_point (
  item_id int not null primary key references item (id) on delete cascade,
  point   geography(Point,4326) not null
);

create index item_point_point on item_point USING GIST (point);

create table item_vehicle_type (
  item_id         int not null references item (id) on delete cascade,
  vehicle_type_id int not null references vehicle_type (id),
  inherited       bool not null,
  primary key (item_id, vehicle_type_id)
);

create table log_events (
  id           INT GENERATED BY DEFAULT AS IDENTITY primary key,
  user_id      int not null references users (id),
  add_datetime timestamptz    not null,
  description  text   not null
);

create index log_events_add_datetime on log_events (add_datetime);

create table log_events_articles (
  log_event_id int not null references log_events (id) on delete cascade,
  article_id   int not null references article (id) on delete cascade,
  primary key (log_event_id, article_id)
);

create table log_events_item
(
  log_event_id int not null references log_events (id) on delete cascade,
  item_id      int not null references item (id) on delete cascade,
  primary key (log_event_id, item_id)
);

create table log_events_pictures (
  log_event_id int not null references log_events (id) on delete cascade,
  picture_id   int not null references pictures (id) on delete cascade,
  primary key (log_event_id, picture_id)
);

create table log_events_user (
  log_event_id int not null references log_events (id),
  user_id      int not null references users (id),
  primary key (log_event_id, user_id)
);

create table of_day (
  day_date      date                not null primary key,
  picture_id    int                 null references pictures (id) on delete cascade,
  item_id       int                 null references item (id) on delete cascade,
  user_id       int                 null references users (id) on delete set null,
  twitter_sent  bool default false not null,
  facebook_sent bool default false not null,
  vk_sent       bool default false not null
);

create table personal_messages (
  id              INT GENERATED BY DEFAULT AS IDENTITY primary key,
  from_user_id    int                  null references users (id),
  to_user_id      int                  not null references users (id),
  contents        text                     not null,
  add_datetime    timestamptz                    not null,
  readen          bool default false not null,
  deleted_by_from bool default false not null,
  deleted_by_to   bool default false not null
);

create index IX_personal_messages on personal_messages (from_user_id, to_user_id, readen, deleted_by_to);
create index IX_personal_messages2 on personal_messages (to_user_id, from_user_id, deleted_by_to);
create index personal_messages_to_user_id on personal_messages (to_user_id, readen);

create table picture_item (
  picture_id     int                         not null references pictures (id) on delete cascade,
  item_id        int                         not null references item (id),
  type           int default 1               not null,
  perspective_id int                         null references perspectives (id),
  crop_left      smallint                    null,
  crop_top       smallint                    null,
  crop_width     smallint                    null,
  crop_height    smallint                    null,
  timestamp      timestamptz default NOW() not null
);

create table picture_moder_vote (
  user_id    int not null references users (id) on delete cascade,
  picture_id int not null references pictures (id) on delete cascade,
  day_date   timestamptz                    not null,
  reason     varchar(80)                  not null,
  vote       smallint default 0 not null,
  primary key (user_id, picture_id)
);

create table picture_view (
  picture_id int not null primary key references pictures (id) on delete cascade,
  views      int not null
);

create table picture_vote (
  picture_id int not null references pictures (id) on delete cascade,
  user_id    int not null references users (id) on delete cascade,
  value      smallint      not null,
  timestamp  timestamptz    not null,
  primary key (picture_id, user_id)
);

create table picture_vote_summary (
  picture_id int  not null primary key references pictures (id) on delete cascade,
  positive   int default 0 not null,
  negative   int default 0 not null
);

create table telegram_chat (
  chat_id  int not null primary key,
  user_id  int null references users (id) on delete cascade,
  token    varchar(50) null,
  messages bool default false not null
);

create index telegram_chat_token on telegram_chat (token);

create table telegram_brand (
  chat_id int not null,
  inbox   bool default false not null,
  new     bool default false not null,
  item_id int not null references item (id) on delete cascade,
  primary key (chat_id, item_id)
);

create table user_account (
  id           INT GENERATED BY DEFAULT AS IDENTITY primary key,
  user_id      int      not null references users (id) on delete cascade,
  external_id  varchar(255)     not null,
  name         varchar(255)     not null,
  link         varchar(255)     not null,
  used_for_reg bool not null,
  service_id   varchar(50)      not null,
  constraint user_account_unique_service_id unique (service_id, external_id)
);

create table user_item_subscribe (
  user_id int not null references users (id) on delete cascade,
  item_id int not null references item (id) on delete cascade,
  primary key (user_id, item_id)
);
