CREATE TABLE `pages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` int(10) unsigned DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `breadcrumbs` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `is_group_node` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `registered_only` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `class` varchar(30) DEFAULT NULL,
  `guest_only` tinyint(3) unsigned NOT NULL,
  `position` smallint(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_position` (`parent_id`,`position`),
  KEY `parent_id` (`parent_id`),
  CONSTRAINT `pages_fk` FOREIGN KEY (`parent_id`) REFERENCES `pages` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `pages` VALUES 
(1,NULL,'Index page','Encyclopedia of cars in the pictures. AutoWP.ru','','/',0,0,'',0,1),
    (2,1,'Главное меню','','','',1,0,'',0,1),
        (21,2,'Mostly','Mostly','','/ng/mosts',0,0,'',0,24),
            (154,21,'%MOST_NAME%','%MOST_NAME%','%MOST_NAME%','/ng/mosts/%MOST_CATNAME%',0,0,'',0,1),
                (155,154,'Most %MOST_NAME% %CAR_TYPE_NAME%','Most %MOST_NAME% %CAR_TYPE_NAME%','%CAR_TYPE_NAME%','/ng/mosts/%MOST_CATNAME%/%CAR_TYPE_CATNAME%',0,0,'',0,1),
                    (156,155,'Most %MOST_NAME% %CAR_TYPE_NAME% %YEAR_NAME%','Most %MOST_NAME% %CAR_TYPE_NAME% %YEAR_NAME%','%YEAR_NAME%','/ng/mosts/%MOST_CATNAME%/%CAR_TYPE_CATNAME%/%YEAR_CATNAME%',0,0,'',0,1),
        (22,2,'Categories','Categories','','/category',0,0,'',0,25),
            (23,22,'%CATEGORY_NAME%','%CATEGORY_NAME%','%CATEGORY_SHORT_NAME%','/category/%CATEGORY_CATNAME%',0,0,'/category/%CATEGORY_CATNAME%',0,1),
                (162,23,'Pictures','Pictures','','/category/%CATEGORY_CATNAME%/pictures',0,0,'',0,4),
                    (184,162,'%PICTURE_NAME%','%PICTURE_NAME%','%PICTURE_NAME%','/category/%CATEGORY_CATNAME%/pictures/%PICTURE_ID%',0,0,'',0,1),
                (185,23,'%CAR_NAME%','%CAR_NAME%','%CAR_NAME%','/category/%CATEGORY_CATNAME%/%CAR_ID%',0,0,'',0,3),
                    (186,185,'Pictures','Pictures','Pictures','/category/%CATEGORY_CATNAME%/%CAR_ID%/pictures',0,0,'',0,1),
                        (187,186,'%PICTURE_NAME%','%PICTURE_NAME%','%PICTURE_NAME%','/category/%CATEGORY_CATNAME%/%CAR_ID%/pictures/%PICTURE_ID%',0,0,'',0,1),
        (25,2,'Twins','','','/twins',0,0,'',0,23),
            (26,25,'%TWINS_GROUP_NAME%','%TWINS_GROUP_NAME%','%TWINS_GROUP_NAME%','/twins/group%TWINS_GROUP_ID%',0,0,'',0,6),
                (27,26,'Specifications of %TWINS_GROUP_NAME%','Specifications of %TWINS_GROUP_NAME%','Specifications','/twins/group%TWINS_GROUP_ID%/specifications',0,0,'',0,9),
                (28,26,'All pictures of %TWINS_GROUP_NAME%','All pictures of %TWINS_GROUP_NAME%','All pictures','/twins/group%TWINS_GROUP_ID%/pictures',0,0,'',0,7),
                    (183,28,'%PICTURE_NAME%','%PICTURE_NAME%','%PICTURE_NAME%','/twins/group%TWINS_GROUP_ID%/pictures/%PICTURE_ID%',0,0,'',0,1),
            (153,25,'%BRAND_NAME% Twins','%BRAND_NAME% Twins','%BRAND_NAME%','/twins/%BRAND_CATNAME%',0,0,'',0,7),
        (42,2,'Forums','Forums','','/ng/forums',0,0,'',0,27),
            (43,42,'%THEME_NAME%','%THEME_NAME%','%THEME_NAME%','/ng/forums/%THEME_ID%',0,0,'',0,1),
                (44,43,'%TOPIC_NAME%','%TOPIC_NAME%','%TOPIC_NAME%','/forums/topic/topic/topic_id/%TOPIC_ID%',0,0,'',0,5),
                    (83,44,'Move','Move','Move','/forums/topic/move/topic_id/%TOPIC_ID%',0,0,'',0,1),
                (45,43,'New topic','New topic','New topic','/ng/forums/new-topic/%THEME_ID%',0,0,'',0,4),
        (117,2,'Map','Map','','/ng/map',0,0,'',0,26),
            (159,117,'Museum','%MUSEUM_NAME%','%MUSEUM_NAME%','/museums/museum/id/%MUSEUM_ID%',0,0,'',0,1),
            (181,117,'%FACTORY_NAME%','%FACTORY_NAME%','%FACTORY_NAME%','/factory/factory/id/%FACTORY_ID%',0,0,'',0,2),
                (182,181,'Vehicles','Vehicles','Vehicles','/factory/factory-cars/id/%FACTORY_ID%',0,0,'',0,1),
    (10,1,'Brand','%BRAND_NAME%','%BRAND_NAME%','/%BRAND_CATNAME%/',0,0,'',0,1045),
        (14,10,'%BRAND_NAME% cars in chronological order','%BRAND_NAME% cars in chronological order','Cars in chronological order','/%BRAND_CATNAME%/cars/',0,0,'',0,913),
            (138,14,'%BRAND_NAME% %CAR_TYPE_NAME% in chronological order','%BRAND_NAME% %CAR_TYPE_NAME% in chronological order','%CAR_TYPE_NAME%','/%BRAND_CATNAME%/cars/%CAR_TYPE_CATNAME%/',0,0,'',0,1),
        (15,10,'Last pictures of %BRAND_NAME%','Last pictures of %BRAND_NAME%','Last pictures','/%BRAND_CATNAME%/recent/',0,0,'',0,918),
        (33,10,'%CAR_NAME%','%CAR_NAME%','%SHORT_CAR_NAME%','/%BRAND_CATNAME%/%CAR_CATNAME%/',0,0,'',0,909),
            (34,33,'All pictures of %CAR_NAME%','All pictures of %CAR_NAME%','All pictures','%ALL_PICTURES_URL%',0,0,'',0,13),
                (194,34,'%PICTURE_NAME%','%PICTURE_NAME%','%PICTURE_NAME%','/%BRAND_CATNAME%/%CAR_CATNAME%/pictures/%PICTURE_ID%',0,0,'',0,1),
            (36,33,'Specifications of %CAR_NAME%','Specifications of %CAR_NAME%','Specifications','/%BRAND_CATNAME%/%CAR_CATNAME%/specifications/',0,0,'',0,14),
        (37,10,'Concepts & prototypes','Concepts & prototypes','Concepts & prototypes','/%BRAND_CATNAME%/concepts/',0,0,'',0,915),
        (39,10,'%BRAND_NAME% logotypes','%BRAND_NAME% logotypes','Logotypes','/%BRAND_CATNAME%/logotypes/',0,0,'',0,916),
            (192,39,'%PICTURE_NAME%','%PICTURE_NAME%','%PICTURE_NAME%','/%BRAND_CATNAME%/logotypes/%PICTURE_ID%',0,0,'',0,1),
        (40,10,'%BRAND_NAME% miscellaneous','%BRAND_NAME% miscellaneous','Miscellaneous','/%BRAND_CATNAME%/mixed/',0,0,'',0,917),
            (190,40,'%PICTURE_NAME%','%PICTURE_NAME%','%PICTURE_NAME%','/%BRAND_CATNAME%/mixed/%PICTURE_ID%',0,0,'',0,1),
        (41,10,'Unsorted','Unsorted','Unsorted','/%BRAND_CATNAME%/other/',0,0,'',0,920),
            (191,41,'%PICTURE_NAME%','%PICTURE_NAME%','%PICTURE_NAME%','/%BRAND_CATNAME%/other/%PICTURE_ID%',0,0,'',0,1),
        (58,10,'%BRAND_NAME% %DPBRAND_NAME%','%BRAND_NAME% %DPBRAND_NAME%','%DPBRAND_NAME%','/%BRAND_CATNAME%/%DPBRAND_CATNAME%/',0,0,'',0,901),
        (59,10,'%BRAND_NAME% %DESIGN_PROJECT_NAME%','%BRAND_NAME% %DESIGN_PROJECT_NAME%','%DESIGN_PROJECT_NAME%','/%BRAND_CATNAME%/%DESIGN_PROJECT_CATNAME%/',0,0,'',0,902),
            (66,59,'All pictures of %BRAND_NAME% %DESIGN_PROJECT_NAME%','All pictures of %BRAND_NAME% %DESIGN_PROJECT_NAME%','All pictures','/%BRAND_CATNAME%/%DESIGN_PROJECT_CATNAME%/pictures/',0,0,'',0,1),
                (193,66,'%PICTURE_NAME%','%PICTURE_NAME%','%PICTURE_NAME%','/%BRAND_CATNAME%/%DESIGN_PROJECT_CATNAME%/%PICTURE_ID%',0,0,'',0,1),
        (164,10,'Mosts','Mosts','Mosts','/%BRAND_CATNAME%/mosts/',0,0,'',0,919),
            (165,164,'Most %MOST_NAME% %BRAND_NAME%','Most %MOST_NAME% %BRAND_NAME%','%MOST_NAME%','/%BRAND_CATNAME%/mosts/%MOST_CATNAME%',0,0,'',0,1),
                (166,165,'Most %MOST_NAME% %CAR_TYPE_NAME% %BRAND_NAME%','Most %MOST_NAME% %CAR_TYPE_NAME% %BRAND_NAME%','%CAR_TYPE_NAME%','/%BRAND_CATNAME%/mosts/%MOST_CATNAME%/%CAR_TYPE_CATNAME%',0,0,'',0,1),
                    (167,166,'Most %MOST_NAME% %CAR_TYPE_NAME% %BRAND_NAME% %YEAR_NAME%','Most %MOST_NAME% %CAR_TYPE_NAME% %BRAND_NAME% %YEAR_NAME%','%YEAR_NAME%','/%BRAND_CATNAME%/mosts/%MOST_CATNAME%/%CAR_TYPE_CATNAME%/%YEAR_CATNAME%',0,0,'',0,1),
        (208,10,'%BRAND_NAME% engines','','','/%BRAND_CATNAME%/engines',0,0,'',0,921),
    (18,1,'%PICTURE_NAME%','%PICTURE_NAME%','%PICTURE_NAME%','/picture/%PICTURE_ID%',0,0,'',0,1021),
    (19,1,'Brands','Brands','Brands','',0,0,'',0,1035),
        (20,19,'Тип производителей','',NULL,NULL,0,0,NULL,0,1),
    (24,1,'Лимитированные и специальные серии автомобилей','','','/limitededitions/',0,0,'',0,777),
    (31,1,'Articles','Articles','Articles','/articles/',0,0,'',0,1046),
        (32,31,'%ARTICLE_NAME%','%ARTICLE_NAME%','%ARTICLE_NAME%','',0,0,'/articles/%ARTICLE_CATNAME%/',0,1),
    (87,1,'More','More','','',1,0,'',0,1043),
        (89,87,'Feedback','','','/ng/feedback',0,0,'',0,19),
            (93,89,'Message sent','','','',0,0,'',0,0),
        (90,87,'Sign out','','','/login/logout',0,1,'',0,30),
        (91,87,'Registration','','','/ng/signup',0,0,'',1,4),
        (29,87,'Add picture','Add picture','','/ng/upload',0,1,'',0,18),
            (30,29,'Select brand','Select brand','Select brand','',0,0,'',0,5),
        (48,87,'Cabinet','Cabinet','','/ng/account',0,1,'',0,28),
            (49,48,'Personal messages','Personal messages','','/ng/account/messages',0,0,'',0,23),
                (80,49,'Sent','Sent','','/ng/account/messages?folder=sent',0,0,'',0,15),
                (81,49,'System messages','System messages','','/ng/account/messages?folder=system',0,0,'',0,18),
                (128,49,'Inbox','Inbox','','/ng/account/messages',0,1,'',0,17),
            (54,48,'Confirm the email address','Confirm the email address','','',0,0,'',0,21),
            (55,48,'My e-mail','My e-mail','','/ng/account/email',0,1,'',0,26),
                (56,55,'Changed','Changing e-mail','','',0,1,'',0,1),
            (57,48,'Forums subscriptions','Forums subscriptions','','/ng/forums/subscriptions',0,1,'',0,31),
            (94,48,'Unmoderated','Unmoderated','','/ng/account/inbox-pictures',0,1,'',0,25),
            (129,48,'Profile','Profile','','/ng/account/profile',0,1,'',0,12),
            (130,48,'My pictures','My pictures','','',0,1,'',0,30),
            (133,48,'Access','Access Control','','/ng/account/access',0,1,'',0,27),
            (137,48,'Account delete','','','/ng/account/delete',0,1,'',0,28),
            (123,48,'My accounts','My accounts','My accounts','/ng/account/accounts',0,1,'',0,22),
            (188,48,'Conflicts','Conflicts','Conflicts','/ng/account/specs-conflics',0,1,'',0,29),
            (198,48,'Contacts','Contacts','Contacts','/ng/account/contacts',0,1,'',0,33),
        (124,87,'Who is online?','','','/users/online',0,0,'online',0,24),
        (136,87,'About us','About us','','/ng/about',0,0,'',0,29),
        (211,87,'Contacts','Contacts','Contacts','/ng/account/contacts',0,1,'',0,27),
    (51,1,'New pictures','','','/ng/new',0,0,'',0,1036),
        (209,51,'%DATE%','%DATE%','%DATE%','/ng/new/%DATE_STR%',0,0,'',0,1),
            (210,209,'%ITEM_NAME%','%ITEM_NAME%','%ITEM_NAME%','%ITEM_URL%',0,0,'',0,1),
    (52,1,'Registration','Registration','','/ng/signup',0,0,'',0,1056),
        (53,52,'ok','Успешная регистрация','','',0,0,'',0,1),
    (60,1,'Password recovery','Password recovery','','',0,0,'',0,1038),
        (134,60,'New password','New password','','',0,0,'',0,4),
        (135,60,'New password saved','','','',0,1,'',0,5),
    (61,1,'All brands','','','/brands/',0,0,'',0,1039),
    (62,1,'%USER_NAME%','%USER_NAME%','%USER_NAME%','/ng/users/%USER_IDENTITY%',0,0,'',0,1020),
        (63,62,'User\'s pictures','User\'s pictures','Pictures','/ng/users/%USER_IDENTITY%/pictures',0,0,'',0,1),
            (141,63,'%BRAND_NAME% pictures','%BRAND_NAME% pictures','%BRAND_NAME% pictures','/ng/users/%USER_IDENTITY%/pictures/%BRAND_CATNAME%',0,0,'',0,1),
        (205,62,'User\'s comments','User\'s comments','Comments','/ng/users/%USER_IDENTITY%/comments',0,0,'',0,2),
    (67,1,'Moderator page','','','/ng/moder',0,0,'',0,1040),
        (68,67,'Страницы сайта','','','/moder/pages',0,0,NULL,0,1),
            (69,68,'Добавить','','','',0,0,NULL,0,1),
            (70,68,'Изменить','','','',0,0,NULL,0,2),
            (120,68,'Блоки','','','',0,1,'',0,3),
        (71,67,'Права','','','/moder/rights',0,0,NULL,0,2),
        (73,67,'Картинки','','','/moder/pictures',0,1,'',0,20),
            (72,73,'%PICTURE_NAME%','%PICTURE_NAME%','%PICTURE_NAME%','/moder/pictures/picture/picture_id/%PICTURE_ID%',0,1,'',0,3),
                (148,72,'Cropper','Cropper','Cropper','',0,1,'',0,1),
                (149,72,'Move picture','Move picture','Move picture','',0,1,'',0,12),
        (74,67,'Автомобили по алфавиту','','','/ng/moder/cars/alpha',0,0,NULL,0,5),
        (75,67,'Журнал событий','','','/ng/log',0,0,NULL,0,6),
        (77,67,'Трафик','','','/moder/trafic',0,0,NULL,0,7),
        (131,67,'Vehicles, engines, categories','Vehicles, engines, categories','Vehicles, engines, categories','/ng/moder/items',0,1,'',0,33),
            (78,131,'%CAR_NAME%','%CAR_NAME%','%CAR_NAME%','/ng/moder/items/item/%CAR_ID%',0,1,'',0,26),
                (144,78,'Brand selection','Brand selection','Brand selection','',0,1,'',0,1),
                (178,78,'Factory selection','Factory selection','Factory selection','',0,0,'',0,9),
            (163,131,'New vehicle','New vehicle','New vehicle','',0,0,'',0,28),
        (97,67,'Ракурсы','','','',0,1,'',0,12),
        (100,67,'Аттрибуты','','','/moder/attrs',0,1,'',0,14),
            (101,100,'%ATTR_NAME%','%ATTR_NAME%','%ATTR_NAME%','',0,1,'',0,1),
            (142,100,'%ATTR_ITEMTYPE_NAME% %ZONE_NAME%','%ATTR_ITEMTYPE_NAME% %ZONE_NAME%','%ATTR_ITEMTYPE_NAME% %ZONE_NAME%','/moder/attrs/zone/zone_id/%ZONE_ID%',0,1,'',0,4),
        (107,67,'Заявки на удаление','Заявки на удаление','','',0,0,'',0,15),
        (110,67,'Комментарии','Комментарии','','/ng/moder/comments',0,1,'',0,35),
        (114,67,'Журнал ТТХ','Журнал ТТХ','','/moder/spec',0,1,'',0,17),
        (119,67,'Статистика','','','/moder/index/stat',0,1,'',0,19),
        (202,67,'Perspectives','Perspectives','Perspectives','/moder/perspectives',0,0,'',0,30),
        (203,67,'Users','Users','Users','/moder/users',0,1,'',0,31),
        (212,67,'Picture vote templates','Picture vote templates','Picture vote templates','/moder/picture-vote-template',0,0,'',0,34),
    (76,1,'Немодерированное','Немодерированное','','',0,0,'',0,1053),
    (79,1,'Sign in','Sign in','','/ng/login',0,0,'',1,1058),
    (102,1,'Specs editors %CAR_NAME%','Specs editors %CAR_NAME%','Specs editors','',0,0,'',0,1047),
        (103,102,'История изменения','История изменения','','/moder/index/attrs-change-log',0,1,'',0,18),
        (189,102,'Low weight','Low weight','Low weight','',0,0,'',0,17),
    (104,1,'Пользовательская статистика','','','',0,0,'',0,1000),
    (105,1,'Add a comment','Add a comment','','',0,0,'',0,1041),
    (106,1,'Rules','Rules','','/rules',0,0,'',0,1042),
    (109,1,'Cutaway','','Cutaway','/cutaway',0,0,'',0,1003),
    (122,1,'Specifications','Specifications','Specifications','/spec/',0,0,'',0,1057),
    (157,1,'%VOTING_NAME%','%VOTING_NAME%','%VOTING_NAME%','/voting/voting/id/%VOTING_ID%',0,0,'',0,1022),
    (161,1,'Pulse','Pulse','Pulse','/pulse/',0,0,'',0,1049),
    (180,1,'Factories','Factories','Factories','/factory',0,0,'',0,1052),
    (197,1,'Text history','Text history','Text history','/info/text',0,0,'',0,1064),
    (196,1,'Donate','Donate','Donate','/donate',0,0,'',0,1061),
    (204,1,'Telegram','Telegram','Telegram','/telegram',0,0,'',0,1066),
    (201,1,'Mascots','Mascots','Mascots','/mascots',0,0,'',0,1065),
    (214,1,'Persons','','','/ng/persons',0,0,'',0,1068),
        (213,214,'%PERSON_NAME%','','','/ng/persons/%PERSON_ID%',0,0,'',0,1067),
    (173,1,'Statistics','Statistics','Statistics','/ng/users/rating',0,0,'',0,1050),
    (174,1,'Specs','Specs','Specs','/info/spec',0,0,'',0,1051);
