-- Append-only record of every cookie-consent decision a signed-in user makes, kept for GDPR
-- Art. 7(1) accountability. Anonymous visitors' choices live only in their browser.
CREATE TABLE user_consent_log (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        bigint NOT NULL REFERENCES users (id),
  analytics      boolean NOT NULL,
  policy_version int NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX user_consent_log_user_id ON user_consent_log (user_id, created_at);
