CREATE TABLE content_report (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type smallint NOT NULL,
    entity_id bigint NOT NULL,
    reason smallint NOT NULL,
    message varchar(2000) NOT NULL DEFAULT '',
    reporter_id bigint REFERENCES users (id) ON DELETE SET NULL,
    reporter_ip inet,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    status smallint NOT NULL DEFAULT 1,
    resolved_by bigint REFERENCES users (id) ON DELETE SET NULL,
    resolved_at timestamptz,
    resolution varchar(2000) NOT NULL DEFAULT ''
);

CREATE INDEX content_report_queue ON content_report (status, created_at);
CREATE INDEX content_report_entity ON content_report (entity_type, entity_id);
