UPDATE spec SET short_name='Belgium' WHERE id=40;
UPDATE spec SET short_name='Italia' WHERE id=39;
UPDATE spec SET short_name='Luxembourg' WHERE id=38;
UPDATE spec SET short_name='Switzerland' WHERE id=33;
UPDATE spec SET short_name='Singapore' WHERE id=32;
UPDATE spec SET short_name='France' WHERE id=30;
UPDATE spec SET short_name='Spain' WHERE id=27;
UPDATE spec SET short_name='Thailand' WHERE id=26;
UPDATE spec SET short_name='New Zealand' WHERE id=25;
UPDATE spec SET short_name='Iran' WHERE id=24;
UPDATE spec SET short_name='Netherlands', name='Netherlands' WHERE id=23;
UPDATE spec SET short_name='Germany' WHERE id=22;
UPDATE spec SET short_name='South Korea' WHERE id=21;
UPDATE spec SET short_name='Malaysia' WHERE id=19;
UPDATE spec SET short_name='Taiwan' WHERE id=18;
UPDATE spec SET short_name='Hong Kong' WHERE id=17;
UPDATE spec SET short_name='Canada' WHERE id=16;
UPDATE spec SET short_name='CIS', name='CIS' WHERE id=15;
UPDATE spec SET short_name='India' WHERE id=14;
UPDATE spec SET short_name='Finland' WHERE id=13;
UPDATE spec SET short_name='UAE' WHERE id=12;
UPDATE spec SET short_name='Argentina' WHERE id=11;
UPDATE spec SET short_name='Mexico' WHERE id=10;
UPDATE spec SET short_name='Russia' WHERE id=8;
UPDATE spec SET short_name='Brazil' WHERE id=5;
UPDATE spec SET short_name='Australia' WHERE id=3;
