CREATE TABLE `spec` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `short_name` varchar(15) NOT NULL,
  `parent_id` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `short_name` (`short_name`),
  KEY `parent_id` (`parent_id`),
  CONSTRAINT `spec_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `spec` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `spec` 
VALUES 
(35,'Right-hand drive countries','RHD',NULL),
  (2,'United Kingdom & Ireland','UK-spec',35),
    (37,'Ireland','Ireland',2),
  (3,'Australia','AU-spec',35),
  (7,'South Africa','ZA-spec',35),
  (25,'New Zealand','NZ-spec',35),
  (31,'Asian RHD','Asia RHD',35),
    (4,'Japan','JP-spec',31),
    (14,'India','India',31),
    (17,'Hong Kong','HK-spec',31),
    (19,'Malaysia','MY-spec',31),
    (26,'Thailand','TH-spec',31),
    (32,'Singapore','SG-spec',31),
    (44,'Pakistan','Pakistan',31),
(36,'Left-hand drive countries','LHD',NULL),
  (1,'United States & Canada','North America',36),
    (16,'Canada','CA-spec',1),
    (34,'United States of America','US-spec',1),
  (29,'Worldwide except US and RHD countries','Worldwide',36),
    (6,'Europe except United Kingdom & Ireland','EU-spec',29),
      (13,'Finland','FI-spec',6),
      (15,'СНГ','CIS-spec',6),
        (8,'Russian Federation','RU-spec',15),
      (22,'Germany','DE-spec',6),
      (23,'Nederlands','NL-spec',6),
      (27,'Spain','ES-spec',6),
      (30,'France','FR-spec',6),
      (33,'Switzerland','CH-spec',6),
      (38,'Luxembourg','LU-spec',6),
      (39,'Italia','IT-spec',6),
      (40,'Belgium','BE-spec',6),
      (41,'Poland','Poland',6),
      (42,'Hungary','Hungary',6),
      (43,'Greece','Greece',6),
      (47,'Norway','Norway',6),
      (48,'Sweden','Sweden',6),
    (9,'China','China',29),
    (10,'Mexico','MX-spec',29),
    (18,'Taiwan','TW-spec',29),
    (20,'Latin America','Latam',29),
      (5,'Brazil','BR-spec',20),
      (11,'Argentina','AR-spec',20),
    (21,'South Korea','KR-spec',29),
    (24,'Iran','IR-spec',29),
    (45,'Oman','Oman',29),
    (46,'Turkey','Turkey',29),
    (49,'Ethiopia','Ethiopia',29),
    (12,'United Arab Emirates','AE-spec',29),
    (28,'Philippines','Philippines',29);