<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => $this->museum->id ? 116 : 118,
        'args'   => [
            'MUSEUM_ID'   => $this->museum->id,
            'MUSEUM_NAME' => $this->museum->name,
        ]
    ]);

    $this->layout()->moduleName = 'moder/museum/edit';
    $this->layout()->moduleOptions = [
        'addressToLatLngUrl' => $this->url('moder/museum/params', [
            'action' => 'address-to-lat-lng'
        ])
    ];
?>

<div class="well">
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->form
    ])?>
</div>