<?php

    if (!$this->theme) {
        $this->pageEnv([
            'layout' => [
                'blankPage' => false,
                'needRight' => true
            ],
            'pageId' => 42,
        ]);
    } else {
        $this->pageEnv([
            'layout' => [
                'blankPage' => false,
                'needRight' => true
            ],
            'pageId' => 43,
            'args'   => [
                'THEME_NAME' => $this->translate($this->theme['name']),
                'THEME_ID'   => $this->theme['id']
            ]
        ]);

        if ($this->forumAdmin) {
            $this->layout()->moduleName = 'default/forums/theme';
            $this->layout()->moduleOptions = [
                'openUrl'   => $this->openUrl,
                'closeUrl'  => $this->closeUrl,
                'deleteUrl' => $this->deleteUrl
            ];
        }
    }
?>

<?php foreach ($this->themes as $theme) { ?>
    <div class="row">
        <div class="col-md-6">
            <div class="well">
                <p><i class="fa fa-th-list"></i> <strong><?=$this->htmlA([
                    'href'  => $theme['url'],
                    'title' => $this->translate('forums/go-to-theme-%1$s', $this->translate($theme['name']))
                ], $this->translate($theme['name'])) ?></strong></p>
                <?php if ($theme['description']) { ?>
                    <p><?=$this->escapeHtml($theme['description']) ?></p>
                <?php } ?>
                <p>
                    <?=$this->escapeHtml(sprintf($this->translate('%1$s topics', null, $theme['topics']), $theme['topics']))?>,
                    <?=$this->escapeHtml(sprintf($this->translate('%1$s messages', null, $theme['messages']), $theme['messages']))?>
                </p>
                <?php if (count($theme['subthemes'])) { ?>
                    <?=$this->escapeHtml($this->translate('forums/subforums'))?>:
                    <?php foreach ($theme['subthemes'] as $idx => $subtheme) {
                        if ($idx) {
                            print ', ';
                        }
                        print $this->htmlA($subtheme['url'], $this->translate($subtheme['name']));
                    } ?>
                <?php } else { ?>
                    <p><?=$this->htmlA($theme['url'], $this->translate('forums/go-to-theme')) ?></p>
                <?php } ?>
            </div>
        </div>
        <?php if ($theme['lastTopic']) { ?>
            <div class="col-md-6">
                <div class="well transparent">
                    <?php if ($lastMessage = $theme['lastMessage']) { ?>
                        <p>
                            <i class="fa fa-comment"></i>
                            <?=sprintf($this->translate('forums/last-message-in-topic-%1$s'), $this->htmlA($lastMessage['url'], $theme['lastTopic']['name']))?>
                        </p>
                        <p>
                            <?php if ($lastMessage['date']) { ?>
                                <?=$this->pastTimeIndicator($lastMessage['date'])?>
                            <?php } ?>
                            <?php if ($lastMessage['author']) { ?>
                                <?=$this->user($lastMessage['author']) ?>
                            <?php } ?>
                            <?=$this->htmlA([
                                'href'  => $lastMessage['message-url'],
                                'title' => $this->translate('forums/go-to-last-message')
                            ], '<i class="fa fa-share"></i>', false) ?>
                        </p>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>

<?php if ($this->theme && !$this->theme['disable_topics']) { ?>
    <?=$this->htmlA([
        'class' => 'btn btn-info',
        'href'  => $this->newTopicUrl,
    ], '<i class="fa fa-comment"></i> ' . $this->escapeHtml($this->translate('forums/create-new-topic')), false) ?>

    <table class="table table-striped">
        <thead>
            <tr>
                <th><?=$this->escapeHtml($this->translate('forums/theme/topics'))?></th>
                <th><?=$this->escapeHtml($this->translate('forums/theme/author'))?></th>
                <th><?=$this->escapeHtml($this->translate('forums/theme/last-message'))?></th>
                <?php if ($this->forumAdmin) { ?>
                    <th></th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->topics as $topic) { ?>
                <tr>
                    <td>
                        <?=$this->htmlA($topic['url'], $topic['name']) ?>
                        <span class="badge"><?=$topic['oldMessages'] ?><?php if ($topic['newMessages'] > 0) { ?>+<?=$topic['newMessages']?><?php } ?></span>
                        <?=$this->paginationControl($topic['paginator'], 'Sliding', 'application/forums/paginator', [
                            'topic_id' => $topic['id']
                        ]) ?>
                    </td>
                    <td>
                        <?php if ($topic['addDatetime']) { ?>
                            <small><?=$this->pastTimeIndicator($topic['addDatetime'])?></small><br />
                        <?php } ?>
                        <?php if ($topic['author']) { ?>
                            <?=$this->user($topic['author']) ?>
                        <?php } ?>
                    </td>
                    <td>
                        <?php if ($topic['lastMessage']) { ?>
                            <?php if ($topic['lastMessage']['date']) { ?>
                                <small><?=$this->pastTimeIndicator($topic['lastMessage']['date'])?></small><br />
                            <?php } ?>
                            <?php if ($topic['lastMessage']['author']) { ?>
                                <?=$this->user($topic['lastMessage']['author']) ?>
                                <?=$this->htmlA([
                                    'href'  => $topic['lastMessage']['url'],
                                    'title' => $this->translate('forums/go-to-last-message')
                                ], '<i class="fa fa-share"></i>', false) ?>
                            <?php } ?>
                        <?php } else { ?>
                            &#x2014;
                        <?php } ?>
                    </td>
                    <?php if ($this->forumAdmin) { ?>
                        <td>
                            <div class="btn-group">
                                <?php if ($topic['status'] == Autowp\Forums\Forums::STATUS_CLOSED) { ?>
                                    <button title="<?=$this->escapeHtmlAttr($this->translate('forums/topic/open'))?>" class="btn btn-xs btn-warning open" id="open-topic-<?=$topic['id'] ?>">
                                        <i class="fa fa-check-circle"></i>
                                    </button>
                                <?php } else { ?>
                                    <button title="<?=$this->escapeHtmlAttr($this->translate('forums/topic/close'))?>" class="btn btn-xs btn-warning close-topic" id="close-topic-<?=$topic['id'] ?>">
                                        <i class="fa fa-times-circle"></i>
                                    </button>
                                <?php } ?>
                                <?=$this->htmlA([
                                    'href'  => $this->url('forums/move', [
                                        'topic_id' => $topic['id'],
                                    ]),
                                    'class' => 'btn btn-default btn-xs',
                                    'title' => $this->translate('forums/topic/move')
                                ], '<i class="fa fa-share"></i>', false) ?>
                                <button title="<?=$this->escapeHtmlAttr($this->translate('forums/topic/delete'))?>" class="btn btn-xs btn-danger delete" id="delete-topic-<?=$topic['id'] ?>">
                                    <i class="fa fa-ban"></i>
                                </button>
                            </div>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <?php if ($this->paginator) { ?>
        <?=$this->paginationControl($this->paginator, null, null, [
            'route'     => 'forums/index',
            'urlParams' => [
                'theme_id' => $this->theme ? $this->theme['id'] : null
            ]
        ]) ?>
    <?php } ?>
<?php } ?>

<?php if ($this->theme) { ?>
    <p class="text-right small">
        <?=$this->escapeHtml($this->translate('forums/theme/total:'))?>
        <?=$this->escapeHtml(sprintf($this->translate('%1$s topics', null, $this->theme['topics']), $this->theme['topics']))?>,
        <?=$this->escapeHtml(sprintf($this->translate('%1$s messages', null, $this->theme['messages']), $this->theme['messages']))?>
    </p>
<?php } ?>