<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => true
        ],
        'pageId' => 45,
        'args'   => [
            'THEME_NAME' => $this->translate($this->theme['name']),
            'THEME_ID'   => $this->theme['id'],
        ]
    ]);
?>
<?php if ($this->user()->logedIn()) { ?>
    <?php if ($this->needWait) { ?>
        <p class="alert alert-block alert-warning">
            <?=$this->escapeHtml($this->translate('forums/need-wait-to-post'))?>
        </p>
    <?php } ?>
    <?=$this->partial('application/forms/bootstrap-horizontal', [
        'form' => $this->formTopicNew
    ])?>
<?php } else { ?>
    <div class="alert alert-block alert-error">
        <?=$this->markdown($this->translate('forums/register-to-create-topic'))?>
    </div>
<?php } ?>