<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => true
        ],
        'pageId' => 44,
        'args'   => [
            'THEME_NAME' => $this->translate($this->theme['name']),
            'THEME_ID'   => $this->theme['id'],
            'TOPIC_NAME' => $this->topic['name'],
            'TOPIC_ID'   => $this->topic['id']
        ]
    ]);

    $this->layout()->moduleName = 'default/forums/topic';
?>

<section class="forum-topic-page comments" data-module="comments" data-comments-item-id="<?=$this->topic['id']?>" data-comments-type="<?=Autowp\Comments\CommentsService::FORUMS_TYPE_ID?>">
    <?=$this->partial('application/comments/messages', [
        'messages'          => $this->messages,
        'canRemoveComments' => $this->canRemoveComments,
        'canAddComments'    => $this->canAddComments,
        'canViewIp'         => $this->canViewIp,
        'canMoveMessage'    => $this->canMoveMessage,
        'moveMessageRoute'  => $this->moveMessageRoute,
        'moveMessageUrl'    => $this->moveMessageUrl
    ])?>

    <div class="row" style="margin-bottom:10px">
        <div class="col-sm-6">
            <?=$this->paginationControl($this->paginator, null, null, [
                'route'     => 'forums/topic',
                'urlParams' => [
                    'topic_id' => $this->topic['id']
                ]
            ]) ?>
        </div>
        <div class="col-sm-6 text-right">
            <?php if ($this->canSubscribe) { ?>
                <form action="<?=$this->escapeHtmlAttr($this->subscribeUrl) ?>" method="post"><div>
                    <i class="fa fa-envelope"></i>
                    <a href="#" onclick="this.parentNode.parentNode.submit();return false;">
                        <?=$this->escapeHtml($this->translate('forums/subscribe'))?>
                    </a>
                </div></form>
            <?php } ?>
            <?php if ($this->canUnsubscribe) { ?>
                <form action="<?=$this->escapeHtmlAttr($this->unsubscribeUrl) ?>" method="post"><div>
                    <i class="fa fa-envelope"></i>
                    <?=$this->escapeHtml($this->translate('forums/subscribed'))?>
                    <a href="#" onclick="this.parentNode.parentNode.submit();return false;">
                        <?=$this->escapeHtml($this->translate('forums/unsubscribe'))?>
                    </a>
                </div></form>
            <?php } ?>
        </div>
    </div>

    <?php if ($this->topic['status'] == Application\Model\Forums::STATUS_NORMAL) { ?>
        <?php if (!$this->user()->logedIn()) { ?>
            <div class="well">
                <?=$this->markdown($this->translate('forums/register-to-post'))?>
            </div>
        <?php } ?>
        <?php if ($this->canAddComments) { ?>
            <?php if ($this->needWait) { ?>
                <p class="alert alert-block alert-warning">
                    <?=$this->escapeHtml($this->translate('forums/need-wait-to-post'))?>
                </p>
            <?php } ?>
            <div class="form-holder">
                <?=$this->partial('application/forms/comment', [
                    'form' => $this->formMessageNew
                ])?>
            </div>
        <?php } ?>
    <?php } else { ?>
        <p class="alert alert-block alert-error">
            <?=$this->escapeHtml($this->translate('forums/topic-closed-text'))?>
        </p>
    <?php } ?>
</section>