<?php if (count($this->carList)) { ?>
    <?php if ($this->brand->img) { ?>
        <?=$this->htmlA($this->url('catalogue', [
            'action'        => 'brand',
            'brand_catname' => $this->brand->folder
        ]), $this->img($this->brand->img, [
            'alt'    => '',
            'title'  => ($this->brandLang ? $this->brandLang->name : $this->brand->caption),
            'style'  => "float:right;margin:0 0 5px 5px",
            'format' => 'brandicon2'
        ]), false)?>
    <?php } ?>
    <?php foreach ($this->carList as $car) {?>
        <p><?=$this->escapeHtml($car->getFullName($this->language()))?></p>
    <?php } ?>
    <br style="clear:both" />
<?php } ?>