<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 153,
        'args'   => array(
            'BRAND_NAME'    => $this->brand->caption,
            'BRAND_CATNAME' => $this->brand->folder
        )
    ));
?>
<?=$this->partial('twins/partial/list.phtml', array(
    'groups'  => $this->groups,
    'canEdit' => $this->canEdit
))?>
<?=$this->paginationControl($this->paginator) ?>