<?php
    $this->layout()->assign(array(
        'blankPage' => false,
        'needLeft'  => true,
        'needRight' => false
    ));
    $title = $this->page->name . ' ' . $this->brand->caption;
    $this->pageTitle($title);
    $this->headTitle($title, 'SET');
    $this->breadcrumbs($this->url(array(
        'action'        => 'brand',
        'brand_catname' => $this->brand->folder
    ), 'twins', true), $this->brand->caption);
?>
<?=$this->twinsGroupList($this->paginator->getCurrentItems()) ?>
<?=$this->paginationControl($this->paginator) ?>