<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 26,
        'args'   => array(
            'TWINS_GROUP_NAME' => $this->group->name,
            'TWINS_GROUP_ID'   => $this->group->id
        )
    ));
?>

<?php foreach ($this->cars as $car) { ?>
    <h3><?=$this->escape($car['name'])?></h3>
    <?=$this->pictureListHorizontal2($car['pictures'])?>
<?php } ?>

<ul class="carLinks">
    <?php if ($this->hasSpecs) {?>
        <li>
            <span class="glyphicon glyphicon-list-alt"></span>
            <?=$this->htmlA($this->specsUrl, 'технические характеристики')?>
        </li>
    <?php } ?>

    <?php if ($this->picturesCount) { ?>
        <li>
            <span class="glyphicon glyphicon-th"></span>
            <?=$this->htmlA($this->picturesUrl, 'все картинки ('.$this->picturesCount.')')?>
        </li>
    <?php } ?>
</ul>

<?php if (strlen($this->group->description)){ ?>
    <h3>Описание</h3>
    <div class="well"><?=$this->group->description ?></div>
<?php } ?>

<?=$this->action('comments', 'comments', 'default', array(
    'type'    => Comment_Message::TWINS_TYPE_ID,
    'item_id' => $this->group->id
)) ?>