<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 26,
        'args'   => array(
            'TWINS_GROUP_NAME' => $this->group['name'],
            'TWINS_GROUP_ID'   => $this->group['id']
        )
    ));
?>

<?=$this->partial('cars.phtml', $this->cars)?>

<ul class="carLinks">
    <?php if ($this->hasSpecs) {?>
        <li>
            <i class="fa fa-list-alt"></i>
            <?=$this->htmlA($this->specsUrl, 'технические характеристики')?>
        </li>
    <?php } ?>

    <?php if ($this->picturesCount) { ?>
        <li>
            <i class="fa fa-th"></i>
            <?=$this->htmlA($this->picturesUrl, 'все картинки ('.$this->picturesCount.')')?>
        </li>
    <?php } ?>
</ul>

<?php if (strlen($this->description)){ ?>
    <h3>Описание</h3>
    <div class="well"><?=$this->markdown($this->description) ?></div>
<?php } ?>

<?=$this->action('comments', 'comments', 'default', array(
    'type'    => Comment_Message::TWINS_TYPE_ID,
    'item_id' => $this->group['id']
)) ?>