<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 26,
        'args'   => array(
            'TWINS_GROUP_NAME' => $this->group->name,
            'TWINS_GROUP_ID'   => $this->group->id
        )
    ));
?>

<?=$this->getHelper('twinsGroupList')->detailed($this->group) ?>

<?php if (strlen($this->group->description)){ ?>
    <h3>Описание</h3>
    <div class="well"><?=$this->group->description ?></div>
<?php } ?>

<?=$this->action('comments', 'comments', 'default', array(
    'type'    => Comments_Messages::TWINS_TYPE_ID,
    'item_id' => $this->group->id
)) ?>