<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 183,
        'args'   => array(
            'PICTURE_NAME'     => $this->pic()->textTitle($this->name),
            'TWINS_GROUP_NAME' => $this->group['name'],
            'TWINS_GROUP_ID'   => $this->group['id']
        )
    ));
?>
<?=$this->render('picture/picture.phtml')?>