<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => true,
            'needRight' => false
        ),
        'pageId' => 28,
        'args'   => array(
            'TWINS_GROUP_NAME' => $this->group['name'],
            'TWINS_GROUP_ID'   => $this->group['id']
        )
    ));
?>
<?=$this->partial('pictures.phtml', $this->picturesData)?>
<?=$this->paginationControl($this->paginator) ?>