<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ),
        'pageId' => 27,
        'args'   => array(
            'TWINS_GROUP_NAME' => $this->group->name,
            'TWINS_GROUP_ID'   => $this->group->id
        )
    ));
?>
<?=$this->specifications($this->carList) ?>