export const environment = {
  apiUrl: '',
  grpcHost: '',
  ssrGrpcHost: 'localhost:8080',
  keycloak: {
    clientId: 'frontend',
    realm: 'autowp',
    url: 'https://auth.wheelsage.org/auth/',
  },
  languages: [
    {
      code: 'en',
      flag: 'flag-icon flag-icon-gb',
      hostname: 'en.wheelsage.org',
      locale: 'en-GB',
      name: 'English',
    },
    {
      code: 'zh',
      flag: 'flag-icon flag-icon-cn',
      hostname: 'zh.wheelsage.org',
      locale: 'zh-CN',
      name: '中文',
    },
    {
      code: 'ru',
      flag: 'flag-icon flag-icon-ru',
      hostname: 'www.autowp.ru',
      locale: 'ru',
      name: 'Русский',
    },
    {
      code: 'pt-br',
      flag: 'flag-icon flag-icon-br',
      hostname: 'br.wheelsage.org',
      locale: 'pt-BR',
      name: 'Português brasileiro',
    },
    {
      code: 'fr',
      flag: 'flag-icon flag-icon-fr',
      hostname: 'fr.wheelsage.org',
      locale: 'fr',
      name: 'Français',
    },
    {
      code: 'be',
      flag: 'flag-icon flag-icon-by',
      hostname: 'be.wheelsage.org',
      locale: 'be',
      name: 'Беларуская',
    },
    {
      code: 'uk',
      flag: 'flag-icon flag-icon-ua',
      hostname: 'uk.wheelsage.org',
      locale: 'uk',
      name: 'Українська',
    },
    {
      code: 'es',
      flag: 'flag-icon flag-icon-es',
      hostname: 'es.wheelsage.org',
      locale: 'es-ES',
      name: 'Español',
    },
    {
      code: 'it',
      flag: 'flag-icon flag-icon-it',
      hostname: 'it.wheelsage.org',
      locale: 'it',
      name: 'Italiano',
    },
    {
      code: 'he',
      flag: 'flag-icon flag-icon-he',
      hostname: 'he.wheelsage.org',
      locale: 'he',
      name: 'עִברִית',
    },
  ],
  production: true,
};
