<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 110
    ]);
?>
<div class="row">
    <div class="col-md-4">
        <h2><?=$this->escapeHtml($this->translate('moder/comments/filter'))?></h2>
        <div class="well">
            <?=$this->partial('application/forms/bootstrap-vertical', [
                'form' => $this->form
            ])?>
        </div>
    </div>
    <div class="col-md-8">
        <h2>
            <?=$this->escapeHtml($this->translate('moder/comments/title'))?>
            <?php if ($count = $this->paginator->getTotalItemCount()) {?>
                <small><?=$this->escapeHtml(sprintf($this->translatePlural('%1$s comments', null, $count), $count)) ?></small>
            <?php } ?>
        </h2>
        <ul class="comments">
            <?php foreach ($this->comments as $comment) { ?>
                <li>
                    <?php if ($comment['new']) { ?>
                        <span class="label label-warning"><?=$this->escapeHtml($this->translate('moder/comments/not-readed'))?></span>
                    <?php } ?>
                    <?=$comment['status']?>
                    <?=$this->htmlA($comment['url'], $comment['message'])?>
                    <?php if ($comment['user']) { ?>
                        <?=$this->user($comment['user']) ?>
                    <?php } ?>
                </li>
            <?php } ?>
        </ul>
        <?=$this->paginationControl($this->paginator, null, null, [
            'route'     => 'moder/comments/params',
            'urlParams' => $this->urlParams
        ]) ?>
    </div>
</div>