<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
        'pageId' => 143,
        'args'   => array(
            'TWINS_GROUP_NAME' => $this->group->name,
            'TWINS_GROUP_ID'   => $this->group->id
        )
    ));
?>
<?php
    $url = $this->url(array(
        'module' => 'default',
        'controller' => 'twins',
        'action' => 'group',
        'twins_group_id' => $this->group->id
    ), 'twins', true);
?>
<div class="row">
    <div class="col-md-6">
        <div class="well">
            <p>
                В базе данных чиcлится под номером <strong><?=$this->group->id ?></strong><br />
                На сайте: <?=$this->htmlA($url, $url) ?><br />
                <?=$this->htmlA($this->url(array(
                    'module' => 'default',
                    'controller' => 'log',
                    'action' => 'index',
                    'twins_group_id' => $this->group->id
                ), 'default', true), 'Журнал событий по группе') ?>
            </p>
        </div>

        <h2>Мета-информация</h2>
        <div class="well">

            <?php if ($this->canEdit) { ?>
                <?=$this->formEdit->render($this) ?>
            <?php } else { ?>
                <table><tbody>
                    <tr>
                        <td>Название</td>
                        <td><?=$this->escape($this->group->name) ?></td>
                    </tr>
                    <tr>
                        <td>Описание</td>
                        <td><?=$this->group->description ?></td>
                    </tr>
                </tbody></table>
            <?php } ?>
        </div>

        <h3>Краткое описание</h3>
        <div class="well">
            <?php if ($this->canEdit) { ?>
                <?=$this->descriptionForm->render($this)?>
            <?php } else { ?>
                <?=$this->markup($this->description)?>
            <?php } ?>
            <?php if ($this->group->text_id) { ?>
                <p>
                    <?=$this->htmlA(array(
                        'class' => 'pull-right',
                        'href'  => $this->url(array(
                            'module'     => 'default',
                            'controller' => 'info',
                            'action'     => 'text',
                            'id'         => $this->group->text_id
                        ), null, true)
                    ), 'History')?>
                </p>
            <?php } ?>
        </div>
    </div>
    <div class="col-md-6">
        <h2>Автомобили</h2>
        <div class="well">
            <ul>
                <?php foreach ($this->group->findCarsViaTwins_Groups_Cars() as $car) { ?>
                    <li>
                        <?=$this->htmlA($this->url(array(
                            'module' => 'moder',
                            'controller' => 'cars',
                            'action' => 'car',
                            'car_id' => $car->id
                        ), 'default', true), $car->getFullName()) ?>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>
</div>