<?php
    $this->pageEnv(array(
        'layout' => array(
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => true
        ),
        'pageId' => 43,
        'args'   => array(
            'THEME_NAME' => $this->translate($this->theme->caption),
            'THEME_ID'   => $this->theme->id
        )
    ));

    if ($this->forumAdmin) {
        $this->layout()->moduleName = 'forums/theme/theme';
        $this->layout()->moduleOptions = array(
            'openUrl' => $this->url(array(
                'module'     => 'forums',
                'controller' => 'topic',
                'action'     => 'open'
            ), null, true),
            'closeUrl' => $this->url(array(
                'module'     => 'forums',
                'controller' => 'topic',
                'action'     => 'close'
            ), null, true),
            'deleteUrl' => $this->url(array(
                'module'     => 'forums',
                'controller' => 'topic',
                'action'     => 'delete'
            ), null, true)
        );
    }
?>

<?php foreach ($this->themes as $theme) { ?>
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="well">
                <p><span class="glyphicon glyphicon-th-list"></span> <strong><?=$this->htmlA(array(
                    'href'  => $theme['url'],
                    'title' => $this->translate('forums/go-to-theme-%1$s', $this->translate($theme['name']))
                ), $this->translate($theme['name'])) ?></strong></p>
                <?php if ($theme['description']) { ?>
                    <p><?=$this->escape($theme['description']) ?></p>
                <?php } ?>
                <p>
                    <?=$this->escape($this->translate(['%1$s topics', null, $theme['topics']], $theme['topics']))?>,
                    <?=$this->escape($this->translate(['%1$s messages', null, $theme['messages']], $theme['messages']))?>
                </p>
                <p><?=$this->htmlA($theme['url'], $this->translate('forums/go-to-theme')) ?></p>
            </div>
        </div>
        <?php if ($topic = $theme['lastTopic']) { ?>
            <div class="col-lg-6 col-md-6">
                <div class="well transparent">
                    <?php if ($lastMessage = $theme['lastMessage']) { ?>
                        <p>
                            <span class="glyphicon glyphicon-comment"></span>
                            <?=$this->translate('forums/last-message-in-topic-%1$s', $this->htmlA($this->url(array(
                                'controller' => 'topic',
                                'action'     => 'topic',
                                'topic_id'   => $topic->id
                            )), $topic->caption))?>
                        </p>
                        <p>
                            <?php if ($date = $lastMessage->getDate('datetime')) { ?>
                                <?=$this->pastTimeIndicator($date)?>
                            <?php } ?>
                            <?php if ($lastMessageAuthor = $lastMessage->findParentUsersByAuthor()) { ?>
                                <?=$this->user($lastMessageAuthor) ?>
                            <?php } ?>
                            <?=$this->htmlA(array(
                                'href'  => $this->url(array(
                                    'controller' => 'topic',
                                    'action'     => 'topic-message',
                                    'message_id' => $lastMessage->id
                                )),
                                'title' => $this->translate('forums/go-to-last-message')
                            ), '<img src="/img/forums/icon_latest_reply.gif" alt="-&gt;" style="width:18px;height:9px" />', false) ?>
                        </p>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>

<?php if (!$this->theme->disable_topics) { ?>
    <?=$this->htmlA(array(
        'class' => 'btn btn-info',
        'href'  => $this->url(array(
            'controller' => 'topic',
            'action'     => 'new'
        )),
    ), '<span class="glyphicon glyphicon-comment"></span> ' . $this->escape($this->translate('forums/create-new-topic')), false) ?>

    <table class="table table-striped">
        <thead>
            <tr>
                <th><?=$this->escape($this->translate('forums/theme/topics'))?></th>
                <th><?=$this->escape($this->translate('forums/theme/author'))?></th>
                <th><?=$this->escape($this->translate('forums/theme/last-message'))?></th>
                <?php if ($this->forumAdmin) { ?>
                    <th></th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->topics as $topic) { ?>
                <tr>
                    <td>
                        <?=$this->htmlA($topic['url'], $topic['name']) ?>
                        <span class="badge"><?=$topic['oldMessages'] ?><?php if ($topic['newMessages'] > 0) { ?>+<?=$topic['newMessages']?><?php } ?></span>
                        <?=$this->paginationControl($topic['paginator'], 'Sliding', 'theme/paginator.phtml', array(
                            'topic_id' => $topic['id']
                        )) ?>
                    </td>
                    <td>
                        <?php if ($topic['addDatetime']) { ?>
                            <small><?=$this->pastTimeIndicator($topic['addDatetime'])?></small><br />
                        <?php } ?>
                        <?php if ($topic['author']) { ?>
                            <?=$this->user($topic['author']) ?>
                        <?php } ?>
                    </td>
                    <td>
                        <?php if ($topic['lastMessage']) { ?>
                            <?php if ($topic['lastMessageDate']) { ?>
                                <small><?=$this->pastTimeIndicator($topic['lastMessageDate'])?></small><br />
                            <?php } ?>
                            <?php if ($topic['lastMessageAuthor']) { ?>
                                <?=$this->user($topic['lastMessageAuthor']) ?>
                                <?=$this->htmlA(array(
                                    'href'  => $topic['lastMessageUrl'],
                                    'title' => 'Перейти к последнему сообщению'
                                ), '<img src="/img/forums/icon_latest_reply.gif" alt="-&gt;" style="width:18px;height:9px" />', false) ?>
                            <?php } ?>
                        <?php } else { ?>
                            &#x2014;
                        <?php } ?>
                    </td>
                    <?php if ($this->forumAdmin) { ?>
                        <td>
                            <div class="btn-group">
                                <?php if ($topic['status'] == Forums_Topics::STATUS_CLOSED) { ?>
                                    <button title="открыть" class="btn btn-xs btn-warning open" id="open-topic-<?=$topic['id'] ?>">
                                        <span class="glyphicon glyphicon-ok-circle"></span>
                                    </button>
                                <?php } else { ?>
                                    <button title="закрыть" class="btn btn-xs btn-warning close-topic" id="close-topic-<?=$topic['id'] ?>">
                                        <span class="glyphicon glyphicon-remove-circle"></span>
                                    </button>
                                <?php } ?>
                                <?=$this->htmlA(array(
                                    'href'  => $this->url(array(
                                        'module'     => 'forums',
                                        'controller' => 'topic',
                                        'action'     => 'move',
                                        'topic_id'   => $topic['id'],
                                        'theme_id'   => null
                                    )),
                                    'class' => 'btn btn-default btn-xs',
                                    'title' => 'переместить'
                                ), '<span class="glyphicon glyphicon-share-alt"></span>', false) ?>
                                <button title="удалить" class="btn btn-xs btn-danger delete" id="delete-topic-<?=$topic['id'] ?>">
                                    <span class="glyphicon glyphicon-ban-circle"></span>
                                </button>
                            </div>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <?=$this->paginationControl($this->paginator) ?>
<?php } ?>

<p style="text-align:right" class="small">
    <?=$this->escape($this->translate('forums/theme/total:'))?>
    <?=$this->escape($this->translate(['%1$s topics', null, $this->theme->topics], $this->theme->topics))?>,
    <?=$this->escape($this->translate(['%1$s messages', null, $this->theme->messages], $this->theme->messages))?>
</p>