<div class="comments">
    <?php foreach ($this->messages as $message) { ?>
        <div class="message">
            <div>
                <?php if ($message['author']) { ?>
                    <?=$this->user($message['author'])?>
                <?php } else { ?>
                    <?=$this->escape($this->translate('account/personal-message/system-notification'))?>
                <?php } ?>
            </div>
            <div class="photo">
                <?php if ($message['author'] && !$message['author']->deleted) { ?>
                    <?=$this->htmlA($message['authorUrl'], $this->user($message['author'])->avatar(), false)?>
                <?php } ?>
            </div>
            <div class="content">
                <div class="text">
                    <p><?=$message['contents']?></p>
                </div>
                <div>
                    <?php if ($message['isNew']) { ?>
                        <span class="label label-info">новое</span>
                    <?php } ?>
                    <?php if ($message['canDelete']) { ?>
                        <?=$this->htmlA(array(
                            'href'         => '#',
                            'class'        => 'pull-right',
                            'data-trigger' => 'delete-pm',
                            'data-id'      => $message['id']
                        ), '<span class="glyphicon glyphicon-trash"></span> ' . $this->escape($this->translate('account/personal-message/delete')), false)?>
                    <?php } ?>
                    <?php if ($message['canReply']) { ?>
                        <span class="glyphicon glyphicon-share-alt"></span>
                        <?=$this->htmlA(array(
                            'href'         => '#',
                            'data-trigger' => 'show-pm-dialog',
                            'data-user-id' => $message['author']->id
                        ), $this->translate('account/personal-message/reply')) ?>
                        &nbsp;
                        <?php if ($message['allMessagesLink']) { ?>
                            <span class="glyphicon glyphicon-align-justify"></span>
                            <?=$this->htmlA($this->url(array(
                                'controller' => 'account',
                                'action'     => 'personal-messages-user',
                                'user_id'    => $message['author']->id
                            )), $this->translate('account/personal-message/entire-dialog')) ?>
                            <small>(<?=$message['dialogCount']?>)</small>
                            &nbsp;
                        <?php } ?>
                    <?php } ?>
                    <?php if ($message['date']) { ?>
                        <span class="glyphicon glyphicon-time"></span>
                        <?=$this->escape($this->user()->humanTime($message['date']))?>
                    <?php } ?>
                </div>
            </div>
        </div>
    <?php } ?>
</div>