<fieldset>
    <?php if ($legend = $this->element->getLegend()) { ?>
        <legend><?=$this->escape($legend)?></legend>
    <?php } ?>
    <?php foreach ($this->element->getElements() as $element) { ?>
        <?php if ($element instanceof Zend_Form_Element) { ?>
            <?php if ($element instanceof Zend_Form_Element_File) { ?>
                <div class="form-group<?=$element->hasErrors() ? ' has-error' : ''?>">
                    <label class="control-label" for="<?=$element->getId()?>"><?=$this->escape($element->getLabel())?></label>
                    <?=$element?>
                    <?php foreach ($element->getMessages() as $error) { ?>
                        <p class="help-block"><?=$this->escape($error)?></p>
                    <?php } ?>
                </div>
            <?php } elseif ($element instanceof Zend_Form_Element_Multicheckbox) { ?>
                <div class="form-group<?=$element->hasErrors() ? ' has-error' : ''?>">
                    <label class="control-label" for="<?=$element->getId()?>"><?=$this->escape($element->getLabel())?></label>
                    <?=$element?>
                    <?php foreach ($element->getMessages() as $error) { ?>
                        <p class="help-block"><?=$this->escape($error)?></p>
                    <?php } ?>
                </div>
            <?php } elseif ($element instanceof Zend_Form_Element_Checkbox) { ?>
                <div class="checkbox<?=$element->hasErrors() ? ' has-error' : ''?>">
                    <label>
                        <?=$element?>
                        <?=$this->escape($element->getLabel())?>
                    </label>
                    <?php foreach ($element->getMessages() as $error) { ?>
                        <p class="help-block"><?=$this->escape($error)?></p>
                    <?php } ?>
                </div>
            <?php } elseif (!$element instanceof Zend_Form_Element_Submit) { ?>
                <div class="form-group<?=$element->hasErrors() ? ' has-error' : ''?>">
                    <label class="control-label" for="<?=$element->getId()?>"><?=$this->escape($element->getLabel())?></label>
                    <?=$element->setAttrib('class', $element->getAttrib('class') . ' form-control')?>
                    <?php foreach ($element->getMessages() as $error) { ?>
                        <p class="help-block"><?=$this->escape($error)?></p>
                    <?php } ?>
                </div>
            <?php } ?>
        <?php } elseif ($element instanceof Zend_Form) { ?>
            <?=$element->render($this)?>
        <?php } elseif ($element instanceof Zend_Form_DisplayGroup) { ?>
            <div class="form-group">
                <label class="control-label"><?=$this->escape($element->getLegend())?></label>
                <?=$element->render($this)?>
            </div>
        <?php } ?>
    <?php } ?>
    <?php
        $submitFound = false;
    ?>
    <?php foreach ($this->element as $element) { ?>
        <?php if ($element instanceof Zend_Form_Element_Submit) { ?>
            <?php
                $element->setAttrib(
                    'class',
                    $element->getAttrib('class') . ($element->getAttrib('class') ? ' ' : '') . 'btn'
                );
                if (!$submitFound) {
                    $element->setAttrib(
                        'class',
                        $element->getAttrib('class') . ' btn-primary'
                    );
                    $submitFound = true;
                }
            ?>
            <div class="form-group">
                <?=$element ?>
            </div>
        <?php } ?>
    <?php } ?>
    <?php if ($desc = $this->element->getDescription()) { ?>
        <p><?=$this->escape($desc)?></p>
    <?php } ?>
    <?php if (!$submitFound && !$this->element instanceof Zend_Form_SubForm) { ?>
        <?=$this->formSubmit('submit', $this->translate('sumbit'), array(
            'class' => 'btn btn-primary'
        ))?>
    <?php } ?>

</fieldset>