<table cellspacing="0">
    <tr>
        <td style="text-align:right;white-space:nowrap">
            <?=$this->element->rimwidth ?>J x
        </td>
        <td rowspan="2" style="font-size:20px;vertical-align:middle;text-aleign:left;white-space:nowrap">
            R<?=$this->element->radius ?>
        </td>
    </tr>
    <tr><td style="text-align:right;white-space:nowrap">
        <?=$this->element->tyrewidth ?>
        /
        <?=$this->element->tyreseries ?>
    </td></tr>
</table>