<?php if (count($this->attributes)) { ?>
    <ul>
        <?php foreach ($this->attributes as $attribute) { ?>
            <li>
                <label>
                    <input type="checkbox" name="attribute_id[]" id="attribute_id_<?=$attribute['id']?>" value="<?=$attribute['id']?>" <?=$attribute['checked'] ? 'checked' : ''?> />
                    <?=$this->escapeHtml($this->translate($attribute['name'])) ?>
                </label>
                <?=$this->partial('application/moder/attrs/zone/attributes-list-partial', [
                    'attributes' =>  $attribute['childAttributes']
                ]) ?>
            </li>
        <?php } ?>
    </ul>
<?php } ?>