<?php foreach ($this->attributes as $idx => $attribute) { ?>
    <tr>
        <td>
            <?php if ($idx > 0) { ?>
                <form action="<?=$this->escapeHtmlAttr($attribute['moveUpUrl']) ?>">
                    <button type="submit" class="btn btn-link btn-sm">
                        <span class="fa fa-arrow-up"></span>
                    </button>
                </form>
            <?php } ?>
        </td>
        <td>
            <?php if ($idx < count($this->attributes)-1) { ?>
                <form action="<?=$this->escapeHtmlAttr($attribute['moveDownUrl']) ?>">
                    <button type="submit" class="btn btn-link btn-sm">
                        <span class="fa fa-arrow-down"></span>
                    </button>
                </form>
            <?php } ?>
        </td>
        <td>
            <?=str_repeat('——', $this->deep) ?>
            <?=$this->htmlA($this->url('moder/attrs/params', [
                'action'       => 'attribute',
                'attribute_id' => $attribute['id']
            ]), $this->translate($attribute['name'])) ?>
        </td>
    </tr>
    <?=$this->partial('application/moder/attrs/zone/attributes-rows-partial', [
        'attributes' => $attribute['childAttributes'],
        'deep'       => $this->deep + 1
    ]) ?>
<?php } ?>