<?php if (count($this->attributes)) { ?>
    <ul>
        <?php foreach ($this->attributes as $attribute) { ?>
            <li>
                <label>
                    <input type="checkbox" name="attribute_id[]" id="attribute_id_<?=$attribute->id?>" value="<?=$attribute->id?>" <?=$this->zone->hasAttribute($attribute) ? 'checked' : ''?> />
                    <?=$this->escapeHtml($attribute->name) ?>
                </label>
                <?=$this->partial('application/moder/attrs/zone/attributes-list-partial', [
                    'zone'       =>  $this->zone,
                    'attributes' =>  $attribute->getTable()->fetchAll(
                        $attribute->getTable()->select()
                            ->where('parent_id = ?', $attribute->id)
                    ),
                ]) ?>
            </li>
        <?php } ?>
    </ul>
<?php } ?>