<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ],
        'pageId' => 143,
        'args'   => [
            'TWINS_GROUP_NAME' => $this->group->name,
            'TWINS_GROUP_ID'   => $this->group->id
        ]
    ]);
?>
<?php
    $url = $this->url('twins/group', [
        'id' => $this->group->id
    ]);
?>
<div class="row">
    <div class="col-md-6">
        <div class="well">
            <p><?=$this->escapeHtml(sprintf($this->translate('moder/database-id-%s'), $this->group->id))?></p>
            <p>
                На сайте: <?=$this->htmlA($url, $url) ?><br />
                <?=$this->htmlA($this->url('log/params', [
                    'twins_group_id' => $this->group->id
                ]), $this->translate('moder/log-of-events')) ?>
            </p>
        </div>

        <h2>Мета-информация</h2>
        <div class="well">

            <?php if ($this->canEdit) { ?>
                <?=$this->partial('application/forms/bootstrap-horizontal', [
                    'form' => $this->editForm
                ])?>
            <?php } else { ?>
                <table><tbody>
                    <tr>
                        <td>Название</td>
                        <td><?=$this->escapeHtml($this->group->name) ?></td>
                    </tr>
                </tbody></table>
            <?php } ?>
        </div>

        <h3>Краткое описание</h3>
        <div class="well">
            <?php if ($this->canEdit) { ?>
                <?=$this->partial('application/forms/markdown', [
                    'form' => $this->descForm
                ])?>
            <?php } else { ?>
                <?=$this->markdown($this->description)?>
            <?php } ?>
            <?php if ($this->group->text_id) { ?>
                <p>
                    <?=$this->htmlA([
                        'class' => 'pull-right',
                        'href'  => $this->url('info/text', [
                            'id' => $this->group->text_id
                        ])
                    ], 'History')?>
                </p>
            <?php } ?>
        </div>
    </div>
    <div class="col-md-6">
        <h2>Автомобили</h2>
        <div class="well">
            <ul>
                <?php foreach ($this->cars as $car) { ?>
                    <li>
                        <?=$this->htmlA($this->url('moder/cars/params', [
                            'action' => 'car',
                            'car_id' => $car->id
                        ]), $car->getFullName($this->language())) ?>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>
</div>