<h3>Авторизация</h3>
<div class="well">
    <?php if ($this->user()->logedIn()) { ?>
        <div>
            Здравствуйте, <?=$this->user() ?><br />
            <a href="/account/profile/">Личная страница</a><br />
            <a href="/login/logout/">Выход</a>
        </div>
        <p>
            <span class="glyphicon glyphicon-comment"></span>
            <?php if ($this->newPersonalMessages > 0) { ?>
                <?=$this->htmlA(array(
                    'href'  => '/account/pm/',
                    'class' => 'label label-danger'
                ), $this->translate(array('layout/you-have-%1$s-new-messages', null, $this->newPersonalMessages), $this->newPersonalMessages))?>
            <?php } else { ?>
                <?=$this->htmlA('/account/pm/', $this->translate('layout/personal-messages'))?>
            <?php } ?>
        </p>
    <?php } else { ?>
        <form action="/login/" method="post" class="login"><div>
            <p><input type="text" name="login" placeholder="Логин или e-mail" class="form-control" /></p>
            <p><input type="password" name="password" placeholder="Пароль" class="form-control" /></p>
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="1" name="remember" /> запомнить?
                </label>
            </div>
            <div>
                <div class="pull-right text-right">
                    <a href="/registration/">Регистрация</a><br />
                    <a href="/restorepassword/">Забыли пароль?</a>
                </div>
                <input type="submit" value="войти" class="btn btn-primary" />
            </div>
        </div></form>
    <?php } ?>
</div>

<a class="twitter-timeline"  href="https://twitter.com/autowp_ru"  data-widget-id="323907714319253505" data-chrome="nofooter" width="370" height="730">Твиты пользователя @autowp_ru</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>