<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 73,
    ]);
    $this->layout()->moduleName = 'moder/pictures/index';
    $this->layout()->moduleOptions = [
        'acceptUrl' => $this->url('moder/pictures/params', [
            'action' => 'accept'
        ], [], true),
        'voteUrl' => $this->url('moder/pictures/params', [
            'action' => 'vote'
        ], [], true),
    ];
?>
<ul class="nav nav-pills">
    <li>
        <?=$this->htmlA('/moder/pictures/index/order/1/status/inbox', $this->translate('moder/picture/inbox'))?>
    </li>
    <li>
        <?=$this->htmlA('/moder/pictures/index/order/1/status/accepted/perspective_id/null/type_id/1', $this->translate('moder/picture/missing-perspective'))?>
    </li>
    <li>
        <?=$this->htmlA('/moder/pictures/index/order/1/status/removing', $this->translate('moder/picture/delete-queue'))?>
    </li>
    <li>
        <?=$this->htmlA('/moder/pictures/index/order/1/requests/3/status/custom1', $this->translate('moder/picture/votes'))?>
    </li>
    <li>
        <?=$this->htmlA('/moder/pictures/index/order/7/comments/1', $this->translate('moder/picture/comments'))?>
    </li>
    <li>
        <?=$this->htmlA('/moder/pictures/index/order/9/requests/3/status/custom1/', $this->translate('moder/picture/new-votes'))?>
    </li>
    <li>
        <?=$this->htmlA('/moder/pictures/index/order/1/status/inbox/replace/1', $this->translate('moder/picture/replaces'))?>
    </li>
</ul>
<div class="row">
    <div class="col-lg-4 col-md-4">
        <h2>Фильтр</h2>
        <div class="well">
            <?=$this->partial('application/forms/bootstrap-vertical', [
                'form' => $this->form
            ])?>
        </div>
    </div>
    <div class="col-lg-8 col-md-8">

        <div class="toolbar clearfix">
            <button class="btn btn-success btn-accept pull-left" disabled="disabled">Принять</button>

            <div class="input-group-btn pull-left" style="margin-left:20px">
                <button type="button" class="btn btn-default dropdown-toggle dropdown-reason-toggle" data-toggle="dropdown" aria-expanded="true">Сообщение <span class="caret"></span></button>
                <ul class="dropdown-menu dropdown-reason" role="menu">
                    <?php foreach ($this->reasons as $reason) { ?>
                        <li><?=$this->htmlA([
                            'href'        => '#',
                            'data-reason' => $reason
                        ], $reason)?></li>
                    <?php } ?>
                    <?php /*<li class="divider"></li>
                    <li><a href="#">Своя</a></li>*/?>
                </ul>
                <button name="vote" class="btn btn-success btn-vote" data-vote="1">Хочу принять</button>
                <button name="vote" class="btn btn-danger btn-vote" data-vote="0">Хочу удалить</button>
            </div>
        </div>

        <h2>
            <?=$this->escapeHtml($this->page(73)->name)?>
            <?php if ($count = $this->paginator->getTotalItemCount()) {?>
                <small><?=$this->escapeHtml(sprintf($this->translatePlural('%1$s picures', '%1$s picures', $count), $count))?></small>
            <?php } ?>
        </h2>
        <?=$this->partial('application/moder/pictures/partial/pictures.phtml', $this->picturesData)?>
        <?=$this->paginationControl($this->paginator, null, null, [
            'route' => 'moder/pictures/params'
        ]) ?>
    </div>
</div>