<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ],
        'pageId' => 152,
        'args'   => [
            'PICTURE_ID'   => $this->picture->id,
            'PICTURE_NAME' => 'Изображение № "'.$this->picture->id.'"'
        ]
    ]);
?>

<div class="well">
    <?php if (!$this->brand) { ?>
        <?php
            $columns = 6;
            $count = count($this->brands);
            $perOne = ceil($count / $columns);
            $width = round(100*$perOne/$count);
            $idx = 0;
        ?>
        <table width="100%" class="brand-selector"><tbody><tr>
            <td valign="top" style="width:<?=(100-$width*($columns-1)) ?>%">
                <?php foreach ($this->brands as $brand) { ?>
                    <?php if ($idx && ($idx%$perOne == 0)) { ?>
                        </td><td valign="top" style="width:<?=$width ?>%">
                    <?php } ?>
                    <?=$this->htmlA($this->url(null, [
                        'brand_id' => $brand['id']
                    ], [], true), $brand['name']) ?><br />
                    <?php $idx++ ?>
                <?php } ?>
            </td>
        </tr></tbody></table>
    <?php } else { ?>
        <form action="" method="post">
            <input type="hidden" name="brand" value="<?=(int)$this->brand->id?>" />
            <?=$this->partial('application/moder/pictures/picture-select-engine-walk-tree.phtml', [
                'engines' => $this->engines
            ])?>
        </form>
    <?php } ?>
</div>