<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needRight'   => false
        ],
        'pageId' => 72,
        'args'   => [
            'PICTURE_ID'   => $this->picture->id,
            'PICTURE_NAME' => sprintf($this->translate('moder/picture/picture-n-%s'), $this->picture->id)
        ]
    ]);

    $this->layout()->moduleName = 'moder/pictures/picture';
    $this->layout()->moduleOptions = [
        'normalizeUrl' => $this->url(null, [
            'action' => 'normalize'
        ], [], true),
        'flopUrl' => $this->url(null, [
            'action' => 'flop'
        ], [], true),
        'filesRepairUrl' => $this->url(null, [
            'action' => 'files-repair'
        ], [], true),
        'filesCorrectNamesUrl' => $this->url(null, [
            'action' => 'files-correct-names'
        ], [], true),
        'width'       => (int)$this->picture->width,
        'height'      => (int)$this->picture->height,
        'sourceUrl'   => $this->galleryFullUrl,
        'cropSaveUrl' => $this->url(null, [
            'action' => 'cropper-save'
        ], [], true),
        'crop'        => $this->crop ? [
            'x' => $this->crop[0],
            'y' => $this->crop[1],
            'w' => $this->crop[2],
            'h' => $this->crop[3],
        ] : false
    ];
?>

<div class="row">
    <div class="col-md-6 text-right">
        <p>
            <?php if ($this->prevPicture) { ?>
                <?=$this->htmlA($this->url(null, [
                    'picture_id' => $this->prevPicture->id
                ], [], true), $this->translate('moder/picture/previous')) ?>
                <br />
            <?php } ?>
            <?php if ($this->prevNewPicture) { ?>
                <?=$this->htmlA($this->url(null, [
                    'picture_id' => $this->prevNewPicture->id
                ], [], true), $this->translate('moder/picture/previous-new')) ?>
            <?php } ?>
        </p>
    </div>
    <div class="col-md-6">
        <p>
            <?php if ($this->nextPicture) { ?>
                <?=$this->htmlA($this->url(null, [
                    'picture_id' => $this->nextPicture->id
                ], [], true), $this->translate('moder/picture/next')) ?>
                <br />
            <?php } ?>
            <?php if ($this->nextNewPicture) { ?>
                <?=$this->htmlA($this->url(null, [
                    'picture_id' => $this->nextNewPicture->id
                ], [], true), $this->translate('moder/picture/next-new')) ?>
            <?php } ?>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <?php if ($this->picture->image_id) { ?>
            <?=$this->img($this->picture->getFormatRequest(), [
                'format' => 'picture-thumb',
            ])?>
        <?php } ?>
    </div>
    <div class="col-md-5">
        <div class="well">
            <p><?=$this->escapeHtml(sprintf($this->translate('moder/database-id-%s'), $this->picture->id))?></p>
            <?php $url = $this->pic($this->picture)->url() ?>
            <p>
                <?=$this->escapeHtml($this->translate('moder/picture/public-url:'))?>
                <?=$this->htmlA($url, $url) ?>
            </p>
            <p>
                <?=$this->escapeHtml($this->translate('moder/picture/image:'))?>
                <?=$this->htmlA($this->sourceUrl, parse_url($this->sourceUrl, PHP_URL_PATH))?>
            </p>
            <?=$this->htmlA($this->url('log/params', [
                'action'     => 'index',
                'picture_id' => $this->picture->id
            ]), $this->translate('moder/log-of-events')) ?>
        </div>
    </div>
    <div class="col-md-5">
        <div class="well">
            <?=$this->escapeHtml($this->translate('moder/picture/resolution:'))?>
            <b><?=$this->picture->width ?>×<?=$this->picture->height ?></b><br />
            <?=$this->escapeHtml($this->translate('moder/picture/filesize:'))?>
            <b><?=$this->fileSize($this->picture->filesize) ?></b><br />
            <?=$this->escapeHtml($this->translate('moder/picture/upload-date:'))?>
            <b><?=$this->picture->add_date ?></b>
        </div>
    </div>
</div>

<h3><?=$this->escapeHtml($this->translate('moder/picture/catalogue'))?></h3>
<div class="well">
    <?=$this->render('application/moder/pictures/partial/picture-catalogue')?>
</div>

<div class="row">
    <div class="col-md-6">
        <h3><?=$this->escapeHtml($this->translate('moder/picture/settings'))?></h3>
        <div class="well">
            <?=$this->partial('application/forms/bootstrap-vertical', [
                'form' => $this->editPictureForm
            ])?>
        </div>

        <h3><?=$this->escapeHtml($this->translate('moder/picture/copyrights'))?></h3>
        <div class="well">
            <?=$this->partial('application/forms/markdown', [
                'form' => $this->copyrightsForm
            ])?>
            <?php if ($this->picture->copyrights_text_id) { ?>
                <p>
                    <?=$this->htmlA([
                        'class' => 'pull-right',
                        'href'  => $this->url('info/text', [
                            'id' => $this->picture->copyrights_text_id
                        ])
                    ], 'History')?>
                </p>
            <?php } ?>
        </div>

        <?php if ($this->iptc) { ?>
            <h3>IPTC</h3>
            <div class="well" style="overflow:auto"><small><?=$this->iptc ?></small></div>
        <?php } ?>

        <?php if ($this->exif) { ?>
            <h3>EXIF</h3>
            <div class="well" style="overflow:auto"><small><?=$this->exif?></small></div>
        <?php } ?>

    </div>

    <div class="col-md-6">

        <?php if ($this->replacePicture) { ?>
            <h3><?=$this->escapeHtml($this->translate('moder/picture/replacement'))?></h3>
            <div class="well">
                <p>
                    <?=$this->escapeHtml($this->translate('moder/picture/replacement/photo-suggested-to-replace'))?>
                    <?=$this->htmlA($this->replacePicture['url'], $this->serverUrl($this->replacePicture['url']))?>
                </p>
                <?php if ($this->replacePicture['canAccept']) { ?>
                    <form action="<?=$this->escapeHtmlAttr($this->replacePicture['acceptUrl'])?>" method="post">
                        <button type="submit" class="btn btn-primary">
                            <i class="fa fa-exchange"></i>
                            <?=$this->escapeHtml($this->translate('moder/picture/replacement/accept-and-delete-double'))?>
                        </button>
                    </form>
                    <form action="<?=$this->escapeHtmlAttr($this->replacePicture['cancelUrl'])?>" method="post">
                        <button type="submit" class="btn btn-danger">
                            <i class="fa fa-times"></i>
                            <?=$this->escapeHtml($this->translate('moder/picture/replacement/cancel'))?>
                        </button>
                    </form>
                <?php } ?>
            </div>
        <?php } ?>


        <h3><?=$this->escapeHtml($this->translate('moder/picture/acceptance'))?></h3>
        <div class="well">
            <?=$this->render('application/moder/pictures/partial/picture-status')?>
        </div>

        <?php if ($this->canNormalize || $this->canFlop || $this->canCrop) { ?>
            <h3><?=$this->escapeHtml($this->translate('moder/picture/edit-and-repair'))?></h3>
            <div class="well">

                <div class="btn-group">

                    <?php if ($this->canNormalize) { ?>
                        <button class="btn btn-danger normalize">
                            <i class="fa fa-signal"></i>
                            <?=$this->escapeHtml($this->translate('moder/picture/edit-and-repair/normalize'))?>
                        </button>
                    <?php } ?>
                    <?php if ($this->canFlop) { ?>
                        <button class="btn btn-danger flop">
                            <i class="fa fa-arrows-h"></i>
                            <?=$this->escapeHtml($this->translate('moder/picture/edit-and-repair/flop'))?>
                        </button>
                    <?php } ?>
                    <?php if ($this->canCrop) { ?>
                        <button class="btn btn-success crop">
                            <i class="fa fa-crop"></i>
                            <?=$this->escapeHtml($this->translate('moder/picture/edit-and-repair/crop'))?>
                        </button>
                    <?php } ?>
                </div>

                <div class="btn-group">
                    <button class="btn btn-default files-repair">
                        <i class="fa fa-wrench"></i>
                        <?=$this->escapeHtml($this->translate('moder/picture/edit-and-repair/repair-all-files'))?>
                    </button>
                    <button class="btn btn-default files-correct-names">
                        <i class="fa fa-wrench"></i>
                        <?=$this->escapeHtml($this->translate('moder/picture/edit-and-repair/rebuild-files-names'))?>
                    </button>
                </div>

            </div>
        <?php } ?>

        <h3><?=$this->escapeHtml($this->translate('moder/picture/uploader'))?></h3>
        <div class="well">
            <?php if ($user = $this->picture->findParentRow(Autowp\User\Model\DbTable\User::class, 'Owner')) { ?>
                <?=$this->user($user) ?>
            <?php } else { ?>
                <?=$this->escapeHtml($this->translate('moder/picture/uploader/unknown'))?>
            <?php } ?>
            <?php if ($this->picture->ip) { ?>
                <?=$this->escapeHtml($this->translate('moder/picture/uploader/id-address:'))?>
                <b><?=$this->escapeHtml(inet_ntop($this->picture->ip))?></b><br />
                <?php if ($this->ban) { ?>
                    <p>
                        <?=$this->escapeHtml($this->translate('ban/that-address-is-banned'))?>
                        <?php if ($this->ban['user']) { ?>
                            <?=$this->user($this->ban['user']) ?>
                        <?php } ?>
                        <?php if ($this->ban['up_to']) { ?>
                            <?=$this->escapeHtml($this->translate('ban/until'))?>
                            <?=$this->ban['up_to']->format(MYSQL_DATETIME_FORMAT) ?>
                            <?php if ($this->ban['reason']) { ?>
                                (<?=$this->escapeHtml($this->ban['reason'])?>)
                            <?php } ?>
                        <?php } ?>
                    </p>

                    <?php if ($this->canBan) { ?>
                        <form action="<?=$this->url('ban/unban-ip', [
                            'ip' => inet_ntop($this->picture->ip)
                        ]) ?>" method="post" style="margin:10px 0">
                            <input type="submit" value="<?=$this->escapeHtmlAttr($this->translate('ban/unban'))?>" />
                        </form>
                    <?php } ?>
                <?php } ?>

                <?php if ($this->canBan) { ?>
                    <?=$this->partial('application/forms/bootstrap-horizontal', [
                        'form' => $this->banForm
                    ])?>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
</div>