<?php
    $tiny = isset($this->tiny) && $this->tiny;
?>
<form method="post" action="<?=$this->escapeHtmlAttr($this->url)?>" class="tiny" data-module="perspective-selector">
    <?php if (!$tiny) { ?>
        <label><?=$this->escapeHtml($this->translate('moder/picture/perspective'))?></label>
    <?php } ?>
    <div>
        <?=$this->car()->htmlTitle($this->name)?>
        <?=$this->formElement(
            (new Zend\Form\Element\Select('perspective_id'))
                ->setAttributes([
                    'class' => 'form-control' . ($tiny ? ' input-sm' : '')
                ])
                ->setValueOptions((array)$this->options)
                ->setValue($this->value)
        )?>
    </div>
</form>