<?php foreach ($this->engines as $idx => $engine) { ?>
    <button name="engine" type="submit" value="<?=(int)$engine['id']?>" class="btn btn-link">
        <?=$this->escapeHtml($engine['caption'])?>
    </button><br />
    <?php if (count($engine['childs'])) { ?>
        <div style="margin-left:2em">
            <?=$this->partial('application/moder/pictures/picture-select-engine-walk-tree.phtml', [
                'engines' => $engine['childs']
            ])?>
        </div>
    <?php } ?>
<?php } ?>