<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ],
        'pageId' => 72,
        'args'   => [
            'PICTURE_ID'   => $this->picture->id,
            'PICTURE_NAME' => sprintf($this->translate('moder/picture/picture-n-%s'), $this->picture->id)
        ]
    ]);

    $this->layout()->moduleName = 'moder/pictures/picture';
    $this->layout()->moduleOptions = [
        'normalizeUrl' => $this->url(null, [
            'action' => 'normalize'
        ], [], true),
        'flopUrl' => $this->url(null, [
            'action' => 'flop'
        ], [], true),
        'filesRepairUrl' => $this->url(null, [
            'action' => 'files-repair'
        ], [], true),
        'filesCorrectNamesUrl' => $this->url(null, [
            'action' => 'files-correct-names'
        ], [], true),
        'width'       => (int)$this->picture->width,
        'height'      => (int)$this->picture->height,
        'sourceUrl'   => $this->galleryFullUrl,
        'cropSaveUrl' => $this->url(null, [
            'action' => 'cropper-save'
        ], [], true),
        'crop'        => $this->crop ? [
            'x' => $this->crop[0],
            'y' => $this->crop[1],
            'w' => $this->crop[2],
            'h' => $this->crop[3],
        ] : false
    ];
?>
<div class="row">
    <div class="col-md-6 text-right">
        <?php if ($this->prevPicture) { ?>
            <?=$this->htmlA($this->url(null, [
                'picture_id' => $this->prevPicture->id
            ], [], true), $this->translate('moder/picture/previous')) ?>
            <br />
        <?php } ?>
        <?php if ($this->prevNewPicture) { ?>
            <?=$this->htmlA($this->url(null, [
                'picture_id' => $this->prevNewPicture->id
            ], [], true), $this->translate('moder/picture/previous-new')) ?>
        <?php } ?>
    </div>
    <div class="col-md-6">
        <?php if ($this->nextPicture) { ?>
            <?=$this->htmlA($this->url(null, [
                'picture_id' => $this->nextPicture->id
            ], [], true), $this->translate('moder/picture/next')) ?>
            <br />
        <?php } ?>
        <?php if ($this->nextNewPicture) { ?>
            <?=$this->htmlA($this->url(null, [
                'picture_id' => $this->nextNewPicture->id
            ], [], true), $this->translate('moder/picture/next-new')) ?>
        <?php } ?>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <?php if ($this->picture->image_id) { ?>
            <?=$this->img($this->picture->getFormatRequest(), [
                'format' => 'picture-thumb',
            ])?>
        <?php } else { ?>
            <?=$this->image($this->picture, 'file_name', [
                'format' => 6,
            ])?>
        <?php } ?>

        <p><?=$this->escapeHtml(sprintf($this->translate('moder/database-id-%s'), $this->picture->id))?></p>
        <?php $url = $this->pic($this->picture)->url() ?>
        <p>На сайте: <?=$this->htmlA($url, $url) ?></p>
        <p>Картинка: <?=$this->htmlA($this->sourceUrl, parse_url($this->sourceUrl, PHP_URL_PATH))?></p>
        <?=$this->htmlA($this->url('log/params', [
            'action'     => 'index',
            'picture_id' => $this->picture->id
        ]), $this->translate('moder/log-of-events')) ?>

        <h3>Характеристики изображения:</h3>
        <div class="well">
            Разрешение: <b><?=$this->picture->width ?>×<?=$this->picture->height ?></b><br />
            Размер файла: <b><?=$this->fileSize($this->picture->filesize) ?></b><br />
            Добавлено: <b><?=$this->picture->add_date ?></b>
        </div>

        <h3>Настройки</h3>
        <div class="well">
            <?=$this->partial('application/forms/bootstrap-vertical', [
                'form' => $this->editPictureForm
            ])?>
        </div>

        <h3>Копирайты</h3>
        <div class="well">
            <?=$this->partial('application/forms/markdown', [
                'form' => $this->copyrightsForm
            ])?>
            <?php if ($this->picture->copyrights_text_id) { ?>
                <p>
                    <?=$this->htmlA([
                        'class' => 'pull-right',
                        'href'  => $this->url('info/text', [
                            'id' => $this->picture->copyrights_text_id
                        ])
                    ], 'History')?>
                </p>
            <?php } ?>
        </div>

        <?php if ($this->iptc) { ?>
            <h3>IPTC</h3>
            <div class="well" style="overflow:auto"><small><?=$this->iptc ?></small></div>
        <?php } ?>

        <?php if ($this->exif) { ?>
            <h3>EXIF</h3>
            <div class="well" style="overflow:auto"><small><?=$this->exif?></small></div>
        <?php } ?>

    </div>

    <div class="col-md-6">

        <h3><?=$this->escapeHtml($this->translate('moder/picture/catalogue'))?></h3>
        <div class="well">
            <?php
                switch ($this->picture->type) {
                    case Picture::CAR_TYPE_ID:
                        ?>
                        <p>
                            <?=$this->escapeHtml($this->translate('moder/picture/catalogue/vehicle'))?>
                            <?php $car = $this->picture->findParentCars() ?>
                            <?php if ($car) { ?>
                                <?=$this->htmlA($this->url('moder/cars/params', [
                                    'action'     => 'car',
                                    'car_id'     => $car->id
                                ]), $car->getFullName()) ?>
                            <?php } else { ?>
                                <?=$this->escapeHtml($this->translate('moder/picture/catalogue/not-set'))?>
                            <?php } ?>
                        </p>
                        <?php
                        break;

                    case Picture::LOGO_TYPE_ID:
                        ?>
                        <p>
                            <?=$this->escapeHtml($this->translate('moder/picture/catalogue/logo'))?>
                            <?php if ($brand = $this->picture->findParentBrands()) { ?>
                                <?=$this->htmlA($this->url('moder/brands/params', [
                                    'action'     => 'brand',
                                    'brand_id'   => $brand->id
                                ]), $brand->caption) ?>
                            <?php } else { ?>
                                <?=$this->escapeHtml($this->translate('moder/picture/catalogue/not-set'))?>
                            <?php } ?>
                        </p>
                        <?php
                        break;

                    case Picture::MIXED_TYPE_ID:
                        ?>
                        <p>
                            <?=$this->escapeHtml($this->translate('moder/picture/catalogue/mixed'))?>
                            <?php if ($brand = $this->picture->findParentBrands()) { ?>
                                <?=$this->htmlA($this->url('moder/brands/params', [
                                    'action'   => 'brand',
                                    'brand_id' => $brand->id
                                ]), $brand->caption) ?>
                            <?php } else { ?>
                                <?=$this->escapeHtml($this->translate('moder/picture/catalogue/not-set'))?>
                            <?php } ?>
                        </p>
                        <?php
                        break;

                    case Picture::UNSORTED_TYPE_ID:
                        ?>
                        <p>
                            <?=$this->escapeHtml($this->translate('moder/picture/catalogue/unsorted'))?>
                            <?php if ($brand = $this->picture->findParentBrands()) { ?>
                                <?=$this->htmlA($this->url('moder/brands/params', [
                                    'action'   => 'brand',
                                    'brand_id' => $brand->id
                                ]), $brand->caption) ?>
                            <?php } else { ?>
                                <?=$this->escapeHtml($this->translate('moder/picture/catalogue/not-set'))?>
                            <?php } ?>
                        </p>
                        <?php
                        break;

                    case Picture::ENGINE_TYPE_ID:
                        ?>
                        <p>
                            <?=$this->escapeHtml($this->translate('moder/picture/catalogue/engine'))?>
                            <?php $engine = $this->picture->findParentEngines() ?>
                            <?php if ($engine) { ?>
                                <?=$this->htmlA($this->url('moder/engines/params', [
                                    'action'    => 'engine',
                                    'engine_id' => $engine->id
                                ]), $engine->caption) ?>
                            <?php } else { ?>
                                <?=$this->escapeHtml($this->translate('moder/picture/catalogue/not-set'))?>
                            <?php } ?>
                            </p>
                        <?php
                        break;

                    case Picture::FACTORY_TYPE_ID:
                        ?>
                        <p>
                            <?=$this->escapeHtml($this->translate('moder/picture/catalogue/factory'))?>
                            <?php if ($factory = $this->picture->findParentFactory()) { ?>
                                <?=$this->htmlA($this->url('moder/factories/params', [
                                    'action'     => 'factory',
                                    'factory_id' => $factory->id
                                ]), $factory->name) ?>
                            <?php } else { ?>
                                <?=$this->escapeHtml($this->translate('moder/picture/catalogue/not-set'))?>
                            <?php } ?>
                        </p>
                        <?php
                        break;
                }
            ?>
            <?php if ($this->canMove) { ?>
                <?php if ($this->lastCar) { ?>
                    <p><?=$this->htmlA([
                        'class' => 'btn btn-default',
                        'href'  => $this->url(null, [
                            'action'     => 'move',
                            'picture_id' => $this->picture->id,
                            'type'       => Picture::CAR_TYPE_ID,
                            'car_id'     => $this->lastCar->id
                        ])
                    ], '<i class="fa fa-arrow-right"></i> ' . $this->escapeHtml($this->translate('moder/picture/catalogue/move-to')) . ' ' . $this->escapeHtml($this->lastCar->getFullName()), false) ?></p>
                <?php } ?>
                <?php foreach ($this->relatedBrands as $brand) { ?>
                    <p><?=$this->htmlA([
                        'class' => 'btn btn-default',
                        'href' => $this->url(null, [
                            'action'     => 'move',
                            'brand_id'   => $brand['id'],
                            'picture_id' => $this->picture->id
                        ])
                    ], '<i class="fa fa-arrow-right"></i> ' . $this->escapeHtml($this->translate('moder/picture/catalogue/move-to')) . ' ' . $this->escapeHtml($brand['name']) . ' ...', false) ?></p>
                <?php } ?>
                <p><?=$this->htmlA([
                    'class' => 'btn btn-default',
                    'href' => $this->url('moder/pictures/params', [
                        'action' => 'move'
                    ], [], true),
                ], '<i class="fa fa-arrow-right"></i> ' . $this->escapeHtml($this->translate('moder/picture/catalogue/move-to')) . ' ...', false)?></p>
            <?php } ?>
        </div>


    <?php if ($this->picture->type == Picture::CAR_TYPE_ID) { ?>
        <h3><?=$this->escapeHtml($this->translate('moder/picture/perspective'))?></h3>
        <div class="well">
            <?=$this->partial('application/moder/pictures/picture-perspective', $this->picturePerspective)?>
        </div>
    <?php } ?>

    <?php if ($this->replacePicture) { ?>
        <h3>Замена</h3>
        <div class="well">
            <p>Фото предложено на замену <?=$this->htmlA($this->replacePicture['url'], $this->serverUrl($this->replacePicture['url']))?></p>
            <?php if ($this->replacePicture['canAccept']) { ?>
                <form action="<?=$this->escapeHtmlAttr($this->replacePicture['acceptUrl'])?>" method="post">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-exchange"></i>
                        Принять замену и удалить дубль
                    </button>
                </form>
                <form action="<?=$this->escapeHtmlAttr($this->replacePicture['cancelUrl'])?>" method="post">
                    <button type="submit" class="btn btn-danger">
                        <i class="fa fa-times"></i>
                        Отклонить замену
                    </button>
                </form>
            <?php } ?>
        </div>
    <?php } ?>


    <h3><?=$this->escapeHtml($this->translate('moder/picture/acceptance'))?></h3>
    <div class="well">
        <div style="margin-bottom:15px"><?php
            $changeStatusUserHtml = '';
            if ($this->picture->change_status_user_id) {
                $changeStatusUserHtml = ' '.$this->user($this->picture->findParentUsersByChange_Status_User());
            }

            switch ($this->picture->status) {
                case Picture::STATUS_NEW:
                case Picture::STATUS_INBOX:
                    ?>
                    <p><strong class="label label-warning">
                        <?=$this->escapeHtml($this->translate('moder/picture/acceptance/not-accepted'))?>
                        <?=$changeStatusUserHtml?>
                        <?=(Picture::STATUS_INBOX == $this->picture->status ? ' (новое)' : '')?>
                    </strong></p>
                    <?php if ($this->canAccept) { ?>
                        <form action="<?=$this->escapeHtmlAttr($this->acceptUrl)?>" method="post">
                            <button type="submit" class="btn btn-success"><?=$this->escapeHtml($this->translate('moder/picture/acceptance/accept'))?></button>
                        </form>
                    <?php } ?>
                    <?php
                    break;

                case Picture::STATUS_ACCEPTED:
                    ?>
                    <p><strong class="label label-success"><?=$this->escapeHtml($this->translate('moder/picture/acceptance/accepted'))?></strong></p>
                    <?=$changeStatusUserHtml?>
                    <?php if ($this->canUnaccept) { ?>
                        <form action="<?=$this->escapeHtmlAttr($this->unacceptUrl)?>" method="post">
                            <button type="submit" class="btn btn-warning"><?=$this->escapeHtml($this->translate('moder/picture/acceptance/unaccept'))?></button>
                        </form>
                    <?php } ?>
                    <?php
                    break;

                case Picture::STATUS_REMOVING:
                    ?><p>
                        <strong class="label label-danger">
                            <?=$this->escapeHtml($this->translate('moder/picture/acceptance/in-delete-queue'))?>
                        </strong>
                        &nbsp;
                        <?=$changeStatusUserHtml?>
                    </p>
                    <?php if ($this->canRestore) { ?>
                        <form action="<?=$this->escapeHtmlAttr($this->restoreUrl)?>" method="post">
                            <button type="submit" class="btn btn-success"><?=$this->escapeHtml($this->translate('moder/picture/acceptance/restore'))?></button>
                        </form>
                    <?php }
                    break;

                case Picture::STATUS_REMOVED:
                    ?><p><strong style="color:red">
                        <?=$this->escapeHtml($this->translate('moder/picture/acceptance/removed'))?>
                        <?=$changeStatusUserHtml?>
                    </strong></p><?php
                    break;
            }
        ?></div>

        <?=$this->partial('application/moder/pictures/picture-vote', $this->pictureVote)?>
    </div>

    <?php if ($this->canNormalize || $this->canFlop || $this->canCrop) { ?>
        <h3>Редактирование и устранение проблем</h3>
        <div class="well">

            <div class="btn-group">

                <?php if ($this->canNormalize) { ?>
                    <button class="btn btn-danger normalize"><i class="fa fa-signal"></i> Автоконтраст</button>
                <?php } ?>
                <?php if ($this->canFlop) { ?>
                    <button class="btn btn-danger flop"><i class="fa fa-arrows-h"></i> Отразить</button>
                <?php } ?>
                <?php if ($this->canCrop) { ?>
                    <button class="btn btn-success crop">
                        <i class="fa fa-crop"></i> Выделить область
                    </button>
                <?php } ?>
            </div>

            <div class="btn-group">
                <button class="btn btn-default files-repair"><i class="fa fa-wrench"></i> Исправить все файлы</button>
                <button class="btn btn-default files-correct-names"><i class="fa fa-wrench"></i> Пересчитать имена файлов</button>
            </div>

        </div>
    <?php } ?>

    <h3>Закачал</h3>
    <div class="well">
        <?php if ($user = $this->picture->findParentUsersByOwner()) { ?>
            <?=$this->user($user) ?>
        <?php } else { ?>
            Неизвестно
        <?php } ?>
        <?php if ($this->picture->ip) { ?>
            IP-адрес закачавшего: <b><?=$this->escapeHtml(inet_ntop($this->picture->ip))?></b><br />
            <?php if ($this->ban) { ?>
                <p>
                    Этот адрес забанил
                    <?php if ($this->ban['user']) { ?>
                        <?=$this->user($this->ban['user']) ?>
                    <?php } ?>
                    <?php if ($this->ban['up_to']) { ?>
                        до
                        <?=$this->ban['up_to']->format(MYSQL_DATETIME_FORMAT) ?>
                        <?php if ($this->ban['reason']) { ?>
                            (<?=$this->escapeHtml($this->ban['reason'])?>)
                        <?php } ?>
                    <?php } ?>
                </p>

                <?php if ($this->canBan) { ?>
                    <form action="<?=$this->url('ban/unban-ip', [
                        'ip' => inet_ntop($this->picture->ip)
                    ]) ?>" method="post" style="margin:10px 0">
                        <input type="submit" value="снять бан" />
                    </form>
                <?php } ?>
            <?php } ?>

            <?php if ($this->canBan) { ?>
                <?=$this->partial('application/forms/bootstrap-horizontal', [
                    'form' => $this->banForm
                ])?>
            <?php } ?>
        <?php } ?>
    </div>
</div>