<?php if ($this->canVote) { ?>
    <div class="btn-group" role="group" data-module="picture-moder-vote" data-url="<?=$this->escapeHtmlAttr($this->voteUrl)?>">
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <?=$this->escapeHtml($this->translate('moder/picture/acceptance/want-accept'))?>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <?php foreach ($this->voteOptions['positive'] as $value) { ?>
                    <li><?=$this->htmlA([
                        'data-vote'   => 1,
                        'data-reason' => $value,
                        'href'        => '#'
                    ], $value)?></li>
                <?php } ?>
                <li role="separator" class="divider"></li>
                <li><?=$this->htmlA([
                    'data-vote' => 1,
                    'href'      => '#'
                ], $this->translate('moder/picture/acceptance/custom'))?></li>
            </ul>
        </div>

        <div class="btn-group" role="group">
            <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <?=$this->escapeHtml($this->translate('moder/picture/acceptance/want-delete'))?>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <?php foreach ($this->voteOptions['negative'] as $value) { ?>
                    <li><?=$this->htmlA([
                        'data-vote'   => -1,
                        'data-reason' => $value,
                        'href'        => '#'
                    ], $value)?></li>
                <?php } ?>
                <li role="separator" class="divider"></li>
                <li><?=$this->htmlA([
                    'data-vote' => -1,
                    'href'      => '#'
                ], $this->translate('moder/picture/acceptance/custom'))?></li>
            </ul>
        </div>
    </div>
<?php } ?>

<?php if ($this->voteExists) { ?>
    <div data-module="picture-moder-vote" data-url="<?=$this->escapeHtmlAttr($this->voteUrl)?>">
        <button type="submit" class="btn btn-default btn-cancel-vote">
            <?=$this->escapeHtml($this->translate('moder/picture/acceptance/cancel-vote'))?>
        </button>
    </div>
<?php } ?>

<?php if (isset($this->moderVotes) && count($this->moderVotes) > 0) { ?>
    <?=$this->escapeHtml($this->translate('moder/picture/acceptance/already-voted'))?>
    <?php $idx = 0 ?>
    <?php foreach ($this->moderVotes as $vote) { ?>
        <?php if ($idx++ > 0) { ?>, <?php } ?>
        <?php if ($vote['user']) { ?>
            <?=$this->user($vote['user']) ?>
        <?php } ?>
        <span style="color:<?=$vote['vote'] ? 'green' : 'red' ?>">&#xa0;(<?=$this->escapeHtml($vote['reason']) ?>)</span>
    <?php } ?>
<?php } ?>

<?php if ($this->canDelete) { ?>
    <button data-module="picture-delete-button" class="btn btn-danger" data-url="<?=$this->escapeHtmlAttr($this->apiUrl)?>">
        <?=$this->escapeHtml($this->translate('moder/picture/acceptance/delete'))?>
    </button>
<?php } ?>

<?php if ($this->isLastPicture) { ?>
    <p><span class="label label-warning">
        <?=$this->escapeHtml($this->translate('moder/picture/acceptance/that-is-one-accepted-picture'))?>
    </span></p>
<?php } elseif ($this->acceptedCount !== null && $this->acceptedCount <= 4) { ?>
    <p><span class="label label-warning">
        <?=$this->escapeHtml(sprintf($this->translate('moder/picture/acceptance/accepted-pictures-is-%s'), $this->acceptedCount))?>
    </span></p>
<?php } ?>