<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ],
        'pageId' => 179,
        'args'   => [
            'PICTURE_ID'   => $this->picture->id,
            'PICTURE_NAME' => 'Изображение № "'.$this->picture->id.'"'
        ]
    ]);
?>

<div class="well">
    <form action="<?=$this->escapeHtmlAttr($this->url(null, [], [], true))?>" method="post">
        <?php foreach ($this->factories as $factory) { ?>
            <?=$this->formButton('factory_id', $factory['id'], [
                'type'    => 'submit',
                'class'   => 'btn btn-link',
                'value'   => $factory['id'],
                'content' => $factory['name']
            ])?><br />
        <?php } ?>
    </form>
</div>