<?php if ($this->canVote) { ?>
    <form action="<?=$this->escapeHtmlAttr($this->pictureVoteUrl)?>" class="form-inline" method="post">
        <div data-module="moder-vote-reason">
            <?=$this->formElement(
                (new Zend\Form\Element\Select('reason_select'))
                    ->setAttributes([
                        'id'    => 'reason_select',
                        'class' => 'form-control'
                    ])
                    ->setValueOptions($this->voteOptions)
            )?>
            <?php foreach ($this->voteOptions as $value) { ?>
                <input type="text" name="reason" id="reason" value="<?=$this->escapeHtmlAttr($value)?>" style="display: none" class="form-control">
            <?php break; } ?>
        </div>

        <div class="btn-group btn-group-sm">
            <button type="submit" name="vote" value="1" class="btn btn-success">
                <?=$this->escapeHtml($this->translate('moder/picture/acceptance/want-accept'))?>
            </button>
            <button type="submit" name="vote" value="0" class="btn btn-danger">
                <?=$this->escapeHtml($this->translate('moder/picture/acceptance/want-delete'))?>
            </button>
        </div>
    </form>
<?php } ?>

<?php if ($this->voteExists) { ?>
    <form action="<?=$this->escapeHtmlAttr($this->pictureUnvoteUrl)?>" method="post">
        <input type="submit" name="send" id="send" value="<?=$this->escapeHtmlAttr($this->translate('moder/picture/acceptance/cancel-vote'))?>" class="btn btn-default">
    </form>
<?php } ?>

<?php if (isset($this->moderVotes) && count($this->moderVotes) > 0) { ?>
    <?=$this->escapeHtml($this->translate('moder/picture/acceptance/already-voted'))?>
    <?php $idx = 0 ?>
    <?php foreach ($this->moderVotes as $vote) { ?>
        <?php if ($idx++ > 0) { ?>, <?php } ?>
        <?php if ($user = $vote->findParentRow(Application\Model\DbTable\User::class)) { ?>
            <?=$this->user($user) ?>
        <?php } ?>
        <span style="color:<?=$vote->vote ? 'green' : 'red' ?>">&#xa0;(<?=$this->escapeHtml($vote->reason) ?>)</span>
    <?php } ?>
<?php } ?>

<?php if ($this->canDelete) { ?>
    <form action="<?=$this->escapeHtmlAttr($this->pictureDeleteUrl)?>" method="post">
        <input type="submit" name="send" id="send" value="<?=$this->escapeHtmlAttr($this->translate('moder/picture/acceptance/delete'))?>" class="btn btn-danger">
    </form>
<?php } ?>

<?php if ($this->isLastPicture) { ?>
    <p><span class="label label-warning">
        <?=$this->escapeHtml($this->translate('moder/picture/acceptance/that-is-one-accepted-picture'))?>
    </span></p>
<?php } elseif ($this->acceptedCount !== null && $this->acceptedCount <= 4) { ?>
    <p><span class="label label-warning">
        <?=$this->escapeHtml(sprintf($this->translate('moder/picture/acceptance/accepted-pictures-is-%s'), $this->acceptedCount))?>
    </span></p>
<?php } ?>