<?php
    $tiny = isset($this->tiny) && $this->tiny;
?>
<form method="post" action="<?=$this->escapeHtmlAttr($this->url)?>" class="tiny" data-module="perspective-selector">
    <?php if (!$tiny) { ?>
        <label for="perspective_id">Ракурс</label>
    <?php } ?>

    <?=$this->formElement(
        (new Zend\Form\Element\Select('perspective_id'))
            ->setAttributes([
                'id'    => 'perspective_id',
                'class' => 'form-control' . ($tiny ? ' input-sm' : '')
            ])
            ->setValueOptions($this->options)
            ->setValue($this->value)
    )?>
</form>
<?php if ($this->user) { ?>
    <p>Установил: <?=$this->user($this->user) ?></p>
<?php } ?>