<?php
    $this->pageEnv([
        'layout' => [
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ],
        'pageId' => 72,
        'args'   => [
            'PICTURE_ID'   => $this->picture->id,
            'PICTURE_NAME' => 'Изображение № "'.$this->picture->id.'"'
        ]
    ]);

    $this->layout()->moduleName = 'moder/pictures/picture';
    $this->layout()->moduleOptions = [
        'normalizeUrl' => $this->url(null, [
            'action' => 'normalize'
        ], [], true),
        'flopUrl' => $this->url(null, [
            'action' => 'flop'
        ], [], true),
        'filesRepairUrl' => $this->url(null, [
            'action' => 'files-repair'
        ], [], true),
        'filesCorrectNamesUrl' => $this->url(null, [
            'action' => 'files-correct-names'
        ], [], true),
        'width'       => (int)$this->picture->width,
        'height'      => (int)$this->picture->height,
        'sourceUrl'   => $this->galleryFullUrl,
        'cropSaveUrl' => $this->url(null, [
            'action' => 'cropper-save'
        ], [], true),
        'crop'        => $this->crop ? [
            'x' => $this->crop[0],
            'y' => $this->crop[1],
            'w' => $this->crop[2],
            'h' => $this->crop[3],
        ] : false
    ];
?>
<div class="row">
    <div class="col-md-6 text-right">
        <?php if ($this->prevPicture) { ?>
            <?=$this->htmlA($this->url(null, [
                'picture_id' => $this->prevPicture->id
            ], [], true), '<< предыдущее') ?>
            <br />
        <?php } ?>
        <?php if ($this->prevNewPicture) { ?>
            <?=$this->htmlA($this->url(null, [
                'picture_id' => $this->prevNewPicture->id
            ], [], true), '<< предыдущее не обработанное') ?>
        <?php } ?>
    </div>
    <div class="col-md-6">
        <?php if ($this->nextPicture) { ?>
            <?=$this->htmlA($this->url(null, [
                'picture_id' => $this->nextPicture->id
            ], [], true), 'следующее >>') ?>
            <br />
        <?php } ?>
        <?php if ($this->nextNewPicture) { ?>
            <?=$this->htmlA($this->url(null, [
                'picture_id' => $this->nextNewPicture->id
            ], [], true), 'следующее не обработанное >>') ?>
        <?php } ?>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <?php if ($this->picture->image_id) { ?>
            <?=$this->img($this->picture->getFormatRequest(), [
                'format' => 'picture-thumb',
            ])?>
        <?php } else { ?>
            <?=$this->image($this->picture, 'file_name', [
                'format' => 6,
            ])?>
        <?php } ?>

        <p>В базе данных чиcлится под номером <b><?=$this->picture->id?></b></p>
        <?php $url = $this->pic($this->picture)->url() ?>
        <p>На сайте: <?=$this->htmlA($url, $url) ?></p>
        <p>Картинка: <?=$this->htmlA($this->sourceUrl, parse_url($this->sourceUrl, PHP_URL_PATH))?></p>
        <?=$this->htmlA($this->url('log/params', [
            'action'     => 'index',
            'picture_id' => $this->picture->id
        ]), 'Журнал событий по картинке') ?>

        <h3>Характеристики изображения:</h3>
        <div class="well">
            Разрешение: <b><?=$this->picture->width ?>×<?=$this->picture->height ?></b><br />
            Размер файла: <b><?=$this->fileSize($this->picture->filesize) ?></b><br />
            Добавлено: <b><?=$this->picture->add_date ?></b>
        </div>

        <h3>Настройки</h3>
        <div class="well">
        	<?=$this->editPictureForm->render($this) ?>
    	</div>

    	<h3>Копирайты</h3>
        <div class="well">
            <?=$this->copyrightsForm->render($this)?>
            <?php if ($this->picture->copyrights_text_id) { ?>
                <p>
                    <?=$this->htmlA([
                        'class' => 'pull-right',
                        'href'  => $this->url('info/text', [
                            'id' => $this->picture->copyrights_text_id
                        ])
                    ], 'History')?>
                </p>
            <?php } ?>
        </div>

        <?php if ($this->iptc) { ?>
            <h3>IPTC</h3>
            <div class="well" style="overflow:auto"><small><?=$this->iptc ?></small></div>
        <?php } ?>

        <?php if ($this->exif) { ?>
            <h3>EXIF</h3>
            <div class="well" style="overflow:auto"><small><?=$this->exif?></small></div>
        <?php } ?>

    </div>

    <div class="col-md-6">

        <h3>Тип картинки</h3>
        <div class="well">
            <?php if ($this->formModerPictureType) { ?>
                <?=$this->formModerPictureType->render($this) ?>
            <?php } ?>
            <p>
            <?php
                switch ($this->picture->type) {
                    case Picture::CAR_TYPE_ID:
                        ?>
                        Автомобиль:
                        <?php $car = $this->picture->findParentCars() ?>
                        <?php if ($car) { ?>
                            <?=$this->htmlA($this->url('moder/cars/params', [
                                'action'     => 'car',
                                'car_id'     => $car->id
                            ]), $car->getFullName()) ?>
                        <?php } else { ?>
                            Не задан
                        <?php } ?>
                        <?php if ($this->canMove) { ?>
                            <?php if ($car) { ?>
                                <?php foreach ($car->findBrandsViaBrands_Cars() as $brand) { ?>
                                    <br />
                                    <?=$this->htmlA(
                                        $this->url(null, [
                                            'action'     => 'picture-select-car',
                                            'brand_id'   => $brand->id,
                                            'picture_id' => $this->picture->id
                                        ]), 'выбрать автомобиль из '.$brand->caption .' ...'
                                    ) ?>
                                <?php } ?>
                            <?php } ?>
                            <br />
                            <?=$this->htmlA(
                                $this->url(null, [
                                    'action'     => 'picture-select-car',
                                    'picture_id' => $this->picture->id
                                ]), 'выбрать автомобиль'
                            ) ?>
                            <?php if ($this->lastCar) { ?>
                                <br />
                                <?=$this->htmlA(
                                    $this->url(null, [
                                        'action'     => 'picture-select-car',
                                        'picture_id' => $this->picture->id,
                                        'car_id'     => $this->lastCar->id
                                    ]), 'переместить в '. $this->lastCar->getFullName()
                                ) ?>
                            <?php } ?>
                        <?php } ?>
                        <?php
                        break;

                    case Picture::LOGO_TYPE_ID:
                        ?>
                        Логотип бренда:
                        <?php $brand = $this->picture->findParentBrands() ?>
                        <?php if ($brand) { ?>
                            <?=$this->htmlA($this->url('moder/brands/params', [
                                'action'     => 'brand',
                                'brand_id'   => $brand->id
                            ]), $brand->caption) ?>
                        <?php } else { ?>
                            Не задан
                        <?php } ?>
                        <?php if ($this->canMove) { ?>
                            <br />
                            <?=$this->htmlA(
                                $this->url(null, [
                                    'action'     => 'picture-select-brand',
                                    'picture_id' => $this->picture->id
                                ]), 'выбрать бренд'
                            ) ?>
                        <?php } ?>
                        <?php
                        break;

                    case Picture::MIXED_TYPE_ID:
                        ?>
                        Смешанное бренда:
                        <?php $brand = $this->picture->findParentBrands() ?>
                        <?php if ($brand) { ?>
                            <?=$this->htmlA($this->url('moder/brands/params', [
                                'action'   => 'brand',
                                'brand_id' => $brand->id
                            ]), $brand->caption) ?>
                        <?php } else { ?>
                            Не задан
                        <?php } ?>
                        <?php if ($this->canMove) { ?>
                            <br />
                            <?=$this->htmlA(
                                $this->url(null, [
                                    'action'     => 'picture-select-brand',
                                    'picture_id' => $this->picture->id
                                ]), 'выбрать бренд'
                            ) ?>
                        <?php } ?>
                        <?php
                        break;

                    case Picture::UNSORTED_TYPE_ID:
                        ?>
                        Несортировано бренда:
                        <?php $brand = $this->picture->findParentBrands() ?>
                        <?php if ($brand) { ?>
                            <?=$this->htmlA($this->url('moder/brands/params', [
                                'action'   => 'brand',
                                'brand_id' => $brand->id
                            ]), $brand->caption) ?>
                        <?php } else { ?>
                            Не задан
                        <?php } ?>
                        <?php if ($this->canMove) { ?>
                            <br />
                            <?=$this->htmlA(
                                $this->url(null, [
                                    'action'     => 'picture-select-brand',
                                    'picture_id' => $this->picture->id
                                ]), 'выбрать бренд'
                            ) ?>
                        <?php } ?>
                        <?php
                        break;

                    case Picture::ENGINE_TYPE_ID:
                        ?>
                        Двигатель:
                        <?php $engine = $this->picture->findParentEngines() ?>
                        <?php if ($engine) { ?>
                            <?=$this->htmlA($this->url('moder/engines/params', [
                                'action'    => 'engine',
                                'engine_id' => $engine->id
                            ]), $engine->caption) ?>
                        <?php } else { ?>
                            Не задан
                        <?php } ?>
                        <?php if ($this->canMove) { ?>
                            <br />
                            <?=$this->htmlA(
                                $this->url(null, [
                                    'action'     => 'picture-select-engine',
                                    'picture_id' => $this->picture->id
                                ]), 'выбрать двигатель'
                            ) ?>
                        <?php } ?>
                        <?php
                        break;

                    case Picture::FACTORY_TYPE_ID:
                        ?>
                        Завод:
                        <?php if ($factory = $this->picture->findParentFactory()) { ?>
                            <?=$this->htmlA($this->url('moder/factories/params', [
                                'action'     => 'factory',
                                'factory_id' => $factory->id
                            ]), $factory->name) ?>
                        <?php } else { ?>
                            Не задан
                        <?php } ?>
                        <?php if ($this->canMove) { ?>
                            <br />
                            <?=$this->htmlA(
                                $this->url(null, [
                                    'action'     => 'picture-select-factory',
                                    'picture_id' => $this->picture->id
                                ]), 'выбрать завод'
                            ) ?>
                        <?php } ?>
                        <?php
                        break;
                }
            ?>
            </p>
        </div>


    <?php if ($this->picture->type == Picture::CAR_TYPE_ID) { ?>
        <h3>Ракурс</h3>
        <div class="well">
            <?=$this->action('picture-perspective', 'pictures', 'moder', [
                'picture_id' => $this->picture->id
            ]) ?>
        </div>
    <?php } ?>

    <?php if ($this->replacePicture) { ?>
        <h3>Замена</h3>
        <div class="well">
            <p>Фото предложено на замену <?=$this->htmlA($this->replacePicture['url'], $this->serverUrl($this->replacePicture['url']))?></p>
            <?php if ($this->replacePicture['canAccept']) { ?>
                <form action="<?=$this->escapeHtmlAttr($this->replacePicture['acceptUrl'])?>" method="post">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-exchange"></i>
                        Принять замену и удалить дубль
                    </button>
                </form>
                <form action="<?=$this->escapeHtmlAttr($this->replacePicture['cancelUrl'])?>" method="post">
                    <button type="submit" class="btn btn-danger">
                        <i class="fa fa-times"></i>
                        Отклонить замену
                    </button>
                </form>
            <?php } ?>
        </div>
    <?php } ?>


    <h3>Статус/Удаление/Принятие</h3>
    <div class="well">
        <p><?php
            $changeStatusUserHtml = '';
            if ($this->picture->change_status_user_id) {
                $changeStatusUserHtml = ' '.$this->user($this->picture->findParentUsersByChange_Status_User());
            }

            switch ($this->picture->status) {
                case Picture::STATUS_NEW:
                case Picture::STATUS_INBOX:
                    ?>
                    <strong class="label label-warning">Не принято <?=$changeStatusUserHtml?><?=(Picture::STATUS_INBOX == $this->picture->status ? ' (новое)' : '')?></strong>
                    <?php if ($this->canAccept) { ?>
                        <?=$this->acceptPictureForm->render($this) ?>
                    <?php } ?>
                    <?php
                    break;

                case Picture::STATUS_ACCEPTED:
                    ?>
                    <strong class="label label-success">Принято</strong>
                    <?=$changeStatusUserHtml?>
                    <?php if ($this->canUnaccept) { ?>
                        <?=$this->unacceptPictureForm->render($this) ?>
                    <?php } ?>
                    <?php
                    break;

                case Picture::STATUS_REMOVING:
                    ?><strong class="label label-danger">Поставлено в очередь на удаление</strong> <?=$changeStatusUserHtml?>
                    <?php if ($this->canRestore) { ?>
                        <?=$this->restorePictureForm->render($this) ?>
                    <?php }
                    break;

                case Picture::STATUS_REMOVED:
                    ?><strong style="color:red">Удалено <?=$changeStatusUserHtml?></strong><?php
                    break;
            }
        ?></p>

        <?=$this->action('picture-vote', 'pictures', 'moder', [
            'picture_id' => $this->picture->id
        ])?>
    </div>

    <?php if ($this->canNormalize || $this->canFlop || $this->canCrop) { ?>
        <h3>Редактирование и устранение проблем</h3>
        <div class="well">

            <div class="btn-group">

                <?php if ($this->canNormalize) { ?>
                    <button class="btn btn-danger normalize"><i class="fa fa-signal"></i> Автоконтраст</button>
                <?php } ?>
                <?php if ($this->canFlop) { ?>
                    <button class="btn btn-danger flop"><i class="fa fa-arrows-h"></i> Отразить</button>
                <?php } ?>
                <?php if ($this->canCrop) { ?>
                    <button class="btn btn-success crop">
                        <i class="fa fa-crop"></i> Выделить область
                    </button>
                <?php } ?>
            </div>

            <div class="btn-group">
                <button class="btn btn-default files-repair"><i class="fa fa-wrench"></i> Исправить все файлы</button>
                <button class="btn btn-default files-correct-names"><i class="fa fa-wrench"></i> Пересчитать имена файлов</button>
            </div>

        </div>
    <?php } ?>

    <h3>Закачал</h3>
    <div class="well">
        <?php if ($user = $this->picture->findParentUsersByOwner()) { ?>
            <?=$this->user($user) ?>
        <?php } else { ?>
            Неизвестно
        <?php } ?>
        <?php if ($this->picture->ip) { ?>
            IP-адрес закачавшего: <b><?=$this->escapeHtml(inet_ntop($this->picture->ip))?></b><br />
            <?php if ($this->ban) { ?>
                <p>
                    Этот адрес забанил
                    <?php if ($this->ban['user']) { ?>
                        <?=$this->user($this->ban['user']) ?>
                    <?php } ?>
                    <?php if ($this->ban['up_to']) { ?>
                        до
                        <?=$this->ban['up_to']->format(MYSQL_DATETIME_FORMAT) ?>
                        <?php if ($this->ban['reason']) { ?>
                            (<?=$this->escapeHtml($this->ban['reason'])?>)
                        <?php } ?>
                    <?php } ?>
                </p>

                <?php if ($this->canBan) { ?>
                    <form action="<?=$this->url('ban/unban-ip', [
                        'ip' => inet_ntop($this->picture->ip)
                    ]) ?>" method="post" style="margin:10px 0">
                        <input type="submit" value="снять бан" />
                    </form>
                <?php } ?>
            <?php } ?>

            <?php if ($this->canBan) { ?>
                <form action="<?=$this->url('ban/ban-ip', [
                    'ip' => inet_ntop($this->picture->ip)
                ]) ?>" method="post" class="form-horizontal">
                    <fieldset>
                        <legend>Забанить</legend>
                        <div class="control-group">
                            <label class="control-label" for="period">На время</label>
                            <div class="controls">
                                <?=$this->formSelect('period', '1', [], [
                                    1  => 'час',
                                    2  => '2 часа',
                                    4  => '4 часа',
                                    8  => '8 часов',
                                    16 => '16 часов',
                                    24 => 'сутки',
                                    48 => 'двое суток',
                                ])?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="period">Причина</label>
                            <div class="controls">
                                <?=$this->formText('reason', '')?>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn btn-danger" type="submit">забанить</button>
                        </div>
                    </fieldset>
                </form>
            <?php } ?>
        <?php } ?>
    </div>
</div>