<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
    ));
?>
<ul>
    <?php foreach ($this->pages as $page) { ?>
        <li>
            [<?=$this->escape($page['id'])?>]
            <?=$this->escape($page['name'])?>
            <table style="margin-bottom:20px"><tr>
                <?php foreach ($page['groups'] as $group) { ?>
                    <td>
                        [<?=$this->escape($group['id'])?>]
                        <?=$this->escape($group['name'])?>
                        <ul>
                            <?php foreach ($group['perspectives'] as $perspective) { ?>
                                <li>
                                    [<?=$this->escape($perspective['id'])?>]
                                    <?=$this->escape($perspective['name'])?>
                                </li>
                            <?php } ?>
                        </ul>
                    </td>
                <?php } ?>
            </tr></table>
        </li>
    <?php } ?>
</ul>