<?php
    $layout = [
        'blankPage' => false,
        'needRight' => false
    ];
    if ($this->carType) {
        if ($this->cYear) {
            $this->pageEnv([
                'layout' => $layout,
                'pageId' => 156,
                'args'   => [
                    'MOST_CATNAME'     => $this->cMost['catName'],
                    'MOST_NAME'        => $this->translate('most/'.$this->cMost['catName']),
                    'CAR_TYPE_NAME'    => $this->translate($this->carType['name_rp']),
                    'CAR_TYPE_CARNAME' => $this->carType['catname'],
                    'YEAR_NAME'        => $this->translate($this->cYear['name']),
                    'YEAR_CATNAME'     => $this->cYear['folder'],
                ]
            ]);
        } else {
            $this->pageEnv([
                'layout' => $layout,
                'pageId' => 155,
                'args'   => [
                    'MOST_CATNAME'     => $this->cMost['catName'],
                    'MOST_NAME'        => $this->translate('most/'.$this->cMost['catName']),
                    'CAR_TYPE_NAME'    => $this->translate($this->carType['name_rp']),
                    'CAR_TYPE_CARNAME' => $this->carType['catname']
                ]
            ]);
        }
    } else {
        $this->pageEnv([
            'layout' => $layout,
            'pageId' => 154,
            'args'   => [
                'MOST_CATNAME' => $this->cMost['catName'],
                'MOST_NAME'    => $this->translate('most/'.$this->cMost['catName']),
            ]
        ]);
    }

    $this->layout()->moduleName = 'default/most';
?>
<ul class="nav nav-pills">
    <?php foreach ($this->years as $year) { ?>
        <li<?=$year['active'] ? ' class="active"' : '' ?>>
            <?=$this->htmlA($year['url'], $this->translate($year['name'])) ?>
        </li>
    <?php } ?>
</ul>

<?php $idx = 0 ?>
<?php foreach ($this->carList['cars'] as $car) { ?>
    <div class="row">
        <div class="col-md-9">
            <h3><?=$this->car()->htmlTitle($car['name'])?></h3>
        </div>
        <div class="col-md-3">
            <?php if ($idx++ == 0) { ?>
                <h3><?=$this->escapeHtml($this->translate('most/'.$this->cMost['catName'].'/param')) ?></h3> <?php /* $this->carList['paramName'] */ ?>
            <?php } ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="row thumbnails">
                <?php foreach ($car['pictures'] as $picture) { ?>
                    <div class="col-md-4">
                        <?php if ($picture) { ?>
                            <?=$this->htmlA([
                                'href'  => $picture['url'],
                                'class' => 'thumbnail'
                            ], $this->htmlImg([
                                'src'     => $picture['src'],
                                'format'  => 'picture-thumb',
                                'alt'     => $this->pic()->textTitle($picture['name']),
                                'title'   => $this->pic()->textTitle($picture['name']),
                                'shuffle' => true
                            ]), false)?>
                        <?php } else { ?>
                            &#xa0;
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
            <?php if ($car['description']) { ?>
                <div><?=$this->markdown($car['description']) ?></div>
            <?php } ?>
        </div>
        <div class="col-md-3">
            <h3>
                <?php if (isset($car['valueHtml'])) { ?>
                    <?=$car['valueHtml']?>
                <?php } else {?>
                    <?=$this->escapeHtml($car['valueText']) ?>
                <?php } ?>
                <?php if ($this->carList['unit']) { ?>
                    <small class="unit" title="<?=$this->escapeHtmlAttr($this->carList['unit']->name) ?>"><?=$this->escapeHtml($this->carList['unit']->abbr) ?></small>
                <?php } ?>
            </h3>
        </div>
    </div>
<?php } ?>