<div class="card card-body">
    <ul class="nav flex-column nav-pills">
        <li class="nav-item nav-header">
            <h3 class="nav-link"><?=$this->escapeHtml($this->translate('mosts/sidebar/mostly…'))?></h3>
        </li>
        <?php foreach ($this->sidebar['mosts'] as $most) { ?>
            <li class="nav-item">
                <?=$this->htmlA([
                    'class' => 'nav-link' . (most['active'] ? ' active' : ''),
                    'href'  => $most['url']
                ], $this->translate($most['name'])) ?>
            </li>
        <?php } ?>
        <li class="nav-item" class="nav-header">
            <h3 class="nav-link"><?=$this->escapeHtml($this->translate('mosts/sidebar/between…'))?></h3>
        </li>
        <?php foreach ($this->sidebar['carTypes'] as $carType) { ?>
            <li class="nav-item">
                <?=$this->htmlA([
                    'class' => 'nav-link' . ($carType['active'] ? ' active' : ''),
                    'href'  => $carType['url']
                ], $this->translate($carType['name'])) ?>
                <?php if ($carType['childs']) { ?>
                    <ul class="nav flex-column nav-pills">
                        <?php foreach ($carType['childs'] as $child) { ?>
                            <li class="nav-item">
                                <?=$this->htmlA([
                                    'class' => 'nav-link' . ($child['active'] ? ' active' : ''),
                                    'href'  => $child['url']
                                ], $this->translate($child['name'])) ?>
                            </li>
                        <?php } ?>
                    </ul>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>
</div>
