<div class="well">
    <ul class="nav nav-pills nav-stacked">
        <li class="nav-header">
            <h3><?=$this->escapeHtml($this->translate('mosts/sidebar/mostly…'))?></h3>
        </li>
        <?php foreach ($this->sidebar['mosts'] as $most) { ?>
            <li<?=$most['active'] ? ' class="active"' : '' ?>>
                <?=$this->htmlA($most['url'], $this->translate($most['name'])) ?>
            </li>
        <?php } ?>
        <li class="nav-header">
            <h3><?=$this->escapeHtml($this->translate('mosts/sidebar/between…'))?></h3>
        </li>
        <?php foreach ($this->sidebar['carTypes'] as $carType) { ?>
            <li<?=$carType['active'] ? ' class="active"' : '' ?>>
                <?=$this->htmlA($carType['url'], $this->translate($carType['name'])) ?>
                <?php if ($carType['childs']) { ?>
                    <ul class="nav nav-pills nav-stacked">
                        <?php foreach ($carType['childs'] as $child) { ?>
                            <li<?=$child['active'] ? ' class="active"' : '' ?>>
                                <?=$this->htmlA($child['url'], $this->translate($child['name'])) ?>
                            </li>
                        <?php } ?>
                    </ul>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>
</div>