<?php
    $this->pageEnv(array(
        'layout' => array(
            'isAdminPage' => true,
            'blankPage'   => false,
            'needLeft'    => false,
            'needRight'   => false
        ),
    ));
?>
<?php if ($this->canManage) { ?>
    <form action="<?=$this->escape($this->url(array(
        'action' => 'clear-all',
    )))?>" method="psot" class="form-inline">
        <?=$this->formSubmit('submit', 'Clear all', array(
            'class' => 'btn btn-danger'
        ))?>
    </form>
<?php } ?>
<table class="table table-border">
    <thead>
        <tr>
            <th>Host</th>
            <th>URL</th>
            <th>Count</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->hosts as $host) { ?>
            <tr>
                <td>
                    <?=$this->escape($host['host'])?>
                    <?php if ($this->canManage) { ?>
                        <form action="<?=$this->escape($this->url(array(
                            'action' => 'clear-host',
                            'host'   => $host['host']
                        )))?>" method="psot" class="form-inline">
                            <?=$this->formSubmit('submit', 'Clear', array(
                                'class' => 'btn btn-warning btn-xs'
                            ))?>
                        </form>
                        <?php if (!$host['whitelisted']) { ?>
                            <form action="<?=$this->escape($this->url(array(
                                'action' => 'whitelist-host',
                                'host'   => $host['host']
                            )))?>" method="psot" class="form-inline">
                                <?=$this->formSubmit('submit', 'Whitelist', array(
                                    'class' => 'btn btn-success btn-xs'
                                ))?>
                            </form>
                            <form action="<?=$this->escape($this->url(array(
                                'action' => 'whitelist-and-clear-host',
                                'host'   => $host['host']
                            )))?>" method="psot" class="form-inline">
                                <?=$this->formSubmit('submit', 'Whitelist&Clear', array(
                                    'class' => 'btn btn-success btn-xs'
                                ))?>
                            </form>
                        <?php } ?>
                        <?php if (!$host['blacklisted']) { ?>
                            <form action="<?=$this->escape($this->url(array(
                                'action' => 'blacklist-host',
                                'host'   => $host['host']
                            )))?>" method="psot" class="form-inline">
                                <?=$this->formSubmit('submit', 'Blacklist', array(
                                    'class' => 'btn btn-danger btn-xs'
                                ))?>
                            </form>
                        <?php } ?>
                    <?php } ?>
                </td>
                <td>
                    <?php foreach ($host['links'] as $link) { ?>
                        <?=$link['last_date']?> <?=$this->htmlA($link['url'], mb_strlen($link['url']) > 70 ? mb_substr($link['url'], 0, 70) . ' ...' : $link['url'])?> <small>(<?=$link['count']?>)</small><br />
                        <?=$this->escape($link['accept'])?><br />
                    <?php } ?>
                </td>
                <td><?=$host['c']?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>