<?php if ($this->pageCount > 1) { ?>
    <div id="pager" class="clearfix text-right">
        <div class="nearLinks">
            <?php if (isset($this->previous)) { ?>
                <?php if ($this->pictures[$this->previous]) { ?>
                    <?=$this->htmlA(
                        $this->pictures[$this->previous],
                        '<i class="fa fa-chevron-left"></i> ' . $this->escapeHtml($this->translate('previous')),
                        false
                    ) ?>
                <?php } ?>
            <?php } else { ?>
                <i class="fa fa-chevron-left"></i> <?=$this->escapeHtml($this->translate('previous'))?>
            <?php } ?>

            <?php if (isset($this->next)) { ?>
                <?php if ($this->pictures[$this->next]) { ?>
                    <?=$this->htmlA(
                        $this->pictures[$this->next],
                        $this->escapeHtml($this->translate('next')) . ' <i class="fa fa-chevron-right"></i>',
                        false
                    ) ?>
                <?php } ?>
            <?php } else { ?>
                <?=$this->escapeHtml($this->translate('next'))?> <i class="fa fa-chevron-right"></i></span>
            <?php } ?>
        </div>
        <div class="numberLinks">
            <?php $format = '%0'.max(2, strlen($this->pageCount)).'d' ?>
            <?php foreach ($this->pagesInRange as $page) { ?>
                <?php if ($page != $this->current) { ?>
                    <?php if ($this->pictures[$page]) { ?>
                        <?=$this->htmlA($this->pictures[$page], sprintf($format, $page)) ?>
                    <?php } ?>
                <?php } else { ?>
                    <strong style="font-size:1.5em"><?=sprintf($format, $page) ?></strong>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
<?php } ?>