<?php
    if ($this->previewUrl) {
        $this->headMeta()
            ->appendName('photo',                              'twitter:card'  )
            ->appendName($this->pic()->textTitle($this->name), 'twitter:title' )
            ->appendName($this->previewUrl,  'twitter:image' );
            /*->headMeta('twitter:image:width',  $image->width() )
            ->headMeta('twitter:image:height', $image->height());*/
    }

    $this->layout()->moduleName = 'default/picture';
    $this->layout()->moduleOptions = [
        'gallery2'   => isset($this->gallery2) && $this->gallery2,
        'galleryUrl' => $this->galleryUrl,
        'gallery'    => $this->gallery
    ];

    //$this->headTitle($this->pic()->textTitle($this->name), 'SET');
?>

<?php $this->pageTitle()->setAutoEscape(false)->captureStart('SET') ?>
    <?=$this->pic()->htmlTitle($this->name) ?>
    <?php if ($this->designProject) { ?>
        <sup class="designBrand"><?=sprintf($this->translate('carlist/designed by %s'), $this->htmlA($this->designProject['url'], $this->designProject['brand']))?></sup>
    <?php } ?>
<?php $this->pageTitle()->captureEnd() ?>

<div class="row">
    <div class="col-md-6">
        <div class="picture-preview-medium">
            <?=$this->htmlA([
                'class' => 'thumbnail',
                'href'  => $this->sourceUrl
            ], $this->htmlImg([
                'src'     => $this->previewUrl,
                'alt'     => $this->pic()->textTitle($this->name),
                'title'   => $this->pic()->textTitle($this->name),
                'shuffle' => true
            ]), false)?>
            <?php if ($this->picture->type == Application\Model\DbTable\Picture::VEHICLE_TYPE_ID) { ?>
                <?php if (isset($this->altNames) && count($this->altNames)) { ?>
                    <div class="languages">
                        <p><?=$this->escapeHtml($this->translate('picture/other-languages'))?></p>
                        <ul class="list-unstyled">
                            <?php foreach ($this->altNames as $name => $languages) { ?>
                                <li>
                                    <?php foreach ($languages as $language) { ?>
                                        <sup><?=$this->escapeHtml(strtoupper($language))?></sup>
                                    <?php } ?>
                                    <?=$this->escapeHtml($name) ?>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                <?php } ?>
            <?php } ?>
        </div>
        <?php if ($this->copyrights) { ?>
            <div>
                <?=$this->markdown($this->copyrights) ?>
            </div>
        <?php } ?>

        <?php if ($this->picture->type == Application\Model\DbTable\Picture::VEHICLE_TYPE_ID) { ?>

            <?php if (count($this->modifications) > 0) { ?>
                <p>
                    <?php foreach ($this->modifications as $modification) { ?>
                        <?php if ($modification['url']) { ?>
                            <?=$this->htmlA([
                                'class' => 'label label-primary',
                                'href'  => $modification['url']
                            ], $modification['name'])?>
                        <?php } else { ?>
                            <span class="label label-primary"><?=$this->escapeHtml($modification['name'])?></span>
                        <?php } ?>
                    <?php } ?>
                </p>
            <?php } ?>

            <?php if ($this->carDescription) { ?>
                <div style="margin-bottom:10px">
                    <?=$this->markdown($this->carDescription) ?>
                </div>
            <?php } ?>
            <?php if ($this->carHtml) { ?>
                <p>
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($this->carDetailsUrl, $this->translate('carlist/details')) ?>
                </p>
            <?php } ?>
        <?php } ?>

        <?php if ($this->replacePicture) { ?>
            <p>
                <?=$this->escapeHtml($this->translate('picture/picture-suggested-to-replace'))?>
                <?=$this->htmlA($this->replacePicture, $this->serverUrl($this->replacePicture))?>
            </p>
        <?php } ?>

    </div>
    <div class="col-md-6">
        <p><?=$this->escapeHtml($this->translate('picture/image-specifications'))?>:</p>
        <ul>
            <li><?=$this->escapeHtml($this->translate('Resolution'))?>: <strong><?=(int)$this->picture->width.'×'.(int)$this->picture->height ?></strong></li>
            <li><?=$this->escapeHtml($this->translate('Filesize'))?>: <strong><?=$this->escapeHtml($this->fileSize($this->picture->filesize)) ?></strong></li>
            <?php if ($this->owner) { ?>
                <li>
                    <?=$this->escapeHtml($this->translate('picture/added-by:'))?>
                    <?=$this->user($this->owner) ?>,
                    <?=$this->escapeHtml($this->user()->humanTime($this->addDate)) ?>
                </li>
            <?php } ?>
            <li>
                <?=$this->escapeHtml($this->translate('picture/status:'))?>
                <?php
                    switch ($this->picture->status) {
                        case Application\Model\DbTable\Picture::STATUS_NEW:      echo $this->escapeHtml($this->translate('picture/status/new')); break;
                        case Application\Model\DbTable\Picture::STATUS_INBOX:    echo $this->escapeHtml($this->translate('picture/status/inbox')); break;
                        case Application\Model\DbTable\Picture::STATUS_ACCEPTED: echo $this->escapeHtml($this->translate('picture/status/accepted')); break;
                        case Application\Model\DbTable\Picture::STATUS_REMOVING: echo '<span class="text-danger">'.$this->escapeHtml($this->translate('picture/status/removing')).'</span>'; break;
                    }
                ?>
            </li>
        </ul>
        <?php if ($source = $this->picture->findParentRow('Application\\Model\\DbTable\\Sources')) { ?>
            <p>
                <?=$this->escapeHtml($this->translate('picture/photo-is-owned-by'))?>
                <?=$this->htmlA($source->url, $source->name) ?>
            </p>
        <?php } else { ?>
            <p><?=$this->escapeHtml($this->translate('picture/all-images-have-owners'))?></p>
        <?php } ?>
        <p><?=$this->escapeHtml($this->translate('picture/if-you-found-error'))?></p>
        <p><?=$this->translate('picture/where-to-talk')?></p>
        <?php
            $list = [];

            foreach ($this->ofLinks as $link) {
                $list[] = $this->htmlA($link->url, '<i class="fa fa-globe"></i> ' . $this->escapeHtml($link->caption), false);
            }
        ?>
        <?php
            switch ($this->picture->type) {
                case Application\Model\DbTable\Picture::VEHICLE_TYPE_ID:
                    $car = $this->picture->findParentCars();
                    if ($car) {

                        foreach ($this->categories as $category) {
                            $list[] = $this->htmlA($category['url'], '<i class="fa fa-tag"></i> ' . $this->escapeHtml($category['name']), false);
                        }

                        if ($this->user()->isAllowed('specifications', 'edit')) {
                            $list[] = $this->htmlA($this->url('cars/params', [
                                'action' => 'car-specifications-editor',
                                'car_id' => $car->id
                            ]), '<i class="fa fa-pencil"></i> ' . $this->escapeHtml($this->translate('carlist/edit-specs')), false);
                        }

                        if ($this->vehicleHasSpecs) {

                            foreach ($this->car($car)->cataloguePaths() as $path) {
                                $url = $this->url('catalogue', [
                                    'action'        => 'brand-car-specifications',
                                    'brand_catname' => $path['brand_catname'],
                                    'car_catname'   => $path['car_catname'],
                                    'path'          => $path['path']
                                ]);

                                $name = $car->getFullName($this->language());
                                $list[] = $this->htmlA(
                                    $url,
                                    '<i class="fa fa-list-alt"></i> ' .
                                    $this->escapeHtml(sprintf($this->translate('catalogue/specifications-of-%1$s'), $name)),
                                    false
                                );

                                break;
                            }
                        }

                        if ($this->designProject) {
                            $list[] = sprintf($this->translate('carlist/designed by %s'), $this->htmlA(
                                $this->designProject['url'],
                                $this->designProject['brand']
                            ));
                        }

                        foreach ($this->vehicleTwins as $twinsGroup) {
                            $list[] = $this->htmlA(
                                $twinsGroup['url'],
                                '<i class="fa fa-adjust"></i> ' . $this->escapeHtml($this->page(96)->name),
                                false
                            );
                        }

                        if ($this->user()->logedIn()) {
                            $list[] = $this->htmlA($this->url('upload/params', [
                                'action'     => 'index',
                                'type'       => '1',
                                'car_id'     => $car->id
                            ]), '<i class="fa fa-upload"></i> ' . $this->escapeHtml($this->page(29)->name) . ' ' . $this->pic()->htmlTitle($this->name), false);
                        }
                    }
                    break;

                case Application\Model\DbTable\Picture::MIXED_TYPE_ID:
                    if ($this->user()->logedIn()) {
                        if ($brand = $this->picture->findParentRow(Application\Model\DbTable\Brand::class)) {
                            $list[] = $this->htmlA($this->url('upload/params', [
                                'action'     => 'index',
                                'type'       => Application\Model\DbTable\Picture::MIXED_TYPE_ID,
                                'brand_id'   => $brand->id
                            ]), '<i class="fa fa-upload"></i> ' . $this->escapeHtml($this->page(29)->name) . ' ' . $this->pic()->htmlTitle($this->name), false);
                        }
                    }
                    break;

                case Application\Model\DbTable\Picture::ENGINE_TYPE_ID:
                    if (count($this->engineCars) > 0) {
                        if (count($this->engineCars) == 1)
                            foreach ($this->engineCars as $car) {
                                $list[] = $this->escapeHtml($this->translate('picture/that-engine-is-mounted-to-vehicle')) . $this->htmlA($car['url'], $car['name']);
                            }
                        else {
                            $a = [];
                            foreach ($this->engineCars as $car) {
                                $a[] = $this->htmlA($car['url'], $car['name']);
                            }
                            $list[] = $this->escapeHtml($this->translate('picture/that-engine-is-mounted-to-vehicles:')) .
                                      $this->htmlList($a, false, [], false);
                        }
                    }

                    if ($this->engine) {
                        if ($this->engineHasSpecs) {
                            $list[] = $this->htmlA(
                                $this->engineSpecsUrl,
                                '<i class="fa fa-list-alt"></i> ' .
                                sprintf($this->escapeHtml($this->translate('catalogue/specifications-of-%1$s')), $this->escapeHtml($this->engine->caption)),
                                false
                            );
                        }

                        if ($this->user()->isAllowed('specifications', 'edit')) {
                            $list[] = $this->htmlA($this->url('cars', [
                                'action'     => 'engine-spec-editor',
                                'engine_id'  => $this->engine->id
                            ]), '<i class="fa fa-pencil"></i> ' . $this->escapeHtml($this->translate('carlist/edit-specs')), false);
                        }
                    }
                    break;

                case Application\Model\DbTable\Picture::FACTORY_TYPE_ID:
                    if ($this->factory) {
                        $list[] = $this->htmlA($this->url('factories/factory', [
                            'id' => $this->factory->id
                        ]), $this->translate('picture/factory-details'));
                    }
                    if (count($this->factoryCars) > 0) {
                        if (count($this->factoryCars) == 1)
                            foreach ($this->factoryCars as $car) {
                                $list[] = $this->escapeHtml($this->translate('picture/on-that-factory-produced-vehicle')) . ' ' . $this->htmlA($car['url'], $car['name']);
                            }
                        else {
                            $a = [];
                            foreach ($this->factoryCars as $car) {
                                $a[] = $this->htmlA($car['url'], $car['name']);
                            }

                            if ($this->factoryCarsMore) {
                                $a[] = ' ' . $this->escapeHtml($this->translate('picture/on-that-factory-produced-vehicles/and')) .
                                       ' ' . $this->htmlA($this->url('factories/factory-cars', [
                                    'id' => $this->factory->id
                                ]), $this->translate('picture/on-that-factory-produced-vehicles/and-other'));
                            }

                            $list[] = $this->escapeHtml($this->translate('picture/on-that-factory-produced-vehicles:')) .
                                      $this->htmlList($a, false, [], false);
                        }
                    }
                    break;
            }

            if ($this->user()->logedIn()) {
                if ($this->picture->car_id || $this->picture->brand_id || $this->picture->engine_id) {
                    $list[] = $this->htmlA($this->url('upload/params', [
                        'action'  => 'index',
                        'replace' => $this->picture->identity ? $this->picture->identity : $this->picture->id
                    ]), '<i class="fa fa-exchange"></i> ' . $this->escapeHtml($this->translate('picture/propose-image-replacement')), false);
                }
            }
        ?>

        <?php if (count($list)) { ?>
            <?=$this->htmlList($list, false, [
                'class' => 'unstyled'
            ], false) ?>
        <?php } ?>

        <?php if ($this->paginator && $this->paginator->count() > 1) { ?>
            <h4 class="text-right"><?=$this->escapeHtml($this->translate('catalogue/other-photos'))?></h4>
            <?=$this->paginationControl(
                $this->paginator,
                'Sliding',
                'application/picture/paginator',
                [
                    'pictures'  => $this->paginatorPictures,
                    'picture'   => $this->picture
                ]
            )?>
        <?php } ?>
    </div>
</div>

<?php if (count($this->moderVotes) > 0) { ?>
    <div>
        <p><?=$this->escapeHtml($this->translate('picture/moderators-about-this-picture'))?>:</p>
        <ul class="list-unstyled">
            <?php foreach ($this->moderVotes as $moderVote) { ?>
                <li>
                    <?php if ($moderVote['vote']) { ?>
                        <i style="color:green" class="fa fa-thumbs-up"></i>
                        <?=$this->user($moderVote['user'])?>
                        <span style="color:green"><?=$this->escapeHtml($moderVote['reason'])?></span>
                    <?php } else { ?>
                        <i style="color:red" class="fa fa-thumbs-down"></i>
                        <?=$this->user($moderVote['user'])?>
                        <span style="color:red"><?=$this->escapeHtml($moderVote['reason'])?></span>
                    <?php } ?>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>

<?php if ($this->user()->inheritsRole('moder')) { ?>
    <h3><?=$this->htmlA($this->url('moder/index'), $this->page(67)->name) ?></h3>
    <div class="well">
        <div class="row">
            <div class="col-md-6">
                <?=$this->partial('application/moder/pictures/picture-vote', $this->pictureVote)?>
            </div>
            <div class="col-md-6">
                <?php foreach ($this->moderLinks as $url => $name) { ?>
                    <p><i class="fa fa-cog"></i> <?=$this->htmlA($url, $name)?></p>
                <?php } ?>
            </div>
            <?php if ($this->picture->type == Application\Model\DbTable\Picture::VEHICLE_TYPE_ID) { ?>
                <div class="col-md-6">
                    <?=$this->partial('application/moder/pictures/picture-perspective', $this->picturePerspective)?>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>

<div id="comments">
    <?=$this->comments([
        'type'    => Application\Model\DbTable\Comment\Message::PICTURES_TYPE_ID,
        'item_id' => $this->picture->id
    ]) ?>
</div>