<?php
    $this->headMeta()
        ->appendName('twitter:card', 'summary_large_image')
        ->appendName('twitter:title', $this->pic()->textTitle($this->name))
        ->appendName('twitter:description', $this->pic()->textTitle($this->name))
        ->appendName('medium', 'image')
        ->appendProperty('og:type', 'website')
        ->appendProperty('og:title', $this->pic()->textTitle($this->name))
        ->appendProperty('og:url', $this->url(null, [], [
            'force_canonical' => true
        ], true))
        ->appendProperty('og:description', $this->pic()->textTitle($this->name));

    if ($this->twitterCreatorId) {
        $this->headMeta()->appendName('twitter:creator:id', $this->twitterCreatorId);
    }

    if ($this->galleryImage) {
        $this->headMeta()
            ->appendProperty('og:image', $this->galleryImage->getSrc())
            ->appendProperty('og:image:width',  $this->galleryImage->getWidth())
            ->appendProperty('og:image:height', $this->galleryImage->getHeight())
            ->appendName('twitter:image', $this->galleryImage->getSrc());

        $this->headLink(['rel' => 'image_src', 'href' => $this->galleryImage->getSrc()]);
    }

    $this->layout()->moduleName = 'default/picture';
    $this->layout()->moduleOptions = [
        'galleryUrl' => $this->galleryUrl,
        'gallery'    => $this->gallery
    ];

    //$this->headTitle($this->pic()->textTitle($this->name), 'SET');
?>

<?php $this->pageTitle()->setAutoEscape(false)->captureStart('SET') ?>
    <?=$this->pic()->htmlTitle($this->name) ?>
    <?php if (count($this->items) == 1) { ?>
        <?php if ($this->items[0]['designProject']) { ?>
            <sup class="design-brand">
                <?=sprintf(
                    $this->translate('carlist/designed by %s'),
                    $this->htmlA(
                        $this->items[0]['designProject']['url'],
                        $this->items[0]['designProject']['name']
                    )
                )?>
            </sup>
        <?php } ?>
    <?php } ?>
<?php $this->pageTitle()->captureEnd() ?>

<div class="row">
    <div class="col-md-6">
        <div class="picture-preview-medium">
            <?=$this->htmlA([
                'class' => 'thumbnail',
                'href'  => $this->sourceUrl
            ], $this->htmlImg([
                'src'     => $this->previewUrl,
                'alt'     => $this->pic()->textTitle($this->name),
                'title'   => $this->pic()->textTitle($this->name),
                'shuffle' => true
            ]), false)?>
            <?php if (count($this->items) == 1) { ?>
                <?php if (count($this->items[0]['altNames'])) { ?>
                    <div class="languages">
                        <p><?=$this->escapeHtml($this->translate('picture/other-languages'))?></p>
                        <ul class="list-unstyled">
                            <?php foreach ($this->items[0]['altNames'] as $name => $languages) { ?>
                                <li>
                                    <?php foreach ($languages as $language) { ?>
                                        <sup><?=$this->escapeHtml(strtoupper($language))?></sup>
                                    <?php } ?>
                                    <?=$this->escapeHtml($name) ?>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                <?php } ?>
            <?php } ?>
        </div>

        <div class="row">
            <div class="col-xs-6">
                <div class="picture-vote" data-id="<?=(int)$this->picture['id']?>">
                    <?php if ($this->user()->logedIn()) { ?>
                        <?=$this->htmlA([
                            'href'  => '#',
                            'class' => 'fa fa-2x vote-up ' . ($this->votes['value'] > 0 ? 'fa-thumbs-up' : 'fa-thumbs-o-up')
                        ], '')?>
                    <?php } else { ?>
                        <i class="fa fa-2x fa-thumbs-o-up"></i>
                    <?php } ?>
                    <span class="positive<?=$this->votes['positive'] ? '' : ' zero'?>"><?=$this->votes['positive']?></span>
                    <?php if ($this->user()->logedIn()) { ?>
                        <?=$this->htmlA([
                            'href'  => '#',
                            'class' => 'fa fa-2x vote-down ' . ($this->votes['value'] < 0 ? 'fa-thumbs-down' : 'fa-thumbs-o-down')
                        ], '')?>
                    <?php } else { ?>
                        <i class="fa fa-2x fa-thumbs-o-down"></i>
                    <?php } ?>
                    <span class="negative<?=$this->votes['negative'] ? '' : ' zero'?>"><?=$this->votes['negative']?></span>
                </div>
            </div>
            <div class="col-xs-6 text-right">
                <?php if ($this->user()->logedIn()) { ?>
                    <a href="#" class="picture-subscription subscription<?=$this->subscribed ? ' subscribed' : ''?>" data-url="<?=$this->escapeHtmlAttr($this->subscribeUrl) ?>">
                        <span class="fa fa-2x fa-envelope-o subscribe" title="<?=$this->escapeHtmlAttr($this->translate('comments/subscribe'))?>"></span>
                        <span class="fa fa-2x fa-envelope unsubscribe" title="<?=$this->escapeHtmlAttr($this->translate('comments/unsubscribe'))?>"></span>
                    </a>
                <?php } ?>
                <a href="#" class="fa fa-2x fa-share-alt btn-share-dialog" title="Share ..."></a>
            </div>
        </div>

        <div class="share-dialog">
            <?=$this->partial('application/share', [
                'url'     => $this->canonicalUrl,
                'text'    => $this->pic()->textTitle($this->name),
                'picture' => $this->preview
            ])?>
        </div>

        <?php if ($this->authors) { ?>
            <p>
                Author:
                <?php foreach ($this->authors as $idx => $author) {
                    if ($idx) {
                        echo ', ';
                    }
                    echo $this->htmlA($author['url'], $author['name']);
                } ?>
            </p>
        <?php } ?>

        <?php if ($this->copyrights) { ?>
            <div>
                <?=$this->markdown($this->copyrights) ?>
            </div>
        <?php } ?>

        <?php /*if (count($this->modifications) > 0) { ?>
            <p>
                <?php foreach ($this->modifications as $modification) { ?>
                    <?php if ($modification['url']) { ?>
                        <?=$this->htmlA([
                            'class' => 'label label-primary',
                            'href'  => $modification['url']
                        ], $modification['name'])?>
                    <?php } else { ?>
                        <span class="label label-primary"><?=$this->escapeHtml($modification['name'])?></span>
                    <?php } ?>
                <?php } ?>
            </p>
        <?php } */ ?>

        <?php foreach ($this->items as $item) { ?>
            <?php if ($item['description']) { ?>
                <div style="margin-bottom:10px">
                    <?=$this->markdown($item['description']) ?>
                </div>
            <?php } ?>
            <?php if ($item['detailsUrl']) { ?>
                <p>
                    <i class="fa fa-align-left"></i>
                    <?=$this->htmlA($item['detailsUrl'], $this->translate('carlist/details')) ?>
                </p>
            <?php } ?>
        <?php } ?>

        <?php if ($this->replacePicture) { ?>
            <p>
                <?=$this->escapeHtml($this->translate('picture/picture-suggested-to-replace'))?>
                <?=$this->htmlA($this->replacePicture, $this->serverUrl($this->replacePicture))?>
            </p>
        <?php } ?>

    </div>
    <div class="col-md-6">
        <p><?=$this->escapeHtml($this->translate('picture/image-specifications'))?>:</p>
        <ul>
            <li>
                <?=$this->escapeHtml($this->translate('Resolution'))?>: <strong><?=(int)$this->picture['width'].'×'.(int)$this->picture['height'] ?></strong>
                <?php if ($this->picture['dpi_x'] || $this->picture['dpi_y']) { ?>
                    @ <strong><?=$this->picture['dpi_x'] ?>×<?=$this->picture['dpi_y'] ?></strong>
                    <a href="https://en.wikipedia.org/wiki/Dots_per_inch"><abbr title="Dots Per Inch">DPI</abbr></a>
                    <?php if ($this->picture['dpi_x'] > 0 && $this->picture['dpi_y'] > 0) { ?>
                        <?=round(2.54 * $this->picture['width'] / $this->picture['dpi_x']) ?>×<?=round(2.54 * $this->picture['height'] / $this->picture['dpi_y']) ?>cm
                    <?php } ?>
                <?php } ?>
            </li>
            <li><?=$this->escapeHtml($this->translate('Filesize'))?>: <strong><?=$this->escapeHtml($this->fileSize($this->picture['filesize'])) ?></strong></li>
            <?php if ($this->owner) { ?>
                <li>
                    <?=$this->escapeHtml($this->translate('picture/added-by:'))?>
                    <?=$this->user($this->owner) ?>,
                    <?=$this->escapeHtml($this->user()->humanTime($this->addDate)) ?>
                </li>
            <?php } ?>
            <?php if ($this->point) { ?>
                <li>
                    <span class="fa fa-map-pin"></span>
                    <?=$this->htmlA(
                        'https://www.openstreetmap.org/?mlat='.$this->point->y().'&mlon='.$this->point->x().'#map=6/'.$this->point->y().'/'.$this->point->x(),
                        $this->translate('picture/location')
                    )?>
                </li>
            <?php } ?>
            <li>
                <?=$this->escapeHtml($this->translate('picture/status:'))?>
                <?php
                    switch ($this->picture['status']) {
                        case Application\Model\Picture::STATUS_INBOX:    echo $this->escapeHtml($this->translate('picture/status/inbox')); break;
                        case Application\Model\Picture::STATUS_ACCEPTED: echo $this->escapeHtml($this->translate('picture/status/accepted')); break;
                        case Application\Model\Picture::STATUS_REMOVING: echo '<span class="text-danger">'.$this->escapeHtml($this->translate('picture/status/removing')).'</span>'; break;
                    }
                ?>
            </li>
        </ul>
        <p><?=$this->escapeHtml($this->translate('picture/all-images-have-owners'))?></p>
        <p><?=$this->escapeHtml($this->translate('picture/if-you-found-error'))?></p>
        <p><?=$this->translate('picture/where-to-talk')?></p>
        <?php
            $list = [];

            foreach ($this->ofLinks as $link) {
                $list[] = $this->htmlA($link['url'], '<i class="fa fa-globe"></i> ' . $this->escapeHtml($link['name']), false);
            }

            foreach ($this->items as $item) {

                foreach ($item['categories'] as $category) {
                    $list[$category['url']] = $this->htmlA(
                        $category['url'],
                        '<i class="fa fa-tag"></i> ' . $this->car()->htmlTitle($category['name']),
                        false
                    );
                }

                if ($item['specsEditUrl']) {
                    $list[] = $this->htmlA(
                        $item['specsEditUrl'],
                        '<i class="fa fa-pencil"></i> ' . $this->escapeHtml($this->translate('carlist/edit-specs')),
                        false
                    );
                }

                if ($item['hasSpecs'] && $item['specsUrl']) {
                    $list[] = $this->htmlA(
                        $item['specsUrl'],
                        '<i class="fa fa-list-alt"></i> ' .
                        sprintf(
                            $this->escapeHtml($this->translate('catalogue/specifications-of-%1$s')),
                            $this->car()->htmlTitle($item['name'])
                        ),
                        false
                    );
                }

                if ($item['designProject']) {
                    $list[] = sprintf($this->translate('carlist/designed by %s'), $this->htmlA(
                        $item['designProject']['url'],
                        $item['designProject']['name']
                    ));
                }

                foreach ($item['twins'] as $twinsGroup) {
                    $list[] = $this->htmlA(
                        $twinsGroup['url'],
                        '<i class="fa fa-adjust"></i> ' . $this->escapeHtml($this->page(96)->name),
                        false
                    );
                }

                foreach ($item['factories'] as $factory) {
                    $list[] = $this->htmlA(
                        $factory['url'],
                        '<i class="fa fa-cogs"></i> ' . $this->escapeHtml($factory['name']),
                        false
                    );
                }
            }

            $uploadUrlCount = 0;
            foreach ($this->items as $item) {
                if ($item['uploadUrl']) {
                    $uploadUrlCount++;
                }
            }

            if ($uploadUrlCount > 1) {
                $uploads = [];
                foreach ($this->items as $item) {
                    if ($item['uploadUrl']) {
                        $uploads[] = $this->htmlA(
                            $item['uploadUrl'],
                            '<i class="fa fa-upload"></i> ' .
                            $this->escapeHtml($this->page(29)->name) . ' ' .
                            $this->car()->htmlTitle($item['name']),
                            false
                        );
                    }
                }

                $list[] = '<div class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        ' . $this->escapeHtml($this->page(29)->name) .'
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li>' . implode('</li><li>', $uploads) . '</li>
                    </ul>
                </div>';

            } else {
                foreach ($this->items as $item) {
                    if ($item['uploadUrl']) {
                        $list[] = $this->htmlA(
                            $item['uploadUrl'],
                            '<i class="fa fa-upload"></i> ' .
                            $this->escapeHtml($this->page(29)->name) . ' ' .
                            $this->car()->htmlTitle($item['name']),
                            false
                        );
                    }
                }
            }

            foreach ($this->engines as $engine) {
                if (count($engine['vehicles']) > 0) {
                    if (count($engine['vehicles']) == 1)
                        foreach ($engine['vehicles'] as $car) {
                            $list[] = $this->escapeHtml($this->translate('picture/that-engine-is-mounted-to-vehicle')) . ' ' . $this->htmlA($car['url'], $car['name']);
                        }
                    else {
                        $a = [];
                        foreach ($engine['vehicles'] as $car) {
                            $a[] = $this->htmlA($car['url'], $car['name']);
                        }
                        $list[] = $this->escapeHtml($this->translate('picture/that-engine-is-mounted-to-vehicles:')) .
                        $this->htmlList($a, false, [], false);
                    }
                }

                if ($engine['hasSpecs']) {
                    $list[] = $this->htmlA(
                        $engine['specsUrl'],
                        '<i class="fa fa-list-alt"></i> ' .
                        sprintf(
                            $this->escapeHtml($this->translate('catalogue/specifications-of-%1$s')),
                            $this->escapeHtml($engine['name'])
                        ),
                        false
                    );
                }

                if ($engine['specsEditUrl']) {
                    $list[] = $this->htmlA(
                        $engine['specsEditUrl'],
                        '<i class="fa fa-pencil"></i> ' . $this->escapeHtml($this->translate('carlist/edit-specs')),
                        false
                    );
                }
            }

            foreach ($this->factories as $factory) {
                if ($factory) {
                    $list[] = $this->htmlA($this->url('factories/factory', [
                        'id' => $factory['id']
                    ]), $this->translate('picture/factory-details'));
                }
                if (count($factory['items']) > 0) {
                    if (count($factory['items']) == 1)
                        foreach ($factory['items'] as $car) {
                            $list[] = $this->escapeHtml($this->translate('picture/on-that-factory-produced-vehicle')) . ' ' . $this->htmlA($car['url'], $car['name']);
                        }
                    else {
                        $a = [];
                        foreach ($factory['items'] as $car) {
                            $a[] = $this->htmlA($car['url'], $car['name']);
                        }

                        if ($factory['itemsMore']) {
                            $a[] = ' ' . $this->escapeHtml($this->translate('picture/on-that-factory-produced-vehicles/and')) .
                                   ' ' . $this->htmlA($this->url('factories/factory-cars', [
                                'id' => $factory['id']
                            ]), $this->translate('picture/on-that-factory-produced-vehicles/and-other'));
                        }

                        $list[] = $this->escapeHtml($this->translate('picture/on-that-factory-produced-vehicles:')) .
                                  $this->htmlList($a, false, [], false);
                    }
                }
            }

            if ($this->user()->logedIn()) {
                if (count($this->items) || count($this->engines)) {
                    $list[] = $this->htmlA($this->url('upload/params', [
                        'action'  => 'index',
                        'replace' => $this->picture['identity']
                    ]), '<i class="fa fa-exchange"></i> ' . $this->escapeHtml($this->translate('picture/propose-image-replacement')), false);
                }
            }
        ?>

        <?php if (count($list)) { ?>
            <?=$this->htmlList($list, false, [
                'class' => 'unstyled'
            ], false) ?>
        <?php } ?>

        <?php if ($this->paginator && $this->paginator->count() > 1) { ?>
            <h4 class="text-right"><?=$this->escapeHtml($this->translate('catalogue/other-photos'))?></h4>
            <?=$this->paginationControl(
                $this->paginator,
                'Sliding',
                'application/picture/paginator',
                [
                    'pictures'  => $this->paginatorPictures,
                    'picture'   => $this->picture
                ]
            )?>
        <?php } ?>
    </div>
</div>

<?php if (count($this->moderVotes) > 0) { ?>
    <div>
        <p><?=$this->escapeHtml($this->translate('picture/moderators-about-this-picture'))?>:</p>
        <ul class="list-unstyled">
            <?php foreach ($this->moderVotes as $moderVote) { ?>
                <li>
                    <?php if ($moderVote['vote']) { ?>
                        <i style="color:green" class="fa fa-thumbs-up"></i>
                        <?=$this->user($moderVote['user'])?>
                        <span style="color:green"><?=$this->escapeHtml($moderVote['reason'])?></span>
                    <?php } else { ?>
                        <i style="color:red" class="fa fa-thumbs-down"></i>
                        <?=$this->user($moderVote['user'])?>
                        <span style="color:red"><?=$this->escapeHtml($moderVote['reason'])?></span>
                    <?php } ?>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>

<?php if ($this->user()->inheritsRole('moder')) { ?>
    <h3><?=$this->htmlA('/ng/moder', $this->page(67)->name) ?></h3>
    <div class="well">
        <div class="row">
            <div class="col-md-6">
                <?=$this->partial('application/moder/pictures/picture-vote', $this->pictureVote)?>
            </div>
            <div class="col-md-6">
                <?php foreach ($this->moderLinks as $url => $name) { ?>
                    <p><i class="fa fa-cog"></i> <?=$this->htmlA($url, $name)?></p>
                <?php } ?>
            </div>
            <?php if (count($this->items)) { ?>
                <div class="col-md-6">
                    <?php foreach ($this->items as $item) { ?>
                        <?=$this->partial('application/moder/pictures/picture-perspective', $item['perspective'])?>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>

<div id="comments">
    <?=$this->comments([
        'type'    => Application\Comments::PICTURES_TYPE_ID,
        'item_id' => $this->picture['id']
    ]) ?>
</div>