<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageId' => 32,
        'args'   => [
            'ARTICLE_NAME'    => $this->article->name,
            'ARTICLE_CATNAME' => $this->article->catname,
        ]
    ]);
?>
<div class="well">
    <div class="article clearfix">
        <?=$this->html ?>
    </div>
</div>

<?php if ($this->article->enabled) { ?>
    <div style="text-align:left;margin-bottom:20px;clear:both">
        <?=$this->comments([
            'type'    => \Application\Comments::ARTICLES_TYPE_ID,
            'item_id' => $this->article->id
        ]) ?>
    </div>
<?php } ?>