<?php
    $this->pageEnv([
        'layout' => [
            'blankPage' => false,
            'needLeft'  => false,
            'needRight' => false
        ],
        'pageId' => 32,
        'args'   => [
            'ARTICLE_NAME'    => $this->article->name,
            'ARTICLE_CATNAME' => $this->article->catname,
        ]
    ]);
?>
<div class="row">
    <div class="col-sm-4">
        <?=$this->partial('application/articles/sidebar', [
            'brands'   => $this->menu,
            'selected' => $this->selectedBrandIds
        ])?>
    </div>
    <div class="col-sm-8">
        <div class="well">
            <div class="article clearfix"><?=$this->article->findParentHtmls()->html ?></div>
        </div>

        <?php if (count($this->links)) { ?>
            <div class="well">
                <?php foreach ($this->links as $link) { ?>
                    <?=$this->htmlA($link['url'], $link['name']) ?>
                <?php } ?>
            </div>
        <?php } ?>

        <?php if ($this->article->enabled) { ?>
            <div style="text-align:left;margin-bottom:20px;clear:both">
                <?=$this->comments([
                    'type'    => Comment_Message::ARTICLES_TYPE_ID,
                    'item_id' => $this->article->id
                ]) ?>
            </div>
        <?php } ?>
    </div>
</div>