<div class="well">
    <ul class="nav nav-pills nav-stacked">
        <?php foreach ($this->brands as $brand) { ?>
            <?php
                $selected = in_array($brand['id'], $this->selected) ? ' class="selected"' : '';
            ?>
            <li<?=$selected ? ' class="active"' : ''?>>
                <?=$this->htmlA($this->url('articles', [
                    'action'        => 'index',
                    'brand_catname' => $brand['catname']
                ]), $brand['name']) ?>
            </li>
        <?php } ?>
    </ul>
</div>