<?php
    $this->pageEnv([
        'layout'    => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageTitle' => '',
        'pageId'    => 1
    ]);
    $this->layout()->moduleName = 'default/index';
?>
<?php /*
<?php $this->headStyle()->captureStart()?>
html {
    -webkit-filter: grayscale(100%);
    -moz-filter: grayscale(100%);
    filter: grayscale(100%);
}
<?php $this->headStyle()->captureEnd()?>
*/ ?>
<div class="row">
    <div class="col-md-6">
        <?php if ($this->carOfDay['name']) { ?>
            <h2>
                <?=$this->car()->htmlTitle($this->carOfDay['name'])?>
                <small><?=$this->escapeHtml($this->translate('car-of-day')) ?></small>
            </h2>

            <?php if ($this->carOfDay['pictures']) { ?>
                <div class="row thumbnails">
                    <?php foreach ($this->carOfDay['pictures'] as $idx => $picture) { ?>
                        <?php if ($idx == 0) { ?>
                            <?php if ($picture) { ?>
                                <div class="col-sm-8">
                                    <?=$this->htmlA([
                                        'href'  => $picture['url'],
                                        'class' => 'thumbnail'
                                    ], $this->htmlImg([
                                        'src'   => $picture['src'],
                                        'title' => $this->pic()->textTitle($picture['name']),
                                        'alt'   => $this->pic()->textTitle($picture['name']),
                                    ]), false)?>
                                </div>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                    <div class="col-sm-4">
                        <?php foreach ($this->carOfDay['pictures'] as $idx => $picture) { ?>
                            <?php if ($idx == 1 || $idx == 2) { ?>
                                <?php if ($picture) { ?>
                                    <?=$this->htmlA([
                                        'href'  => $picture['url'],
                                        'class' => 'thumbnail'
                                    ], $this->htmlImg([
                                        'src'   => $picture['src'],
                                        'title' => $this->pic()->textTitle($picture['name']),
                                        'alt'   => $this->pic()->textTitle($picture['name']),
                                    ]), false)?>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                    </div>
                </div>
                <div class="row thumbnails">
                    <div class="col-md-12">
                        <div class="row">
                            <?php foreach ($this->carOfDay['pictures'] as $idx => $picture) { ?>
                                <?php if ($idx > 2) { ?>
                                    <?php if ($picture) { ?>
                                        <div class="col-sm-4">
                                            <?=$this->htmlA([
                                                'href'  => $picture['url'],
                                                'class' => 'thumbnail'
                                            ], $this->htmlImg([
                                                'src'   => $picture['src'],
                                                'title' => $this->pic()->textTitle($picture['name']),
                                                'alt'   => $this->pic()->textTitle($picture['name']),
                                            ]), false)?>
                                        </div>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <?php if ($this->carOfDay['links']) { ?>
                    <p>
                        <?php foreach ($this->carOfDay['links'] as $i => $item) { ?>
                            <?php if ($i) { ?> &#xa0; <?php } ?>
                            <span class="fa fa-<?=$item['icon']?>"></span>
                            <?=$this->htmlA($item['url'], $item['text'] . (isset($item['count']) ? ' ('.$item['count'].')' : ''))?>
                        <?php } ?>
                    </p>
                <?php } ?>
            <?php } ?>
        <?php } ?>

        <div class="page-header-small">
            <h3><?=$this->escapeHtml($this->page(51)->name) ?> <small><?=$this->htmlA('/new', $this->translate('all-link'))?></small></h3>
        </div>
        <?=$this->partial('application/pictures', $this->newPictures)?>
        <p>
            <span class="fa fa-th"></span>
            <?=$this->htmlA('/new', $this->translate('All new pictures') . ' …') ?>
        </p>
    </div>
    <div class="col-md-6">
        <?=$this->partial('application/index/partial/brands', $this->brands)?>

        <div class="row">

            <div class="col-md-6">
                <h4><?=$this->escapeHtml($this->page(25)->name) ?> <small><?=$this->htmlA('/twins', $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->twinsBlock['brands'] as $brand) { ?>
                        <?=$this->htmlA($brand['url'], $brand['name']) ?>
                        <span class="count">(<?=$brand['count'] - $brand['new_count'] ?><?php if ($brand['new_count'] > 0) { ?><span>+<?=$brand['new_count'] ?></span><?php } ?>)</span>,
                    <?php } ?>
                    <?php if ($more = $this->twinsBlock['more_count']) { ?>
                        …
                        <?=$this->escapeHtml($this->translate('and'))?>
                        <?=$this->htmlA(
                            '/twins',
                            sprintf($this->translatePlural('brands/more-companies', 'brands/more-companies', $more), $more)
                        )?>
                    <?php } ?>
                </p>
                <?php if (in_array($this->language(), ['ru', 'zh', 'fr'])) { ?>
                    <?=$this->markdown($this->translate('index/twins/description'))?>
                <?php } ?>
            </div>

            <div class="col-md-6">
                <h4><?=$this->escapeHtml($this->page(22)->name) ?> <small><?=$this->htmlA('/category', $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->categories as $category) { ?>
                        <?=$this->htmlA($category['url'], $category['short_name'])?>&#xa0;<span class="count">(<?=$category['cars_count']-$category['new_cars_count'] ?><?php if ($category['new_cars_count'] > 0) { ?><span>+<?=$category['new_cars_count'] ?></span><?php } ?>)</span>,
                    <?php } ?>
                </p>
                <?php if (in_array($this->language(), ['ru', 'zh', 'fr'])) { ?>
                    <?=$this->markdown($this->translate('index/categories/description'))?>
                <?php } ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h4><?=$this->escapeHtml($this->page(21)->name) ?> <small><?=$this->htmlA('/mosts', $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->mosts as $url => $name) { ?>
                        <?=$this->htmlA($url, $this->translate($name)) ?>,
                    <?php } ?>
                    …
                </p>
                <?php if (in_array($this->language(), ['ru', 'zh', 'fr'])) { ?>
                    <?=$this->markdown($this->translate('index/categories/mosts'))?>
                <?php } ?>
            </div>

            <div class="col-md-6">
                <h4><?=$this->escapeHtml($this->translate('index/factories'))?> <small><?=$this->htmlA('/map', $this->translate('all-link'))?></small></h4>
                <?php foreach ($this->factories as $factory) {
                    echo $this->htmlA($factory['url'], $factory['name']) .
                        '&#xa0;<span class="count">(' . $factory['count'] . ')</span> ';
                } ?>
            </div>
        </div>
    </div>
</div>

<?php if (count($this->specsCars) > 0) { ?>
    <h4>
        <?=$this->escapeHtml($this->translate('index/specifications'))?>
        <small><?=$this->htmlA('/users/rating', $this->page(173)->name)?></small>
    </h4>
    <?=$this->partial('application/index/partial/specs-cars', $this->specsCars)?>
<?php } ?>