<?php
    $this->pageEnv([
        'layout'    => [
            'blankPage' => false,
            'needRight' => false
        ],
        'pageTitle' => '',
        'pageId'    => 1
    ]);
    $this->layout()->moduleName = 'default/index';
?>
<?php /*
<?php $this->headStyle()->captureStart()?>
html {
    -webkit-filter: grayscale(100%);
    -moz-filter: grayscale(100%);
    filter: grayscale(100%);
}
<?php $this->headStyle()->captureEnd()?>
*/ ?>
<div class="row">
    <div class="col-md-6">
        <?=$this->partial('application/index/partial/item-of-day', [
            'itemOfDay' => $this->carOfDay
        ])?>

        <div class="page-header-small">
            <h3><?=$this->escapeHtml($this->page(51)->name) ?> <small><?=$this->htmlA('/ng/new', $this->translate('all-link'))?></small></h3>
        </div>
        <?=$this->partial('application/pictures', $this->newPictures)?>
        <p>
            <span class="fa fa-th"></span>
            <?=$this->htmlA('/ng/new', $this->translate('All new pictures') . ' …') ?>
        </p>
    </div>
    <div class="col-md-6">
        <?=$this->partial('application/index/partial/brands', $this->brands)?>

        <div class="row">

            <div class="col-md-6">
                <h4><?=$this->escapeHtml($this->page(25)->name) ?> <small><?=$this->htmlA('/twins', $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->twinsBlock['brands'] as $brand) { ?>
                        <?=$this->htmlA($brand['url'], $brand['name']) ?>
                        <span class="count">(<?=$brand['count'] - $brand['new_count'] ?><?php if ($brand['new_count'] > 0) { ?><span>+<?=$brand['new_count'] ?></span><?php } ?>)</span>,
                    <?php } ?>
                    <?php if ($more = $this->twinsBlock['brands_count'] - count($this->twinsBlock['brands'])) { ?>
                        …
                        <?=$this->escapeHtml($this->translate('and'))?>
                        <?=$this->htmlA(
                            '/twins',
                            sprintf($this->translatePlural('brands/more-companies', 'brands/more-companies', $more), $more)
                        )?>
                    <?php } ?>
                </p>
                <?=$this->markdown($this->translate('index/twins/description'))?>
            </div>

            <div class="col-md-6">
                <?=$this->render('application/index/partial/categories')?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h4><?=$this->escapeHtml($this->page(21)->name) ?> <small><?=$this->htmlA('/ng/mosts', $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->mosts as $url => $name) { ?>
                        <?=$this->htmlA($url, $this->translate($name)) ?>,
                    <?php } ?>
                    …
                </p>
                <?=$this->markdown($this->translate('index/categories/mosts'))?>
            </div>

            <div class="col-md-6">
                <?=$this->render('application/index/partial/factories')?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h4><?=$this->translate('persons/content-persons') ?> <small><?=$this->htmlA('/ng/persons', $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->contentPersons as $person) { ?>
                        <?=$this->htmlA('/ng/persons/' . $person['id'], $person['name']) ?>,
                    <?php } ?>
                    …
                </p>
            </div>

            <div class="col-md-6">
                <h4><?=$this->translate('persons/author-persons') ?> <small><?=$this->htmlA('/ng/persons/authors', $this->translate('all-link'))?></small></h4>
                <p>
                    <?php foreach ($this->authorPersons as $person) { ?>
                        <?=$this->htmlA('/ng/persons/' . $person['id'], $person['name']) ?>,
                    <?php } ?>
                    …
                </p>
            </div>
        </div>
    </div>
</div>

<?php if (count($this->specsCars) > 0) { ?>
    <h4>
        <?=$this->escapeHtml($this->translate('index/specifications'))?>
        <small><?=$this->htmlA('/ng/users/rating', $this->page(173)->name)?></small>
    </h4>
    <?=$this->partial('application/index/partial/specs-cars', $this->specsCars)?>
<?php } ?>