<?php foreach ($this->engines as $engine) { ?>
    <?=$this->formButton('parent_id', $engine['id'], array(
        'type'    => 'submit',
        'class'   => 'btn btn-link',
        'value'   => $engine['id'],
        'content' => $engine['name']
    ))?><br />
    <?php if (count($engine['childs'])) { ?>
        <div style="margin-left:2em">
            <?=$this->partial('engines/select-parent-walk-tree.phtml', array(
                'engines' => $engine['childs']
            ))?>
        </div>
    <?php } ?>
<?php } ?>