<?php
    $this->element->setAttrib(
        'class',
        $this->element->getAttrib('class') . ' form-horizontal'
    );
?>
<fieldset>
    <?php if ($description = $this->element->getDescription()) { ?>
        <legend><?=$this->escape($description)?></legend>
    <?php } ?>
    <?php foreach ($this->element->getElements() as $element) { ?>
        <?php
            $errors = $element->getMessages();
        ?>
        <div class="row<?=$errors ? ' error' : ''?>">
            <label class="control-label col-lg-2" for="<?=$element->getId()?>"><?=$this->escape($element->getLabel())?></label>
            <div class="col-lg-10">
                <?=$element?>
                <?php foreach ($errors as $error) { ?>
                    <span class="help-inline"><?=$this->escape($error)?></span>
                <?php } ?>
            </div>
        </div>
    <?php } ?>
    <div class="row">
        <div class="col-lg-10 col-offset-2">
            <?=$this->formSubmit('submit', 'Отправить', array(
                'class' => 'btn btn-primary'
            ))?>
        </div>
    </div>
</fieldset>