<?php foreach ($this->groups as $twinsGroup) { ?>
    <h3><?=$this->car()->htmlTitle($twinsGroup['name'])?></h3>

    <?php while ($items = array_splice($twinsGroup['cars'], 0, 4)) { ?>
        <div class="twins row">
            <?php foreach ($items as $car) { ?>
                <div class="col-lg-3 col-md-3">
                    <div class="card mb-4">
                        <?php if ($car['picture']) { ?>
                            <?=$this->htmlA(
                                $car['picture']['url'],
                                $this->htmlImg([
                                    'src'   => $car['picture']['src'],
                                    'alt'   => $this->car()->textTitle($car['name']),
                                    'title' => $this->car()->textTitle($car['name']),
                                    'class' => 'card-img-top'
                                ]),
                                false
                            )?>
                        <?php } else { ?>
                            &#xa0;
                        <?php } ?>
                        <div class="card-body">
                            <p class="card-title"><?=$this->car()->htmlTitle($car['name'])?></p>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } ?>

    <ul class="carLinks">
        <li>
            <i class="fa fa-file"></i>
            <?php if ($twinsGroup['msgCount'] > 0) { ?>
                <?=$this->htmlA(
                    $twinsGroup['detailsUrl'],
                    $this->translate('carlist/details') . ' … (' . sprintf($this->translate('%1$s comments', null, $twinsGroup['msgCount']), $twinsGroup['msgCount']) . ')'
                )?>
            <?php } else { ?>
                <?=$this->htmlA($twinsGroup['detailsUrl'], $this->translate('carlist/details') . ' …')?>
            <?php } ?>
        </li>
        <?php if ($twinsGroup['hasSpecs']) { ?>
            <li>
                <i class="fa fa-list-alt"></i>
                <?=$this->htmlA($twinsGroup['specsUrl'], $this->translate('carlist/specifications'))?>
            </li>
        <?php }?>
        <?php if ($twinsGroup['picturesCount'] > $twinsGroup['picturesShown']) { ?>
            <li>
                <span class="fa fa-th"></span>
                <?=$this->htmlA($twinsGroup['picturesUrl'], $this->translate('carlist/all pictures') . ' ('.$twinsGroup['picturesCount'].')')?>
            </li>
        <?php } ?>
        <?php if ($this->canEdit) { ?>
            <li>
                <i class="fa fa-cog"></i>
                <?=$this->htmlA($twinsGroup['moderUrl'], $this->translate('moder/edit-object'))?>
            </li>
        <?php } ?>
    </ul>
<?php } ?>