<?php
$this->layout()->setVariables([
    'blankPage' => false,
    'needRight' => false
]);
?>
<?php if (count($this->positiveVotes)) { ?>
    <p>
        <strong>+1</strong>:
        <?php foreach ($this->positiveVotes as $user) { ?>
            <?=$this->user($user) . ' ' ?>
        <?php } ?>
    </p>
<?php } ?>

<?php if (count($this->negativeVotes)) { ?>
    <p>
        <strong>-1</strong>:
        <?php foreach ($this->negativeVotes as $user) { ?>
            <?=$this->user($user) . ' ' ?>
        <?php } ?>
    </p>
<?php } ?>
