apiVersion: v1
kind: Service
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ include "autowp.goautowp.serve.fullname" . | quote }}
spec:
  ports:
    - name: app-port
      port: 8080
      protocol: TCP
      targetPort: app-port
    - name: grpc-port
      port: 8082
      protocol: TCP
      targetPort: app-port
    - name: frontend-port
      port: 4000
      protocol: TCP
      targetPort: frontend-port
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: goautowp-serve
  type: ClusterIP
