<?php
    $blankPage = isset($this->layout()->blankPage) ? $this->layout()->blankPage : $this->blankPage;
    $needLeft  = isset($this->layout()->needLeft)  ? $this->layout()->needLeft  : $this->needLeft;
    $needRight = isset($this->layout()->needRight) ? $this->layout()->needRight : $this->needRight;
    $isAdminPage = isset($this->layout()->isAdminPage) ? $this->layout()->isAdminPage : $this->isAdminPage;

    $moderMenu = '';
    if (!$blankPage && $this->user()->logedIn() && $this->acl()->inheritsRole($this->user()->get()->role, 'moder')) {
        $moderMenu = $this->action('moder-menu', 'index', 'moder');
    }

    $mainMenu = '';
    if (!$blankPage) {
        $mainMenu = $this->action('main-menu', 'pages', 'default');
    }

    if ($this->jQuery()->uiIsEnabled()) {
        $this->headLink()->appendStylesheet('/js/libs/jquery/ui/theme/ui.all.css');
    }
?>
<?=$this->doctype() . PHP_EOL ?>
<html dir="ltr" lang="<?=$this->language()->get()?>">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php
            echo $this->headMeta();
            echo $this->headTitle();
            echo $this->headLink(array('rel' => 'shortcut icon', 'href' => '/favicon.ico', 'type' => 'image/x-icon'), 'PREPEND');

            //echo $this->stylesheets();
            echo $this->jQuery();
            echo $this->headScript()
                ->appendFile(
                    'http://html5shim.googlecode.com/svn/trunk/html5.js',
                    'text/javascript',
                    array('conditional' => 'lt IE 9')
                )
                ->appendFile(
                    '/vendor/scottjehl/Respond/respond.min.js',
                    'text/javascript',
                    array('conditional' => 'lt IE 9')
                );
            echo $this->headStyle();
        ?>
    </head>
    <body>
        <?=$moderMenu ?>

        <?php
            $spanLeft = $needLeft ? 4 : 0;
            $spanRight = $needRight ? 4 : 0;
            $spanCenter = 12 - $spanLeft - $spanRight;
        ?>

        <?php if (!$blankPage) { ?>
            <?=$mainMenu ?>
        <?php }  ?>

        <div class="container">

            <div class="row">
                <div class="col-lg-<?=$spanCenter?> col-sm-<?=$spanCenter?> col-push-<?=$spanLeft?>">
                    <?=$this->action('flash-messages', 'layout', 'default') ?>
                    <?=$this->breadcrumbs() ?>
                    <?=$this->pageTitle() ?>
                    <?=$this->layout()->content ?>
                </div>
                <?php if ($needLeft) { ?>
                    <div class="col-lg-<?=$spanLeft?> col-sm-<?=$spanLeft?> col-pull-<?=$spanCenter?>">
                        <?=$this->layout()->sidebar ?>
                    </div>
                <?php } ?>
                <?php if ($needRight) { ?>
                    <div class="col-lg-<?=$spanRight?> col-sm-<?=$spanRight?>">
                        <?=$this->action('sidebar-right', 'layout', 'default') ?>
                    </div>
                <?php } ?>
            </div>

            <?php if ((!$blankPage) && (!$isAdminPage) ) { ?>
                <div class="bottom-line"><p><strong>AutoWP.ru '2005&ndash;<?=$this->escape($this->translate('present-time-abbr'))?></strong></p></div>

                <footer class="footer">
                    <div class="row">
                        <div class="col-lg-6">
                            <?=$this->htmlA(
                                'http://www.liveinternet.ru/click',
                                $this->htmlImg(array(
                                    'src'   => 'http://counter.yadro.ru/hit?t16.11;r' . urlencode(isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '') . ';' . rand(),
                                    'alt'   => 'liveinternet.ru',
                                    'title' => 'liveinternet.ru'
                                )),
                                false
                            )?>
<?php $this->inlineScript()->captureStart() ?>
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-24654784-1']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
<?php $this->inlineScript()->captureEnd() ?>
<?=$this->inlineScript() ?>
                        </div>
                        <div class="col-lg-6">
                            <p class="copyrights">
                                Обращаем Ваше внимание на то, что все материалы, размещенные на сервере autowp.ru, добавлены посетителями сайта.<br />
                                Администрация сайта не располагает информацией о правомерности публикования этих материалов.<br />
                                Все изображения размещены в ознакомительных целях.<br />
                                <a href="mailto:autowp@yandex.ru">Сообщить о нарушении авторских прав</a>.
                            </p>
                        </div>
                    </div>
                </footer>
            <?php } ?>
        </div>
    </body>
</html>