<?php
    $blankPage = isset($this->layout()->blankPage) ? $this->layout()->blankPage : $this->blankPage;
    $needLeft  = isset($this->layout()->needLeft)  ? $this->layout()->needLeft  : $this->needLeft;
    $needRight = isset($this->layout()->needRight) ? $this->layout()->needRight : $this->needRight;
    $isAdminPage = isset($this->layout()->isAdminPage) ? $this->layout()->isAdminPage : $this->isAdminPage;

    $moderMenu = '';
    if (!$blankPage && $this->user()->logedIn() && $this->acl()->inheritsRole($this->user()->get()->role, 'moder')) {
        $moderMenu = $this->action('moder-menu', 'index', 'moder');
    }

    $mainMenu = '';
    if (!$blankPage) {
        $mainMenu = $this->action('main-menu', 'pages', 'default');
    }

?>
<?=$this->doctype() . PHP_EOL ?>
<html dir="ltr" lang="<?=$this->language()->get()?>">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="theme-color" content="#ede9de">
        <meta name="msapplication-navbutton-color" content="#ede9de">
        <meta name="apple-mobile-web-app-status-bar-style" content="#ede9de">
        <?php
            echo $this->headMeta()
                ->appendName('keywords', 'auto, avto, автомобиль')
                ->appendName('description', 'Энциклопедия автомобилей в картинках. AutoWP.ru');
            echo $this->headTitle();
            echo $this
                ->headLink(array('rel' => 'shortcut icon', 'href' => '/favicon.ico', 'type' => 'image/x-icon'), 'PREPEND')
                ->appendStylesheet('/css/styles.css', 'screen');
            echo $this->headScript()
                ->appendFile(
                    'http://html5shim.googlecode.com/svn/trunk/html5.js',
                    'text/javascript',
                    array('conditional' => 'lt IE 9')
                )
                ->appendFile(
                    '/vendor/scottjehl/Respond/dest/respond.min.js',
                    'text/javascript',
                    array('conditional' => 'lt IE 9')
                )
                ->appendFile('/js/application.js');

            echo $this->headStyle();
        ?>
        <script type="text/javascript">
require(['application'], function(App) {
    App.init();
    <?php
        $moduleOptions = isset($this->layout()->moduleOptions)
            ? $this->layout()->moduleOptions
            : null;
    ?>
    <?php if (isset($this->layout()->moduleName)) { ?>
        require([<?=Zend_Json::encode($this->layout()->moduleName)?>], function(Module) {
            Module.init(<?=Zend_Json::encode($moduleOptions)?>);
        });
    <?php } ?>
});
        </script>
    </head>
    <body>
        <?=$moderMenu ?>

        <?php
            $spanLeft = $needLeft ? 4 : 0;
            $spanRight = $needRight ? 4 : 0;
            $spanCenter = 12 - $spanLeft - $spanRight;
        ?>

        <?php if (!$blankPage) { ?>
            <?=$mainMenu ?>
        <?php }  ?>

        <div class="container">

            <div class="row">
                <div class="col-sm-<?=$spanCenter?> col-sm-push-<?=$spanLeft?>">
                    <?=$this->action('flash-messages', 'layout', 'default') ?>
                    <?=$this->breadcrumbs() ?>
                    <?=$this->pageTitle() ?>
                    <?=$this->layout()->content ?>
                </div>
                <?php if ($needLeft) { ?>
                    <div class="col-sm-<?=$spanLeft?> col-sm-pull-<?=$spanCenter?>">
                        <?=$this->layout()->sidebar ?>
                    </div>
                <?php } ?>
                <?php if ($needRight) { ?>
                    <div class="col-sm-<?=$spanRight?>">
                        <?=$this->action('sidebar-right', 'layout', 'default') ?>
                    </div>
                <?php } ?>
            </div>

            <?php if ((!$blankPage) && (!$isAdminPage) ) { ?>
                <div class="bottom-line"><p><strong>AutoWP.ru '2005&ndash;<?=$this->escape($this->translate('present-time-abbr'))?></strong></p></div>

                <footer class="footer">
                    <div class="row">
                        <div class="col-md-6">
<?php $this->inlineScript()->captureStart() ?>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-24654784-1', 'auto');
ga('require', 'displayfeatures');
ga('send', 'pageview');
<?php $this->inlineScript()->captureEnd() ?>
<?=$this->inlineScript() ?>
                        </div>
                        <div class="col-md-6">
                            <p class="copyrights"><?=$this->translate('layout/footer')?></p>
                        </div>
                    </div>
                </footer>
            <?php } ?>
        </div>
    </body>
</html>